// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foundation.sql

package navsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const foundationPing = `-- name: FoundationPing :one
SELECT 1::bigint AS value
`

func (q *Queries) FoundationPing(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, foundationPing)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const getPublicSiteByID = `-- name: GetPublicSiteByID :one
SELECT id, name, name_en, info, info_en, create_time, update_time,
       country, nsfw, welfare, icon, deleted, view_count
FROM gfn_site
WHERE id = $1
  AND deleted IS NOT TRUE
LIMIT 1
`

func (q *Queries) GetPublicSiteByID(ctx context.Context, siteID int64) (GfnSite, error) {
	row := q.db.QueryRow(ctx, getPublicSiteByID, siteID)
	var i GfnSite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Country,
		&i.Nsfw,
		&i.Welfare,
		&i.Icon,
		&i.Deleted,
		&i.ViewCount,
	)
	return i, err
}

const getRandomSaying = `-- name: GetRandomSaying :one
SELECT id, author, saying, create_time, update_time, language
FROM gfn_saying
WHERE language = $1
   OR ($1 <> 'zh' AND language = 'zh')
ORDER BY
    CASE WHEN language = $1 THEN 0 ELSE 1 END,
    random()
LIMIT 1
`

func (q *Queries) GetRandomSaying(ctx context.Context, language string) (GfnSaying, error) {
	row := q.db.QueryRow(ctx, getRandomSaying, language)
	var i GfnSaying
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Saying,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Language,
	)
	return i, err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id, name, name_en, info, info_en, create_time, update_time,
       country, nsfw, welfare, icon, deleted, view_count
FROM gfn_site
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSiteByID(ctx context.Context, siteID int64) (GfnSite, error) {
	row := q.db.QueryRow(ctx, getSiteByID, siteID)
	var i GfnSite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Country,
		&i.Nsfw,
		&i.Welfare,
		&i.Icon,
		&i.Deleted,
		&i.ViewCount,
	)
	return i, err
}

const listCollectorObservations = `-- name: ListCollectorObservations :many
SELECT
    id,
    site_id,
    target,
    protocol,
    status,
    observed_at,
    COALESCE(duration_ms, 0)::bigint AS duration_ms,
    error_code,
    error_message,
    COALESCE(payload->>'collector_id', '')::text AS collector_id,
    COALESCE(payload->>'job_id', '')::text AS job_id
FROM gfn_collector_observation
WHERE ($1::bigint <= 0 OR site_id = $1)
  AND ($2::text = '' OR target = $2)
  AND ($3::text = '' OR protocol = $3)
  AND ($4::text = '' OR status = $4)
ORDER BY observed_at DESC, id DESC
LIMIT $6
OFFSET $5
`

type ListCollectorObservationsParams struct {
	SiteID    int64  `json:"site_id"`
	Target    string `json:"target"`
	Protocol  string `json:"protocol"`
	Status    string `json:"status"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

type ListCollectorObservationsRow struct {
	ID           int64              `json:"id"`
	SiteID       int64              `json:"site_id"`
	Target       string             `json:"target"`
	Protocol     string             `json:"protocol"`
	Status       string             `json:"status"`
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	DurationMs   int64              `json:"duration_ms"`
	ErrorCode    *string            `json:"error_code"`
	ErrorMessage *string            `json:"error_message"`
	CollectorID  string             `json:"collector_id"`
	JobID        string             `json:"job_id"`
}

func (q *Queries) ListCollectorObservations(ctx context.Context, arg ListCollectorObservationsParams) ([]ListCollectorObservationsRow, error) {
	rows, err := q.db.Query(ctx, listCollectorObservations,
		arg.SiteID,
		arg.Target,
		arg.Protocol,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectorObservationsRow{}
	for rows.Next() {
		var i ListCollectorObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Target,
			&i.Protocol,
			&i.Status,
			&i.ObservedAt,
			&i.DurationMs,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CollectorID,
			&i.JobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedSites = `-- name: ListFeaturedSites :many
SELECT f.id, f.site_id, f.weight, f.create_time, f.update_time
FROM gfn_featured_site AS f
INNER JOIN gfn_site AS s
    ON s.id = f.site_id
   AND s.deleted IS NOT TRUE
ORDER BY f.weight DESC, f.id DESC
`

func (q *Queries) ListFeaturedSites(ctx context.Context) ([]GfnFeaturedSite, error) {
	rows, err := q.db.Query(ctx, listFeaturedSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfnFeaturedSite{}
	for rows.Next() {
		var i GfnFeaturedSite
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Weight,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationStatusSummary = `-- name: ListObservationStatusSummary :many
SELECT protocol, status, COUNT(*)::bigint AS count
FROM gfn_collector_observation
WHERE observed_at >= NOW() - INTERVAL '7 days'
GROUP BY protocol, status
ORDER BY protocol ASC, status ASC
`

type ListObservationStatusSummaryRow struct {
	Protocol string `json:"protocol"`
	Status   string `json:"status"`
	Count    int64  `json:"count"`
}

func (q *Queries) ListObservationStatusSummary(ctx context.Context) ([]ListObservationStatusSummaryRow, error) {
	rows, err := q.db.Query(ctx, listObservationStatusSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObservationStatusSummaryRow{}
	for rows.Next() {
		var i ListObservationStatusSummaryRow
		if err := rows.Scan(&i.Protocol, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCollectorDomains = `-- name: ListPublicCollectorDomains :many
SELECT id, name, proxy, prefix, tls, site_id, deleted
FROM gfn_collector_domain
WHERE site_id = $1
  AND deleted IS NOT TRUE
ORDER BY id ASC
`

func (q *Queries) ListPublicCollectorDomains(ctx context.Context, siteID *int64) ([]GfnCollectorDomain, error) {
	rows, err := q.db.Query(ctx, listPublicCollectorDomains, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfnCollectorDomain{}
	for rows.Next() {
		var i GfnCollectorDomain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Proxy,
			&i.Prefix,
			&i.Tls,
			&i.SiteID,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicSiteIndex = `-- name: ListPublicSiteIndex :many
SELECT
    s.id,
    json_build_object(
        'domain',
        COALESCE(cd.domains, ARRAY[]::text[])
    )::text AS domain,
    s.update_time
FROM gfn_site AS s
LEFT JOIN LATERAL (
    SELECT array_agg(
        trim(COALESCE(prefix, '') || name)
        ORDER BY id ASC
    ) AS domains
    FROM gfn_collector_domain
    WHERE site_id = s.id
      AND site_id > 0
      AND deleted IS NOT TRUE
      AND trim(COALESCE(prefix, '') || name) <> ''
) AS cd ON TRUE
WHERE s.deleted IS NOT TRUE
ORDER BY s.id ASC
`

type ListPublicSiteIndexRow struct {
	ID         int64            `json:"id"`
	Domain     string           `json:"domain"`
	UpdateTime pgtype.Timestamp `json:"update_time"`
}

func (q *Queries) ListPublicSiteIndex(ctx context.Context) ([]ListPublicSiteIndexRow, error) {
	rows, err := q.db.Query(ctx, listPublicSiteIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicSiteIndexRow{}
	for rows.Next() {
		var i ListPublicSiteIndexRow
		if err := rows.Scan(&i.ID, &i.Domain, &i.UpdateTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicSites = `-- name: ListPublicSites :many
SELECT
    s.id,
    s.name,
    s.name_en,
    json_build_object(
        'domain',
        COALESCE(cd.domains, ARRAY[]::text[])
    )::text AS domain,
    s.info,
    s.info_en,
    s.create_time,
    s.update_time,
    s.country,
    s.nsfw,
    s.welfare,
    s.view_count,
    s.icon,
    s.deleted
FROM gfn_site AS s
LEFT JOIN LATERAL (
    SELECT array_agg(
        trim(COALESCE(prefix, '') || name)
        ORDER BY id ASC
    ) AS domains
    FROM gfn_collector_domain
    WHERE site_id = s.id
      AND site_id > 0
      AND deleted IS NOT TRUE
      AND trim(COALESCE(prefix, '') || name) <> ''
) AS cd ON TRUE
WHERE s.deleted IS NOT TRUE
ORDER BY s.update_time DESC, s.id DESC
`

type ListPublicSitesRow struct {
	ID         int64            `json:"id"`
	Name       string           `json:"name"`
	NameEn     string           `json:"name_en"`
	Domain     string           `json:"domain"`
	Info       string           `json:"info"`
	InfoEn     string           `json:"info_en"`
	CreateTime pgtype.Timestamp `json:"create_time"`
	UpdateTime pgtype.Timestamp `json:"update_time"`
	Country    *string          `json:"country"`
	Nsfw       string           `json:"nsfw"`
	Welfare    string           `json:"welfare"`
	ViewCount  int64            `json:"view_count"`
	Icon       *string          `json:"icon"`
	Deleted    bool             `json:"deleted"`
}

func (q *Queries) ListPublicSites(ctx context.Context) ([]ListPublicSitesRow, error) {
	rows, err := q.db.Query(ctx, listPublicSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicSitesRow{}
	for rows.Next() {
		var i ListPublicSitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameEn,
			&i.Domain,
			&i.Info,
			&i.InfoEn,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Country,
			&i.Nsfw,
			&i.Welfare,
			&i.ViewCount,
			&i.Icon,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicUpdateNotices = `-- name: ListPublicUpdateNotices :many
SELECT id, title, title_en, body, body_en, published_at,
       create_time, update_time, deleted
FROM gfn_nav_update_notice
WHERE deleted IS NOT TRUE
ORDER BY published_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListPublicUpdateNotices(ctx context.Context, rowLimit int32) ([]GfnNavUpdateNotice, error) {
	rows, err := q.db.Query(ctx, listPublicUpdateNotices, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfnNavUpdateNotice{}
	for rows.Next() {
		var i GfnNavUpdateNotice
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleEn,
			&i.Body,
			&i.BodyEn,
			&i.PublishedAt,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteGroupMappings = `-- name: ListSiteGroupMappings :many
SELECT id, site_id, group_id, weight, create_time, update_time
FROM gfn_site_group_map
ORDER BY group_id ASC, weight DESC, update_time DESC, id DESC, site_id ASC
`

type ListSiteGroupMappingsRow struct {
	ID         int64            `json:"id"`
	SiteID     int64            `json:"site_id"`
	GroupID    int64            `json:"group_id"`
	Weight     int64            `json:"weight"`
	CreateTime pgtype.Timestamp `json:"create_time"`
	UpdateTime pgtype.Timestamp `json:"update_time"`
}

func (q *Queries) ListSiteGroupMappings(ctx context.Context) ([]ListSiteGroupMappingsRow, error) {
	rows, err := q.db.Query(ctx, listSiteGroupMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiteGroupMappingsRow{}
	for rows.Next() {
		var i ListSiteGroupMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.GroupID,
			&i.Weight,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteGroups = `-- name: ListSiteGroups :many
SELECT id, name, name_en, info, info_en, priority, create_time, update_time
FROM gfn_site_group
ORDER BY priority ASC
`

func (q *Queries) ListSiteGroups(ctx context.Context) ([]GfnSiteGroup, error) {
	rows, err := q.db.Query(ctx, listSiteGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfnSiteGroup{}
	for rows.Next() {
		var i GfnSiteGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameEn,
			&i.Info,
			&i.InfoEn,
			&i.Priority,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetObservations = `-- name: ListTargetObservations :many
SELECT id, site_id, target, protocol, status, observed_at,
       COALESCE(duration_ms, 0)::bigint AS duration_ms,
       error_code, error_message, payload, schema_version, create_time
FROM gfn_collector_observation
WHERE site_id = $1
  AND target = $2
  AND protocol = $3
ORDER BY observed_at DESC, id DESC
LIMIT $4
`

type ListTargetObservationsParams struct {
	SiteID   int64  `json:"site_id"`
	Target   string `json:"target"`
	Protocol string `json:"protocol"`
	RowLimit int32  `json:"row_limit"`
}

type ListTargetObservationsRow struct {
	ID            int64              `json:"id"`
	SiteID        int64              `json:"site_id"`
	Target        string             `json:"target"`
	Protocol      string             `json:"protocol"`
	Status        string             `json:"status"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	DurationMs    int64              `json:"duration_ms"`
	ErrorCode     *string            `json:"error_code"`
	ErrorMessage  *string            `json:"error_message"`
	Payload       []byte             `json:"payload"`
	SchemaVersion int32              `json:"schema_version"`
	CreateTime    pgtype.Timestamptz `json:"create_time"`
}

func (q *Queries) ListTargetObservations(ctx context.Context, arg ListTargetObservationsParams) ([]ListTargetObservationsRow, error) {
	rows, err := q.db.Query(ctx, listTargetObservations,
		arg.SiteID,
		arg.Target,
		arg.Protocol,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTargetObservationsRow{}
	for rows.Next() {
		var i ListTargetObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Target,
			&i.Protocol,
			&i.Status,
			&i.ObservedAt,
			&i.DurationMs,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Payload,
			&i.SchemaVersion,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteViewCount = `-- name: UpdateSiteViewCount :exec
UPDATE gfn_site
SET view_count = $1
WHERE id = $2
`

type UpdateSiteViewCountParams struct {
	ViewCount int64 `json:"view_count"`
	SiteID    int64 `json:"site_id"`
}

func (q *Queries) UpdateSiteViewCount(ctx context.Context, arg UpdateSiteViewCountParams) error {
	_, err := q.db.Exec(ctx, updateSiteViewCount, arg.ViewCount, arg.SiteID)
	return err
}
