// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gofurry/gorm-generator/model"
)

func newGfgGameComment(db *gorm.DB, opts ...gen.DOOption) gfgGameComment {
	_gfgGameComment := gfgGameComment{}

	_gfgGameComment.gfgGameCommentDo.UseDB(db, opts...)
	_gfgGameComment.gfgGameCommentDo.UseModel(&model.GfgGameComment{})

	tableName := _gfgGameComment.gfgGameCommentDo.TableName()
	_gfgGameComment.ALL = field.NewAsterisk(tableName)
	_gfgGameComment.ID = field.NewInt64(tableName, "id")
	_gfgGameComment.Region = field.NewString(tableName, "region")
	_gfgGameComment.Content = field.NewString(tableName, "content")
	_gfgGameComment.Score = field.NewFloat64(tableName, "score")
	_gfgGameComment.CreateTime = field.NewTime(tableName, "create_time")
	_gfgGameComment.GameID = field.NewInt64(tableName, "game_id")
	_gfgGameComment.IP = field.NewString(tableName, "ip")
	_gfgGameComment.Name = field.NewString(tableName, "name")

	_gfgGameComment.fillFieldMap()

	return _gfgGameComment
}

type gfgGameComment struct {
	gfgGameCommentDo

	ALL        field.Asterisk
	ID         field.Int64   // 评论表ID
	Region     field.String  // 地区
	Content    field.String  // 评论
	Score      field.Float64 // 评分
	CreateTime field.Time    // 创建时间
	GameID     field.Int64   // 游戏表ID
	IP         field.String  // ip
	Name       field.String  // 评论人名称

	fieldMap map[string]field.Expr
}

func (g gfgGameComment) Table(newTableName string) *gfgGameComment {
	g.gfgGameCommentDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gfgGameComment) As(alias string) *gfgGameComment {
	g.gfgGameCommentDo.DO = *(g.gfgGameCommentDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gfgGameComment) updateTableName(table string) *gfgGameComment {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.Region = field.NewString(table, "region")
	g.Content = field.NewString(table, "content")
	g.Score = field.NewFloat64(table, "score")
	g.CreateTime = field.NewTime(table, "create_time")
	g.GameID = field.NewInt64(table, "game_id")
	g.IP = field.NewString(table, "ip")
	g.Name = field.NewString(table, "name")

	g.fillFieldMap()

	return g
}

func (g *gfgGameComment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gfgGameComment) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["id"] = g.ID
	g.fieldMap["region"] = g.Region
	g.fieldMap["content"] = g.Content
	g.fieldMap["score"] = g.Score
	g.fieldMap["create_time"] = g.CreateTime
	g.fieldMap["game_id"] = g.GameID
	g.fieldMap["ip"] = g.IP
	g.fieldMap["name"] = g.Name
}

func (g gfgGameComment) clone(db *gorm.DB) gfgGameComment {
	g.gfgGameCommentDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gfgGameComment) replaceDB(db *gorm.DB) gfgGameComment {
	g.gfgGameCommentDo.ReplaceDB(db)
	return g
}

type gfgGameCommentDo struct{ gen.DO }

func (g gfgGameCommentDo) Debug() *gfgGameCommentDo {
	return g.withDO(g.DO.Debug())
}

func (g gfgGameCommentDo) WithContext(ctx context.Context) *gfgGameCommentDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gfgGameCommentDo) ReadDB() *gfgGameCommentDo {
	return g.Clauses(dbresolver.Read)
}

func (g gfgGameCommentDo) WriteDB() *gfgGameCommentDo {
	return g.Clauses(dbresolver.Write)
}

func (g gfgGameCommentDo) Session(config *gorm.Session) *gfgGameCommentDo {
	return g.withDO(g.DO.Session(config))
}

func (g gfgGameCommentDo) Clauses(conds ...clause.Expression) *gfgGameCommentDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gfgGameCommentDo) Returning(value interface{}, columns ...string) *gfgGameCommentDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gfgGameCommentDo) Not(conds ...gen.Condition) *gfgGameCommentDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gfgGameCommentDo) Or(conds ...gen.Condition) *gfgGameCommentDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gfgGameCommentDo) Select(conds ...field.Expr) *gfgGameCommentDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gfgGameCommentDo) Where(conds ...gen.Condition) *gfgGameCommentDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gfgGameCommentDo) Order(conds ...field.Expr) *gfgGameCommentDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gfgGameCommentDo) Distinct(cols ...field.Expr) *gfgGameCommentDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gfgGameCommentDo) Omit(cols ...field.Expr) *gfgGameCommentDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gfgGameCommentDo) Join(table schema.Tabler, on ...field.Expr) *gfgGameCommentDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gfgGameCommentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *gfgGameCommentDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gfgGameCommentDo) RightJoin(table schema.Tabler, on ...field.Expr) *gfgGameCommentDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gfgGameCommentDo) Group(cols ...field.Expr) *gfgGameCommentDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gfgGameCommentDo) Having(conds ...gen.Condition) *gfgGameCommentDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gfgGameCommentDo) Limit(limit int) *gfgGameCommentDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gfgGameCommentDo) Offset(offset int) *gfgGameCommentDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gfgGameCommentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *gfgGameCommentDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gfgGameCommentDo) Unscoped() *gfgGameCommentDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gfgGameCommentDo) Create(values ...*model.GfgGameComment) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gfgGameCommentDo) CreateInBatches(values []*model.GfgGameComment, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gfgGameCommentDo) Save(values ...*model.GfgGameComment) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gfgGameCommentDo) First() (*model.GfgGameComment, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGameComment), nil
	}
}

func (g gfgGameCommentDo) Take() (*model.GfgGameComment, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGameComment), nil
	}
}

func (g gfgGameCommentDo) Last() (*model.GfgGameComment, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGameComment), nil
	}
}

func (g gfgGameCommentDo) Find() ([]*model.GfgGameComment, error) {
	result, err := g.DO.Find()
	return result.([]*model.GfgGameComment), err
}

func (g gfgGameCommentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GfgGameComment, err error) {
	buf := make([]*model.GfgGameComment, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gfgGameCommentDo) FindInBatches(result *[]*model.GfgGameComment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gfgGameCommentDo) Attrs(attrs ...field.AssignExpr) *gfgGameCommentDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gfgGameCommentDo) Assign(attrs ...field.AssignExpr) *gfgGameCommentDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gfgGameCommentDo) Joins(fields ...field.RelationField) *gfgGameCommentDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gfgGameCommentDo) Preload(fields ...field.RelationField) *gfgGameCommentDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gfgGameCommentDo) FirstOrInit() (*model.GfgGameComment, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGameComment), nil
	}
}

func (g gfgGameCommentDo) FirstOrCreate() (*model.GfgGameComment, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGameComment), nil
	}
}

func (g gfgGameCommentDo) FindByPage(offset int, limit int) (result []*model.GfgGameComment, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gfgGameCommentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gfgGameCommentDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gfgGameCommentDo) Delete(models ...*model.GfgGameComment) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gfgGameCommentDo) withDO(do gen.Dao) *gfgGameCommentDo {
	g.DO = *do.(*gen.DO)
	return g
}
