// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gofurry/gorm-generator/model"
)

func newGfgGameNews(db *gorm.DB, opts ...gen.DOOption) gfgGameNews {
	_gfgGameNews := gfgGameNews{}

	_gfgGameNews.gfgGameNewsDo.UseDB(db, opts...)
	_gfgGameNews.gfgGameNewsDo.UseModel(&model.GfgGameNews{})

	tableName := _gfgGameNews.gfgGameNewsDo.TableName()
	_gfgGameNews.ALL = field.NewAsterisk(tableName)
	_gfgGameNews.ID = field.NewInt64(tableName, "id")
	_gfgGameNews.GameID = field.NewInt64(tableName, "game_id")
	_gfgGameNews.Headline = field.NewString(tableName, "headline")
	_gfgGameNews.Content = field.NewString(tableName, "content")
	_gfgGameNews.Index = field.NewInt64(tableName, "index")
	_gfgGameNews.PostTime = field.NewTime(tableName, "post_time")
	_gfgGameNews.CreateTime = field.NewTime(tableName, "create_time")
	_gfgGameNews.Author = field.NewString(tableName, "author")
	_gfgGameNews.URL = field.NewString(tableName, "url")
	_gfgGameNews.Total = field.NewInt64(tableName, "total")
	_gfgGameNews.Lang = field.NewString(tableName, "lang")

	_gfgGameNews.fillFieldMap()

	return _gfgGameNews
}

type gfgGameNews struct {
	gfgGameNewsDo

	ALL        field.Asterisk
	ID         field.Int64  // 游戏更新公告记录表id
	GameID     field.Int64  // 游戏表id
	Headline   field.String // 更新公告标题
	Content    field.String // 更新公告内容
	Index      field.Int64  // 更新公告编号
	PostTime   field.Time   // 更新公告上传日期
	CreateTime field.Time   // 采集时间
	Author     field.String // 公告作者
	URL        field.String // 更新公告原始地址
	Total      field.Int64  // 公告总数
	Lang       field.String // 记录的语言

	fieldMap map[string]field.Expr
}

func (g gfgGameNews) Table(newTableName string) *gfgGameNews {
	g.gfgGameNewsDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gfgGameNews) As(alias string) *gfgGameNews {
	g.gfgGameNewsDo.DO = *(g.gfgGameNewsDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gfgGameNews) updateTableName(table string) *gfgGameNews {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.GameID = field.NewInt64(table, "game_id")
	g.Headline = field.NewString(table, "headline")
	g.Content = field.NewString(table, "content")
	g.Index = field.NewInt64(table, "index")
	g.PostTime = field.NewTime(table, "post_time")
	g.CreateTime = field.NewTime(table, "create_time")
	g.Author = field.NewString(table, "author")
	g.URL = field.NewString(table, "url")
	g.Total = field.NewInt64(table, "total")
	g.Lang = field.NewString(table, "lang")

	g.fillFieldMap()

	return g
}

func (g *gfgGameNews) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gfgGameNews) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 11)
	g.fieldMap["id"] = g.ID
	g.fieldMap["game_id"] = g.GameID
	g.fieldMap["headline"] = g.Headline
	g.fieldMap["content"] = g.Content
	g.fieldMap["index"] = g.Index
	g.fieldMap["post_time"] = g.PostTime
	g.fieldMap["create_time"] = g.CreateTime
	g.fieldMap["author"] = g.Author
	g.fieldMap["url"] = g.URL
	g.fieldMap["total"] = g.Total
	g.fieldMap["lang"] = g.Lang
}

func (g gfgGameNews) clone(db *gorm.DB) gfgGameNews {
	g.gfgGameNewsDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gfgGameNews) replaceDB(db *gorm.DB) gfgGameNews {
	g.gfgGameNewsDo.ReplaceDB(db)
	return g
}

type gfgGameNewsDo struct{ gen.DO }

func (g gfgGameNewsDo) Debug() *gfgGameNewsDo {
	return g.withDO(g.DO.Debug())
}

func (g gfgGameNewsDo) WithContext(ctx context.Context) *gfgGameNewsDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gfgGameNewsDo) ReadDB() *gfgGameNewsDo {
	return g.Clauses(dbresolver.Read)
}

func (g gfgGameNewsDo) WriteDB() *gfgGameNewsDo {
	return g.Clauses(dbresolver.Write)
}

func (g gfgGameNewsDo) Session(config *gorm.Session) *gfgGameNewsDo {
	return g.withDO(g.DO.Session(config))
}

func (g gfgGameNewsDo) Clauses(conds ...clause.Expression) *gfgGameNewsDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gfgGameNewsDo) Returning(value interface{}, columns ...string) *gfgGameNewsDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gfgGameNewsDo) Not(conds ...gen.Condition) *gfgGameNewsDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gfgGameNewsDo) Or(conds ...gen.Condition) *gfgGameNewsDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gfgGameNewsDo) Select(conds ...field.Expr) *gfgGameNewsDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gfgGameNewsDo) Where(conds ...gen.Condition) *gfgGameNewsDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gfgGameNewsDo) Order(conds ...field.Expr) *gfgGameNewsDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gfgGameNewsDo) Distinct(cols ...field.Expr) *gfgGameNewsDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gfgGameNewsDo) Omit(cols ...field.Expr) *gfgGameNewsDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gfgGameNewsDo) Join(table schema.Tabler, on ...field.Expr) *gfgGameNewsDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gfgGameNewsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *gfgGameNewsDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gfgGameNewsDo) RightJoin(table schema.Tabler, on ...field.Expr) *gfgGameNewsDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gfgGameNewsDo) Group(cols ...field.Expr) *gfgGameNewsDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gfgGameNewsDo) Having(conds ...gen.Condition) *gfgGameNewsDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gfgGameNewsDo) Limit(limit int) *gfgGameNewsDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gfgGameNewsDo) Offset(offset int) *gfgGameNewsDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gfgGameNewsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *gfgGameNewsDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gfgGameNewsDo) Unscoped() *gfgGameNewsDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gfgGameNewsDo) Create(values ...*model.GfgGameNews) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gfgGameNewsDo) CreateInBatches(values []*model.GfgGameNews, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gfgGameNewsDo) Save(values ...*model.GfgGameNews) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gfgGameNewsDo) First() (*model.GfgGameNews, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGameNews), nil
	}
}

func (g gfgGameNewsDo) Take() (*model.GfgGameNews, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGameNews), nil
	}
}

func (g gfgGameNewsDo) Last() (*model.GfgGameNews, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGameNews), nil
	}
}

func (g gfgGameNewsDo) Find() ([]*model.GfgGameNews, error) {
	result, err := g.DO.Find()
	return result.([]*model.GfgGameNews), err
}

func (g gfgGameNewsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GfgGameNews, err error) {
	buf := make([]*model.GfgGameNews, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gfgGameNewsDo) FindInBatches(result *[]*model.GfgGameNews, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gfgGameNewsDo) Attrs(attrs ...field.AssignExpr) *gfgGameNewsDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gfgGameNewsDo) Assign(attrs ...field.AssignExpr) *gfgGameNewsDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gfgGameNewsDo) Joins(fields ...field.RelationField) *gfgGameNewsDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gfgGameNewsDo) Preload(fields ...field.RelationField) *gfgGameNewsDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gfgGameNewsDo) FirstOrInit() (*model.GfgGameNews, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGameNews), nil
	}
}

func (g gfgGameNewsDo) FirstOrCreate() (*model.GfgGameNews, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGameNews), nil
	}
}

func (g gfgGameNewsDo) FindByPage(offset int, limit int) (result []*model.GfgGameNews, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gfgGameNewsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gfgGameNewsDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gfgGameNewsDo) Delete(models ...*model.GfgGameNews) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gfgGameNewsDo) withDO(do gen.Dao) *gfgGameNewsDo {
	g.DO = *do.(*gen.DO)
	return g
}
