// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gofurry/gorm-generator/model"
)

func newGfgPrize(db *gorm.DB, opts ...gen.DOOption) gfgPrize {
	_gfgPrize := gfgPrize{}

	_gfgPrize.gfgPrizeDo.UseDB(db, opts...)
	_gfgPrize.gfgPrizeDo.UseModel(&model.GfgPrize{})

	tableName := _gfgPrize.gfgPrizeDo.TableName()
	_gfgPrize.ALL = field.NewAsterisk(tableName)
	_gfgPrize.ID = field.NewInt64(tableName, "id")
	_gfgPrize.Title = field.NewString(tableName, "title")
	_gfgPrize.Desc = field.NewString(tableName, "desc")
	_gfgPrize.Prize = field.NewString(tableName, "prize")
	_gfgPrize.Key = field.NewString(tableName, "key")
	_gfgPrize.StartTime = field.NewTime(tableName, "start_time")
	_gfgPrize.EndTime = field.NewTime(tableName, "end_time")
	_gfgPrize.CreateTime = field.NewTime(tableName, "create_time")
	_gfgPrize.Status = field.NewBool(tableName, "status")

	_gfgPrize.fillFieldMap()

	return _gfgPrize
}

type gfgPrize struct {
	gfgPrizeDo

	ALL        field.Asterisk
	ID         field.Int64  // 抽奖活动表id
	Title      field.String // 标题
	Desc       field.String // 描述
	Prize      field.String // 奖品
	Key        field.String // 参与密钥
	StartTime  field.Time   // 开始时间
	EndTime    field.Time   // 结束时间
	CreateTime field.Time   // 创建时间
	Status     field.Bool   // 状态

	fieldMap map[string]field.Expr
}

func (g gfgPrize) Table(newTableName string) *gfgPrize {
	g.gfgPrizeDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gfgPrize) As(alias string) *gfgPrize {
	g.gfgPrizeDo.DO = *(g.gfgPrizeDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gfgPrize) updateTableName(table string) *gfgPrize {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.Title = field.NewString(table, "title")
	g.Desc = field.NewString(table, "desc")
	g.Prize = field.NewString(table, "prize")
	g.Key = field.NewString(table, "key")
	g.StartTime = field.NewTime(table, "start_time")
	g.EndTime = field.NewTime(table, "end_time")
	g.CreateTime = field.NewTime(table, "create_time")
	g.Status = field.NewBool(table, "status")

	g.fillFieldMap()

	return g
}

func (g *gfgPrize) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gfgPrize) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 9)
	g.fieldMap["id"] = g.ID
	g.fieldMap["title"] = g.Title
	g.fieldMap["desc"] = g.Desc
	g.fieldMap["prize"] = g.Prize
	g.fieldMap["key"] = g.Key
	g.fieldMap["start_time"] = g.StartTime
	g.fieldMap["end_time"] = g.EndTime
	g.fieldMap["create_time"] = g.CreateTime
	g.fieldMap["status"] = g.Status
}

func (g gfgPrize) clone(db *gorm.DB) gfgPrize {
	g.gfgPrizeDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gfgPrize) replaceDB(db *gorm.DB) gfgPrize {
	g.gfgPrizeDo.ReplaceDB(db)
	return g
}

type gfgPrizeDo struct{ gen.DO }

func (g gfgPrizeDo) Debug() *gfgPrizeDo {
	return g.withDO(g.DO.Debug())
}

func (g gfgPrizeDo) WithContext(ctx context.Context) *gfgPrizeDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gfgPrizeDo) ReadDB() *gfgPrizeDo {
	return g.Clauses(dbresolver.Read)
}

func (g gfgPrizeDo) WriteDB() *gfgPrizeDo {
	return g.Clauses(dbresolver.Write)
}

func (g gfgPrizeDo) Session(config *gorm.Session) *gfgPrizeDo {
	return g.withDO(g.DO.Session(config))
}

func (g gfgPrizeDo) Clauses(conds ...clause.Expression) *gfgPrizeDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gfgPrizeDo) Returning(value interface{}, columns ...string) *gfgPrizeDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gfgPrizeDo) Not(conds ...gen.Condition) *gfgPrizeDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gfgPrizeDo) Or(conds ...gen.Condition) *gfgPrizeDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gfgPrizeDo) Select(conds ...field.Expr) *gfgPrizeDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gfgPrizeDo) Where(conds ...gen.Condition) *gfgPrizeDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gfgPrizeDo) Order(conds ...field.Expr) *gfgPrizeDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gfgPrizeDo) Distinct(cols ...field.Expr) *gfgPrizeDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gfgPrizeDo) Omit(cols ...field.Expr) *gfgPrizeDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gfgPrizeDo) Join(table schema.Tabler, on ...field.Expr) *gfgPrizeDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gfgPrizeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *gfgPrizeDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gfgPrizeDo) RightJoin(table schema.Tabler, on ...field.Expr) *gfgPrizeDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gfgPrizeDo) Group(cols ...field.Expr) *gfgPrizeDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gfgPrizeDo) Having(conds ...gen.Condition) *gfgPrizeDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gfgPrizeDo) Limit(limit int) *gfgPrizeDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gfgPrizeDo) Offset(offset int) *gfgPrizeDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gfgPrizeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *gfgPrizeDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gfgPrizeDo) Unscoped() *gfgPrizeDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gfgPrizeDo) Create(values ...*model.GfgPrize) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gfgPrizeDo) CreateInBatches(values []*model.GfgPrize, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gfgPrizeDo) Save(values ...*model.GfgPrize) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gfgPrizeDo) First() (*model.GfgPrize, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgPrize), nil
	}
}

func (g gfgPrizeDo) Take() (*model.GfgPrize, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgPrize), nil
	}
}

func (g gfgPrizeDo) Last() (*model.GfgPrize, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgPrize), nil
	}
}

func (g gfgPrizeDo) Find() ([]*model.GfgPrize, error) {
	result, err := g.DO.Find()
	return result.([]*model.GfgPrize), err
}

func (g gfgPrizeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GfgPrize, err error) {
	buf := make([]*model.GfgPrize, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gfgPrizeDo) FindInBatches(result *[]*model.GfgPrize, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gfgPrizeDo) Attrs(attrs ...field.AssignExpr) *gfgPrizeDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gfgPrizeDo) Assign(attrs ...field.AssignExpr) *gfgPrizeDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gfgPrizeDo) Joins(fields ...field.RelationField) *gfgPrizeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gfgPrizeDo) Preload(fields ...field.RelationField) *gfgPrizeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gfgPrizeDo) FirstOrInit() (*model.GfgPrize, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgPrize), nil
	}
}

func (g gfgPrizeDo) FirstOrCreate() (*model.GfgPrize, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgPrize), nil
	}
}

func (g gfgPrizeDo) FindByPage(offset int, limit int) (result []*model.GfgPrize, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gfgPrizeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gfgPrizeDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gfgPrizeDo) Delete(models ...*model.GfgPrize) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gfgPrizeDo) withDO(do gen.Dao) *gfgPrizeDo {
	g.DO = *do.(*gen.DO)
	return g
}
