// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gofurry/gorm-generator/model"
)

func newGfgGame(db *gorm.DB, opts ...gen.DOOption) gfgGame {
	_gfgGame := gfgGame{}

	_gfgGame.gfgGameDo.UseDB(db, opts...)
	_gfgGame.gfgGameDo.UseModel(&model.GfgGame{})

	tableName := _gfgGame.gfgGameDo.TableName()
	_gfgGame.ALL = field.NewAsterisk(tableName)
	_gfgGame.ID = field.NewInt64(tableName, "id")
	_gfgGame.Name = field.NewString(tableName, "name")
	_gfgGame.NameEn = field.NewString(tableName, "name_en")
	_gfgGame.Info = field.NewString(tableName, "info")
	_gfgGame.InfoEn = field.NewString(tableName, "info_en")
	_gfgGame.CreateTime = field.NewTime(tableName, "create_time")
	_gfgGame.UpdateTime = field.NewTime(tableName, "update_time")
	_gfgGame.Resources = field.NewString(tableName, "resources")
	_gfgGame.Groups = field.NewString(tableName, "groups")
	_gfgGame.ReleaseDate = field.NewString(tableName, "release_date")
	_gfgGame.Developers = field.NewString(tableName, "developers")
	_gfgGame.Publishers = field.NewString(tableName, "publishers")
	_gfgGame.Appid = field.NewInt64(tableName, "appid")
	_gfgGame.Header = field.NewString(tableName, "header")
	_gfgGame.Links = field.NewString(tableName, "links")
	_gfgGame.Weight = field.NewInt64(tableName, "weight")
	_gfgGame.PrimaryTag = field.NewInt64(tableName, "primary_tag")
	_gfgGame.SecondaryTag = field.NewInt64(tableName, "secondary_tag")

	_gfgGame.fillFieldMap()

	return _gfgGame
}

type gfgGame struct {
	gfgGameDo

	ALL          field.Asterisk
	ID           field.Int64  // 游戏表ID
	Name         field.String // 游戏名称
	NameEn       field.String // 游戏英文名称
	Info         field.String // 游戏简介
	InfoEn       field.String // 游戏英文简介
	CreateTime   field.Time   // 创建时间
	UpdateTime   field.Time   // 更新时间
	Resources    field.String // 游戏相关资源
	Groups       field.String // 游戏相关社群
	ReleaseDate  field.String // 发行日期
	Developers   field.String // 开发商
	Publishers   field.String // 发行商
	Appid        field.Int64  // SteamAPI appid
	Header       field.String // 游戏封面图
	Links        field.String // 三方网站链接
	Weight       field.Int64  // 权重
	PrimaryTag   field.Int64  // 主标签
	SecondaryTag field.Int64  // 次标签

	fieldMap map[string]field.Expr
}

func (g gfgGame) Table(newTableName string) *gfgGame {
	g.gfgGameDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gfgGame) As(alias string) *gfgGame {
	g.gfgGameDo.DO = *(g.gfgGameDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gfgGame) updateTableName(table string) *gfgGame {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.Name = field.NewString(table, "name")
	g.NameEn = field.NewString(table, "name_en")
	g.Info = field.NewString(table, "info")
	g.InfoEn = field.NewString(table, "info_en")
	g.CreateTime = field.NewTime(table, "create_time")
	g.UpdateTime = field.NewTime(table, "update_time")
	g.Resources = field.NewString(table, "resources")
	g.Groups = field.NewString(table, "groups")
	g.ReleaseDate = field.NewString(table, "release_date")
	g.Developers = field.NewString(table, "developers")
	g.Publishers = field.NewString(table, "publishers")
	g.Appid = field.NewInt64(table, "appid")
	g.Header = field.NewString(table, "header")
	g.Links = field.NewString(table, "links")
	g.Weight = field.NewInt64(table, "weight")
	g.PrimaryTag = field.NewInt64(table, "primary_tag")
	g.SecondaryTag = field.NewInt64(table, "secondary_tag")

	g.fillFieldMap()

	return g
}

func (g *gfgGame) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gfgGame) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 18)
	g.fieldMap["id"] = g.ID
	g.fieldMap["name"] = g.Name
	g.fieldMap["name_en"] = g.NameEn
	g.fieldMap["info"] = g.Info
	g.fieldMap["info_en"] = g.InfoEn
	g.fieldMap["create_time"] = g.CreateTime
	g.fieldMap["update_time"] = g.UpdateTime
	g.fieldMap["resources"] = g.Resources
	g.fieldMap["groups"] = g.Groups
	g.fieldMap["release_date"] = g.ReleaseDate
	g.fieldMap["developers"] = g.Developers
	g.fieldMap["publishers"] = g.Publishers
	g.fieldMap["appid"] = g.Appid
	g.fieldMap["header"] = g.Header
	g.fieldMap["links"] = g.Links
	g.fieldMap["weight"] = g.Weight
	g.fieldMap["primary_tag"] = g.PrimaryTag
	g.fieldMap["secondary_tag"] = g.SecondaryTag
}

func (g gfgGame) clone(db *gorm.DB) gfgGame {
	g.gfgGameDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gfgGame) replaceDB(db *gorm.DB) gfgGame {
	g.gfgGameDo.ReplaceDB(db)
	return g
}

type gfgGameDo struct{ gen.DO }

func (g gfgGameDo) Debug() *gfgGameDo {
	return g.withDO(g.DO.Debug())
}

func (g gfgGameDo) WithContext(ctx context.Context) *gfgGameDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gfgGameDo) ReadDB() *gfgGameDo {
	return g.Clauses(dbresolver.Read)
}

func (g gfgGameDo) WriteDB() *gfgGameDo {
	return g.Clauses(dbresolver.Write)
}

func (g gfgGameDo) Session(config *gorm.Session) *gfgGameDo {
	return g.withDO(g.DO.Session(config))
}

func (g gfgGameDo) Clauses(conds ...clause.Expression) *gfgGameDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gfgGameDo) Returning(value interface{}, columns ...string) *gfgGameDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gfgGameDo) Not(conds ...gen.Condition) *gfgGameDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gfgGameDo) Or(conds ...gen.Condition) *gfgGameDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gfgGameDo) Select(conds ...field.Expr) *gfgGameDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gfgGameDo) Where(conds ...gen.Condition) *gfgGameDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gfgGameDo) Order(conds ...field.Expr) *gfgGameDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gfgGameDo) Distinct(cols ...field.Expr) *gfgGameDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gfgGameDo) Omit(cols ...field.Expr) *gfgGameDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gfgGameDo) Join(table schema.Tabler, on ...field.Expr) *gfgGameDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gfgGameDo) LeftJoin(table schema.Tabler, on ...field.Expr) *gfgGameDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gfgGameDo) RightJoin(table schema.Tabler, on ...field.Expr) *gfgGameDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gfgGameDo) Group(cols ...field.Expr) *gfgGameDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gfgGameDo) Having(conds ...gen.Condition) *gfgGameDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gfgGameDo) Limit(limit int) *gfgGameDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gfgGameDo) Offset(offset int) *gfgGameDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gfgGameDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *gfgGameDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gfgGameDo) Unscoped() *gfgGameDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gfgGameDo) Create(values ...*model.GfgGame) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gfgGameDo) CreateInBatches(values []*model.GfgGame, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gfgGameDo) Save(values ...*model.GfgGame) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gfgGameDo) First() (*model.GfgGame, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGame), nil
	}
}

func (g gfgGameDo) Take() (*model.GfgGame, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGame), nil
	}
}

func (g gfgGameDo) Last() (*model.GfgGame, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGame), nil
	}
}

func (g gfgGameDo) Find() ([]*model.GfgGame, error) {
	result, err := g.DO.Find()
	return result.([]*model.GfgGame), err
}

func (g gfgGameDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GfgGame, err error) {
	buf := make([]*model.GfgGame, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gfgGameDo) FindInBatches(result *[]*model.GfgGame, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gfgGameDo) Attrs(attrs ...field.AssignExpr) *gfgGameDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gfgGameDo) Assign(attrs ...field.AssignExpr) *gfgGameDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gfgGameDo) Joins(fields ...field.RelationField) *gfgGameDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gfgGameDo) Preload(fields ...field.RelationField) *gfgGameDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gfgGameDo) FirstOrInit() (*model.GfgGame, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGame), nil
	}
}

func (g gfgGameDo) FirstOrCreate() (*model.GfgGame, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfgGame), nil
	}
}

func (g gfgGameDo) FindByPage(offset int, limit int) (result []*model.GfgGame, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gfgGameDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gfgGameDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gfgGameDo) Delete(models ...*model.GfgGame) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gfgGameDo) withDO(do gen.Dao) *gfgGameDo {
	g.DO = *do.(*gen.DO)
	return g
}
