// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gofurry/gorm-generator/model"
)

func newGfnSite(db *gorm.DB, opts ...gen.DOOption) gfnSite {
	_gfnSite := gfnSite{}

	_gfnSite.gfnSiteDo.UseDB(db, opts...)
	_gfnSite.gfnSiteDo.UseModel(&model.GfnSite{})

	tableName := _gfnSite.gfnSiteDo.TableName()
	_gfnSite.ALL = field.NewAsterisk(tableName)
	_gfnSite.ID = field.NewInt64(tableName, "id")
	_gfnSite.Name = field.NewString(tableName, "name")
	_gfnSite.NameEn = field.NewString(tableName, "name_en")
	_gfnSite.Domain = field.NewString(tableName, "domain")
	_gfnSite.Info = field.NewString(tableName, "info")
	_gfnSite.InfoEn = field.NewString(tableName, "info_en")
	_gfnSite.CreateTime = field.NewTime(tableName, "create_time")
	_gfnSite.UpdateTime = field.NewTime(tableName, "update_time")
	_gfnSite.Country = field.NewString(tableName, "country")
	_gfnSite.Nsfw = field.NewString(tableName, "nsfw")
	_gfnSite.Welfare = field.NewString(tableName, "welfare")
	_gfnSite.Icon = field.NewString(tableName, "icon")
	_gfnSite.Deleted = field.NewBool(tableName, "deleted")

	_gfnSite.fillFieldMap()

	return _gfnSite
}

type gfnSite struct {
	gfnSiteDo

	ALL        field.Asterisk
	ID         field.Int64  // 站点表id
	Name       field.String // 站点名称
	NameEn     field.String // 站点名称-英文
	Domain     field.String // 站点域名
	Info       field.String // 站点描述
	InfoEn     field.String // 站点描述-英文
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 修改时间
	Country    field.String // 站点所属国家
	Nsfw       field.String // 是否NSFW 1 0
	Welfare    field.String // 是否公益项目 1 0
	Icon       field.String // 站点图标
	Deleted    field.Bool   // 软删除

	fieldMap map[string]field.Expr
}

func (g gfnSite) Table(newTableName string) *gfnSite {
	g.gfnSiteDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gfnSite) As(alias string) *gfnSite {
	g.gfnSiteDo.DO = *(g.gfnSiteDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gfnSite) updateTableName(table string) *gfnSite {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.Name = field.NewString(table, "name")
	g.NameEn = field.NewString(table, "name_en")
	g.Domain = field.NewString(table, "domain")
	g.Info = field.NewString(table, "info")
	g.InfoEn = field.NewString(table, "info_en")
	g.CreateTime = field.NewTime(table, "create_time")
	g.UpdateTime = field.NewTime(table, "update_time")
	g.Country = field.NewString(table, "country")
	g.Nsfw = field.NewString(table, "nsfw")
	g.Welfare = field.NewString(table, "welfare")
	g.Icon = field.NewString(table, "icon")
	g.Deleted = field.NewBool(table, "deleted")

	g.fillFieldMap()

	return g
}

func (g *gfnSite) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gfnSite) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 13)
	g.fieldMap["id"] = g.ID
	g.fieldMap["name"] = g.Name
	g.fieldMap["name_en"] = g.NameEn
	g.fieldMap["domain"] = g.Domain
	g.fieldMap["info"] = g.Info
	g.fieldMap["info_en"] = g.InfoEn
	g.fieldMap["create_time"] = g.CreateTime
	g.fieldMap["update_time"] = g.UpdateTime
	g.fieldMap["country"] = g.Country
	g.fieldMap["nsfw"] = g.Nsfw
	g.fieldMap["welfare"] = g.Welfare
	g.fieldMap["icon"] = g.Icon
	g.fieldMap["deleted"] = g.Deleted
}

func (g gfnSite) clone(db *gorm.DB) gfnSite {
	g.gfnSiteDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gfnSite) replaceDB(db *gorm.DB) gfnSite {
	g.gfnSiteDo.ReplaceDB(db)
	return g
}

type gfnSiteDo struct{ gen.DO }

func (g gfnSiteDo) Debug() *gfnSiteDo {
	return g.withDO(g.DO.Debug())
}

func (g gfnSiteDo) WithContext(ctx context.Context) *gfnSiteDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gfnSiteDo) ReadDB() *gfnSiteDo {
	return g.Clauses(dbresolver.Read)
}

func (g gfnSiteDo) WriteDB() *gfnSiteDo {
	return g.Clauses(dbresolver.Write)
}

func (g gfnSiteDo) Session(config *gorm.Session) *gfnSiteDo {
	return g.withDO(g.DO.Session(config))
}

func (g gfnSiteDo) Clauses(conds ...clause.Expression) *gfnSiteDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gfnSiteDo) Returning(value interface{}, columns ...string) *gfnSiteDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gfnSiteDo) Not(conds ...gen.Condition) *gfnSiteDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gfnSiteDo) Or(conds ...gen.Condition) *gfnSiteDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gfnSiteDo) Select(conds ...field.Expr) *gfnSiteDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gfnSiteDo) Where(conds ...gen.Condition) *gfnSiteDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gfnSiteDo) Order(conds ...field.Expr) *gfnSiteDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gfnSiteDo) Distinct(cols ...field.Expr) *gfnSiteDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gfnSiteDo) Omit(cols ...field.Expr) *gfnSiteDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gfnSiteDo) Join(table schema.Tabler, on ...field.Expr) *gfnSiteDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gfnSiteDo) LeftJoin(table schema.Tabler, on ...field.Expr) *gfnSiteDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gfnSiteDo) RightJoin(table schema.Tabler, on ...field.Expr) *gfnSiteDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gfnSiteDo) Group(cols ...field.Expr) *gfnSiteDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gfnSiteDo) Having(conds ...gen.Condition) *gfnSiteDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gfnSiteDo) Limit(limit int) *gfnSiteDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gfnSiteDo) Offset(offset int) *gfnSiteDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gfnSiteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *gfnSiteDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gfnSiteDo) Unscoped() *gfnSiteDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gfnSiteDo) Create(values ...*model.GfnSite) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gfnSiteDo) CreateInBatches(values []*model.GfnSite, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gfnSiteDo) Save(values ...*model.GfnSite) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gfnSiteDo) First() (*model.GfnSite, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfnSite), nil
	}
}

func (g gfnSiteDo) Take() (*model.GfnSite, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfnSite), nil
	}
}

func (g gfnSiteDo) Last() (*model.GfnSite, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfnSite), nil
	}
}

func (g gfnSiteDo) Find() ([]*model.GfnSite, error) {
	result, err := g.DO.Find()
	return result.([]*model.GfnSite), err
}

func (g gfnSiteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GfnSite, err error) {
	buf := make([]*model.GfnSite, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gfnSiteDo) FindInBatches(result *[]*model.GfnSite, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gfnSiteDo) Attrs(attrs ...field.AssignExpr) *gfnSiteDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gfnSiteDo) Assign(attrs ...field.AssignExpr) *gfnSiteDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gfnSiteDo) Joins(fields ...field.RelationField) *gfnSiteDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gfnSiteDo) Preload(fields ...field.RelationField) *gfnSiteDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gfnSiteDo) FirstOrInit() (*model.GfnSite, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfnSite), nil
	}
}

func (g gfnSiteDo) FirstOrCreate() (*model.GfnSite, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfnSite), nil
	}
}

func (g gfnSiteDo) FindByPage(offset int, limit int) (result []*model.GfnSite, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gfnSiteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gfnSiteDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gfnSiteDo) Delete(models ...*model.GfnSite) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gfnSiteDo) withDO(do gen.Dao) *gfnSiteDo {
	g.DO = *do.(*gen.DO)
	return g
}
