// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gofurry/gorm-generator/model"
)

func newGfnLogUpdate(db *gorm.DB, opts ...gen.DOOption) gfnLogUpdate {
	_gfnLogUpdate := gfnLogUpdate{}

	_gfnLogUpdate.gfnLogUpdateDo.UseDB(db, opts...)
	_gfnLogUpdate.gfnLogUpdateDo.UseModel(&model.GfnLogUpdate{})

	tableName := _gfnLogUpdate.gfnLogUpdateDo.TableName()
	_gfnLogUpdate.ALL = field.NewAsterisk(tableName)
	_gfnLogUpdate.ID = field.NewInt64(tableName, "id")
	_gfnLogUpdate.Title = field.NewString(tableName, "title")
	_gfnLogUpdate.URL = field.NewString(tableName, "url")
	_gfnLogUpdate.CreateTime = field.NewTime(tableName, "create_time")
	_gfnLogUpdate.UpdateTime = field.NewTime(tableName, "update_time")
	_gfnLogUpdate.Deleted = field.NewBool(tableName, "deleted")

	_gfnLogUpdate.fillFieldMap()

	return _gfnLogUpdate
}

type gfnLogUpdate struct {
	gfnLogUpdateDo

	ALL        field.Asterisk
	ID         field.Int64  // 更新公告表id
	Title      field.String // 更新公告标题
	URL        field.String // 更新公告文档地址
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 更新时间
	Deleted    field.Bool   // 软删除

	fieldMap map[string]field.Expr
}

func (g gfnLogUpdate) Table(newTableName string) *gfnLogUpdate {
	g.gfnLogUpdateDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gfnLogUpdate) As(alias string) *gfnLogUpdate {
	g.gfnLogUpdateDo.DO = *(g.gfnLogUpdateDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gfnLogUpdate) updateTableName(table string) *gfnLogUpdate {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.Title = field.NewString(table, "title")
	g.URL = field.NewString(table, "url")
	g.CreateTime = field.NewTime(table, "create_time")
	g.UpdateTime = field.NewTime(table, "update_time")
	g.Deleted = field.NewBool(table, "deleted")

	g.fillFieldMap()

	return g
}

func (g *gfnLogUpdate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gfnLogUpdate) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 6)
	g.fieldMap["id"] = g.ID
	g.fieldMap["title"] = g.Title
	g.fieldMap["url"] = g.URL
	g.fieldMap["create_time"] = g.CreateTime
	g.fieldMap["update_time"] = g.UpdateTime
	g.fieldMap["deleted"] = g.Deleted
}

func (g gfnLogUpdate) clone(db *gorm.DB) gfnLogUpdate {
	g.gfnLogUpdateDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gfnLogUpdate) replaceDB(db *gorm.DB) gfnLogUpdate {
	g.gfnLogUpdateDo.ReplaceDB(db)
	return g
}

type gfnLogUpdateDo struct{ gen.DO }

func (g gfnLogUpdateDo) Debug() *gfnLogUpdateDo {
	return g.withDO(g.DO.Debug())
}

func (g gfnLogUpdateDo) WithContext(ctx context.Context) *gfnLogUpdateDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gfnLogUpdateDo) ReadDB() *gfnLogUpdateDo {
	return g.Clauses(dbresolver.Read)
}

func (g gfnLogUpdateDo) WriteDB() *gfnLogUpdateDo {
	return g.Clauses(dbresolver.Write)
}

func (g gfnLogUpdateDo) Session(config *gorm.Session) *gfnLogUpdateDo {
	return g.withDO(g.DO.Session(config))
}

func (g gfnLogUpdateDo) Clauses(conds ...clause.Expression) *gfnLogUpdateDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gfnLogUpdateDo) Returning(value interface{}, columns ...string) *gfnLogUpdateDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gfnLogUpdateDo) Not(conds ...gen.Condition) *gfnLogUpdateDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gfnLogUpdateDo) Or(conds ...gen.Condition) *gfnLogUpdateDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gfnLogUpdateDo) Select(conds ...field.Expr) *gfnLogUpdateDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gfnLogUpdateDo) Where(conds ...gen.Condition) *gfnLogUpdateDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gfnLogUpdateDo) Order(conds ...field.Expr) *gfnLogUpdateDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gfnLogUpdateDo) Distinct(cols ...field.Expr) *gfnLogUpdateDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gfnLogUpdateDo) Omit(cols ...field.Expr) *gfnLogUpdateDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gfnLogUpdateDo) Join(table schema.Tabler, on ...field.Expr) *gfnLogUpdateDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gfnLogUpdateDo) LeftJoin(table schema.Tabler, on ...field.Expr) *gfnLogUpdateDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gfnLogUpdateDo) RightJoin(table schema.Tabler, on ...field.Expr) *gfnLogUpdateDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gfnLogUpdateDo) Group(cols ...field.Expr) *gfnLogUpdateDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gfnLogUpdateDo) Having(conds ...gen.Condition) *gfnLogUpdateDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gfnLogUpdateDo) Limit(limit int) *gfnLogUpdateDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gfnLogUpdateDo) Offset(offset int) *gfnLogUpdateDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gfnLogUpdateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *gfnLogUpdateDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gfnLogUpdateDo) Unscoped() *gfnLogUpdateDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gfnLogUpdateDo) Create(values ...*model.GfnLogUpdate) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gfnLogUpdateDo) CreateInBatches(values []*model.GfnLogUpdate, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gfnLogUpdateDo) Save(values ...*model.GfnLogUpdate) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gfnLogUpdateDo) First() (*model.GfnLogUpdate, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfnLogUpdate), nil
	}
}

func (g gfnLogUpdateDo) Take() (*model.GfnLogUpdate, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfnLogUpdate), nil
	}
}

func (g gfnLogUpdateDo) Last() (*model.GfnLogUpdate, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfnLogUpdate), nil
	}
}

func (g gfnLogUpdateDo) Find() ([]*model.GfnLogUpdate, error) {
	result, err := g.DO.Find()
	return result.([]*model.GfnLogUpdate), err
}

func (g gfnLogUpdateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GfnLogUpdate, err error) {
	buf := make([]*model.GfnLogUpdate, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gfnLogUpdateDo) FindInBatches(result *[]*model.GfnLogUpdate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gfnLogUpdateDo) Attrs(attrs ...field.AssignExpr) *gfnLogUpdateDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gfnLogUpdateDo) Assign(attrs ...field.AssignExpr) *gfnLogUpdateDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gfnLogUpdateDo) Joins(fields ...field.RelationField) *gfnLogUpdateDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gfnLogUpdateDo) Preload(fields ...field.RelationField) *gfnLogUpdateDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gfnLogUpdateDo) FirstOrInit() (*model.GfnLogUpdate, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfnLogUpdate), nil
	}
}

func (g gfnLogUpdateDo) FirstOrCreate() (*model.GfnLogUpdate, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GfnLogUpdate), nil
	}
}

func (g gfnLogUpdateDo) FindByPage(offset int, limit int) (result []*model.GfnLogUpdate, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gfnLogUpdateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gfnLogUpdateDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gfnLogUpdateDo) Delete(models ...*model.GfnLogUpdate) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gfnLogUpdateDo) withDO(do gen.Dao) *gfnLogUpdateDo {
	g.DO = *do.(*gen.DO)
	return g
}
