// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGfgGameComment = "gfg_game_comment"

// GfgGameComment mapped from table <gfg_game_comment>
type GfgGameComment struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;comment:评论表ID" json:"id"`                                         // 评论表ID
	Region     string    `gorm:"column:region;type:character varying(50);not null;comment:地区" json:"region"`                       // 地区
	Content    string    `gorm:"column:content;type:character varying(255);not null;comment:评论" json:"content"`                    // 评论
	Score      float64   `gorm:"column:score;type:double precision;not null;comment:评分" json:"score"`                              // 评分
	CreateTime time.Time `gorm:"column:create_time;type:int;type:unsigned;not null;autoCreateTime;comment:创建时间" json:"createTime"` // 创建时间
	GameID     int64     `gorm:"column:game_id;type:bigint;not null;comment:游戏表ID" json:"gameId,string"`                           // 游戏表ID
	IP         string    `gorm:"column:ip;type:character varying(50);not null;comment:ip" json:"ip"`                               // ip
	Name       *string   `gorm:"column:name;type:character varying(50);comment:评论人名称" json:"name"`                                 // 评论人名称
}

// TableName GfgGameComment's table name
func (*GfgGameComment) TableName() string {
	return TableNameGfgGameComment
}
