// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGfgPrizeMember = "gfg_prize_member"

// GfgPrizeMember mapped from table <gfg_prize_member>
type GfgPrizeMember struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;comment:抽奖活动参与表id" json:"id"`                                     // 抽奖活动参与表id
	PrizeID    int64     `gorm:"column:prize_id;type:bigint;not null;comment:抽奖活动id" json:"prizeId,string"`                        // 抽奖活动id
	Name       string    `gorm:"column:name;type:character varying(50);not null;comment:参与者名称" json:"name"`                        // 参与者名称
	Email      string    `gorm:"column:email;type:character varying(255);not null;comment:参与者邮箱" json:"email"`                     // 参与者邮箱
	IP         string    `gorm:"column:ip;type:character varying(50);not null;comment:参与者ip" json:"ip"`                            // 参与者ip
	Agent      string    `gorm:"column:agent;type:character varying(255);not null;comment:User-Agent" json:"agent"`                // User-Agent
	IsWinner   bool      `gorm:"column:is_winner;type:boolean;not null;comment:是否获奖" json:"isWinner"`                              // 是否获奖
	PrizeKey   *string   `gorm:"column:prize_key;type:character varying(255);comment:获奖key" json:"prizeKey"`                       // 获奖key
	CreateTime time.Time `gorm:"column:create_time;type:int;type:unsigned;not null;autoCreateTime;comment:创建时间" json:"createTime"` // 创建时间
}

// TableName GfgPrizeMember's table name
func (*GfgPrizeMember) TableName() string {
	return TableNameGfgPrizeMember
}
