// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGfnSite = "gfn_site"

// GfnSite mapped from table <gfn_site>
type GfnSite struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;comment:站点表id" json:"id"`                                                    // 站点表id
	Name       string    `gorm:"column:name;type:character varying(255);not null;comment:站点名称" json:"name"`                                   // 站点名称
	NameEn     string    `gorm:"column:name_en;type:character varying(255);not null;comment:站点名称-英文" json:"nameEn"`                           // 站点名称-英文
	Domain     string    `gorm:"column:domain;type:jsonb;not null;comment:站点域名" json:"domain"`                                                // 站点域名
	Info       string    `gorm:"column:info;type:text;not null;comment:站点描述" json:"info"`                                                     // 站点描述
	InfoEn     string    `gorm:"column:info_en;type:text;not null;comment:站点描述-英文" json:"infoEn"`                                             // 站点描述-英文
	CreateTime time.Time `gorm:"column:create_time;type:int;type:unsigned;not null;autoCreateTime;comment:创建时间" json:"createTime"`            // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:int;type:unsigned;not null;autoUpdateTime;comment:修改时间" json:"updateTime"`            // 修改时间
	Country    *string   `gorm:"column:country;type:character varying(20);comment:站点所属国家" json:"country"`                                     // 站点所属国家
	Nsfw       string    `gorm:"column:nsfw;type:character varying(4);not null;default:''::character varying;comment:是否NSFW 1 0" json:"nsfw"` // 是否NSFW 1 0
	Welfare    string    `gorm:"column:welfare;type:character varying(4);not null;comment:是否公益项目 1 0" json:"welfare"`                         // 是否公益项目 1 0
	Weight     int64     `gorm:"column:weight;type:bigint;not null;default:0;comment:权重" json:"weight"`                                        // 权重
	Icon       *string   `gorm:"column:icon;type:character varying(255);comment:站点图标" json:"icon"`                                            // 站点图标
	Deleted    *bool     `gorm:"column:deleted;type:boolean;comment:软删除" json:"deleted"`                                                      // 软删除
}

// TableName GfnSite's table name
func (*GfnSite) TableName() string {
	return TableNameGfnSite
}
