import { fileURLToPath } from 'node:url'
import { readFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { test, expect, openBackground, saveBackground, storedBackground } from '../fixtures/background-storage'

test('page background preserves original SVG through reactive save, reload and clear without uploading', async ({ page, runtime }) => {
  const mutations: string[] = []
  page.on('request', request => { if (!['GET', 'HEAD'].includes(request.method())) mutations.push(request.url()) })
  const panel = await openBackground(page)
  await panel.getByRole('button', { name: '本地图片', exact: true }).click()
  const svg = '<?xml version="1.0"?><!DOCTYPE svg><!-- exported drawing --><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><style>path { fill: black; }</style><path d="M1 1h3v3H1z"/></svg>'
  await panel.locator('input[type=file]').setInputFiles({ name: 'local.svg', mimeType: 'image/svg+xml', buffer: Buffer.from(svg) })
  await expect(panel).toContainText('local.svg')
  await panel.getByLabel('图案颜色', { exact: true }).fill('#123456')
  await panel.getByRole('slider', { name: '透明度' }).focus()
  await page.keyboard.press('Home')
  await panel.getByRole('textbox', { name: '平铺尺寸' }).fill('200')
  await saveBackground(page)
  let stored = await storedBackground(page)
  expect(stored.record).toMatchObject({ kind: 'svg', text: svg })
  expect(stored.preference).toEqual({ version: 1, source: 'local', overrides: { color: '#123456', opacity: 0, size_px: 200 } })
  expect(stored.raw).not.toMatch(/<svg|blob:|data:/)
  await page.reload({ waitUntil: 'load' })
  await expect(page.locator('[data-public-background]')).toHaveAttribute('data-pattern-status', 'local')
  stored = await storedBackground(page)
  expect(stored.record?.text).toBe(svg); expect(stored.preference.overrides.opacity).toBe(0)
  await openBackground(page, false)
  await panel.getByRole('button', { name: '清除本地背景' }).click()
  await saveBackground(page)
  expect((await storedBackground(page)).record).toBeNull()
  await expect(page.locator('[data-public-background]')).toHaveAttribute('data-pattern-status', 'default')
  expect(mutations).toEqual([]); runtime.assertQuiet()
})

test('page background decodes and persists a real raster instead of an SVG color mask', async ({ page, runtime }) => {
  const panel = await openBackground(page)
  await panel.getByRole('button', { name: '本地图片', exact: true }).click()
  const raster = fileURLToPath(new URL('../../../public/logo-mini.png', import.meta.url))
  await panel.locator('input[type=file]').setInputFiles(raster)
  await expect(panel).toContainText('logo-mini.png')
  await expect(panel.getByLabel('图案颜色', { exact: true })).toHaveCount(0)
  await saveBackground(page)
  const before = await storedBackground(page)
  expect(before.record).toMatchObject({ kind: 'raster', name: 'logo-mini.png' })
  expect(before.record!.size).toBeGreaterThan(0)
  expect(before.record!.decoded!.width).toBeGreaterThan(0)
  expect(before.record!.decoded!.height).toBeGreaterThan(0)
  expect(before.record!.digest).toBe(createHash('sha256').update(await readFile(raster)).digest('hex'))
  await page.reload({ waitUntil: 'load' })
  await expect(page.locator('[data-public-background]')).toHaveAttribute('data-pattern-status', 'local')
  expect((await storedBackground(page)).record).toEqual(before.record)
  await expect.poll(() => page.locator('.gf-public-background__pattern').evaluate(el => getComputedStyle(el).backgroundImage)).toContain('blob:')
  await expect(page.locator('.gf-public-background__pattern')).toHaveCSS('mask-image', 'none')
  runtime.assertQuiet()
})

test('server pattern saves only its ID and explicit overrides', async ({ page, runtime }) => {
  const panel = await openBackground(page)
  await panel.getByRole('button', { name: '服务端图案', exact: true }).click()
  await expect(panel).toContainText('Storage fixture')
  const slider = panel.getByRole('slider', { name: '透明度' })
  await slider.focus(); await page.keyboard.press('Home')
  for (let index = 0; index < 100; index++) await page.keyboard.press('ArrowRight')
  await saveBackground(page)
  const stored = await storedBackground(page)
  expect(stored.preference).toEqual({ version: 1, source: 'server', pattern_id: '12', overrides: { opacity: 0.1 } })
  expect(stored.raw).not.toMatch(/object_key|light_color|blob:|data:/)
  runtime.assertQuiet()
})
