import { test, expect, reviewDraft, rejectionText, assertReviewAppearance, assertReviewFocus, assertReviewFeedback, type ReviewScene } from '../fixtures/game-review-dialog'

async function expectReset(scene: ReviewScene) {
  await expect(scene.name).toHaveValue('')
  await expect(scene.content).toHaveValue('')
  await expect(scene.score).toHaveValue('0')
  await expect(scene.feedback).toHaveCount(0)
  await expect(scene.submit).toBeEnabled()
}
async function succeed(scene: ReviewScene, id: string, score: number) {
  const gate = scene.queue()
  await scene.submit.click()
  expect((await gate.waitReceived()).body).toEqual({ id, name: reviewDraft.name, content: reviewDraft.content, score })
  gate.release()
  await assertReviewFeedback(scene, scene.text.success, true)
  await expect(scene.submit).toBeEnabled()
  await expect(scene.dialog).toBeVisible()
}

test('Home review lifecycle resets settled drafts and switches game identity through real controls', async ({ review }) => {
  const scene = await review.open()
  await scene.openDialog()
  await expectReset(scene)
  await assertReviewAppearance(scene)
  await scene.fill()
  await scene.closeDialog()
  await scene.openDialog()
  await expectReset(scene)
  await scene.fill({ name: 'Discard this draft' })
  await scene.closeDialog(true)
  await scene.openDialog(1)
  await expectReset(scene)
  await scene.fill()
  await succeed(scene, '92', 4.3)
  await scene.closeDialog()
  scene.assertQuiet()
})

test('Required fields and lexical score validation block requests while inclusive 0 and 5 submit numbers', async ({ review }) => {
  const scene = await review.open()
  await scene.openDialog()
  for (const [name, content] of [['', ''], ['Reviewer', ''], ['', 'Comment'], ['   ', '   ']]) {
    await scene.name.fill(name!); await scene.content.fill(content!)
    await scene.submit.click()
    await assertReviewFeedback(scene, scene.text.required)
    expect(scene.submissions).toHaveLength(0)
  }
  await scene.fill()
  for (const score of ['', 'abc', '1e0', '-1', '5.1', '.5', '1.']) {
    await scene.score.fill(score)
    await scene.submit.click()
    await assertReviewFeedback(scene, scene.text.score)
    expect(scene.submissions).toHaveLength(0)
  }
  for (const score of [0, 5]) {
    await scene.closeDialog(); await scene.openDialog(); await expectReset(scene)
    await scene.fill({ score: String(score) })
    await succeed(scene, '91', score)
  }
  expect(scene.submissions).toHaveLength(2)
  scene.assertQuiet()
})

test('English Dark review trims fields, normalizes decimals and keeps success after a gated single submission', async ({ review }) => {
  const scene = await review.open({ locale: 'en', theme: 'dark' })
  await scene.openDialog()
  await assertReviewAppearance(scene)
  await scene.fill({ name: '  Reviewer  ', content: `  ${reviewDraft.content}  `, score: '4,26' })
  await scene.score.press('Tab')
  await expect(scene.score).toHaveValue('4.3')
  const gate = scene.queue()
  await scene.submit.click()
  expect((await gate.waitReceived()).body).toEqual({ id: '91', name: reviewDraft.name, content: reviewDraft.content, score: 4.3 })
  await expect(scene.submit).toBeDisabled()
  await expect(scene.submit).toHaveText('Commiting...')
  await expect(scene.submit).toHaveCSS('opacity', '0.56')
  const box = (await scene.submit.boundingBox())!
  await scene.page.mouse.click(box.x + box.width / 2, box.y + box.height / 2)
  await scene.settle()
  expect(scene.submissions).toHaveLength(1)
  gate.release()
  await assertReviewFeedback(scene, scene.text.success, true)
  await expect(scene.submit).toBeEnabled()
  await expect(scene.submit).toHaveText(scene.text.submit)
  await expect(scene.dialog).toBeVisible()
  await expect(scene.name).toHaveValue(reviewDraft.name)
  await expect(scene.content).toHaveValue(reviewDraft.content)
  await expect(scene.score).toHaveValue('4.3')
  scene.assertQuiet()
})

test('Business rejection preserves the draft and only a user retry clears the error with success', async ({ review }) => {
  const scene = await review.open()
  await scene.openDialog(); await scene.fill()
  const gate = scene.queue('rejected')
  await scene.submit.click(); await gate.waitReceived(); gate.release()
  await assertReviewFeedback(scene, rejectionText)
  await expect(scene.submit).toBeEnabled()
  await expect(scene.name).toHaveValue(reviewDraft.name)
  await expect(scene.content).toHaveValue(reviewDraft.content)
  await expect(scene.score).toHaveValue('4.3')
  expect(scene.submissions).toHaveLength(1)
  await succeed(scene, '91', 4.3)
  await expect(scene.dialog.getByText(rejectionText, { exact: true })).toHaveCount(0)
  expect(scene.submissions).toHaveLength(2)
  scene.assertQuiet()
})

test('One injected 503 shows the English failure and settled reopen clears feedback without retrying', async ({ review }) => {
  const scene = await review.open({ locale: 'en', theme: 'dark' })
  await scene.openDialog(); await scene.fill()
  const gate = scene.queue('unavailable')
  await scene.submit.click(); await gate.waitReceived(); gate.release()
  await assertReviewFeedback(scene, scene.text.failure)
  await expect(scene.submit).toBeEnabled()
  await expect(scene.name).toHaveValue(reviewDraft.name)
  await expect(scene.content).toHaveValue(reviewDraft.content)
  await expect(scene.score).toHaveValue('4.3')
  await scene.closeDialog(); await scene.openDialog(); await expectReset(scene)
  expect(scene.submissions).toHaveLength(1)
  scene.assertQuiet()
})

test('Search consumer opens the selected game without card navigation or post-success query refresh', async ({ review }) => {
  const scene = await review.open({ host: 'search', theme: 'dark' })
  const url = scene.page.url()
  await scene.openDialog()
  await expect(scene.page).toHaveURL(url)
  await assertReviewAppearance(scene)
  await scene.fill(); await succeed(scene, '83', 4.3)
  await expect(scene.page).toHaveURL(url)
  scene.assertQuiet()
})

test('Detail wrapper takes its ID from the route and leaves reviews and view tracking untouched after submit', async ({ review }) => {
  const scene = await review.open({ host: 'detail' })
  await scene.openDialog()
  await assertReviewAppearance(scene)
  await scene.fill(); await succeed(scene, '82', 4.3)
  await expect(scene.page).toHaveURL(/\/games\/82$/)
  scene.assertQuiet()
})

test('Mobile review fields retain focus appearance, keyboard order, bounds and backdrop draft reset', async ({ review }) => {
  const scene = await review.open({ width: 390 })
  await scene.openDialog(); await assertReviewAppearance(scene)
  await assertReviewFocus(scene)
  await scene.name.press('Tab'); await expect(scene.content).toBeFocused()
  await scene.content.press('Tab'); await expect(scene.score).toBeFocused()
  await scene.score.press('Tab'); await expect(scene.submit).toBeFocused()
  await scene.fill()
  await scene.assertBounds()
  await scene.closeDialog(true); await scene.openDialog(); await expectReset(scene)
  // Hover appearance belongs to real controls, not additional hover goldens.
  await scene.close.hover(); await scene.settle()
  await expect(scene.close).toHaveCSS('background-color', 'rgba(251, 146, 60, 0.12)')
  await expect(scene.close).toHaveCSS('color', 'rgba(124, 45, 18, 0.94)')
  await scene.submit.hover(); await scene.settle()
  await expect(scene.submit).toHaveCSS('background-color', 'rgba(154, 52, 18, 0.92)')
  await scene.page.mouse.move(1, 1); await scene.settle()
  scene.assertQuiet()
})
