import { test, expect } from '../fixtures/games-search'

for (const width of [1440, 390]) for (const theme of ['light', 'dark'] as const) {
  test(`Filter keyboard dialog isolates the background (${width} ${theme})`, async ({ search }) => {
    await search.page.setViewportSize({ width, height: width === 390 ? 844 : 900 })
    await search.open({ theme })
    const trigger = search.page.locator('.search-filter-button')
    await search.openFilter()
    await expect(search.filter).toHaveAttribute('role', 'dialog')
    await expect(search.filter).toHaveAttribute('aria-modal', 'true')
    await expect(search.keyword).toBeFocused()
    await expect(search.page.locator('#__nuxt')).toHaveAttribute('inert', '')
    const position = await search.page.evaluate(() => window.scrollY)
    await search.page.mouse.move(2, 2); await search.page.mouse.wheel(0, 600)
    await expect.poll(() => search.page.evaluate(() => window.scrollY)).toBe(position)
    const focusables = search.filter.locator('button:visible:not([disabled]):not([tabindex="-1"]), input:visible:not([disabled]):not([tabindex="-1"])')
    await focusables.last().focus(); await search.page.keyboard.press('Tab')
    await expect(focusables.first()).toBeFocused()
    await search.page.keyboard.press('Shift+Tab'); await expect(focusables.last()).toBeFocused()
    const before = search.page.url()
    await search.keyword.fill('discard-me')
    await search.page.keyboard.press('Escape')
    await expect(search.filter).toHaveCount(0); await expect(trigger).toBeFocused()
    await expect(search.page.locator('#__nuxt')).not.toHaveAttribute('inert', '')
    expect(search.page.url()).toBe(before); expect(search.calls('advanced')).toHaveLength(1)
    await search.openFilter(); await expect(search.keyword).toHaveValue(''); await search.cancel()
    search.assertQuiet()
  })
}

test('Jump rejects fractional input rather than writing an inconsistent route', async ({ search }) => {
  await search.open()
  await search.page.locator('.game-search-page-button').filter({ hasText: /^\.\.\.$/ }).first().click()
  const dialog = search.page.locator('.game-search-jump-dialog')
  await dialog.locator('input').fill('1.5')
  await dialog.locator('.game-search-jump-action--primary').click()
  await expect(dialog).toBeVisible()
  await expect(dialog.locator('input')).toHaveAttribute('aria-invalid', 'true')
  expect(new URL(search.page.url()).searchParams.get('page')).toBeNull()
  expect(search.calls('advanced')).toHaveLength(1)
  await search.page.keyboard.press('Escape')
})

for (const locale of ['zh', 'en'] as const) {
  test(`Jump validates integer boundaries and retains locale (${locale})`, async ({ search }) => {
    await search.open({ locale })
    const page = search.page, trigger = page.locator('.game-search-page-button').filter({ hasText: /^\.\.\.$/ }).first()
    const dialog = page.locator('.game-search-jump-dialog'), input = dialog.locator('input')
    await trigger.click(); await expect(input).toBeFocused()
    const original = page.url()
    for (const invalid of ['', '0', '-1', '1.5', '1e1', 'word', '9', '9007199254740993']) {
      await input.fill(invalid); await input.press('Enter')
      await expect(input).toHaveAttribute('aria-invalid', 'true')
      expect(page.url()).toBe(original); expect(search.calls('advanced')).toHaveLength(1)
    }
    await input.fill('1'); await input.press('Enter')
    await expect(dialog).toHaveCount(0); expect(search.calls('advanced')).toHaveLength(1)
    for (const target of [8, 4, 1]) {
      await trigger.click(); await expect(input).toHaveValue(String(target === 8 ? 1 : target === 4 ? 8 : 4))
      await input.fill(` ${target} `); await input.press('Enter')
      await expect(dialog).toHaveCount(0)
      await search.waitResults(`Result ${(target - 1) * 4 + 1}`, target === 8 ? 1 : 4)
      await expect(page.locator('.game-search-page-button[aria-current="page"]')).toHaveText(String(target))
      expect(new URL(page.url()).pathname).toBe(locale === 'en' ? '/en/games/search' : '/games/search')
    }
    expect(search.calls('advanced')).toHaveLength(4)
    await trigger.click(); await input.fill('bad'); await page.keyboard.press('Escape')
    await expect(trigger).toBeFocused(); await trigger.click(); await expect(input).toHaveValue('1')
    await page.keyboard.press('Escape'); search.assertQuiet()
  })
}

for (const theme of ['light', 'dark'] as const) {
  test(`Short mobile Jump is above Footer and restores focus (${theme})`, async ({ search }) => {
    await search.page.setViewportSize({ width: 390, height: 844 })
    await search.open({ theme, query: { pageSize: '1' } })
    const page = search.page, trigger = page.locator('.game-search-page-button').filter({ hasText: /^\.\.\.$/ }).first()
    await trigger.click()
    const panel = page.locator('.game-search-jump-dialog')
    await expect(panel).toHaveAttribute('aria-modal', 'true')
    expect(await panel.evaluate(element => {
      const box = element.getBoundingClientRect()
      return document.querySelector('.gf-footer-shell')!.getBoundingClientRect().top < innerHeight
        && [.1, .5, .95].every(ratio => element.contains(document.elementFromPoint(box.x + box.width / 2, box.y + box.height * ratio)))
    })).toBe(true)
    await panel.locator('input').fill('2')
    await panel.locator('.game-search-jump-action--primary').click()
    await search.waitResults('Result 2', 1)
    // The old ellipsis key disappears on page 2; focus falls back to its current page.
    await expect(page.locator('[aria-current="page"]')).toBeFocused(); search.assertQuiet()
  })
}

test('Calendar Escape consumes one layer and narrow Filter controls remain reachable', async ({ search }) => {
  await search.page.setViewportSize({ width: 390, height: 844 })
  await search.open({ fixedNow: '2026-09-18T12:40:00Z' }); await search.openFilter()
  const input = search.filter.locator('.dp__input').first()
  await input.click(); await expect(search.filter.locator('.dp__menu')).toBeVisible()
  await search.page.keyboard.press('Escape')
  await expect(search.filter.locator('.dp__menu')).toHaveCount(0)
  await expect(input).toBeFocused(); await expect(search.filter).toBeVisible()
  await search.page.keyboard.press('Escape'); await expect(search.filter).toHaveCount(0)
  await search.openFilter()
  await input.click()
  await search.filter.locator('.dp__cell_inner').filter({ hasText: /^18$/ }).click()
  await search.filter.locator('[data-test-id="open-time-picker-btn"]').click()
  await search.filter.locator('[data-test-id="hours-time-inc-btn-0"]').click()
  await search.filter.locator('[data-test-id="select-button"]').click()
  await expect(input).toHaveValue('09/18/2026, 13:40')
  await search.filter.locator('.game-date-picker').first().locator('.dp--clear-btn').click()
  await expect(input).toHaveValue('')
  const released = search.filter.getByRole('radio', { name: '已发售', exact: true })
  await released.focus(); await released.press('ArrowRight')
  await expect(search.filter.getByRole('radio', { name: '未发售', exact: true })).toHaveAttribute('aria-checked', 'true')
  await search.filter.getByRole('radio', { name: '未发售', exact: true }).press('ArrowLeft')
  await expect(released).toHaveAttribute('aria-checked', 'true')
  await search.page.setViewportSize({ width: 320, height: 844 })
  await search.filter.getByRole('button', { name: '展开', exact: true }).click()
  await expect(search.leaf('zh Leaf 1-18')).toBeVisible()
  await search.leaf('zh Leaf 1-18').press('Space')
  await expect(search.leaf('zh Leaf 1-18')).toHaveAttribute('aria-pressed', 'true')
  await search.page.keyboard.press('Escape'); await search.openFilter()
  await expect(search.leaf('zh Leaf 1-1')).toHaveAttribute('aria-pressed', 'false')
  await search.cancel(); search.assertQuiet()
})

test('History navigation while a dialog is open restores inert and document scrolling', async ({ search }) => {
  await search.open()
  await search.leaveForHome()
  await search.page.goBack()
  await search.waitResults('Result')
  await search.openFilter()
  await search.forwardToHome()
  await expect(search.filter).toHaveCount(0)
  await expect(search.page.locator('#__nuxt')).not.toHaveAttribute('inert', '')
  expect(await search.page.evaluate(() => document.documentElement.style.overflow)).toBe('')
  await search.input.focus(); await expect(search.input).toBeFocused()
  search.assertQuiet()
})
