import { test, expect, groupNames, assertGamesHomeAppearance, assertCardHover, assertStatsAppearance } from '../fixtures/games-home'

for (const theme of ['light', 'dark'] as const) {
  test(`Games Home SSR, local pagination, statistics and consumers (${theme})`, async ({ gamesHome }) => {
    const scene = await gamesHome.open({ theme })
    const { page, stats, sidebar, dock } = scene
    await assertGamesHomeAppearance(scene)
    await assertCardHover(scene)
    await expect(sidebar).toBeVisible()
    await expect(dock).toBeVisible()
    await expect(dock.getByRole('button')).toHaveAttribute('aria-label', '去抽奖')
    await expect(dock.getByRole('link')).toHaveAttribute('href', 'https://github.com/gofurry/gofurry-nav-site/issues')
    const lists = [scene.data.panel.latest_games, scene.data.panel.updated_games, scene.data.panel.free_games, scene.data.panel.popular_games!]
    for (let index = 0; index < 4; index++) {
      const group = scene.group(index), name = groupNames[index]!
      await expect(scene.cards(index).locator('.game-card__title')).toHaveText(lists[index]!.slice(0, 8).map(item => item.name))
      await group.getByRole('button', { name: `${name} next page`, exact: true }).click()
      await expect(group.locator('.game-group-pager > span')).toHaveText('2/2')
      await expect(scene.cards(index)).toHaveCount(1)
      await expect(scene.cards(index).locator('.game-card__title')).toHaveText(lists[index]![8]!.name)
      await group.getByRole('button', { name: `${name} next page`, exact: true }).click()
      await expect(group.locator('.game-group-pager > span')).toHaveText('1/2')
      await expect(scene.cards(index)).toHaveCount(8)
      await group.getByRole('button', { name: `${name} previous page`, exact: true }).click()
      await expect(scene.cards(index)).toHaveCount(1)
      await group.getByRole('button', { name: `${name} previous page`, exact: true }).click()
      await expect(scene.cards(index)).toHaveCount(8)
    }
    await expect(scene.cards(0).first().locator('.game-card__release-badge')).toContainText('2026年9月1日')
    await expect(scene.cards(1).first().locator('.game-card__release-badge')).toContainText('2027年2月14日')
    const count = stats.locator('.stats-type-tab').filter({ hasText: '在线人数' })
    const price = stats.locator('.stats-type-tab').filter({ hasText: '价格' })
    await expect(stats.locator('.game-stats-row:not(.game-stats-row--placeholder)')).toHaveCount(16)
    await price.click()
    await expect(price).toHaveClass(/stats-type-tab--active/)
    await expect(count).toHaveClass(/stats-type-tab--idle/)
    await page.mouse.move(1, 1)
    await assertStatsAppearance(scene)
    await expect(stats.locator('.stats-page-tab')).toHaveCount(3)
    const active = stats.locator('.game-stats-page-slide[aria-hidden="false"]')
    await expect(active.locator('.game-stats-feature__title')).toHaveText([lists[0]![0]!.name, lists[0]![1]!.name])
    await expect(active.locator('.game-stats-feature__value').first()).toHaveText('¥48.00')
    await expect(active.locator('.game-stats-row__discount--deal').first()).toHaveText('-50%')
    await stats.locator('.stats-page-tab').nth(1).click()
    await expect(stats.locator('.stats-page-tab--active')).toHaveText('2')
    await count.click()
    await expect(count).toHaveClass(/stats-type-tab--active/)
    await expect(stats.locator('.stats-page-tab--active')).toHaveText('1')
    await expect(stats.locator('.game-stats-row:not(.game-stats-row--placeholder)')).toHaveCount(16)
    const card = scene.cards(0).first()
    await card.hover()
    await card.getByRole('button', { name: `${lists[0]![0]!.name} review` }).click()
    const dialog = page.locator('.review-dialog')
    await expect(dialog).toBeVisible()
    await expect(dialog).toContainText(lists[0]![0]!.name)
    await expect(dialog.locator('textarea')).toBeVisible()
    await dialog.locator('.review-dialog__close').click()
    await expect(dialog).toHaveCount(0)
    await expect(sidebar.locator('.sidebar-expand-button')).toBeVisible()
    await sidebar.locator('.sidebar-expand-button').click()
    await expect(sidebar.getByRole('link', { name: /Patreon/ })).toBeVisible()
    scene.assertQuiet()
  })

  test(`Games Home mobile layout and pagination (${theme})`, async ({ gamesHome }) => {
    const scene = await gamesHome.open({ theme, width: 390 })
    await assertGamesHomeAppearance(scene)
    await expect(scene.sidebar).toBeHidden()
    await expect(scene.dock).toBeHidden()
    await expect(scene.cards(0)).toHaveCount(8)
    await scene.group(0).getByRole('button', { name: '最近发售 next page', exact: true }).click()
    await expect(scene.cards(0)).toHaveCount(1)
    await expect(scene.cards(0).locator('.game-card__title')).toHaveText('最近发售 9')
    await scene.group(0).getByRole('button', { name: '最近发售 previous page', exact: true }).click()
    await expect(scene.cards(0)).toHaveCount(8)
    await scene.settle(scene.group(0))
    const shell = await scene.group(0).locator('.game-group-page-shell').boundingBox()
    const last = await scene.cards(0).last().boundingBox()
    expect(last!.y + last!.height).toBeLessThanOrEqual(shell!.y + shell!.height)
    expect(await scene.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    scene.assertQuiet()
  })
}
