import { test, expect } from '../fixtures/game-detail-contract'

test('populated Facts preserve zero, priced zero, unknown, missing and platform states', async ({ detail }) => {
  await detail.open(); await detail.tab('insights')
  await expect(detail.page.locator('[data-current-players]')).toHaveText('0 人')
  await expect(detail.page.locator('[data-price-kind="priced"]')).toContainText('¥0.00')
  await expect(detail.page.locator('[data-price-kind="unknown"]')).toHaveCount(1)
  await expect(detail.page.locator('[data-price-kind="missing"]')).toHaveCount(1)
  await expect(detail.page.locator('[data-observed-low]')).toContainText('GoFurry 观测低价')
  await expect(detail.page.locator('.game-insights-platform-list')).toContainText('macOS')
  await expect(detail.page.locator('.game-insights-platform-list__state--unknown')).toHaveCount(1)
  await expect(detail.page.locator('[data-player-loaded-ranges]')).toHaveAttribute('data-player-loaded-ranges', '30d')
  detail.assertQuiet()
})

test('region and range caches survive tab switches without redundant history calls', async ({ detail }) => {
  await detail.open(); expect(detail.count('/games/82/insights/players')).toBe(0); await detail.tab('insights')
  const root = detail.page.locator('[data-game-insights]')
  await expect(detail.page.locator('[data-price-region-summary]')).toHaveCount(3)
  await expect(root).toHaveAttribute('data-price-loaded-ranges', 'CN:30d')
  await detail.page.getByRole('button', { name: '美国', exact: true }).click()
  await expect(root).toHaveAttribute('data-price-loaded-ranges', /US:30d/)
  await detail.page.getByRole('button', { name: '香港', exact: true }).click()
  await expect(root).toHaveAttribute('data-price-loaded-ranges', /HK:30d/)
  await detail.page.locator('[data-game-insights-range="90d"]').click()
  await expect(root).toHaveAttribute('data-player-loaded-ranges', '30d,90d')
  await detail.page.locator('[data-game-insights-range="30d"]').click()
  await detail.page.getByRole('button', { name: '中国', exact: true }).click()
  await detail.tab('intro'); await detail.tab('insights')
  expect(detail.count('/games/82/insights/players', { range: '30d' })).toBe(1)
  expect(detail.count('/games/82/insights/prices', { range: '30d', region: 'CN' })).toBe(1)
  expect(detail.count('/games/82/insights/prices', { range: '30d', region: 'US' })).toBe(1)
  expect(detail.count('/games/82/insights/prices', { range: '30d', region: 'HK' })).toBe(1)
  await expect(root).toHaveAttribute('data-price-region', 'CN'); detail.assertQuiet()
})

test('independent history failure, retry and out-of-order responses preserve the selected state', async ({ detail }) => {
  const recover = detail.fail('/games/82/insights/players', { range: '30d' })
  await detail.open(); await detail.tab('insights')
  const player = detail.page.locator('[data-player-history]'), price = detail.page.locator('[data-price-history]')
  await expect(player.getByRole('button')).toBeVisible(); await expect(price.locator('canvas')).toBeVisible()
  recover(); detail.points(1); await player.getByRole('button').click()
  await expect(player.locator('.game-insights-chart-state')).toBeVisible()
  const held = detail.hold('/games/82/insights/players', { range: '90d' }); detail.points(0)
  await detail.page.locator('[data-game-insights-range="90d"]').click(); await held.wait()
  await detail.page.locator('[data-game-insights-range="180d"]').click()
  await expect(detail.page.locator('[data-player-loaded-ranges]')).toHaveAttribute('data-player-loaded-ranges', /180d/)
  held.release(); await expect.poll(() => held.completed).toBe(true)
  await expect(detail.page.locator('[data-game-insights-range="180d"]')).toHaveAttribute('aria-pressed', 'true')
  await expect(player.locator('.game-insights-chart-state')).toBeVisible()
  const restorePrice = detail.fail('/games/82/insights/prices', { region: 'US', range: '180d' })
  await detail.page.getByRole('button', { name: '美国', exact: true }).click()
  await expect(price.getByRole('button')).toBeVisible()
  const playerReads = detail.count('/games/82/insights/players')
  restorePrice(); detail.points(8); await price.getByRole('button').click()
  await expect(price.locator('canvas')).toBeVisible()
  expect(detail.count('/games/82/insights/players')).toBe(playerReads)
  detail.assertQuiet()
})

test('Timeline and real chart themes retain date precision, ordering and responsive canvas', async ({ detail }) => {
  await detail.open(); await detail.tab('insights')
  const timeline = detail.page.locator('[data-entity-timeline]')
  await expect(timeline).toHaveAttribute('data-timeline-mode', 'compact')
  const before = await timeline.locator('time').allTextContents()
  expect(before[0]).toBe('2026-09-18'); expect(before[1]).toContain(':')
  await timeline.locator('button').last().click(); await expect(timeline).toHaveAttribute('data-timeline-mode', 'list')
  await expect(timeline.locator('button').last()).toHaveAttribute('aria-pressed', 'true')
  await expect(timeline.locator('button').last()).toHaveClass(/insights-ranges__button--active/)
  expect(await timeline.locator('time').allTextContents()).toEqual(before)
  const canvas = detail.page.locator('[data-player-history] canvas')
  await expect(canvas).toBeVisible(); await detail.settle(detail.page.locator('[data-player-history]'))
  const tooltipAppearance = async (kind: 'player' | 'price', dark: boolean) => {
    const root = detail.page.locator(`[data-${kind}-history]`), target = root.locator('canvas')
    await target.hover({ position: { x: (await target.boundingBox())!.width / 2, y: 150 } })
    const tooltip = root.locator('.game-insights-chart > div').last()
    await expect(tooltip).toContainText('2026-09')
    await expect(tooltip).toHaveCSS('background-color', dark ? 'rgba(15, 23, 42, 0.96)' : 'rgba(255, 250, 242, 0.98)')
    await expect(tooltip).toHaveCSS('color', dark ? 'rgb(226, 232, 240)' : 'rgb(41, 37, 36)')
    await expect(tooltip).toHaveCSS('border-color', kind === 'player'
      ? dark ? 'rgba(125, 211, 252, 0.28)' : 'rgba(217, 119, 6, 0.22)'
      : dark ? 'rgba(167, 243, 208, 0.28)' : 'rgba(21, 128, 61, 0.22)')
    await detail.page.mouse.move(1, 1); await expect(tooltip).toHaveCSS('visibility', 'hidden')
  }
  await tooltipAppearance('player', false); await tooltipAppearance('price', false)
  const light = await canvas.evaluate(el => (el as HTMLCanvasElement).toDataURL())
  const priceCanvas = detail.page.locator('[data-price-history] canvas')
  const lightPrice = await priceCanvas.evaluate(el => (el as HTMLCanvasElement).toDataURL())
  await detail.page.getByRole('button', { name: '切换明暗主题图标', exact: true }).click()
  await expect(detail.page.locator('html')).toHaveClass(/dark/)
  await expect.poll(() => canvas.evaluate(el => (el as HTMLCanvasElement).toDataURL())).not.toBe(light)
  await expect.poll(() => priceCanvas.evaluate(el => (el as HTMLCanvasElement).toDataURL())).not.toBe(lightPrice)
  const width = (await canvas.boundingBox())!.width
  await detail.page.setViewportSize({ width: 700, height: 900 })
  await expect.poll(async () => (await canvas.boundingBox())!.width).not.toBe(width)
  await detail.settle(detail.page.locator('[data-player-history]'))
  await tooltipAppearance('player', true); await tooltipAppearance('price', true)
  detail.assertQuiet()
})
