import { test, expect } from '../fixtures/game-detail-contract'

test('manual keyboard tabs do not load history until activation', async ({ detail }) => {
  await detail.open()
  const tabs = detail.page.locator('[data-game-tab]')
  await tabs.first().focus(); await detail.page.keyboard.press('ArrowRight')
  await expect(detail.page.locator('[data-game-tab="insights"]')).toBeFocused()
  await expect(tabs.first()).toHaveAttribute('aria-selected', 'true')
  expect(detail.count('/games/82/insights/players')).toBe(0)
  await detail.page.keyboard.press('ArrowLeft'); await expect(tabs.first()).toBeFocused()
  await detail.page.keyboard.press('ArrowRight')
  await detail.page.keyboard.press('Enter')
  await expect(detail.page.locator('[data-player-loaded-ranges]')).toHaveAttribute('data-player-loaded-ranges', '30d')
  await detail.page.keyboard.press('End'); await expect(tabs.last()).toBeFocused()
  await detail.page.keyboard.press('Home'); await expect(tabs.first()).toBeFocused()
  await detail.page.keyboard.press('Space'); await expect(tabs.first()).toHaveAttribute('aria-selected', 'true')
  detail.assertQuiet()
})

for (const width of [1440, 390]) test(`${width}px lightbox closes above Nav and restores keyboard/scroll ownership`, async ({ detail }) => {
  await detail.open({ width }); await detail.tab('gallery')
  const image = detail.page.locator('.game-detail-media-image'), box = detail.page.locator('.game-detail-lightbox')
  await expect(image).toBeVisible(); await detail.page.locator('.game-detail-thumb').last().click()
  await expect(image).toHaveAttribute('src', /detail-shot-11/)
  // This case tests dismissal/focus, not cancellation of an in-flight image.
  // Finish each image load before unmounting it; keep requestfailed checks strict.
  await image.evaluate(el => (el as HTMLImageElement).decode())
  const openLightbox = async () => {
    await image.click()
    await box.locator('img').evaluate(el => (el as HTMLImageElement).decode())
  }
  await openLightbox(); const close = box.locator('button')
  await expect(close).toBeFocused(); await expect(box).toHaveAttribute('role', 'dialog')
  expect(await box.evaluate(el => el.parentElement === document.body)).toBe(true)
  await box.locator('img').click(); await expect(box).toBeVisible()
  await detail.page.keyboard.press('Tab'); await expect(close).toBeFocused()
  await detail.page.keyboard.press('Shift+Tab'); await expect(close).toBeFocused()
  await close.click(); await expect(box).toHaveCount(0); await expect(image).toBeFocused()
  await openLightbox(); await detail.page.keyboard.press('Escape'); await expect(box).toHaveCount(0)
  await openLightbox(); await box.click({ position: { x: 2, y: 120 } }); await expect(box).toHaveCount(0)
  expect(await detail.page.locator('#__nuxt').evaluate(el => (el as HTMLElement).inert)).toBe(false)
  expect(await detail.page.evaluate(() => document.documentElement.style.overflow)).toBe('')
  await openLightbox(); await detail.page.goBack(); await expect(box).toHaveCount(0)
  detail.assertQuiet()
})

test('blocked adult content is inert and only confirmed mode unlocks it', async ({ detail }) => {
  await detail.open({ adult: true, width: 390 })
  const content = detail.page.locator('.blur-wrapper__content'), unlock = detail.page.locator('.blur-wrapper__unlock')
  await expect(content).toHaveAttribute('inert', '')
  await expect(content).toHaveCSS('filter', 'blur(24px)')
  await content.locator('a').focus(); await expect(content.locator('a')).not.toBeFocused()
  await detail.page.locator('[data-game-tab="intro"]').focus(); await detail.page.keyboard.press('Tab')
  await expect(unlock).toBeFocused()
  await unlock.click(); const dialog = detail.page.locator('.gf-modal--compact')
  await expect(dialog.locator('.gf-button--ghost')).toBeFocused()
  await detail.page.keyboard.press('Shift+Tab'); await expect(dialog.locator('.gf-button--primary')).toBeFocused()
  await detail.page.keyboard.press('Tab'); await expect(dialog.locator('.gf-button--ghost')).toBeFocused()
  await detail.page.keyboard.press('Escape'); await expect(dialog).toHaveCount(0); await expect(unlock).toBeFocused()
  await unlock.click(); await dialog.locator('.gf-button--ghost').click(); await expect(unlock).toBeVisible()
  await detail.tab('news'); await expect(content).toHaveAttribute('inert', '')
  await detail.tab('gallery'); await expect(detail.page.locator('video')).toHaveCount(0)
  await unlock.click(); await dialog.locator('.gf-button--primary').click()
  await expect(unlock).toHaveCount(0); await expect(content).not.toHaveAttribute('inert')
  expect(await detail.page.evaluate(() => localStorage.getItem('mode'))).toBe('nsfw')
  await expect(detail.page.locator('.game-detail-media-image')).toBeVisible()
  detail.assertQuiet()
})

test('a real video becomes ready and stops when Gallery is unmounted', async ({ detail }) => {
  await detail.open(); await detail.tab('gallery')
  const held = detail.movieGate()
  await detail.page.locator('.game-detail-thumb').first().click(); await held.wait()
  await expect(detail.page.locator('.game-detail-video-loading')).toBeVisible()
  held.release()
  const video = detail.page.locator('video')
  await expect.poll(() => video.evaluate(el => (el as HTMLVideoElement).readyState)).toBeGreaterThanOrEqual(2)
  await expect(detail.page.locator('.game-detail-video-loading')).toHaveCount(0)
  const handle = await video.elementHandle()
  await detail.tab('intro')
  expect(await handle!.evaluate(el => (el as HTMLVideoElement).paused)).toBe(true)
  await expect(video).toHaveCount(0)
  detail.failMovie(); await detail.tab('gallery'); await detail.page.locator('.game-detail-thumb').first().click()
  await expect.poll(() => video.evaluate(el => (el as HTMLVideoElement).error?.code)).toBe(4)
  await expect(detail.page.locator('.game-detail-video-loading')).toHaveCount(0)
  detail.assertQuiet()
})
