import { test, expect, heroOrigins, expectHeroLoaded } from '../fixtures/hero-preferences'

test('Save commits IDs but retains old Hero through independent API and real image gates', async ({ page, preferences }) => {
  await preferences.open()
  const before = await preferences.currentHero()
  await preferences.openPreferences()
  await page.getByRole('button', { name: '固定云端背景', exact: true }).click()
  await preferences.waitCatalogPosition(1)
  await preferences.browseCatalogTo(3)
  await page.getByRole('tab', { name: '手机', exact: true }).click()
  await preferences.waitCatalogPosition(1)
  await preferences.browseCatalogTo(2)
  // Change the file after preview so the real staged image cannot reuse its decode.
  const replacement = 'nav/hero/desktop/' + 'e'.repeat(32) + '.avif'
  preferences.replaceDesktopObjectKey('12', replacement)
  preferences.holdHeroAPI()
  preferences.holdHeroImages()
  await preferences.savePreferences()
  await expect.poll(() => preferences.heroCalls().length).toBe(1)
  expect(await preferences.cookieValue('gf_hero_mode')).toBe('fixed')
  expect(await preferences.cookieValue('gf_hero_desktop_id')).toBe('12')
  expect(await preferences.cookieValue('gf_hero_mobile_id')).toBe('9007199254740994')
  expect(await preferences.currentHero()).toBe(before)
  expect(preferences.requestedImages.some(url => url.endsWith(replacement))).toBe(false)
  preferences.releaseHeroAPI()
  await expect.poll(() => preferences.requestedImages.includes(`${heroOrigins.primary}/${replacement}`)).toBe(true)
  await expect(page.locator('[data-hero-pending]')).toHaveCount(1)
  expect(await preferences.currentHero()).toBe(before)
  preferences.releaseHeroImages()
  await expect.poll(() => preferences.currentHero()).toBe(`${heroOrigins.primary}/${replacement}`)
  await expectHeroLoaded(page)
  await expect(page.locator('[data-hero-pending]')).toHaveCount(0)
  expect(preferences.homeCalls()).toHaveLength(1)
  expect(preferences.heroCalls()).toHaveLength(1)
  expect(await preferences.cookieValue('gf_asset_cdn_mode')).toBe('primary')
  await preferences.reload()
  expect(await preferences.currentHero()).toBe(`${heroOrigins.primary}/${replacement}`)
  expect(preferences.errors).toEqual([])
})

test('Mobile-only selection plus Mirror pin retains successful Primary Desktop until viewport changes', async ({ page, preferences }) => {
  await preferences.open({ mode: 'fixed', desktopId: '12', mobileId: '9007199254740994' })
  const desktop = await preferences.currentHero()
  expect(desktop).toBe(`${heroOrigins.primary}/${preferences.desktopCatalog[2]!.object_key}`)
  await preferences.openPreferences()
  await preferences.waitCatalogPosition(3)
  await page.getByRole('tab', { name: '手机', exact: true }).click()
  await preferences.waitCatalogPosition(2)
  await preferences.browseCatalogTo(1)
  await page.locator('.preferences-tabs:not(.preferences-tabs--compact)').getByRole('tab').last().click()
  await page.locator('[data-resource-routing] .resource-route').first().getByRole('radio', { name: 'Cloudflare' }).check()
  await preferences.savePreferences()
  await expect.poll(() => preferences.heroCalls().length).toBe(1)
  // Wait for the response AND renderer promotion, not just modal close.
  await page.waitForLoadState('networkidle')
  await expect(page.locator('[data-hero-pending]')).toHaveCount(0)
  expect(await preferences.currentHero()).toBe(desktop)
  expect(await preferences.cookieValue('gf_asset_cdn_mode')).toBe('mirror')
  expect(await preferences.cookieValue('gf_hero_mobile_id')).toBe('9007199254740993')
  expect(preferences.requestedImages).not.toContain(`${heroOrigins.mirror}/${preferences.desktopCatalog[2]!.object_key}`)
  await page.setViewportSize({ width: 390, height: 1000 })
  await expect.poll(() => preferences.currentHero()).toBe(`${heroOrigins.mirror}/${preferences.mobileCatalog[0]!.object_key}`)
  await expectHeroLoaded(page)
  expect(preferences.homeCalls()).toHaveLength(1)
  expect(preferences.heroCalls()).toHaveLength(1)
  expect(preferences.errors).toEqual([])
})

test('failed staged Hero tries Mirror then Primary and retains the old successful frame', async ({ page, preferences }) => {
  await preferences.open({ mode: 'fixed', desktopId: '12' })
  const retained = await preferences.currentHero()
  await preferences.openPreferences()
  await preferences.waitCatalogPosition(3)
  await preferences.browseCatalogTo(5)
  const replacement = 'nav/hero/desktop/' + 'd'.repeat(32) + '.avif'
  preferences.replaceDesktopObjectKey('14', replacement)
  preferences.failedImageKey = replacement
  await page.locator('.preferences-tabs:not(.preferences-tabs--compact)').getByRole('tab').last().click()
  await page.locator('[data-resource-routing] .resource-route').first().getByRole('radio', { name: 'Cloudflare' }).check()
  await preferences.savePreferences()
  const expected = [`${heroOrigins.mirror}/${replacement}`, `${heroOrigins.primary}/${replacement}`]
  await expect.poll(() => preferences.requestedImages.filter(url => url.endsWith(replacement))).toEqual(expected)
  await expect(page.locator('[data-hero-pending]')).toHaveCount(0)
  expect([...preferences.expectedNetworkFailures]).toEqual(expected)
  expect(await preferences.currentHero()).toBe(retained)
  await expectHeroLoaded(page)
  expect(preferences.homeCalls()).toHaveLength(1)
  expect(preferences.heroCalls()).toHaveLength(1)
  expect(preferences.errors).toEqual([])
})
