import { test as lifecycleTest, heroOrigins, lifecycleKey } from '../fixtures/hero-lifecycle'
import { test, expect, displayedHero, expectHeroLoaded } from '../fixtures/hero-preferences'

lifecycleTest('two IndexedDB reads defer Local takeover until Managed Hero has painted', async ({ page, hero }) => {
  await hero.open({ seedLocalCache: true, gateLocalRestore: true })
  const managed = `${heroOrigins.primary}/${lifecycleKey('desktop')}`
  expect(await hero.currentHero()).toBe(managed)
  await expectHeroLoaded(page)
  const managedPaint = await hero.paintSample()
  await hero.waitForLocalReadGate(1)
  expect(await hero.currentHero()).toBe(managed)
  await hero.releaseNextLocalRead()
  await hero.waitForLocalReadGate(2)
  expect(await hero.currentHero()).toBe(managed)
  expect(await hero.paintSample()).toEqual(managedPaint)
  await hero.releaseNextLocalRead()
  await expect.poll(() => hero.currentHero()).toMatch(/^blob:/)
  await expectHeroLoaded(page)
  const localURL = await hero.currentHero()
  expect(await hero.paintSample()).not.toEqual(managedPaint)
  expect(hero.homeCalls).toHaveLength(1)
  await hero.probeAndPinMirror()
  expect(await hero.currentHero()).toBe(localURL)
  expect(hero.homeCalls).toHaveLength(1)
  expect(hero.heroCalls).toHaveLength(0)
  expect(hero.errors).toEqual([])
})

test('explicit Local avoids cloud SSR; Cancel retains it; Random Save survives reload with local metadata', async ({ page, preferences }) => {
  const { ssrHTML } = await preferences.open({ mode: 'local', seedLocalCache: true })
  expect(ssrHTML).not.toContain('/nav/hero/')
  await expect.poll(() => preferences.currentHero()).toMatch(/^blob:/)
  await expectHeroLoaded(page)
  const local = await preferences.currentHero()
  expect(preferences.requestedImages).toEqual([])
  expect(preferences.homeCalls()[0]!.searchParams.get('hero_mode')).toBe('local')
  expect(preferences.heroCalls()).toHaveLength(0)
  await preferences.openPreferences()
  await page.locator('[data-hero-preferences] .gf-modal__actions button').last().click()
  await preferences.cancelPreferences()
  expect(await preferences.currentHero()).toBe(local)
  expect(await preferences.cookieValue('gf_hero_mode')).toBe('local')
  expect(await page.evaluate(() => localStorage.getItem('customNavHeaderBgFolderName'))).toBe('Saved folder')
  await preferences.openPreferences()
  await page.getByRole('button', { name: '云端随机', exact: true }).click()
  await preferences.savePreferences()
  const random = `${heroOrigins.primary}/${preferences.desktopCatalog[0]!.object_key}`
  await expect.poll(() => preferences.currentHero()).toBe(random)
  expect(preferences.heroCalls()).toHaveLength(1)
  await preferences.reload()
  expect(await preferences.currentHero()).toBe(random)
  expect(await preferences.cookieValue('gf_hero_mode')).toBe('random')
  expect(await page.evaluate(() => localStorage.getItem('customNavHeaderBgFolderName'))).toBe('Saved folder')
  expect(preferences.heroCalls()).toHaveLength(1)
  expect(preferences.errors).toEqual([])
})

test('Local cookie without cached Blob falls back to Random exactly once', async ({ preferences }) => {
  const { ssrHTML } = await preferences.open({ mode: 'local' })
  expect(ssrHTML).not.toContain('/nav/hero/')
  await expect.poll(() => preferences.currentHero()).toBe(`${heroOrigins.primary}/${preferences.desktopCatalog[0]!.object_key}`)
  expect(await preferences.cookieValue('gf_hero_mode')).toBe('random')
  expect(preferences.homeCalls()).toHaveLength(1)
  expect(preferences.heroCalls()).toHaveLength(1)
  expect(preferences.errors).toEqual([])
})

test('legacy cached Local becomes an SSR-readable Local cookie without reselecting cloud Hero', async ({ page, preferences }) => {
  await preferences.open({ mode: null, seedLocalCache: true })
  await expect.poll(() => preferences.currentHero()).toMatch(/^blob:/)
  expect(await preferences.cookieValue('gf_hero_mode')).toBe('local')
  const { ssrHTML } = await preferences.reload()
  expect(ssrHTML).not.toContain('/nav/hero/')
  await expect(page.locator(displayedHero)).toHaveAttribute('src', /^blob:/)
  expect(preferences.heroCalls()).toHaveLength(0)
  expect(preferences.errors).toEqual([])
})
