import { test, expect, heroOrigins } from '../fixtures/hero-preferences'

test('Catalog initializes only for Fixed, pages lazily, caches each viewport and discards browsing on Cancel', async ({ page, preferences }) => {
  await preferences.open()
  const before = await preferences.currentHero()
  await preferences.openPreferences()
  await expect(page.getByRole('tab')).toHaveCount(3)
  expect(preferences.catalogCalls()).toHaveLength(0)
  await page.getByRole('button', { name: '固定云端背景', exact: true }).click()
  const picker = page.locator('[data-hero-catalog]:visible')
  await picker.scrollIntoViewIfNeeded()
  await preferences.waitCatalogPosition(1)
  await expect(picker.getByRole('button', { name: '上一张背景', exact: true })).toBeDisabled()
  await expect(picker.locator('select')).toHaveCount(0)
  await expect(picker.getByRole('button')).toHaveCount(2)
  expect(preferences.catalogCalls()).toHaveLength(1)
  expect(preferences.catalogCalls()[0]!.searchParams.get('page_size')).toBe('12')
  expect(new Set(preferences.requestedImages).size).toBe(1)

  await preferences.browseCatalogTo(2)
  await expect.poll(() => picker.locator('img').evaluate(el => (el as HTMLImageElement).complete && (el as HTMLImageElement).naturalWidth > 0)).toBe(true)
  expect(new Set(preferences.requestedImages).size).toBe(2)
  await preferences.browseCatalogTo(12)
  await expect.poll(() => picker.locator('img').evaluate(el => (el as HTMLImageElement).complete)).toBe(true)
  expect(preferences.catalogCalls()).toHaveLength(1)
  const beforeBoundary = new Set(preferences.requestedImages).size
  await preferences.browseCatalogTo(13)
  await expect.poll(() => picker.locator('img').evaluate(el => (el as HTMLImageElement).complete)).toBe(true)
  expect(preferences.catalogCalls()).toHaveLength(2)
  expect(preferences.catalogCalls().at(-1)!.searchParams.get('page_num')).toBe('2')
  expect(preferences.catalogCalls().at(-1)!.searchParams.get('page_size')).toBe('12')
  expect(preferences.catalogCalls().at(-1)!.searchParams.get('selected_id')).toBe('21')
  expect(new Set(preferences.requestedImages).size).toBe(beforeBoundary + 1)
  await preferences.browseCatalogTo(12)
  expect(preferences.catalogCalls()).toHaveLength(2)
  await page.getByRole('tab', { name: '手机', exact: true }).click()
  await preferences.waitCatalogPosition(1)
  await preferences.browseCatalogTo(2)
  await expect(page.locator('[data-hero-catalog] img')).toHaveCount(1)
  await page.getByRole('tab', { name: '桌面', exact: true }).click()
  await preferences.waitCatalogPosition(12)
  expect(preferences.catalogCalls()).toHaveLength(3)
  await page.getByRole('tab', { name: '手机', exact: true }).click()
  await preferences.waitCatalogPosition(2)
  expect(preferences.catalogCalls()).toHaveLength(3)
  await preferences.cancelPreferences()
  expect(await preferences.currentHero()).toBe(before)
  expect(await preferences.cookieValue('gf_hero_mode')).toBe('random')
  expect(await preferences.cookieValue('gf_hero_desktop_id')).toBeUndefined()
  expect(await preferences.cookieValue('gf_hero_mobile_id')).toBeUndefined()
  expect(preferences.heroCalls()).toHaveLength(0)
  expect(preferences.errors).toEqual([])
})

test('out-of-page ID 34 uses bounded metadata lookup and compact viewport keyboard preserves positions', async ({ page, preferences }) => {
  await preferences.open({ mode: 'fixed', desktopId: '34' })
  await preferences.openPreferences()
  const picker = page.locator('[data-hero-catalog]:visible')
  await picker.scrollIntoViewIfNeeded()
  await preferences.waitCatalogPosition(25)
  expect(preferences.catalogCalls()).toHaveLength(2)
  expect(preferences.catalogCalls().map(url => url.searchParams.get('page_num'))).toEqual(['1', '3'])
  expect(preferences.catalogCalls().every(url => url.searchParams.get('selected_id') === '34')).toBe(true)
  expect([...new Set(preferences.requestedImages)]).toEqual([`${heroOrigins.primary}/${preferences.desktopCatalog[24]!.object_key}`])
  await expect(page.locator('[data-hero-catalog] img')).toHaveCount(1)
  const locatedImages = preferences.requestedImages.length
  await preferences.browseCatalogTo(24)
  expect(preferences.catalogCalls().at(-1)!.searchParams.get('page_num')).toBe('2')
  await preferences.browseCatalogTo(25)
  expect(preferences.requestedImages.length).toBeLessThanOrEqual(locatedImages + 2)
  const viewportTabs = page.locator('.preferences-tabs--compact').getByRole('tab')
  await viewportTabs.first().focus()
  await page.keyboard.press('ArrowRight')
  await preferences.waitCatalogPosition(1)
  await expect(viewportTabs.last()).toBeFocused()
  await page.keyboard.press('Home')
  await preferences.waitCatalogPosition(25)
  await expect(viewportTabs.first()).toBeFocused()
  await preferences.cancelPreferences()
  expect(preferences.errors).toEqual([])
})

test('ID 57 resolves to position 48 without intermediate previews and disables Next', async ({ page, preferences }) => {
  await preferences.open({ mode: 'fixed', desktopId: '57' })
  await preferences.openPreferences()
  await preferences.waitCatalogPosition(48)
  const picker = page.locator('[data-hero-catalog]:visible')
  await expect(picker.getByRole('button', { name: '下一张背景', exact: true })).toBeDisabled()
  expect(preferences.catalogCalls()).toHaveLength(3)
  expect([...new Set(preferences.requestedImages)]).toEqual([`${heroOrigins.primary}/${preferences.desktopCatalog[47]!.object_key}`])
  await preferences.browseCatalogTo(47)
  await preferences.browseCatalogTo(48)
  expect(await preferences.cookieValue('gf_hero_desktop_id')).toBe('57')
  await preferences.cancelPreferences()
  expect(preferences.errors).toEqual([])
})

test('page 2 metadata failure retains position and cookie; Retry browses to 13 without saving', async ({ page, preferences }) => {
  await preferences.open({ mode: 'fixed', desktopId: '21' })
  await preferences.openPreferences()
  await preferences.waitCatalogPosition(12)
  preferences.failedCatalogPage = 2
  const picker = page.locator('[data-hero-catalog]:visible')
  await picker.getByRole('button', { name: '下一张背景', exact: true }).click()
  await expect(picker.getByRole('alert')).toBeVisible()
  await preferences.waitCatalogPosition(12)
  expect(await preferences.cookieValue('gf_hero_desktop_id')).toBe('21')
  expect(preferences.expectedNetworkFailures.size).toBeGreaterThan(0)
  preferences.failedCatalogPage = null
  await picker.getByRole('button', { name: '重试', exact: true }).click()
  await preferences.waitCatalogPosition(13)
  expect(await preferences.cookieValue('gf_hero_desktop_id')).toBe('21')
  expect(preferences.heroCalls()).toHaveLength(0)
  await preferences.cancelPreferences()
  expect(preferences.errors).toEqual([])
})
