import { test, expect, quote, weatherURL } from '../fixtures/nav-revealed-content'

test('Core cards, TransitionBar and real group/site popovers retain their runtime contract', async ({ revealed }) => {
  const scene = await revealed.open({ width: 1000 })
  const { page, bar, quoteTrigger, author, groupPopover, sitePopover } = scene
  await scene.reveal()
  await scene.alignContent()
  await expect(scene.dock).toBeHidden()
  const card = scene.card(scene.data.community.name)
  await expect(card.locator('h3')).toHaveCSS('font-size', '16px')
  await expect(card.locator('h3')).toHaveCSS('line-height', '24px')
  await expect(card.locator('h3')).toHaveCSS('font-weight', '500')
  await expect(card.locator('p')).toHaveCSS('font-size', '12px')
  // Current unlayered nav.less line-height: 1.35 wins over text-xs (16px).
  await expect(card.locator('p')).toHaveCSS('line-height', '16.2px')
  await expect(bar.locator('.nav-transition-bar__time')).toHaveText('2026年9月18日 12:40')
  await expect(quoteTrigger).toHaveText(`"${quote.content}"`)
  await expect(bar.locator('iframe')).toHaveAttribute('src', weatherURL)
  await quoteTrigger.focus()
  await expect(author).toHaveText(quote.author)
  await scene.inside(author)
  await quoteTrigger.blur()
  await expect(author).toHaveCount(0)

  await scene.groups.first().getByRole('heading', { name: '社区', exact: true }).hover()
  await expect(groupPopover).toHaveText(scene.data.home.groups[0]!.info)
  await scene.inside(groupPopover)
  await page.mouse.move(1, 1)
  await expect(groupPopover).toHaveCount(0)

  await scene.hoverTopCard()
  await expect(sitePopover.locator('h3')).toHaveText(scene.data.community.name)
  await expect(sitePopover.locator('p')).toHaveText(scene.data.community.info)
  await expect(sitePopover.locator('.site-popover__domain-name')).toHaveText(['community.example', 'mirror.example'])
  await expect(sitePopover.locator('.site-popover__domain-metrics')).toHaveText(['0% / 32', '100% / -'])
  const indicators = await sitePopover.locator('.site-popover__domain-name img').evaluateAll(images => images.map(image => (image as HTMLImageElement).src))
  // Vite inlines these real status SVGs in the production build.
  expect(decodeURIComponent(indicators[0]!)).toContain("fill='#78B159'")
  expect(decodeURIComponent(indicators[1]!)).toContain("fill='#DD2E44'")
  scene.assertQuiet()
})

test('ToolDock caches its real directory, filters SFW search and opens a result without a view POST', async ({ revealed }) => {
  const scene = await revealed.open()
  await scene.reveal()
  await expect(scene.dock).toBeVisible()
  await scene.openSearch()
  await scene.searchInput.fill('wolf')
  await expect(scene.results.locator('strong')).toHaveText(['Wolf Community', 'Wolf Archive'])
  await expect(scene.searchPanel.getByText('Wolf After Dark', { exact: true })).toHaveCount(0)
  await scene.searchInput.fill('zz-no-result')
  await expect(scene.searchPanel.locator('.nav-tool-empty')).toHaveText('没有找到匹配站点')
  await scene.searchInput.press('Escape')
  await expect(scene.searchPanel).toHaveCount(0)
  await scene.openSearch()
  await expect(scene.searchInput).toHaveValue('')
  expect(scene.directoryCount()).toBe(1)
  await scene.searchInput.fill('wolf')
  await expect(scene.results).toHaveCount(2)
  await scene.clickSite(scene.results.first(), scene.data.community, false)
  await expect(scene.searchPanel).toHaveCount(0)
  scene.assertQuiet()
})

test('Spotlight pages animate, wrap and mark real site visits with the exact view request', async ({ revealed }) => {
  const scene = await revealed.open()
  await scene.reveal()
  await expect(scene.content.locator('.spotlight-panel:visible')).toHaveCount(4)
  const pager = scene.featured.locator('.spotlight-panel__pager span')
  await expect(pager).toHaveText('1/2')
  await expect(scene.popular.locator('.spotlight-panel__pager span')).toHaveText('1/2')
  await expect(scene.panels.nth(2).locator('.spotlight-panel__pager')).toHaveCount(0)
  await expect(scene.panels.nth(3).locator('.spotlight-panel__pager')).toHaveCount(0)
  const first = scene.featured.locator('.spotlight-site').first()
  await expect(first.locator('.spotlight-site__rank')).toHaveAttribute('aria-label', '已浏览')
  await expect(scene.content.getByText(scene.data.adultFeatured.name, { exact: true })).toHaveCount(0)
  const track = scene.featured.locator('.spotlight-panel__track')
  const move = async (direction: '下一页' | '上一页', page: string) => {
    await scene.featured.getByRole('button', { name: `精选站点 ${direction}`, exact: true }).click()
    await expect(track).toHaveClass(direction === '下一页' ? /spotlight-panel__track--next/ : /spotlight-panel__track--prev/)
    await expect(pager).toHaveText(page)
    await expect(track).not.toHaveClass(/spotlight-panel__track--(?:next|prev|instant)/)
    await expect(track.locator('.spotlight-panel__slide')).toHaveCount(1)
    await expect(track.locator('.spotlight-panel__slide')).toHaveAttribute('aria-hidden', 'false')
    await scene.settle(scene.featured)
  }
  await move('下一页', '2/2')
  await move('上一页', '1/2')
  await move('上一页', '2/2') // Stable first -> last wrap, through the real pager.
  await move('下一页', '1/2')
  const unvisited = scene.featured.locator('.spotlight-site').filter({ hasText: scene.data.featured[1]!.name })
  await expect(unvisited.locator('.spotlight-site__rank')).not.toHaveAttribute('aria-label', '已浏览')
  await scene.clickSite(unvisited, scene.data.featured[1]!, true)
  await expect(unvisited.locator('.spotlight-site__rank')).toHaveAttribute('aria-label', '已浏览')
  scene.assertQuiet()
})

test('Real resizing selects the Spotlight panels and a fresh saved NSFW mode includes adult sites', async ({ revealed }) => {
  const sfw = await revealed.open()
  await sfw.reveal()
  for (const [width, count] of [[390, 1], [700, 2], [1100, 3], [1440, 4]] as const) {
    await sfw.page.setViewportSize({ width, height: 900 })
    await expect(sfw.content.locator('.spotlight-panel:visible')).toHaveCount(count)
  }
  await expect(sfw.card(sfw.data.adult.name)).toHaveCount(0)
  sfw.assertQuiet()
  const nsfw = await revealed.open({ mode: 'nsfw' })
  await nsfw.reveal()
  await expect(nsfw.card(nsfw.data.adult.name)).toBeVisible()
  await expect(nsfw.featured.getByText(nsfw.data.adultFeatured.name, { exact: true })).toBeVisible()
  await nsfw.openSearch()
  await nsfw.searchInput.fill('wolf')
  await expect(nsfw.results.locator('strong')).toHaveText(['Wolf Community', 'Wolf Archive', 'Wolf After Dark'])
  nsfw.assertQuiet()
})
