import { test, expect, customSeed, searchPopupURL } from '../fixtures/nav-home-header'

test('Search keeps typography, theme parity, debounce, keyboard selection and reveal lock', async ({ page, header }) => {
  await header.open()
  const { input, search, suggestions, items, quick } = header
  const category = search.locator('.search-category-row .search-chip-active')
  const platform = search.locator('.search-platform-row .search-chip-active')
  await expect(category).toHaveText('搜索')
  await expect(platform).toHaveText('必应')
  await expect(quick).toBeVisible()
  await expect(page.locator('.nav-tool-dock')).toHaveCount(0)
  for (const [chip, size, height] of [[category, '14px', '20px'], [platform, '12px', '16px']] as const) {
    await expect(chip).toHaveCSS('font-size', size)
    await expect(chip).toHaveCSS('line-height', height)
    await expect(chip).toHaveCSS('font-weight', '500')
    await expect(chip).toHaveCSS('border-radius', '12px')
    // The actual unlayered nav.less cascade overrides Tailwind transition-all.
    await expect(chip).toHaveCSS('transition-property', 'background, box-shadow, color')
    await expect(chip).toHaveCSS('transition-duration', '0.5s, 0.5s, 0.5s')
  }
  const appearance = () => search.locator('.search-category-row .search-chip-active').evaluate((chip) => {
    const elements = [chip, document.querySelector('.search-input')!, document.querySelector('.quick-site-tile')!]
    return elements.map(element => {
      const style = getComputedStyle(element)
      return Object.fromEntries(['background-color', 'color', 'border-radius', 'box-shadow', 'backdrop-filter',
        'font-size', 'line-height', 'font-weight'].map(property => [property, style.getPropertyValue(property)]))
    })
  })
  const light = await appearance()
  const theme = page.locator('.gf-nav').getByRole('button', { name: '切换明暗主题图标', exact: true })
  await theme.click()
  await expect(page.locator('html')).toHaveClass(/\bdark\b/)
  expect(await page.evaluate(() => localStorage.getItem('theme'))).toBe('dark')
  await header.settle(header.root)
  expect(await appearance()).toEqual(light)
  await theme.click()
  await expect(page.locator('html')).not.toHaveClass(/\bdark\b/)
  await header.settle(header.root)
  expect(await appearance()).toEqual(light)

  header.holdSuggestions()
  await input.focus()
  await input.fill('wolf')
  await header.expectSuggestionRequest('wolf')
  await expect(suggestions).toBeVisible()
  await expect(suggestions.locator('.search-suggestion-loading')).toBeVisible()
  await expect(suggestions.locator('.search-suggestion-spinner')).toBeVisible()
  header.releaseSuggestions()
  await expect(items).toHaveText(['wolf furry', 'wolf art', 'wolf game'])
  await expect(items.first()).toHaveClass(/\bsearch-suggestion-item-active\b/)
  await expect(suggestions.locator('.search-suggestion-header')).toHaveCSS('font-size', '12px')
  await expect(suggestions.locator('.search-suggestion-header')).toHaveCSS('line-height', '16px')
  await expect(items.first()).toHaveCSS('font-size', '14px')
  await expect(items.first()).toHaveCSS('line-height', '20px')
  await expect(items.first()).toHaveCSS('font-weight', '500')
  await input.press('ArrowDown')
  await expect(items.nth(1)).toHaveClass(/\bsearch-suggestion-item-active\b/)
  await expect(items.first()).not.toHaveClass(/\bsearch-suggestion-item-active\b/)
  await input.press('ArrowUp')
  await expect(items.first()).toHaveClass(/\bsearch-suggestion-item-active\b/)
  await input.press('Escape')
  await expect(suggestions).toHaveCount(0)
  await input.fill('noresult')
  await header.expectSuggestionRequest('noresult')
  await expect(suggestions.getByText('暂无搜索建议', { exact: true })).toBeVisible()
  await expect(items).toHaveCount(0)

  // Wheel outside the dropdown (which stops propagation) must reach the real
  // window listener while Search owns its reveal lock. Only observe the event.
  await page.evaluate(() => {
    document.documentElement.dataset.headerWheelObserved = 'false'
    window.addEventListener('wheel', () => { document.documentElement.dataset.headerWheelObserved = 'true' }, { once: true, passive: true })
  })
  await page.mouse.move(20, 400)
  await page.mouse.wheel(0, 180)
  await expect(page.locator('html')).toHaveAttribute('data-header-wheel-observed', 'true')
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
  await expect(page.locator('.nav-tool-dock')).toHaveCount(0)
  await input.press('Escape')
  await page.mouse.click(20, 400)
  await expect(input).not.toBeFocused()
  await page.mouse.wheel(0, 300)
  await expect(page.locator('.nav-tool-dock')).toHaveCount(1)
  // Let the real reveal's scrollIntoView finish before returning to Search;
  // otherwise its pending smooth scroll can race a one-shot scrollTo(0).
  await expect.poll(() => page.locator('.nav-content-shell').evaluate(element => {
    const target = Math.min(element.getBoundingClientRect().top + scrollY,
      document.documentElement.scrollHeight - innerHeight)
    return Math.abs(scrollY - target)
  })).toBeLessThanOrEqual(1)
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  await header.showSuggestions()
  header.allowSearchPopup()
  const popupPromise = page.waitForEvent('popup')
  await input.press('Enter')
  const popup = await popupPromise
  await popup.waitForLoadState('load')
  await expect(popup).toHaveURL(searchPopupURL)
  expect(new URL(popup.url()).searchParams.get('q')).toBe('wolf furry')
  header.assertQuiet()
})

test('Quick Access exposes all slots and persists real Manage add/delete actions', async ({ page, header }) => {
  await header.open()
  const { quick, modal } = header
  await expect(quick.getByText('最近浏览', { exact: true })).toBeVisible()
  await expect(quick.getByText('常用网站', { exact: true })).toBeVisible()
  const sections = quick.locator('.quick-access-section')
  await expect(sections).toHaveCount(2)
  await expect(sections.nth(0).locator('.quick-site-tile')).toHaveCount(8)
  await expect(sections.nth(1).locator('.quick-site-tile')).toHaveCount(8)
  await expect(sections.nth(0).locator('.quick-site-tile-empty')).toHaveCount(6)
  await expect(sections.nth(1).locator('.quick-site-tile-empty')).toHaveCount(5)
  await expect(quick.locator('[title="Community"] img')).toBeVisible()
  await expect(quick.locator('[title="Archive"] .quick-site-fallback')).toHaveText('A')
  await expect(quick.locator('[title="Archive"] img')).toHaveCount(0)
  await quick.getByRole('button', { name: '管理快捷站点', exact: true }).click()
  await expect(page.locator('.quick-modal-backdrop')).toBeVisible()
  await expect(modal).toBeVisible()
  await expect(modal.locator('.quick-modal-item')).toHaveCount(2)
  const submit = modal.locator('button[type="submit"]')
  const name = modal.locator('#custom-site-name')
  const url = modal.locator('#custom-site-url')
  const error = modal.locator('.quick-modal-error')
  await submit.click()
  await expect(error).toHaveText('请输入网站名称')
  await name.fill('Example Site')
  await submit.click()
  await expect(error).toHaveText('请输入网站链接')
  await url.fill('example.com')
  header.allowExampleIcon()
  await submit.click()
  await expect(modal.locator('.quick-modal-item')).toHaveCount(3)
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('navCustomSites')!))
  expect(saved.slice(0, 2)).toEqual(customSeed)
  expect(saved[2]).toEqual({ id: expect.stringMatching(/^custom-/), name: 'Example Site', url: 'https://example.com' })
  await expect(name).toHaveValue('')
  await expect(url).toHaveValue('')
  await expect(error).toHaveCount(0)
  await modal.locator('.quick-modal-item').filter({ hasText: 'Example Site' }).getByRole('button', { name: '删除网站', exact: true }).click()
  await expect(modal.locator('.quick-modal-item')).toHaveCount(2)
  await expect(modal.getByText('Example Site', { exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('navCustomSites')!))).toEqual(customSeed)
  header.assertQuiet()
})
