import { test, expect } from '../fixtures/nav-shell'

test('Desktop Nav Shell retains theme through real language navigation', async ({ page, navShell }) => {
  await navShell.open()
  const { nav, toggle } = navShell
  await expect(nav.getByText('GoFurry', { exact: true })).toBeVisible()
  await navShell.assertLinks('zh')
  await expect(nav.getByRole('link', { name: 'GitHub', exact: true })).toBeVisible()
  await expect(nav.getByRole('button', { name: '模式', exact: true })).toBeVisible()
  await expect(toggle).toBeHidden()
  await navShell.assertLanguage('CN')
  await nav.getByRole('button', { name: '切换明暗主题图标', exact: true }).click()
  await navShell.assertTheme('dark')
  await navShell.language('EN').click()
  await expect(page).toHaveURL(/\/en\/terms$/)
  await navShell.assertLinks('en')
  await navShell.assertLanguage('EN')
  await navShell.assertTheme('dark')
  await expect(nav).toHaveCount(1)
  navShell.assertQuiet()
})

test('Mobile Nav Shell keeps menu, locale and BottomTab state tied to real controls and scrolling', async ({ page, navShell }) => {
  await navShell.open({ width: 390 })
  const { nav, menu, toggle, bottomTabs } = navShell
  await expect(toggle).toBeVisible()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(menu).toHaveCount(0)
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  await navShell.assertBottomTabs(false)
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await expect(menu).toBeVisible()
  await navShell.assertLinks('zh', true)
  await expect(menu.getByRole('button', { name: /模式/ })).toBeVisible()
  await navShell.assertLanguage('CN', true)
  await nav.getByRole('button', { name: '切换明暗主题图标', exact: true }).click()
  await navShell.assertTheme('dark')
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await expect(menu).toBeVisible()
  await navShell.language('EN', true).click()
  await expect(page).toHaveURL(/\/en\/terms$/)
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(menu).toHaveCount(0)
  await navShell.assertTheme('dark')
  await toggle.click()
  await expect(menu).toBeVisible()
  await navShell.assertLinks('en', true)
  await expect(menu.getByRole('button', { name: /Mode/ })).toBeVisible()
  await navShell.assertLanguage('EN', true)
  await toggle.click()
  await expect(menu).toHaveCount(0)

  await navShell.scrollTo(0)
  await navShell.assertBottomTabs(false)
  await navShell.scrollTo(73)
  // Observable production state includes both scroll listeners and the 160ms sync path.
  await navShell.assertBottomTabs(true)
  const mode = bottomTabs.getByRole('button', { name: 'Mode', exact: true })
  await navShell.openBottomMode()
  const modal = page.locator('.gf-preferences-modal')
  await expect(modal).toBeVisible()
  await expect(mode).toHaveClass(/\bmobile-bottom-tabs__item--active\b/)
  await expect(mode).not.toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await expect(mode).not.toHaveCSS('border-top-color', 'rgba(0, 0, 0, 0)')
  await modal.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(modal).toHaveCount(0)
  await expect(mode).not.toHaveClass(/\bmobile-bottom-tabs__item--active\b/)
  await page.setViewportSize({ width: 640, height: 844 })
  await navShell.assertBottomTabs(false)
  await expect(bottomTabs).toHaveCSS('display', 'none')
  navShell.assertQuiet()
})
