<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { getJSON } from '../api'
import { useAuthStore } from '../stores/auth'

type Overview = { domain:'game'|'nav'; detector_key:string; detector_version:number; status:string; description:string; watermark_policy:string; source_start_date:string|null; processed_through:string|null; upstream_processed_through:string|null; lag_days:number|null; latest_projection_date:string|null; latest_event_count:number; total_event_count:number }
type Registry = { domain:'game'|'nav'; detector_key:string; detector_version:number; source_kind:string; source_contracts:string[]; detection_policy:string; watermark_policy:string; event_codes:string[]; processing_grain:string; status:string; description:string }
type Checkpoint = { domain:'game'|'nav'; detector_key:string; detector_version:number; status:string; watermark_policy:string; source_start_date:string|null; processed_through:string|null; upstream_processed_through:string|null; lag_days:number|null; updated_at:string }
type ChangeEvent = { domain:'game'|'nav'; event_key:string; detector_key:string; detector_version:number; entity_id:number; historical_name:string; projection_date:string; event_at:string|null; time_basis:string; event_code:string; scope_kind:string; scope_key:string; old_value:Record<string,unknown>; new_value:Record<string,unknown>; source_event_key:string; source_before_key:string; source_after_key:string; source_before_at:string|null; source_after_at:string|null; source_versions:Record<string,unknown>; materialized_at:string }
type EventPage = { list:ChangeEvent[]; total:number; page:number; page_size:number }
type Tab = 'overview'|'registry'|'checkpoints'|'events'

const allTabs:Array<{key:Tab;label:string;technical?:boolean}>=[{key:'overview',label:'Overview'},{key:'registry',label:'Registry',technical:true},{key:'checkpoints',label:'Checkpoints',technical:true},{key:'events',label:'Events'}]
const auth=useAuthStore()
const canTechnical=computed(()=>auth.has('changes.technical'))
const tabs=computed(()=>allTabs.filter((tab)=>!tab.technical||canTechnical.value))
const activeTab=ref<Tab>('overview')
const loading=ref(false)
const error=ref('')
const overview=ref<Overview[]>([])
const registry=ref<Registry[]>([])
const checkpoints=ref<Checkpoint[]>([])
const events=ref<EventPage>({list:[],total:0,page:1,page_size:50})
const selected=ref<ChangeEvent|null>(null)
const filter=ref({domain:'nav',detector:'',version:0,eventCode:'',entityID:'',from:'',to:'',page:1,pageSize:50})

async function loadFoundation(){loading.value=true;error.value='';try{overview.value=await getJSON<Overview[]>('/api/v1/changes/overview');if(canTechnical.value){;[registry.value,checkpoints.value]=await Promise.all([getJSON<Registry[]>('/api/v1/changes/registry'),getJSON<Checkpoint[]>('/api/v1/changes/checkpoints')])}else{registry.value=[];checkpoints.value=[]}}catch(cause){error.value=cause instanceof Error?cause.message:String(cause)}finally{loading.value=false}}
async function loadEvents(reset=false){if(reset)filter.value.page=1;loading.value=true;error.value='';try{const params=new URLSearchParams({domain:filter.value.domain,page:String(filter.value.page),page_size:String(filter.value.pageSize)});if(filter.value.detector)params.set('detector',filter.value.detector);if(filter.value.version)params.set('version',String(filter.value.version));if(filter.value.eventCode)params.set('event_code',filter.value.eventCode);if(filter.value.entityID)params.set('entity_id',filter.value.entityID);if(filter.value.from)params.set('from',filter.value.from);if(filter.value.to)params.set('to',filter.value.to);events.value=await getJSON<EventPage>(`/api/v1/changes/events?${params}`)}catch(cause){error.value=cause instanceof Error?cause.message:String(cause)}finally{loading.value=false}}
function selectTab(tab:Tab){activeTab.value=tab;if(tab==='events'&&events.value.list.length===0)void loadEvents()}
function previousPage(){if(filter.value.page>1){filter.value.page--;void loadEvents()}}
function nextPage(){if(filter.value.page*filter.value.pageSize<events.value.total){filter.value.page++;void loadEvents()}}
onMounted(loadFoundation)
</script>

<template>
  <main>
    <header class="page-header"><div><div class="page-kicker">P0.4 · read-only verification</div><h1 class="mt-1 text-2xl font-semibold">Change Center</h1><p class="mt-2 text-sm text-[var(--text-muted)]">Versioned detectors, ordered checkpoints and provenance-rich canonical events.</p></div><button class="ui-button px-4" :disabled="loading" @click="loadFoundation">{{ loading?'Loading…':'Refresh' }}</button></header>
    <div class="mt-5 flex flex-wrap gap-2 border-b border-[var(--line)] pb-3"><button v-for="tab in tabs" :key="tab.key" class="ui-button px-4" :class="{'ui-button--primary':activeTab===tab.key}" @click="selectTab(tab.key)">{{ tab.label }}</button></div>
    <p v-if="error" class="status-alert mt-4 px-4 py-3 text-sm text-[var(--danger)]">{{ error }}</p>
    <section v-if="activeTab==='overview'" class="mt-5 grid gap-4 xl:grid-cols-3 md:grid-cols-2"><article v-for="item in overview" :key="`${item.domain}-${item.detector_key}`" class="data-surface border border-[var(--line)] p-4"><div class="flex items-start justify-between gap-3"><div><p class="page-kicker">{{ item.domain }} · v{{ item.detector_version }}</p><h2 class="mt-1 text-lg font-semibold">{{ item.detector_key }}</h2></div><span class="font-mono text-xs text-[var(--text-muted)]">{{ item.latest_projection_date??'no events' }}</span></div><p class="mt-2 min-h-10 text-xs text-[var(--text-muted)]">{{ item.description }}</p><div class="mt-4 grid grid-cols-2 gap-2"><div class="summary-cell"><span class="text-xs text-[var(--text-muted)]">Latest events</span><strong class="mt-1 block text-xl">{{ item.latest_event_count }}</strong></div><div class="summary-cell"><span class="text-xs text-[var(--text-muted)]">All events</span><strong class="mt-1 block text-xl">{{ item.total_event_count }}</strong></div></div><p class="mt-4 border-t border-[var(--line)] pt-3 text-xs text-[var(--text-muted)]">{{ item.watermark_policy }} · checkpoint {{ item.processed_through??'—' }} · upstream {{ item.upstream_processed_through??'—' }} · lag {{ item.lag_days??'—' }}</p></article></section>
    <section v-else-if="activeTab==='registry'" class="resource-table-section"><div class="resource-table-scroll"><table class="resource-table min-w-[1200px]"><thead><tr><th>Domain</th><th>Detector</th><th>Source</th><th>Policy</th><th>Watermark</th><th>Event codes</th><th>Status</th></tr></thead><tbody><tr v-for="item in registry" :key="`${item.domain}-${item.detector_key}-${item.detector_version}`"><td>{{ item.domain }}</td><td><strong>{{ item.detector_key }}</strong><div class="text-xs text-[var(--text-muted)]">v{{ item.detector_version }} · {{ item.description }}</div></td><td class="font-mono text-xs">{{ item.source_kind }}<br>{{ item.source_contracts.join(', ') }}</td><td class="font-mono text-xs">{{ item.detection_policy }}</td><td class="font-mono text-xs">{{ item.watermark_policy }}</td><td class="font-mono text-xs">{{ item.event_codes.join(', ') }}</td><td>{{ item.status }}</td></tr></tbody></table></div></section>
    <section v-else-if="activeTab==='checkpoints'" class="resource-table-section"><div class="resource-table-scroll"><table class="resource-table"><thead><tr><th>Domain</th><th>Detector</th><th>Watermark</th><th>Source Start</th><th>Processed</th><th>Upstream</th><th>Lag</th><th>Updated</th></tr></thead><tbody><tr v-for="item in checkpoints" :key="`${item.domain}-${item.detector_key}-${item.detector_version}`"><td>{{ item.domain }}</td><td>{{ item.detector_key }} v{{ item.detector_version }}</td><td>{{ item.watermark_policy }}</td><td>{{ item.source_start_date??'—' }}</td><td>{{ item.processed_through??'—' }}</td><td>{{ item.upstream_processed_through??'—' }}</td><td>{{ item.lag_days??'—' }}</td><td class="font-mono text-xs">{{ item.updated_at }}</td></tr></tbody></table></div></section>
    <section v-else class="mt-5"><div class="flex flex-wrap gap-2"><select v-model="filter.domain" class="ui-control px-3"><option value="game">game</option><option value="nav">nav</option></select><input v-model="filter.detector" class="ui-control px-3" placeholder="detector"><input v-model="filter.eventCode" class="ui-control px-3" placeholder="event code"><input v-model="filter.entityID" class="ui-control w-28 px-3" placeholder="entity id"><input v-model="filter.from" type="date" class="ui-control px-3"><input v-model="filter.to" type="date" class="ui-control px-3"><button class="ui-button ui-button--primary px-4" @click="loadEvents(true)">Query</button></div><div class="resource-table-section"><div class="resource-table-scroll"><table class="resource-table min-w-[1100px]"><thead><tr><th>Date / Time</th><th>Detector</th><th>Entity</th><th>Event</th><th>Scope</th><th>Values</th></tr></thead><tbody><tr v-for="item in events.list" :key="item.event_key" class="cursor-pointer" @click="selected=item"><td>{{ item.projection_date }}<div class="font-mono text-xs text-[var(--text-muted)]">{{ item.event_at??item.time_basis }}</div></td><td>{{ item.domain }}/{{ item.detector_key }} v{{ item.detector_version }}</td><td><strong>{{ item.historical_name }}</strong><div class="font-mono text-xs text-[var(--text-muted)]">#{{ item.entity_id }}</div></td><td class="font-mono text-xs">{{ item.event_code }}</td><td>{{ item.scope_kind }}/{{ item.scope_key }}</td><td><pre class="max-w-96 whitespace-pre-wrap text-xs">{{ JSON.stringify(item.old_value) }} → {{ JSON.stringify(item.new_value) }}</pre></td></tr></tbody></table></div><div class="resource-pagination"><span>{{ events.total }} events · page {{ filter.page }}</span><button class="ui-button px-3" :disabled="filter.page<=1" @click="previousPage">Previous</button><button class="ui-button px-3" :disabled="filter.page*filter.pageSize>=events.total" @click="nextPage">Next</button></div></div><article v-if="selected" class="data-surface mt-4 border border-[var(--line)] p-4"><div class="flex justify-between gap-3"><h2 class="font-semibold">Event Detail</h2><button class="ui-button px-3" @click="selected=null">Close</button></div><p class="mt-2 break-all font-mono text-xs">{{ selected.event_key }}</p><div class="mt-4 grid gap-4 md:grid-cols-3"><pre class="whitespace-pre-wrap text-xs">old: {{ JSON.stringify(selected.old_value,null,2) }}</pre><pre class="whitespace-pre-wrap text-xs">new: {{ JSON.stringify(selected.new_value,null,2) }}</pre><pre class="whitespace-pre-wrap text-xs">source versions: {{ JSON.stringify(selected.source_versions,null,2) }}</pre></div><p class="mt-3 break-all text-xs text-[var(--text-muted)]">{{ selected.source_before_key }} → {{ selected.source_after_key }} · materialized {{ selected.materialized_at }}</p></article></section>
  </main>
</template>
