// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facts.sql

package gamesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceGameFactCheckpoint = `-- name: AdvanceGameFactCheckpoint :execrows
UPDATE gfg_fact_rollup_checkpoints
SET processed_through = $1,
    updated_at = transaction_timestamp()
WHERE pipeline_key = $2
  AND (processed_through IS NULL OR processed_through < $1)
`

type AdvanceGameFactCheckpointParams struct {
	ProcessedThrough pgtype.Date `json:"processed_through"`
	PipelineKey      string      `json:"pipeline_key"`
}

func (q *Queries) AdvanceGameFactCheckpoint(ctx context.Context, arg AdvanceGameFactCheckpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceGameFactCheckpoint, arg.ProcessedThrough, arg.PipelineKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countGamePlayerFactRows = `-- name: CountGamePlayerFactRows :one
SELECT count(*)::bigint
FROM gfg_game_player_daily
WHERE fact_date >= $1 AND fact_date < $2
`

type CountGamePlayerFactRowsParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CountGamePlayerFactRows(ctx context.Context, arg CountGamePlayerFactRowsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGamePlayerFactRows, arg.StartDate, arg.EndDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countGameStateFactRows = `-- name: CountGameStateFactRows :one
SELECT count(*)::bigint
FROM gfg_game_daily
WHERE fact_date >= $1 AND fact_date < $2
`

type CountGameStateFactRowsParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CountGameStateFactRows(ctx context.Context, arg CountGameStateFactRowsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGameStateFactRows, arg.StartDate, arg.EndDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const gameFactDaySettled = `-- name: GameFactDaySettled :one
SELECT NOT EXISTS (
    SELECT 1
    FROM gfg_collection_jobs job
    WHERE job.trigger = 'scheduled'
      AND job.job_key = $1
      AND job.scheduled_for >= $2
      AND job.scheduled_for < $3
      AND job.status IN ('queued', 'running')
)
AND NOT EXISTS (
    SELECT 1
    FROM gfg_collection_schedules schedule
    WHERE schedule.job_key = $1
      AND schedule.enabled
      AND (schedule.next_scheduled_for IS NULL OR schedule.next_scheduled_for < $3)
) AS settled
`

type GameFactDaySettledParams struct {
	JobKey   string             `json:"job_key"`
	DayStart pgtype.Timestamptz `json:"day_start"`
	DayEnd   pgtype.Timestamptz `json:"day_end"`
}

func (q *Queries) GameFactDaySettled(ctx context.Context, arg GameFactDaySettledParams) (*bool, error) {
	row := q.db.QueryRow(ctx, gameFactDaySettled, arg.JobKey, arg.DayStart, arg.DayEnd)
	var settled *bool
	err := row.Scan(&settled)
	return settled, err
}

const gameFactSourceBounds = `-- name: GameFactSourceBounds :one
SELECT min(collected_at AT TIME ZONE 'UTC')::date AS player_raw_start,
       max(collected_at AT TIME ZONE 'UTC')::date AS player_raw_end
FROM gfg_game_player_counts
`

type GameFactSourceBoundsRow struct {
	PlayerRawStart pgtype.Date `json:"player_raw_start"`
	PlayerRawEnd   pgtype.Date `json:"player_raw_end"`
}

func (q *Queries) GameFactSourceBounds(ctx context.Context) (GameFactSourceBoundsRow, error) {
	row := q.db.QueryRow(ctx, gameFactSourceBounds)
	var i GameFactSourceBoundsRow
	err := row.Scan(&i.PlayerRawStart, &i.PlayerRawEnd)
	return i, err
}

const gamePlayerRebuildSourceAvailable = `-- name: GamePlayerRebuildSourceAvailable :one
SELECT NOT EXISTS (
    SELECT 1
    FROM gfg_game_player_daily fact
    WHERE fact.fact_date = $1
      AND (
          (fact.successful_samples > 0 AND (
              SELECT count(*)
              FROM gfg_game_player_counts raw
              JOIN gfg_collection_runs run ON run.id = raw.run_id
              JOIN gfg_collection_jobs job ON job.id = run.job_id
              WHERE raw.game_id = fact.game_id
                AND raw.appid = fact.appid
                AND raw.status = 'success'
                AND job.trigger = 'scheduled'
                AND job.job_key = 'game.players'
                AND (job.scheduled_for AT TIME ZONE 'UTC')::date = fact.fact_date
          ) < fact.successful_samples)
          OR
          (fact.attempted_samples > 0 AND (
              SELECT count(*)
              FROM gfg_collection_task_results result
              JOIN gfg_collection_runs run ON run.id = result.run_id
              JOIN gfg_collection_jobs job ON job.id = run.job_id
              WHERE result.game_id = fact.game_id
                AND result.appid = fact.appid
                AND result.task_type = 'players'
                AND job.trigger = 'scheduled'
                AND job.job_key = 'game.players'
                AND (job.scheduled_for AT TIME ZONE 'UTC')::date = fact.fact_date
          ) < fact.attempted_samples)
      )
) AS available
`

func (q *Queries) GamePlayerRebuildSourceAvailable(ctx context.Context, factDate pgtype.Date) (bool, error) {
	row := q.db.QueryRow(ctx, gamePlayerRebuildSourceAvailable, factDate)
	var available bool
	err := row.Scan(&available)
	return available, err
}

const listGameFactCheckpoints = `-- name: ListGameFactCheckpoints :many
SELECT pipeline_key, projection_version, source_start_date, processed_through,
       quality_cutover_at, created_at, updated_at
FROM gfg_fact_rollup_checkpoints
ORDER BY pipeline_key
`

func (q *Queries) ListGameFactCheckpoints(ctx context.Context) ([]GfgFactRollupCheckpoint, error) {
	rows, err := q.db.Query(ctx, listGameFactCheckpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfgFactRollupCheckpoint{}
	for rows.Next() {
		var i GfgFactRollupCheckpoint
		if err := rows.Scan(
			&i.PipelineKey,
			&i.ProjectionVersion,
			&i.SourceStartDate,
			&i.ProcessedThrough,
			&i.QualityCutoverAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGameFactCheckpoint = `-- name: LockGameFactCheckpoint :one
SELECT pipeline_key, projection_version, source_start_date, processed_through,
       quality_cutover_at, created_at, updated_at
FROM gfg_fact_rollup_checkpoints
WHERE pipeline_key = $1
FOR UPDATE
`

func (q *Queries) LockGameFactCheckpoint(ctx context.Context, pipelineKey string) (GfgFactRollupCheckpoint, error) {
	row := q.db.QueryRow(ctx, lockGameFactCheckpoint, pipelineKey)
	var i GfgFactRollupCheckpoint
	err := row.Scan(
		&i.PipelineKey,
		&i.ProjectionVersion,
		&i.SourceStartDate,
		&i.ProcessedThrough,
		&i.QualityCutoverAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectGamePlayerFactDay = `-- name: ProjectGamePlayerFactDay :one
SELECT count(*)::bigint AS projected
FROM gfg_project_player_fact_day($1::date)
`

func (q *Queries) ProjectGamePlayerFactDay(ctx context.Context, factDate pgtype.Date) (int64, error) {
	row := q.db.QueryRow(ctx, projectGamePlayerFactDay, factDate)
	var projected int64
	err := row.Scan(&projected)
	return projected, err
}

const projectGameStateFactDay = `-- name: ProjectGameStateFactDay :one
SELECT count(*)::bigint AS projected
FROM gfg_project_state_fact_day($1::date)
`

func (q *Queries) ProjectGameStateFactDay(ctx context.Context, factDate pgtype.Date) (int64, error) {
	row := q.db.QueryRow(ctx, projectGameStateFactDay, factDate)
	var projected int64
	err := row.Scan(&projected)
	return projected, err
}

const pruneGamePlayerRawBatch = `-- name: PruneGamePlayerRawBatch :execrows
WITH eligible AS (
    SELECT raw.id
    FROM gfg_game_player_counts raw
    WHERE raw.collected_at < $1
      AND EXISTS (
          SELECT 1
          FROM gfg_fact_rollup_checkpoints checkpoint
          WHERE checkpoint.pipeline_key = 'game.player_facts'
            AND checkpoint.processed_through IS NOT NULL
            AND (raw.collected_at AT TIME ZONE 'UTC')::date <= checkpoint.processed_through
      )
    ORDER BY raw.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
DELETE FROM gfg_game_player_counts raw
USING eligible
WHERE raw.id = eligible.id
`

type PruneGamePlayerRawBatchParams struct {
	OlderThan pgtype.Timestamptz `json:"older_than"`
	BatchSize int32              `json:"batch_size"`
}

func (q *Queries) PruneGamePlayerRawBatch(ctx context.Context, arg PruneGamePlayerRawBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneGamePlayerRawBatch, arg.OlderThan, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
