// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_domain.sql

package gamesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGameLanguages = `-- name: DeleteGameLanguages :exec
DELETE FROM gfg_game_languages
WHERE game_id = $1
`

func (q *Queries) DeleteGameLanguages(ctx context.Context, gameID int64) error {
	_, err := q.db.Exec(ctx, deleteGameLanguages, gameID)
	return err
}

const getFirstAvailable = `-- name: GetFirstAvailable :one
SELECT game_id, precision, exact_date, release_year, release_month,
       release_quarter, window_start, window_end, source, inferred,
       source_raw, source_observed_at, normalizer_version,
       established_at, updated_at
FROM gfg_game_first_available
WHERE game_id = $1
`

func (q *Queries) GetFirstAvailable(ctx context.Context, gameID int64) (GfgGameFirstAvailable, error) {
	row := q.db.QueryRow(ctx, getFirstAvailable, gameID)
	var i GfgGameFirstAvailable
	err := row.Scan(
		&i.GameID,
		&i.Precision,
		&i.ExactDate,
		&i.ReleaseYear,
		&i.ReleaseMonth,
		&i.ReleaseQuarter,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Source,
		&i.Inferred,
		&i.SourceRaw,
		&i.SourceObservedAt,
		&i.NormalizerVersion,
		&i.EstablishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReleaseState = `-- name: GetReleaseState :one
SELECT game_id, availability, precision, exact_date, release_year,
       release_month, release_quarter, window_start, window_end, raw_text,
       source, source_region, source_locale, normalizer_version,
       observed_at, updated_at
FROM gfg_game_release_state
WHERE game_id = $1
`

func (q *Queries) GetReleaseState(ctx context.Context, gameID int64) (GfgGameReleaseState, error) {
	row := q.db.QueryRow(ctx, getReleaseState, gameID)
	var i GfgGameReleaseState
	err := row.Scan(
		&i.GameID,
		&i.Availability,
		&i.Precision,
		&i.ExactDate,
		&i.ReleaseYear,
		&i.ReleaseMonth,
		&i.ReleaseQuarter,
		&i.WindowStart,
		&i.WindowEnd,
		&i.RawText,
		&i.Source,
		&i.SourceRegion,
		&i.SourceLocale,
		&i.NormalizerVersion,
		&i.ObservedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFirstAvailableIfAbsent = `-- name: InsertFirstAvailableIfAbsent :execrows
INSERT INTO gfg_game_first_available (
    game_id, precision, exact_date, release_year, release_month,
    release_quarter, window_start, window_end, source, inferred,
    source_raw, source_observed_at, normalizer_version
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12, $13
)
ON CONFLICT (game_id) DO NOTHING
`

type InsertFirstAvailableIfAbsentParams struct {
	GameID            int64              `json:"game_id"`
	Precision         string             `json:"precision"`
	ExactDate         pgtype.Date        `json:"exact_date"`
	ReleaseYear       int32              `json:"release_year"`
	ReleaseMonth      *int32             `json:"release_month"`
	ReleaseQuarter    *int32             `json:"release_quarter"`
	WindowStart       pgtype.Date        `json:"window_start"`
	WindowEnd         pgtype.Date        `json:"window_end"`
	Source            string             `json:"source"`
	Inferred          bool               `json:"inferred"`
	SourceRaw         string             `json:"source_raw"`
	SourceObservedAt  pgtype.Timestamptz `json:"source_observed_at"`
	NormalizerVersion string             `json:"normalizer_version"`
}

func (q *Queries) InsertFirstAvailableIfAbsent(ctx context.Context, arg InsertFirstAvailableIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFirstAvailableIfAbsent,
		arg.GameID,
		arg.Precision,
		arg.ExactDate,
		arg.ReleaseYear,
		arg.ReleaseMonth,
		arg.ReleaseQuarter,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Source,
		arg.Inferred,
		arg.SourceRaw,
		arg.SourceObservedAt,
		arg.NormalizerVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertGameLanguage = `-- name: InsertGameLanguage :exec
INSERT INTO gfg_game_languages (
    game_id, language_code, steam_name, steam_api_code, steam_web_code,
    tier, interface_supported, subtitles_supported, full_audio_supported,
    sort_order, source, source_region, source_locale, normalizer_version,
    observed_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10, $11,
    $12, $13,
    $14, $15
)
`

type InsertGameLanguageParams struct {
	GameID             int64              `json:"game_id"`
	LanguageCode       *string            `json:"language_code"`
	SteamName          string             `json:"steam_name"`
	SteamApiCode       *string            `json:"steam_api_code"`
	SteamWebCode       *string            `json:"steam_web_code"`
	Tier               string             `json:"tier"`
	InterfaceSupported *bool              `json:"interface_supported"`
	SubtitlesSupported *bool              `json:"subtitles_supported"`
	FullAudioSupported *bool              `json:"full_audio_supported"`
	SortOrder          int32              `json:"sort_order"`
	Source             string             `json:"source"`
	SourceRegion       string             `json:"source_region"`
	SourceLocale       string             `json:"source_locale"`
	NormalizerVersion  string             `json:"normalizer_version"`
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
}

func (q *Queries) InsertGameLanguage(ctx context.Context, arg InsertGameLanguageParams) error {
	_, err := q.db.Exec(ctx, insertGameLanguage,
		arg.GameID,
		arg.LanguageCode,
		arg.SteamName,
		arg.SteamApiCode,
		arg.SteamWebCode,
		arg.Tier,
		arg.InterfaceSupported,
		arg.SubtitlesSupported,
		arg.FullAudioSupported,
		arg.SortOrder,
		arg.Source,
		arg.SourceRegion,
		arg.SourceLocale,
		arg.NormalizerVersion,
		arg.ObservedAt,
	)
	return err
}

const insertReleaseHistory = `-- name: InsertReleaseHistory :exec
INSERT INTO gfg_game_release_history (
    game_id, availability, precision, exact_date, release_year,
    release_month, release_quarter, window_start, window_end, raw_text,
    source, source_region, source_locale, normalizer_version, observed_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15
)
`

type InsertReleaseHistoryParams struct {
	GameID            int64              `json:"game_id"`
	Availability      string             `json:"availability"`
	Precision         string             `json:"precision"`
	ExactDate         pgtype.Date        `json:"exact_date"`
	ReleaseYear       *int32             `json:"release_year"`
	ReleaseMonth      *int32             `json:"release_month"`
	ReleaseQuarter    *int32             `json:"release_quarter"`
	WindowStart       pgtype.Date        `json:"window_start"`
	WindowEnd         pgtype.Date        `json:"window_end"`
	RawText           string             `json:"raw_text"`
	Source            string             `json:"source"`
	SourceRegion      string             `json:"source_region"`
	SourceLocale      string             `json:"source_locale"`
	NormalizerVersion string             `json:"normalizer_version"`
	ObservedAt        pgtype.Timestamptz `json:"observed_at"`
}

func (q *Queries) InsertReleaseHistory(ctx context.Context, arg InsertReleaseHistoryParams) error {
	_, err := q.db.Exec(ctx, insertReleaseHistory,
		arg.GameID,
		arg.Availability,
		arg.Precision,
		arg.ExactDate,
		arg.ReleaseYear,
		arg.ReleaseMonth,
		arg.ReleaseQuarter,
		arg.WindowStart,
		arg.WindowEnd,
		arg.RawText,
		arg.Source,
		arg.SourceRegion,
		arg.SourceLocale,
		arg.NormalizerVersion,
		arg.ObservedAt,
	)
	return err
}

const insertReleaseState = `-- name: InsertReleaseState :exec
INSERT INTO gfg_game_release_state (
    game_id, availability, precision, exact_date, release_year,
    release_month, release_quarter, window_start, window_end, raw_text,
    source, source_region, source_locale, normalizer_version, observed_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15
)
`

type InsertReleaseStateParams struct {
	GameID            int64              `json:"game_id"`
	Availability      string             `json:"availability"`
	Precision         string             `json:"precision"`
	ExactDate         pgtype.Date        `json:"exact_date"`
	ReleaseYear       *int32             `json:"release_year"`
	ReleaseMonth      *int32             `json:"release_month"`
	ReleaseQuarter    *int32             `json:"release_quarter"`
	WindowStart       pgtype.Date        `json:"window_start"`
	WindowEnd         pgtype.Date        `json:"window_end"`
	RawText           string             `json:"raw_text"`
	Source            string             `json:"source"`
	SourceRegion      string             `json:"source_region"`
	SourceLocale      string             `json:"source_locale"`
	NormalizerVersion string             `json:"normalizer_version"`
	ObservedAt        pgtype.Timestamptz `json:"observed_at"`
}

func (q *Queries) InsertReleaseState(ctx context.Context, arg InsertReleaseStateParams) error {
	_, err := q.db.Exec(ctx, insertReleaseState,
		arg.GameID,
		arg.Availability,
		arg.Precision,
		arg.ExactDate,
		arg.ReleaseYear,
		arg.ReleaseMonth,
		arg.ReleaseQuarter,
		arg.WindowStart,
		arg.WindowEnd,
		arg.RawText,
		arg.Source,
		arg.SourceRegion,
		arg.SourceLocale,
		arg.NormalizerVersion,
		arg.ObservedAt,
	)
	return err
}

const listLegacyFirstAvailableCandidates = `-- name: ListLegacyFirstAvailableCandidates :many
SELECT g.id AS game_id,
       g.release_date,
       (d.game_id IS NOT NULL)::boolean AS has_current_state,
       COALESCE(d.release_coming_soon, false)::boolean AS release_coming_soon,
       d.collected_at AS source_observed_at
FROM gfg_game g
LEFT JOIN gfg_game_v2_details d ON d.game_id = g.id
WHERE btrim(g.release_date) <> ''
ORDER BY g.id
`

type ListLegacyFirstAvailableCandidatesRow struct {
	GameID            int64              `json:"game_id"`
	ReleaseDate       string             `json:"release_date"`
	HasCurrentState   bool               `json:"has_current_state"`
	ReleaseComingSoon bool               `json:"release_coming_soon"`
	SourceObservedAt  pgtype.Timestamptz `json:"source_observed_at"`
}

func (q *Queries) ListLegacyFirstAvailableCandidates(ctx context.Context) ([]ListLegacyFirstAvailableCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listLegacyFirstAvailableCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegacyFirstAvailableCandidatesRow{}
	for rows.Next() {
		var i ListLegacyFirstAvailableCandidatesRow
		if err := rows.Scan(
			&i.GameID,
			&i.ReleaseDate,
			&i.HasCurrentState,
			&i.ReleaseComingSoon,
			&i.SourceObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGameTarget = `-- name: LockGameTarget :one
SELECT id, appid
FROM gfg_game
WHERE id = $1
FOR UPDATE
`

type LockGameTargetRow struct {
	ID    int64 `json:"id"`
	Appid int64 `json:"appid"`
}

func (q *Queries) LockGameTarget(ctx context.Context, gameID int64) (LockGameTargetRow, error) {
	row := q.db.QueryRow(ctx, lockGameTarget, gameID)
	var i LockGameTargetRow
	err := row.Scan(&i.ID, &i.Appid)
	return i, err
}

const updateReleaseState = `-- name: UpdateReleaseState :exec
UPDATE gfg_game_release_state
SET availability = $1,
    precision = $2,
    exact_date = $3,
    release_year = $4,
    release_month = $5,
    release_quarter = $6,
    window_start = $7,
    window_end = $8,
    raw_text = $9,
    source = $10,
    source_region = $11,
    source_locale = $12,
    normalizer_version = $13,
    observed_at = $14,
    updated_at = now()
WHERE game_id = $15
`

type UpdateReleaseStateParams struct {
	Availability      string             `json:"availability"`
	Precision         string             `json:"precision"`
	ExactDate         pgtype.Date        `json:"exact_date"`
	ReleaseYear       *int32             `json:"release_year"`
	ReleaseMonth      *int32             `json:"release_month"`
	ReleaseQuarter    *int32             `json:"release_quarter"`
	WindowStart       pgtype.Date        `json:"window_start"`
	WindowEnd         pgtype.Date        `json:"window_end"`
	RawText           string             `json:"raw_text"`
	Source            string             `json:"source"`
	SourceRegion      string             `json:"source_region"`
	SourceLocale      string             `json:"source_locale"`
	NormalizerVersion string             `json:"normalizer_version"`
	ObservedAt        pgtype.Timestamptz `json:"observed_at"`
	GameID            int64              `json:"game_id"`
}

func (q *Queries) UpdateReleaseState(ctx context.Context, arg UpdateReleaseStateParams) error {
	_, err := q.db.Exec(ctx, updateReleaseState,
		arg.Availability,
		arg.Precision,
		arg.ExactDate,
		arg.ReleaseYear,
		arg.ReleaseMonth,
		arg.ReleaseQuarter,
		arg.WindowStart,
		arg.WindowEnd,
		arg.RawText,
		arg.Source,
		arg.SourceRegion,
		arg.SourceLocale,
		arg.NormalizerVersion,
		arg.ObservedAt,
		arg.GameID,
	)
	return err
}
