// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: historical_facts.sql

package gamesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const refreshCollectedGameDaily = `-- name: RefreshCollectedGameDaily :exec
SELECT gfg_refresh_current_game_daily(
    $1::bigint,
    $2::text
)
`

type RefreshCollectedGameDailyParams struct {
	GameID                int64  `json:"game_id"`
	MaterializationSource string `json:"materialization_source"`
}

func (q *Queries) RefreshCollectedGameDaily(ctx context.Context, arg RefreshCollectedGameDailyParams) error {
	_, err := q.db.Exec(ctx, refreshCollectedGameDaily, arg.GameID, arg.MaterializationSource)
	return err
}

const upsertPriceDailyObserved = `-- name: UpsertPriceDailyObserved :exec
INSERT INTO gfg_game_price_daily (
    tracking_period_id, game_id, appid, region, fact_date, price_state,
    currency, initial_amount, final_amount, discount_percent, observed_at,
    materialization_source, projection_version, finalized_at,
    created_at, updated_at
)
SELECT p.id,
       $1,
       $2,
       $3,
       ($4::timestamptz AT TIME ZONE 'UTC')::date,
       $5,
       CASE WHEN $5::text = 'priced' THEN NULLIF($6::text, '') END,
       CASE WHEN $5::text = 'priced' THEN $7::bigint END,
       CASE WHEN $5::text = 'priced' THEN $8::bigint END,
       CASE WHEN $5::text = 'priced' THEN $9::integer END,
       $4,
       'observed',
       1,
       NULL,
       transaction_timestamp(),
       transaction_timestamp()
FROM gfg_game_tracking_periods p
WHERE p.game_id = $1
  AND p.appid = $2
  AND p.tracking_basis = 'explicit'
  AND p.tracked_until IS NULL
ON CONFLICT (tracking_period_id, region, fact_date) DO UPDATE
SET appid = EXCLUDED.appid,
    price_state = EXCLUDED.price_state,
    currency = EXCLUDED.currency,
    initial_amount = EXCLUDED.initial_amount,
    final_amount = EXCLUDED.final_amount,
    discount_percent = EXCLUDED.discount_percent,
    observed_at = EXCLUDED.observed_at,
    materialization_source = EXCLUDED.materialization_source,
    projection_version = EXCLUDED.projection_version,
    updated_at = transaction_timestamp()
WHERE gfg_game_price_daily.finalized_at IS NULL
  AND (gfg_game_price_daily.observed_at IS NULL
       OR EXCLUDED.observed_at >= gfg_game_price_daily.observed_at)
`

type UpsertPriceDailyObservedParams struct {
	GameID          int64              `json:"game_id"`
	Appid           int64              `json:"appid"`
	Region          string             `json:"region"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	PriceState      string             `json:"price_state"`
	Currency        string             `json:"currency"`
	InitialAmount   int64              `json:"initial_amount"`
	FinalAmount     int64              `json:"final_amount"`
	DiscountPercent int32              `json:"discount_percent"`
}

func (q *Queries) UpsertPriceDailyObserved(ctx context.Context, arg UpsertPriceDailyObservedParams) error {
	_, err := q.db.Exec(ctx, upsertPriceDailyObserved,
		arg.GameID,
		arg.Appid,
		arg.Region,
		arg.ObservedAt,
		arg.PriceState,
		arg.Currency,
		arg.InitialAmount,
		arg.FinalAmount,
		arg.DiscountPercent,
	)
	return err
}
