export type CollectionOverview = { running_count: number; queued_count: number; failed_24h: number; missed_24h: number }
export type CollectorInstance = { domain: string; instance_id: string; collector_id: string; hostname: string; version: string; commit_sha: string; capabilities: string[]; started_at: string; last_heartbeat_at: string; stopped_at?: string; health: string; heartbeat_age_seconds: number }
export type CollectionSchedule = { domain: string; id: number; job_key: string; name: string; enabled: boolean; schedule_kind: string; cron_expression?: string; interval_seconds?: number; anchor_at?: string; timezone: string; misfire_policy: string; misfire_grace_seconds: number; overlap_policy: string; priority: number; concurrency_key: string; version: number; last_materialized_for?: string; next_scheduled_for?: string; last_status: string; last_success_count: number; last_expected_count: number; last_success_coverage: number | null; control_now?: string }
export type CollectionJob = { domain: string; id: number; schedule_id?: number; schedule_version?: number; job_key: string; trigger: string; scope_type: string; scope_id?: number; target?: string; tasks: string[]; priority: number; scheduled_for?: string; status: string; requested_by: string; claimed_by?: string; lease_until?: string; cancel_requested_at?: string; created_at: string; completed_at?: string; run_id?: string; progress?: unknown }
export type CollectionRun = { domain: string; id: string; job_id: number; job_key: string; trigger: string; scope_type: string; scope_id?: number; target?: string; attempt_no: number; collector_instance_id: string; status: string; scheduled_for?: string; started_at: string; ended_at?: string; expected_count: number; attempted_count: number; success_count: number; partial_count: number; failure_count: number; skipped_count: number; schedule_delay_ms: number; duration_ms: number; error_kind: string; error_message: string }
export type CollectionResult = { domain: string; id: number; run_id: string; task: string; entity_id: number; target?: string; status: string; observation_id?: number; duration_ms: number; error_kind: string; error_message: string; started_at: string; ended_at?: string; appid?: number }
export type CollectionChartPoint = { domain: string; job_id: number; job_key: string; job_status: string; run_id?: string; run_status?: string; expected: number; attempted: number; success: number; partial: number; failed: number; skipped: number; coverage: number | null; schedule_delay_ms: number; duration_ms: number; created_at: string; started_at?: string }

export type MetricOverview = { domain: string; metric_key: string; metric_version: number; description: string; processed_through?: string; upstream_processed_through?: string; lag_days?: number; latest_fact_date?: string; population_count: number; eligible_count: number; not_applicable_count: number; positive_count: number; negative_count: number; stale_count: number; not_probed_count: number; probe_failed_count: number; unknown_count: number; adoption_rate: number | null; coverage_rate: number | null }
export type MetricRegistry = { domain: string; metric_key: string; metric_version: number; metric_kind: string; entity_level: string; time_grain: string; source_facts: string[]; eligibility_policy: string; state_policy: string; coverage_policy: string; freshness_seconds?: number; allowed_dimensions: string[]; status: string; description: string; created_at: string; retired_at?: string }
export type MetricCheckpoint = { domain: string; metric_key: string; metric_version: number; status: string; source_start_date?: string; processed_through?: string; upstream_processed_through?: string; lag_days?: number; created_at: string; updated_at: string }
export type MetricDaily = { domain: string; metric_key: string; metric_version: number; fact_date: string; dimension_key: string; dimension_value: string; population_count: number; eligible_count: number; not_applicable_count: number; positive_count: number; negative_count: number; stale_count: number; not_probed_count: number; probe_failed_count: number; unknown_count: number; adoption_rate: number | null; coverage_rate: number | null; computed_at: string }
export type MetricEntity = { domain: string; entity_id: number; historical_name: string; state: string; reason_code: string; source_observed_at?: string; dimension_values: Record<string, unknown>; source_projection_versions: Record<string, unknown>; evaluated_at: string }

export type ChangeOverview = { domain: string; detector_key: string; detector_version: number; status: string; description: string; watermark_policy: string; source_start_date?: string; processed_through?: string; upstream_processed_through?: string; lag_days?: number; latest_projection_date?: string; latest_event_count: number; total_event_count: number }
export type ChangeRegistry = { domain: string; detector_key: string; detector_version: number; source_kind: string; source_contracts: string[]; detection_policy: string; watermark_policy: string; event_codes: string[]; processing_grain: string; status: string; description: string; created_at: string; retired_at?: string }
export type ChangeCheckpoint = { domain: string; detector_key: string; detector_version: number; status: string; watermark_policy: string; source_start_date?: string; processed_through?: string; upstream_processed_through?: string; lag_days?: number; created_at: string; updated_at: string }
export type ChangeEvent = { domain: string; event_key: string; detector_key: string; detector_version: number; entity_id: number; historical_name: string; projection_date: string; event_at?: string; time_basis: string; event_code: string; scope_kind: string; scope_key: string; old_value: Record<string, unknown>; new_value: Record<string, unknown>; source_event_key: string; source_before_key: string; source_after_key: string; source_before_at?: string; source_after_at?: string; source_versions: Record<string, unknown>; materialized_at: string }
export type ChangePage = { total: number; list: ChangeEvent[]; page: number; page_size: number }

export type RelationSize = { name: string; table_bytes: number; index_bytes: number; total_bytes: number }
export type DatabaseStatus = { key: string; health: string; postgresql_version: string; database_name: string; database_size_bytes: number; total_connections: number; active_connections: number; max_connections: number; connection_usage: number | null; database_time?: string; migration: { current_applied: number; expected: number; pending_count: number; status: string }; relations: RelationSize[]; error?: string }
export type DataOpsOverview = { generated_at: string; databases: DatabaseStatus[] }

export type AuditLog = { id: number; action: string; resource: string; target_id: string; operator: string; session_version: number; request_id: string; ip_address: string; user_agent: string; before_data: string; after_data: string; operator_account_id?: number; operator_name: string; operator_role: string; created_at: string }
export type Account = { id: number; username: string; display_name: string; role: 'owner' | 'developer' | 'operator'; status: 'active' | 'disabled'; session_version: number; last_login_at?: string; created_at: string; updated_at: string; password_updated_at?: string }

export type WorkbenchSummary = {
  attention: Array<{ key: string; tone: string; title: string; summary: string; href: string }>
  recent_changes: Array<{ domain: string; event_key: string; historical_name: string; event_code: string; event_at?: string; projection_date: string }>
  recent_operations: Array<{ id: number; action: string; resource: string; target_id: string; operator_name: string; operator_role: string; created_at: string }>
  system_status: Array<{ key: string; label: string; status: string; summary: string; href: string }>
}
