// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collaboration_board.sql

package adminsqlc

import (
	"context"
)

const deleteBoardEdgeVersioned = `-- name: DeleteBoardEdgeVersioned :one
DELETE FROM gfa_collaboration_board_edge WHERE id=$1 AND version=$2 RETURNING id, source_id, target_id, source_handle, target_handle, routing, label, color, arrow, created_by_account_id, updated_by_account_id, version, created_at, updated_at
`

type DeleteBoardEdgeVersionedParams struct {
	ID      int64 `json:"id"`
	Version int64 `json:"version"`
}

func (q *Queries) DeleteBoardEdgeVersioned(ctx context.Context, arg DeleteBoardEdgeVersionedParams) (GfaCollaborationBoardEdge, error) {
	row := q.db.QueryRow(ctx, deleteBoardEdgeVersioned, arg.ID, arg.Version)
	var i GfaCollaborationBoardEdge
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.SourceHandle,
		&i.TargetHandle,
		&i.Routing,
		&i.Label,
		&i.Color,
		&i.Arrow,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoardNodeVersioned = `-- name: DeleteBoardNodeVersioned :one
DELETE FROM gfa_collaboration_board_node WHERE id=$1 AND version=$2 RETURNING id, body, x, y, width, height, z_index, created_by_account_id, updated_by_account_id, version, created_at, updated_at, kind, title, color, rotation, reference_kind, reference_id
`

type DeleteBoardNodeVersionedParams struct {
	ID      int64 `json:"id"`
	Version int64 `json:"version"`
}

func (q *Queries) DeleteBoardNodeVersioned(ctx context.Context, arg DeleteBoardNodeVersionedParams) (GfaCollaborationBoardNode, error) {
	row := q.db.QueryRow(ctx, deleteBoardNodeVersioned, arg.ID, arg.Version)
	var i GfaCollaborationBoardNode
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Title,
		&i.Color,
		&i.Rotation,
		&i.ReferenceKind,
		&i.ReferenceID,
	)
	return i, err
}

const getBoardEdgeForUpdate = `-- name: GetBoardEdgeForUpdate :one
SELECT id, source_id, target_id, source_handle, target_handle, routing, label, color, arrow, created_by_account_id, updated_by_account_id, version, created_at, updated_at FROM gfa_collaboration_board_edge WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetBoardEdgeForUpdate(ctx context.Context, id int64) (GfaCollaborationBoardEdge, error) {
	row := q.db.QueryRow(ctx, getBoardEdgeForUpdate, id)
	var i GfaCollaborationBoardEdge
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.SourceHandle,
		&i.TargetHandle,
		&i.Routing,
		&i.Label,
		&i.Color,
		&i.Arrow,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoardNodeForUpdate = `-- name: GetBoardNodeForUpdate :one
SELECT id, body, x, y, width, height, z_index, created_by_account_id, updated_by_account_id, version, created_at, updated_at, kind, title, color, rotation, reference_kind, reference_id FROM gfa_collaboration_board_node WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetBoardNodeForUpdate(ctx context.Context, id int64) (GfaCollaborationBoardNode, error) {
	row := q.db.QueryRow(ctx, getBoardNodeForUpdate, id)
	var i GfaCollaborationBoardNode
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Title,
		&i.Color,
		&i.Rotation,
		&i.ReferenceKind,
		&i.ReferenceID,
	)
	return i, err
}

const insertBoardEdge = `-- name: InsertBoardEdge :one
INSERT INTO gfa_collaboration_board_edge (source_id,target_id,source_handle,target_handle,routing,label,color,arrow,created_by_account_id,updated_by_account_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING id, source_id, target_id, source_handle, target_handle, routing, label, color, arrow, created_by_account_id, updated_by_account_id, version, created_at, updated_at
`

type InsertBoardEdgeParams struct {
	SourceID     int64  `json:"source_id"`
	TargetID     int64  `json:"target_id"`
	SourceHandle string `json:"source_handle"`
	TargetHandle string `json:"target_handle"`
	Routing      string `json:"routing"`
	Label        string `json:"label"`
	Color        string `json:"color"`
	Arrow        bool   `json:"arrow"`
	AccountID    int64  `json:"account_id"`
}

func (q *Queries) InsertBoardEdge(ctx context.Context, arg InsertBoardEdgeParams) (GfaCollaborationBoardEdge, error) {
	row := q.db.QueryRow(ctx, insertBoardEdge,
		arg.SourceID,
		arg.TargetID,
		arg.SourceHandle,
		arg.TargetHandle,
		arg.Routing,
		arg.Label,
		arg.Color,
		arg.Arrow,
		arg.AccountID,
	)
	var i GfaCollaborationBoardEdge
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.SourceHandle,
		&i.TargetHandle,
		&i.Routing,
		&i.Label,
		&i.Color,
		&i.Arrow,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBoardNode = `-- name: InsertBoardNode :one
INSERT INTO gfa_collaboration_board_node (kind,title,body,color,rotation,reference_kind,reference_id,x,y,width,height,z_index,created_by_account_id,updated_by_account_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13) RETURNING id, body, x, y, width, height, z_index, created_by_account_id, updated_by_account_id, version, created_at, updated_at, kind, title, color, rotation, reference_kind, reference_id
`

type InsertBoardNodeParams struct {
	Kind          string  `json:"kind"`
	Title         string  `json:"title"`
	Body          string  `json:"body"`
	Color         string  `json:"color"`
	Rotation      int32   `json:"rotation"`
	ReferenceKind *string `json:"reference_kind"`
	ReferenceID   *int64  `json:"reference_id"`
	X             int32   `json:"x"`
	Y             int32   `json:"y"`
	Width         int32   `json:"width"`
	Height        int32   `json:"height"`
	ZIndex        int32   `json:"z_index"`
	AccountID     int64   `json:"account_id"`
}

func (q *Queries) InsertBoardNode(ctx context.Context, arg InsertBoardNodeParams) (GfaCollaborationBoardNode, error) {
	row := q.db.QueryRow(ctx, insertBoardNode,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Color,
		arg.Rotation,
		arg.ReferenceKind,
		arg.ReferenceID,
		arg.X,
		arg.Y,
		arg.Width,
		arg.Height,
		arg.ZIndex,
		arg.AccountID,
	)
	var i GfaCollaborationBoardNode
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Title,
		&i.Color,
		&i.Rotation,
		&i.ReferenceKind,
		&i.ReferenceID,
	)
	return i, err
}

const listBoardEdges = `-- name: ListBoardEdges :many
SELECT id, source_id, target_id, source_handle, target_handle, routing, label, color, arrow, created_by_account_id, updated_by_account_id, version, created_at, updated_at FROM gfa_collaboration_board_edge ORDER BY id
`

func (q *Queries) ListBoardEdges(ctx context.Context) ([]GfaCollaborationBoardEdge, error) {
	rows, err := q.db.Query(ctx, listBoardEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfaCollaborationBoardEdge{}
	for rows.Next() {
		var i GfaCollaborationBoardEdge
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.SourceHandle,
			&i.TargetHandle,
			&i.Routing,
			&i.Label,
			&i.Color,
			&i.Arrow,
			&i.CreatedByAccountID,
			&i.UpdatedByAccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardIdeaReferences = `-- name: ListBoardIdeaReferences :many
SELECT id,kind,COALESCE(title,source,'')::text AS title,status FROM gfa_content_idea WHERE id=ANY($1::bigint[])
`

type ListBoardIdeaReferencesRow struct {
	ID     int64  `json:"id"`
	Kind   string `json:"kind"`
	Title  string `json:"title"`
	Status string `json:"status"`
}

func (q *Queries) ListBoardIdeaReferences(ctx context.Context, ids []int64) ([]ListBoardIdeaReferencesRow, error) {
	rows, err := q.db.Query(ctx, listBoardIdeaReferences, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardIdeaReferencesRow{}
	for rows.Next() {
		var i ListBoardIdeaReferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Title,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardNodes = `-- name: ListBoardNodes :many
SELECT id, body, x, y, width, height, z_index, created_by_account_id, updated_by_account_id, version, created_at, updated_at, kind, title, color, rotation, reference_kind, reference_id FROM gfa_collaboration_board_node ORDER BY z_index, id
`

func (q *Queries) ListBoardNodes(ctx context.Context) ([]GfaCollaborationBoardNode, error) {
	rows, err := q.db.Query(ctx, listBoardNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfaCollaborationBoardNode{}
	for rows.Next() {
		var i GfaCollaborationBoardNode
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.ZIndex,
			&i.CreatedByAccountID,
			&i.UpdatedByAccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.Title,
			&i.Color,
			&i.Rotation,
			&i.ReferenceKind,
			&i.ReferenceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentBoardEdgesForUpdate = `-- name: ListIncidentBoardEdgesForUpdate :many
SELECT id, source_id, target_id, source_handle, target_handle, routing, label, color, arrow, created_by_account_id, updated_by_account_id, version, created_at, updated_at FROM gfa_collaboration_board_edge WHERE source_id=$1 OR target_id=$1 ORDER BY id FOR UPDATE
`

func (q *Queries) ListIncidentBoardEdgesForUpdate(ctx context.Context, sourceID int64) ([]GfaCollaborationBoardEdge, error) {
	rows, err := q.db.Query(ctx, listIncidentBoardEdgesForUpdate, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfaCollaborationBoardEdge{}
	for rows.Next() {
		var i GfaCollaborationBoardEdge
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.SourceHandle,
			&i.TargetHandle,
			&i.Routing,
			&i.Label,
			&i.Color,
			&i.Arrow,
			&i.CreatedByAccountID,
			&i.UpdatedByAccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBoardEndpoints = `-- name: LockBoardEndpoints :many
SELECT id FROM gfa_collaboration_board_node WHERE id=ANY($1::bigint[]) AND kind IN ('note','card') ORDER BY id FOR KEY SHARE
`

func (q *Queries) LockBoardEndpoints(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockBoardEndpoints, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveBoardNodeVersioned = `-- name: MoveBoardNodeVersioned :one
UPDATE gfa_collaboration_board_node SET x=$1,y=$2,width=$3,height=$4,z_index=$5,
updated_by_account_id=$6,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$7 AND version=$8 RETURNING id, body, x, y, width, height, z_index, created_by_account_id, updated_by_account_id, version, created_at, updated_at, kind, title, color, rotation, reference_kind, reference_id
`

type MoveBoardNodeVersionedParams struct {
	X                  int32 `json:"x"`
	Y                  int32 `json:"y"`
	Width              int32 `json:"width"`
	Height             int32 `json:"height"`
	ZIndex             int32 `json:"z_index"`
	UpdatedByAccountID int64 `json:"updated_by_account_id"`
	ID                 int64 `json:"id"`
	Version            int64 `json:"version"`
}

func (q *Queries) MoveBoardNodeVersioned(ctx context.Context, arg MoveBoardNodeVersionedParams) (GfaCollaborationBoardNode, error) {
	row := q.db.QueryRow(ctx, moveBoardNodeVersioned,
		arg.X,
		arg.Y,
		arg.Width,
		arg.Height,
		arg.ZIndex,
		arg.UpdatedByAccountID,
		arg.ID,
		arg.Version,
	)
	var i GfaCollaborationBoardNode
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Title,
		&i.Color,
		&i.Rotation,
		&i.ReferenceKind,
		&i.ReferenceID,
	)
	return i, err
}

const updateBoardEdgeVersioned = `-- name: UpdateBoardEdgeVersioned :one
UPDATE gfa_collaboration_board_edge SET routing=$1,label=$2,color=$3,arrow=$4,
updated_by_account_id=$5,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$6 AND version=$7 RETURNING id, source_id, target_id, source_handle, target_handle, routing, label, color, arrow, created_by_account_id, updated_by_account_id, version, created_at, updated_at
`

type UpdateBoardEdgeVersionedParams struct {
	Routing            string `json:"routing"`
	Label              string `json:"label"`
	Color              string `json:"color"`
	Arrow              bool   `json:"arrow"`
	UpdatedByAccountID int64  `json:"updated_by_account_id"`
	ID                 int64  `json:"id"`
	Version            int64  `json:"version"`
}

func (q *Queries) UpdateBoardEdgeVersioned(ctx context.Context, arg UpdateBoardEdgeVersionedParams) (GfaCollaborationBoardEdge, error) {
	row := q.db.QueryRow(ctx, updateBoardEdgeVersioned,
		arg.Routing,
		arg.Label,
		arg.Color,
		arg.Arrow,
		arg.UpdatedByAccountID,
		arg.ID,
		arg.Version,
	)
	var i GfaCollaborationBoardEdge
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.SourceHandle,
		&i.TargetHandle,
		&i.Routing,
		&i.Label,
		&i.Color,
		&i.Arrow,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBoardNodeVersioned = `-- name: UpdateBoardNodeVersioned :one
UPDATE gfa_collaboration_board_node SET title=$1,body=$2,color=$3,rotation=$4,reference_kind=$5,reference_id=$6,
updated_by_account_id=$7,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$8 AND version=$9 RETURNING id, body, x, y, width, height, z_index, created_by_account_id, updated_by_account_id, version, created_at, updated_at, kind, title, color, rotation, reference_kind, reference_id
`

type UpdateBoardNodeVersionedParams struct {
	Title              string  `json:"title"`
	Body               string  `json:"body"`
	Color              string  `json:"color"`
	Rotation           int32   `json:"rotation"`
	ReferenceKind      *string `json:"reference_kind"`
	ReferenceID        *int64  `json:"reference_id"`
	UpdatedByAccountID int64   `json:"updated_by_account_id"`
	ID                 int64   `json:"id"`
	Version            int64   `json:"version"`
}

func (q *Queries) UpdateBoardNodeVersioned(ctx context.Context, arg UpdateBoardNodeVersionedParams) (GfaCollaborationBoardNode, error) {
	row := q.db.QueryRow(ctx, updateBoardNodeVersioned,
		arg.Title,
		arg.Body,
		arg.Color,
		arg.Rotation,
		arg.ReferenceKind,
		arg.ReferenceID,
		arg.UpdatedByAccountID,
		arg.ID,
		arg.Version,
	)
	var i GfaCollaborationBoardNode
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.CreatedByAccountID,
		&i.UpdatedByAccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Title,
		&i.Color,
		&i.Rotation,
		&i.ReferenceKind,
		&i.ReferenceID,
	)
	return i, err
}
