-- V3-P0.2 Game historical identity and raw-integrity foundation.
-- +goose Up

CREATE SEQUENCE public.gfg_game_id_seq AS bigint;

-- The current entity is not the historical high-water mark: a hard-deleted
-- Game can still be named by Raw, acquisition ledger, release history, or
-- another durable production table. Seed from every pre-P0.2 Game-ID owner.
WITH historical_game_ids(game_id) AS (
    SELECT id FROM public.gfg_game
    UNION ALL SELECT scope_id FROM public.gfg_collection_jobs
        WHERE scope_type = 'game' AND scope_id IS NOT NULL
    UNION ALL SELECT game_id FROM public.gfg_collection_task_results
    UNION ALL SELECT game_id FROM public.gfg_game_assets
    UNION ALL SELECT game_id FROM public.gfg_game_comment
    UNION ALL SELECT game_id FROM public.gfg_game_detail_snapshots
    UNION ALL SELECT game_id FROM public.gfg_game_details
    UNION ALL SELECT game_id FROM public.gfg_game_first_available
    UNION ALL SELECT game_id FROM public.gfg_game_languages
    UNION ALL SELECT game_id FROM public.gfg_game_localized_details
    UNION ALL SELECT game_id FROM public.gfg_game_media
    UNION ALL SELECT game_id FROM public.gfg_game_news
    UNION ALL SELECT game_id FROM public.gfg_game_player_counts
    UNION ALL SELECT game_id FROM public.gfg_game_prices
    UNION ALL SELECT source_game_id FROM public.gfg_game_recommendations
    UNION ALL SELECT target_game_id FROM public.gfg_game_recommendations
    UNION ALL SELECT game_id FROM public.gfg_game_release_history
    UNION ALL SELECT game_id FROM public.gfg_game_release_state
    UNION ALL SELECT game_id FROM public.gfg_game_requirements
    UNION ALL SELECT game_id FROM public.gfg_tag_map
), historical_bound AS (
    SELECT max(game_id) AS max_game_id FROM historical_game_ids
)
SELECT setval(
    'public.gfg_game_id_seq',
    GREATEST(COALESCE(max_game_id, 1), 1),
    max_game_id IS NOT NULL
)
FROM historical_bound;

ALTER SEQUENCE public.gfg_game_id_seq OWNED BY public.gfg_game.id;
ALTER TABLE public.gfg_game
    ALTER COLUMN id SET DEFAULT nextval('public.gfg_game_id_seq'::regclass);

ALTER TABLE public.gfg_game_prices
    ADD COLUMN price_state text;

UPDATE public.gfg_game_prices
SET price_state = CASE
    WHEN is_free THEN 'free'
    WHEN btrim(currency) <> '' THEN 'priced'
    ELSE 'unknown'
END;

ALTER TABLE public.gfg_game_prices
    ALTER COLUMN price_state SET NOT NULL,
    ALTER COLUMN price_state SET DEFAULT 'unknown',
    ADD CONSTRAINT gfg_game_prices_price_state_check
        CHECK (price_state IN ('free', 'priced', 'unpriced', 'unknown'));

-- A durable player run has exactly one canonical raw result per Game. Rank any
-- pre-contract duplicates by agreement with the Task Result, observation-time
-- proximity, and then stable id. The audit count is visible in Goose output.
-- +goose StatementBegin
DO $audit$
DECLARE
    duplicate_count bigint;
BEGIN
    SELECT COALESCE(sum(row_count - 1), 0)
    INTO duplicate_count
    FROM (
        SELECT count(*) AS row_count
        FROM public.gfg_game_player_counts
        WHERE run_id <> ''
        GROUP BY run_id, game_id
        HAVING count(*) > 1
    ) duplicates;
    IF duplicate_count > 0 THEN
        RAISE NOTICE 'P0.2 Game raw migration will remove % duplicate Run/Game row(s)', duplicate_count;
    END IF;
END;
$audit$;
-- +goose StatementEnd

WITH ranked AS (
    SELECT raw.id,
           row_number() OVER (
               PARTITION BY raw.run_id, raw.game_id
               ORDER BY
                   CASE WHEN result.status IS NOT NULL AND raw.status = result.status THEN 0 ELSE 1 END,
                   abs(extract(epoch FROM (raw.collected_at - COALESCE(result.ended_at, result.started_at, raw.collected_at)))),
                   raw.id DESC
           ) AS canonical_rank
    FROM public.gfg_game_player_counts raw
    LEFT JOIN LATERAL (
        SELECT candidate.status, candidate.started_at, candidate.ended_at
        FROM public.gfg_collection_task_results candidate
        WHERE candidate.run_id = raw.run_id
          AND candidate.game_id = raw.game_id
          AND candidate.task_type = 'players'
        ORDER BY candidate.id DESC
        LIMIT 1
    ) result ON true
    WHERE raw.run_id <> ''
)
DELETE FROM public.gfg_game_player_counts raw
USING ranked
WHERE ranked.id = raw.id AND ranked.canonical_rank > 1;

CREATE UNIQUE INDEX uq_gfg_game_player_counts_run_game
    ON public.gfg_game_player_counts (run_id, game_id)
    WHERE run_id <> '';

ALTER TABLE public.gfg_game_release_history
    DROP CONSTRAINT gfg_game_release_history_game_id_fkey;

CREATE TABLE public.gfg_game_tracking_periods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint NOT NULL,
    appid bigint NOT NULL,
    tracked_from timestamp with time zone NOT NULL,
    tracked_until timestamp with time zone,
    tracking_basis text NOT NULL,
    opened_reason text NOT NULL,
    closed_reason text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT gfg_game_tracking_periods_interval_check
        CHECK (tracked_until IS NULL OR tracked_until > tracked_from),
    CONSTRAINT gfg_game_tracking_periods_basis_check
        CHECK (tracking_basis IN ('explicit', 'legacy_observed')),
    CONSTRAINT gfg_game_tracking_periods_explicit_shape_check CHECK (
        tracking_basis <> 'explicit' OR appid > 0
    )
);

CREATE UNIQUE INDEX uq_gfg_game_tracking_periods_active_explicit
    ON public.gfg_game_tracking_periods (game_id)
    WHERE tracking_basis = 'explicit' AND tracked_until IS NULL;
CREATE INDEX idx_gfg_game_tracking_periods_identity_time
    ON public.gfg_game_tracking_periods (game_id, appid, tracked_from, tracked_until);
CREATE INDEX idx_gfg_game_tracking_periods_time
    ON public.gfg_game_tracking_periods (tracked_from, tracked_until);

-- Build conservative, closed legacy identity periods from retained evidence.
-- AppID transitions are ordered by the first observation; the next identity's
-- first observation is the previous identity's exclusive upper bound.
WITH migration_clock AS (
    SELECT transaction_timestamp() AS cutover
), evidence AS (
    SELECT game_id, appid, collected_at AS observed_at
    FROM public.gfg_game_player_counts
    WHERE appid > 0
    UNION ALL
    SELECT game_id, appid, started_at
    FROM public.gfg_collection_task_results
    WHERE appid > 0
), identity_bounds AS (
    SELECT game_id, appid, min(observed_at) AS first_observed_at,
           max(observed_at) AS last_observed_at
    FROM evidence
    GROUP BY game_id, appid
), ordered AS (
    SELECT game_id, appid, first_observed_at, last_observed_at,
           lead(first_observed_at) OVER (
               PARTITION BY game_id ORDER BY first_observed_at, appid
           ) AS next_identity_at
    FROM identity_bounds
)
INSERT INTO public.gfg_game_tracking_periods (
    game_id, appid, tracked_from, tracked_until, tracking_basis,
    opened_reason, closed_reason
)
SELECT game_id,
       appid,
       first_observed_at,
       GREATEST(
           first_observed_at + interval '1 microsecond',
           LEAST(
               COALESCE(next_identity_at, migration_clock.cutover),
               migration_clock.cutover
           )
       ),
       'legacy_observed',
       'historical_evidence',
       'p0.2_quality_cutover'
FROM ordered
CROSS JOIN migration_clock
WHERE first_observed_at < migration_clock.cutover;

-- Current identity starts at the rollout transaction; it is never projected
-- backwards over legacy evidence.
INSERT INTO public.gfg_game_tracking_periods (
    game_id, appid, tracked_from, tracking_basis, opened_reason
)
SELECT id, appid, transaction_timestamp(), 'explicit', 'p0.2_rollout'
FROM public.gfg_game;

COMMENT ON TABLE public.gfg_game_tracking_periods IS
    'Immutable Game/AppID eligibility periods used by historical facts; no FK to current gfg_game.';
COMMENT ON COLUMN public.gfg_game_prices.price_state IS
    'Authoritative price state: free, priced, unpriced, or unknown.';

-- +goose Down

DROP TABLE public.gfg_game_tracking_periods;

ALTER TABLE public.gfg_game_release_history
    ADD CONSTRAINT gfg_game_release_history_game_id_fkey
        FOREIGN KEY (game_id) REFERENCES public.gfg_game(id) ON DELETE CASCADE;

DROP INDEX public.uq_gfg_game_player_counts_run_game;

ALTER TABLE public.gfg_game_prices
    DROP CONSTRAINT gfg_game_prices_price_state_check,
    DROP COLUMN price_state;

ALTER TABLE public.gfg_game ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE public.gfg_game_id_seq;
