import type { ResourceConfig } from './types'

const bool01 = [
  { label: '是', value: '1' },
  { label: '否', value: '0' },
]

const groupKeys = ['official', 'discord', 'twitter', 'youtube', 'telegram', 'bsky', 'afdian', 'qq', 'reddit', 'bilibili', 'weibo', 'tiktok', 'vk', 'facebook', 'twitch', 'instagram', 'xiaohongshu']
const linkKeys = ['steamdb', 'steambase', 'gamalytic', 'vgi', 'playtracker', 'pcgamingwiki', 'metacritic']

function kvDefaults(keys: string[]) {
  return keys.map((key) => ({ key, value: '' }))
}

export const resources: ResourceConfig[] = [
  {
    key: 'sayings',
    title: '金句',
    section: 'nav',
    listEndpoint: '/api/v1/nav/sayings',
    detailEndpoint: '/api/v1/nav/sayings',
    columns: [{ key: 'id', label: 'ID' }, { key: 'author', label: '作者' }, { key: 'saying', label: '内容' }],
    fields: [
      { key: 'author', label: '作者', type: 'text' },
      { key: 'saying', label: '内容', type: 'textarea' },
    ],
    defaults: { author: '', saying: '' },
  },
  {
    key: 'update-notices',
    title: '更新公告',
    section: 'nav',
    listEndpoint: '/api/v1/nav/update-notices',
    detailEndpoint: '/api/v1/nav/update-notices',
    columns: [{ key: 'id', label: 'ID' }, { key: 'title', label: '中文标题' }, { key: 'title_en', label: '英文标题' }, { key: 'published_at', label: '发布时间' }],
    fields: [
      { key: 'title', label: '中文标题', type: 'text' },
      { key: 'title_en', label: '英文标题', type: 'text' },
      { key: 'published_at', label: '发布时间', type: 'datetime' },
      { key: 'body', label: '中文正文', type: 'textarea' },
      { key: 'body_en', label: '英文正文', type: 'textarea' },
    ],
    defaults: { title: '', title_en: '', published_at: '', body: '', body_en: '' },
  },
  {
    key: 'collector-domains',
    title: '采集域名',
    section: 'nav',
    listEndpoint: '/api/v1/nav/collector-domains',
    detailEndpoint: '/api/v1/nav/collector-domains',
    columns: [{ key: 'id', label: 'ID' }, { key: 'site_name', label: '网站' }, { key: 'name', label: '域名' }, { key: 'proxy', label: '代理' }, { key: 'tls', label: 'TLS' }],
    fields: [
      { key: 'site_id', label: '网站', type: 'remote-select', optionEndpoint: '/api/v1/options/sites' },
      { key: 'name', label: '域名', type: 'text' },
      { key: 'proxy', label: '代理', type: 'select', options: bool01 },
      { key: 'prefix', label: '前缀', type: 'text' },
      { key: 'tls', label: 'TLS', type: 'select', options: bool01 },
    ],
    defaults: { site_id: '', name: '', proxy: '0', prefix: '', tls: '1' },
  },
  {
    key: 'sites',
    title: '网站',
    section: 'nav',
    listEndpoint: '/api/v1/nav/sites',
    detailEndpoint: '/api/v1/nav/sites',
    columns: [{ key: 'id', label: 'ID' }, { key: 'name', label: '名称' }],
    fields: [
      { key: 'name', label: '中文名', type: 'text' },
      { key: 'name_en', label: '英文名', type: 'text' },
      { key: 'info', label: '中文简介', type: 'textarea' },
      { key: 'info_en', label: '英文简介', type: 'textarea' },
      { key: 'country', label: '国家', type: 'text' },
      { key: 'nsfw', label: 'NSFW', type: 'select', options: bool01 },
      { key: 'welfare', label: '公益', type: 'select', options: bool01 },
      { key: 'icon', label: '图标', type: 'text' },
    ],
    defaults: { name: '', name_en: '', info: '', info_en: '', country: '', nsfw: '0', welfare: '0', icon: '' },
  },
  {
    key: 'site-groups',
    title: '网站分组',
    section: 'nav',
    listEndpoint: '/api/v1/nav/site-groups',
    detailEndpoint: '/api/v1/nav/site-groups',
    columns: [{ key: 'id', label: 'ID' }, { key: 'name', label: '名称' }, { key: 'priority', label: '优先级' }],
    fields: [
      { key: 'name', label: '中文名', type: 'text' },
      { key: 'name_en', label: '英文名', type: 'text' },
      { key: 'info', label: '中文简介', type: 'textarea' },
      { key: 'info_en', label: '英文简介', type: 'textarea' },
      { key: 'priority', label: '优先级', type: 'number' },
    ],
    defaults: { name: '', name_en: '', info: '', info_en: '', priority: 0 },
  },
  {
    key: 'site-group-maps',
    title: '网站分组映射',
    section: 'nav',
    listEndpoint: '/api/v1/nav/site-group-maps',
    detailEndpoint: '/api/v1/nav/site-group-maps',
    columns: [{ key: 'id', label: 'ID' }, { key: 'site_name', label: '网站' }, { key: 'group_name', label: '分组' }],
    fields: [
      { key: 'site_id', label: '网站', type: 'remote-select', optionEndpoint: '/api/v1/options/sites' },
      { key: 'group_id', label: '分组', type: 'remote-select', optionEndpoint: '/api/v1/options/site-groups' },
    ],
    defaults: { site_id: '', group_id: '' },
    bulkReplace: {
      endpoint: '/api/v1/nav/site-group-maps/bulk-replace',
      ownerField: { key: 'owner_id', label: '网站', type: 'remote-select', optionEndpoint: '/api/v1/options/sites' },
      targetField: { key: 'ids', label: '分组集合', type: 'remote-multi', optionEndpoint: '/api/v1/options/site-groups' },
    },
  },
  {
    key: 'featured-sites',
    title: '精选站点',
    section: 'nav',
    listEndpoint: '/api/v1/nav/featured-sites',
    detailEndpoint: '/api/v1/nav/featured-sites',
    columns: [{ key: 'id', label: 'ID' }, { key: 'site_name', label: '网站' }, { key: 'weight', label: '权重' }],
    fields: [
      { key: 'site_id', label: '网站', type: 'remote-select', optionEndpoint: '/api/v1/options/sites' },
      { key: 'weight', label: '权重', type: 'number' },
    ],
    defaults: { site_id: '', weight: 0 },
  },
  {
    key: 'games',
    title: '游戏',
    section: 'game',
    listEndpoint: '/api/v1/game/games',
    detailEndpoint: '/api/v1/game/games',
    columns: [{ key: 'id', label: 'ID' }, { key: 'name', label: '名称' }, { key: 'release_date', label: '发行日' }],
    fields: [
      { key: 'name', label: '中文名', type: 'text' },
      { key: 'name_en', label: '英文名', type: 'text' },
      { key: 'info', label: '中文简介', type: 'textarea' },
      { key: 'info_en', label: '英文简介', type: 'textarea' },
      { key: 'resources', label: '资源', type: 'kv-array' },
      { key: 'groups', label: '社群', type: 'kv-array' },
      { key: 'release_date', label: '发行日', type: 'text' },
      { key: 'developers', label: '开发者', type: 'string-array' },
      { key: 'publishers', label: '发行商', type: 'string-array' },
      { key: 'appid', label: 'Steam AppID', type: 'number' },
      { key: 'header', label: '封面', type: 'text' },
      { key: 'links', label: '第三方链接', type: 'kv-array' },
      { key: 'weight', label: '权重', type: 'number' },
      { key: 'primary_tag', label: '主标签', type: 'remote-select', optionEndpoint: '/api/v1/options/tags' },
      { key: 'secondary_tag', label: '副标签', type: 'remote-select', optionEndpoint: '/api/v1/options/tags' },
    ],
    defaults: { name: '', name_en: '', info: '', info_en: '', resources: [{ key: '', value: '' }], groups: kvDefaults(groupKeys), release_date: '', developers: [''], publishers: [''], appid: 0, header: '', links: kvDefaults(linkKeys), weight: 0, primary_tag: '', secondary_tag: '' },
  },
  {
    key: 'comments',
    title: '游戏评论',
    section: 'game',
    listEndpoint: '/api/v1/game/comments',
    detailEndpoint: '/api/v1/game/comments',
    columns: [{ key: 'id', label: 'ID' }, { key: 'game_id', label: '游戏ID' }, { key: 'score', label: '评分' }],
    fields: [
      { key: 'game_id', label: '游戏', type: 'remote-select', optionEndpoint: '/api/v1/options/games' },
      { key: 'region', label: '地区', type: 'text' },
      { key: 'name', label: '昵称', type: 'text' },
      { key: 'ip', label: 'IP', type: 'text' },
      { key: 'score', label: '评分', type: 'number' },
      { key: 'content', label: '内容', type: 'textarea' },
    ],
    defaults: { game_id: '', region: '', name: '', ip: '', score: 0, content: '' },
  },
  {
    key: 'creators',
    title: '相关作者',
    section: 'game',
    listEndpoint: '/api/v1/game/creators',
    detailEndpoint: '/api/v1/game/creators',
    columns: [{ key: 'id', label: 'ID' }, { key: 'name', label: '名称' }, { key: 'type', label: '类型' }],
    fields: [
      { key: 'name', label: '中文名', type: 'text' },
      { key: 'name_en', label: '英文名', type: 'text' },
      { key: 'info', label: '中文简介', type: 'textarea' },
      { key: 'info_en', label: '英文简介', type: 'textarea' },
      { key: 'main_url', label: '主链接', type: 'text' },
      { key: 'cover', label: '封面', type: 'text' },
      { key: 'type', label: '类型', type: 'number' },
      { key: 'links', label: '链接', type: 'kv-array' },
      { key: 'contact', label: '联系方式', type: 'kv-array' },
    ],
    defaults: { name: '', name_en: '', info: '', info_en: '', main_url: '', cover: '', type: 1, links: [{ key: '', value: '' }], contact: [{ key: '', value: '' }] },
  },
  {
    key: 'prizes',
    title: '抽奖活动',
    section: 'game',
    listEndpoint: '/api/v1/game/prizes',
    detailEndpoint: '/api/v1/game/prizes',
    columns: [{ key: 'id', label: 'ID' }, { key: 'title', label: '标题' }, { key: 'status', label: '启用' }],
    fields: [
      { key: 'title', label: '标题', type: 'text' },
      { key: 'desc', label: '描述', type: 'textarea' },
      { key: 'key', label: '参与口令', type: 'text' },
      { key: 'start_time', label: '开始时间', type: 'datetime' },
      { key: 'end_time', label: '结束时间', type: 'datetime' },
      { key: 'status', label: '启用', type: 'bool' },
      { key: 'prize.title', label: '奖品标题', type: 'text' },
      { key: 'prize.platform', label: '平台', type: 'text' },
      { key: 'prize.keys', label: '奖品 Key 列表', type: 'string-array' },
    ],
    defaults: { title: '', desc: '', key: '', start_time: '', end_time: '', status: true, prize: { title: '', platform: '', keys: [''] } },
  },
  {
    key: 'tags',
    title: '标签',
    section: 'game',
    listEndpoint: '/api/v1/game/tags',
    detailEndpoint: '/api/v1/game/tags',
    columns: [{ key: 'id', label: 'ID' }, { key: 'name', label: '名称' }, { key: 'prefix', label: '父标签' }],
    fields: [
      { key: 'id', label: 'ID', type: 'number' },
      { key: 'name', label: '中文名', type: 'text' },
      { key: 'name_en', label: '英文名', type: 'text' },
      { key: 'info', label: '中文简介', type: 'textarea' },
      { key: 'info_en', label: '英文简介', type: 'textarea' },
      { key: 'prefix', label: '父标签', type: 'number' },
    ],
    defaults: { id: 0, name: '', name_en: '', info: '', info_en: '', prefix: -1 },
  },
  {
    key: 'tag-maps',
    title: '游戏标签映射',
    section: 'game',
    listEndpoint: '/api/v1/game/tag-maps',
    detailEndpoint: '/api/v1/game/tag-maps',
    columns: [{ key: 'id', label: 'ID' }, { key: 'game_name', label: '游戏' }, { key: 'tag_name', label: '标签' }],
    fields: [
      { key: 'game_id', label: '游戏', type: 'remote-select', optionEndpoint: '/api/v1/options/games' },
      { key: 'tag_id', label: '标签', type: 'remote-select', optionEndpoint: '/api/v1/options/tags' },
    ],
    defaults: { game_id: '', tag_id: '' },
    bulkReplace: {
      endpoint: '/api/v1/game/tag-maps/bulk-replace',
      ownerField: { key: 'owner_id', label: '游戏', type: 'remote-select', optionEndpoint: '/api/v1/options/games' },
      targetField: { key: 'ids', label: '标签集合', type: 'remote-multi', optionEndpoint: '/api/v1/options/tags' },
    },
  },
]

export function findResource(section: string, key: string) {
  return resources.find((item) => item.section === section && item.key === key)
}
