services:
  gofurry-nav-web:
    container_name: gofurry-nav-web
    image: gofurry-nav-web:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NUXT_PUBLIC_SITE_URL: ${NUXT_PUBLIC_SITE_URL:-https://go-furry.com}
        NUXT_PUBLIC_NAV_API_BASE: ${NUXT_PUBLIC_NAV_API_BASE:-https://nav.go-furry.com/api/v1}
        NUXT_PUBLIC_NAV_V2_API_BASE: ${NUXT_PUBLIC_NAV_V2_API_BASE:-https://nav.go-furry.com/api/v2}
        NUXT_PUBLIC_GAME_API_BASE: ${NUXT_PUBLIC_GAME_API_BASE:-https://game.go-furry.com/api/v1}
        NUXT_PUBLIC_SITE_LOGO_PREFIX_URL: ${NUXT_PUBLIC_SITE_LOGO_PREFIX_URL:-https://qcdn.go-furry.com/nav/static/SiteLogos/}
        NUXT_PUBLIC_SITE_DEFAULT_LOGO: ${NUXT_PUBLIC_SITE_DEFAULT_LOGO:-https://qcdn.go-furry.com/nav/static/SiteLogos/defaultLogo.svg}
        NUXT_PUBLIC_GAME_SITE_LOGO_PREFIX_URL: ${NUXT_PUBLIC_GAME_SITE_LOGO_PREFIX_URL:-https://qcdn.go-furry.com/game/icons/}
        NUXT_PUBLIC_GAME_PREFIX_URL: ${NUXT_PUBLIC_GAME_PREFIX_URL:-https://qcdn.go-furry.com/game/}
        NUXT_PUBLIC_STEAM_APP_PREFIX_URL: ${NUXT_PUBLIC_STEAM_APP_PREFIX_URL:-https://store.steampowered.com/app/}
        NUXT_PUBLIC_STEAM_COVER_PREFIX_URL: ${NUXT_PUBLIC_STEAM_COVER_PREFIX_URL:-https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/}
        NAV_API_INTERNAL_BASE: ${NAV_API_INTERNAL_BASE:-http://10.6.0.11:9999/api/v1}
        NAV_V2_API_INTERNAL_BASE: ${NAV_V2_API_INTERNAL_BASE:-http://10.6.0.11:9999/api/v2}
        GAME_API_INTERNAL_BASE: ${GAME_API_INTERNAL_BASE:-http://10.6.0.11:9998/api/v1}
        RAG_API_INTERNAL_BASE: ${RAG_API_INTERNAL_BASE:-http://10.6.0.11:9997}

    environment:
      HOST: 0.0.0.0
      PORT: 3000
      NODE_ENV: production
      NUXT_PUBLIC_SITE_URL: ${NUXT_PUBLIC_SITE_URL:-https://go-furry.com}
      NUXT_PUBLIC_NAV_API_BASE: ${NUXT_PUBLIC_NAV_API_BASE:-https://nav.go-furry.com/api/v1}
      NUXT_PUBLIC_NAV_V2_API_BASE: ${NUXT_PUBLIC_NAV_V2_API_BASE:-https://nav.go-furry.com/api/v2}
      NUXT_PUBLIC_GAME_API_BASE: ${NUXT_PUBLIC_GAME_API_BASE:-https://game.go-furry.com/api/v1}
      NUXT_PUBLIC_SITE_LOGO_PREFIX_URL: ${NUXT_PUBLIC_SITE_LOGO_PREFIX_URL:-https://qcdn.go-furry.com/nav/static/SiteLogos/}
      NUXT_PUBLIC_SITE_DEFAULT_LOGO: ${NUXT_PUBLIC_SITE_DEFAULT_LOGO:-https://qcdn.go-furry.com/nav/static/SiteLogos/defaultLogo.svg}
      NUXT_PUBLIC_GAME_SITE_LOGO_PREFIX_URL: ${NUXT_PUBLIC_GAME_SITE_LOGO_PREFIX_URL:-https://qcdn.go-furry.com/game/icons/}
      NUXT_PUBLIC_GAME_PREFIX_URL: ${NUXT_PUBLIC_GAME_PREFIX_URL:-https://qcdn.go-furry.com/game/}
      NUXT_PUBLIC_STEAM_APP_PREFIX_URL: ${NUXT_PUBLIC_STEAM_APP_PREFIX_URL:-https://store.steampowered.com/app/}
      NUXT_PUBLIC_STEAM_COVER_PREFIX_URL: ${NUXT_PUBLIC_STEAM_COVER_PREFIX_URL:-https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/}
      NAV_API_INTERNAL_BASE: ${NAV_API_INTERNAL_BASE:-http://10.6.0.11:9999/api/v1}
      NAV_V2_API_INTERNAL_BASE: ${NAV_V2_API_INTERNAL_BASE:-http://10.6.0.11:9999/api/v2}
      GAME_API_INTERNAL_BASE: ${GAME_API_INTERNAL_BASE:-http://10.6.0.11:9998/api/v1}
      RAG_API_INTERNAL_BASE: ${RAG_API_INTERNAL_BASE:-http://10.6.0.11:9997}
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
