-- V3-P0.2 Nav historical target identity and Primary Target foundation.
-- +goose Up

ALTER TABLE public.gfn_site
    ADD COLUMN deleted_at timestamp with time zone;

UPDATE public.gfn_site
SET deleted_at = update_time AT TIME ZONE 'Asia/Shanghai'
WHERE deleted AND deleted_at IS NULL;

ALTER TABLE public.gfn_site
    ADD CONSTRAINT gfn_site_deleted_at_check CHECK (
        (deleted AND deleted_at IS NOT NULL)
        OR (NOT deleted AND deleted_at IS NULL)
    );

CREATE TABLE public.gfn_target_tracking_periods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collector_domain_id bigint,
    site_id bigint NOT NULL,
    target text NOT NULL,
    tracked_from timestamp with time zone NOT NULL,
    tracked_until timestamp with time zone,
    tracking_basis text NOT NULL,
    opened_reason text NOT NULL,
    closed_reason text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT gfn_target_tracking_periods_target_check CHECK (btrim(target) <> ''),
    CONSTRAINT gfn_target_tracking_periods_interval_check
        CHECK (tracked_until IS NULL OR tracked_until > tracked_from),
    CONSTRAINT gfn_target_tracking_periods_basis_check
        CHECK (tracking_basis IN ('explicit', 'legacy_observed')),
    CONSTRAINT gfn_target_tracking_periods_explicit_shape_check CHECK (
        tracking_basis <> 'explicit' OR collector_domain_id IS NOT NULL
    )
);

CREATE UNIQUE INDEX uq_gfn_target_tracking_periods_active_target
    ON public.gfn_target_tracking_periods (site_id, lower(target))
    WHERE tracked_until IS NULL;
CREATE UNIQUE INDEX uq_gfn_target_tracking_periods_active_domain
    ON public.gfn_target_tracking_periods (collector_domain_id)
    WHERE collector_domain_id IS NOT NULL AND tracked_until IS NULL;
CREATE INDEX idx_gfn_target_tracking_periods_identity_time
    ON public.gfn_target_tracking_periods (site_id, lower(target), tracked_from, tracked_until);
CREATE INDEX idx_gfn_target_tracking_periods_time
    ON public.gfn_target_tracking_periods (tracked_from, tracked_until);

-- Retained pre-cutover observations establish historical identity/value only.
-- Future-dated observations must not extend a legacy period across rollout.
WITH migration_clock AS (
    SELECT transaction_timestamp() AS cutover
)
INSERT INTO public.gfn_target_tracking_periods (
    collector_domain_id, site_id, target, tracked_from, tracked_until,
    tracking_basis, opened_reason, closed_reason
)
SELECT NULL,
       site_id,
       target,
       min(observed_at),
       migration_clock.cutover,
       'legacy_observed',
       'historical_observation',
       'p0.2_quality_cutover'
FROM public.gfn_collector_observation
CROSS JOIN migration_clock
WHERE btrim(target) <> ''
  AND observed_at < migration_clock.cutover
GROUP BY site_id, target, migration_clock.cutover;

-- Reconcile pre-existing duplicate current identities deterministically before
-- the active-period uniqueness contract is enabled. Observations contain only
-- site_id + target and therefore cannot distinguish duplicate CollectorDomain
-- rows; the oldest row is the only evidence-backed stable owner.
-- +goose StatementBegin
DO $audit$
DECLARE
    duplicate_count bigint;
BEGIN
    SELECT COALESCE(sum(target_count - 1), 0)
    INTO duplicate_count
    FROM (
        SELECT count(*) AS target_count
        FROM public.gfn_collector_domain d
        JOIN public.gfn_site s ON s.id = d.site_id
        WHERE NOT d.deleted AND NOT s.deleted AND d.site_id IS NOT NULL
        GROUP BY d.site_id, lower(btrim(COALESCE(d.prefix, '') || d.name))
        HAVING count(*) > 1
    ) duplicates;

    IF duplicate_count > 0 THEN
        RAISE NOTICE 'P0.2 Nav identity migration will soft-delete % duplicate CollectorDomain row(s)', duplicate_count;
    END IF;
END;
$audit$;
-- +goose StatementEnd

WITH ranked AS (
    SELECT d.id,
           row_number() OVER (
               PARTITION BY d.site_id, lower(btrim(COALESCE(d.prefix, '') || d.name))
               ORDER BY d.id
           ) AS identity_rank
    FROM public.gfn_collector_domain d
    JOIN public.gfn_site s ON s.id = d.site_id
    WHERE NOT d.deleted AND NOT s.deleted AND d.site_id IS NOT NULL
)
UPDATE public.gfn_collector_domain d
SET deleted = true
FROM ranked
WHERE ranked.id = d.id AND ranked.identity_rank > 1;

INSERT INTO public.gfn_target_tracking_periods (
    collector_domain_id, site_id, target, tracked_from,
    tracking_basis, opened_reason
)
SELECT d.id,
       d.site_id,
       COALESCE(d.prefix, '') || d.name,
       transaction_timestamp(),
       'explicit',
       'p0.2_rollout'
FROM public.gfn_collector_domain d
JOIN public.gfn_site s ON s.id = d.site_id
WHERE NOT d.deleted
  AND NOT s.deleted
  AND d.site_id IS NOT NULL
  AND btrim(COALESCE(d.prefix, '') || d.name) <> '';

CREATE TABLE public.gfn_site_primary_target_periods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id bigint NOT NULL,
    target_tracking_period_id bigint NOT NULL
        REFERENCES public.gfn_target_tracking_periods(id) ON DELETE RESTRICT,
    effective_from timestamp with time zone NOT NULL,
    effective_until timestamp with time zone,
    basis text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT gfn_site_primary_target_periods_interval_check
        CHECK (effective_until IS NULL OR effective_until > effective_from),
    CONSTRAINT gfn_site_primary_target_periods_basis_check
        CHECK (basis IN ('explicit', 'single_target_inferred', 'deterministic_fallback', 'legacy_backfill'))
);

CREATE UNIQUE INDEX uq_gfn_site_primary_target_periods_active
    ON public.gfn_site_primary_target_periods (site_id)
    WHERE effective_until IS NULL;
CREATE INDEX idx_gfn_site_primary_target_periods_time
    ON public.gfn_site_primary_target_periods (site_id, effective_from, effective_until);

-- Primary selection starts at rollout. No current choice is projected into the
-- historical multi-target interval where a truthful Primary is unknowable.
WITH ranked AS (
    SELECT p.id AS target_tracking_period_id,
           p.site_id,
           count(*) OVER (PARTITION BY p.site_id) AS target_count,
           row_number() OVER (
               PARTITION BY p.site_id
               ORDER BY CASE WHEN COALESCE(d.prefix, '') = '' THEN 0 ELSE 1 END,
                        d.id
           ) AS target_rank
    FROM public.gfn_target_tracking_periods p
    JOIN public.gfn_collector_domain d ON d.id = p.collector_domain_id
    WHERE p.tracking_basis = 'explicit' AND p.tracked_until IS NULL
)
INSERT INTO public.gfn_site_primary_target_periods (
    site_id, target_tracking_period_id, effective_from, basis
)
SELECT site_id,
       target_tracking_period_id,
       transaction_timestamp(),
       CASE WHEN target_count = 1
            THEN 'single_target_inferred'
            ELSE 'deterministic_fallback'
       END
FROM ranked
WHERE target_rank = 1;

COMMENT ON COLUMN public.gfn_site.deleted_at IS
    'UTC soft-delete boundary for historical Site facts; legacy local timestamps are interpreted as Asia/Shanghai.';
COMMENT ON TABLE public.gfn_target_tracking_periods IS
    'Immutable Site target eligibility periods; current CollectorDomain is not a historical FK owner.';
COMMENT ON TABLE public.gfn_site_primary_target_periods IS
    'Single source of truth for effective-dated Primary Target selection.';

-- +goose Down

DROP TABLE public.gfn_site_primary_target_periods;
DROP TABLE public.gfn_target_tracking_periods;

ALTER TABLE public.gfn_site
    DROP CONSTRAINT gfn_site_deleted_at_check,
    DROP COLUMN deleted_at;
