// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights.sql

package gamesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGameInsightGames = `-- name: CountGameInsightGames :one
SELECT count(*)::bigint
FROM public.gfg_game
`

func (q *Queries) CountGameInsightGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGameInsightGames)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countGameInsightOverviewChanges = `-- name: CountGameInsightOverviewChanges :one
SELECT count(*)::bigint
FROM public.gfg_change_events event
WHERE event.projection_date >= (now() AT TIME ZONE 'UTC')::date - 6
  AND event.detector_key = ANY($1::text[])
  AND (event.detector_key <> 'game_price_transition'
       OR (event.scope_kind = 'region' AND event.scope_key = 'CN'))
  AND event.detector_key || '/' || event.detector_version::text || '/' || event.event_code
      = ANY($2::text[])
`

type CountGameInsightOverviewChangesParams struct {
	DetectorKeys []string `json:"detector_keys"`
	ContractIds  []string `json:"contract_ids"`
}

func (q *Queries) CountGameInsightOverviewChanges(ctx context.Context, arg CountGameInsightOverviewChangesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGameInsightOverviewChanges, arg.DetectorKeys, arg.ContractIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getGameInsightGame = `-- name: GetGameInsightGame :one
SELECT id, name, name_en
FROM public.gfg_game
WHERE id = $1
`

type GetGameInsightGameRow struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	NameEn string `json:"name_en"`
}

func (q *Queries) GetGameInsightGame(ctx context.Context, gameID int64) (GetGameInsightGameRow, error) {
	row := q.db.QueryRow(ctx, getGameInsightGame, gameID)
	var i GetGameInsightGameRow
	err := row.Scan(&i.ID, &i.Name, &i.NameEn)
	return i, err
}

const getGameInsightLanguageOverview = `-- name: GetGameInsightLanguageOverview :one
WITH horizon AS (
    SELECT max(fact_date)::date AS as_of FROM public.gfg_game_daily
    WHERE finalized_at IS NOT NULL AND tracked_at_end
), cohort AS (
    SELECT fact.game_id, fact.fact_date, fact.tracking_period_id, fact.appid, fact.snapshot_at, fact.tracked_at_end, fact.name, fact.name_en, fact.view_count, fact.game_type, fact.is_free, fact.windows, fact.mac, fact.linux, fact.release_availability, fact.release_precision, fact.release_exact_date, fact.release_year, fact.release_month, fact.release_quarter, fact.release_window_start, fact.release_window_end, fact.release_observed_at, fact.first_available_precision, fact.first_available_exact_date, fact.first_available_year, fact.first_available_month, fact.first_available_quarter, fact.first_available_window_start, fact.first_available_window_end, fact.first_available_source, fact.first_available_inferred, fact.language_codes, fact.unknown_language_names, fact.full_audio_language_codes, fact.languages_observed_at, fact.developers, fact.publishers, fact.primary_tag_id, fact.secondary_tag_id, fact.tag_ids, fact.details_observed_at, fact.materialization_source, fact.projection_version, fact.finalized_at, fact.created_at, fact.updated_at,
           CASE WHEN fact.languages_observed_at IS NULL THEN 'unobserved'
                WHEN fact.languages_observed_at < ((horizon.as_of + 1)::timestamp AT TIME ZONE 'UTC') - interval '259200 seconds' THEN 'stale'
                ELSE 'fresh' END AS evidence
    FROM horizon JOIN public.gfg_game_daily fact ON fact.fact_date = horizon.as_of
      AND fact.finalized_at IS NOT NULL AND fact.tracked_at_end
)
SELECT horizon.as_of, count(cohort.game_id)::bigint AS population,
       count(*) FILTER (WHERE evidence = 'fresh')::bigint AS fresh,
       count(*) FILTER (WHERE evidence = 'stale')::bigint AS stale,
       count(*) FILTER (WHERE evidence = 'unobserved')::bigint AS unobserved,
       count(*) FILTER (WHERE evidence = 'fresh' AND COALESCE(cardinality(unknown_language_names), 0) = 0)::bigint AS fully_normalized_games,
       count(*) FILTER (WHERE evidence = 'fresh' AND COALESCE(cardinality(unknown_language_names), 0) > 0)::bigint AS unmapped_games,
       COALESCE(sum(cardinality(unknown_language_names)) FILTER (WHERE evidence = 'fresh'), 0)::bigint AS unmapped_entries
FROM horizon LEFT JOIN cohort ON true GROUP BY horizon.as_of
`

type GetGameInsightLanguageOverviewRow struct {
	AsOf                 pgtype.Date `json:"as_of"`
	Population           int64       `json:"population"`
	Fresh                int64       `json:"fresh"`
	Stale                int64       `json:"stale"`
	Unobserved           int64       `json:"unobserved"`
	FullyNormalizedGames int64       `json:"fully_normalized_games"`
	UnmappedGames        int64       `json:"unmapped_games"`
	UnmappedEntries      int64       `json:"unmapped_entries"`
}

func (q *Queries) GetGameInsightLanguageOverview(ctx context.Context) (GetGameInsightLanguageOverviewRow, error) {
	row := q.db.QueryRow(ctx, getGameInsightLanguageOverview)
	var i GetGameInsightLanguageOverviewRow
	err := row.Scan(
		&i.AsOf,
		&i.Population,
		&i.Fresh,
		&i.Stale,
		&i.Unobserved,
		&i.FullyNormalizedGames,
		&i.UnmappedGames,
		&i.UnmappedEntries,
	)
	return i, err
}

const getGameInsightLatestPlayerRankingMeta = `-- name: GetGameInsightLatestPlayerRankingMeta :one
WITH latest_slot AS (
    SELECT max(scheduled_for) AS scheduled_for
    FROM public.gfg_collection_jobs
    WHERE job_key = 'game.players' AND trigger = 'scheduled' AND scope_type = 'all'
      AND status IN ('success', 'partial', 'failed', 'skipped', 'missed', 'canceled')
), snapshot AS (
    SELECT id, scheduled_for
    FROM public.gfg_collection_jobs
    WHERE job_key = 'game.players' AND trigger = 'scheduled' AND scope_type = 'all'
      AND status IN ('success', 'partial')
    ORDER BY scheduled_for DESC, id DESC LIMIT 1
), observations AS (
    SELECT DISTINCT ON (raw.game_id) raw.game_id, raw.collected_at
    FROM snapshot
    JOIN public.gfg_collection_runs run ON run.job_id = snapshot.id
    JOIN public.gfg_game_player_counts raw ON raw.run_id = run.id AND raw.status = 'success'
    ORDER BY raw.game_id, raw.collected_at DESC, raw.id DESC
)
SELECT snapshot.scheduled_for::timestamptz AS snapshot_scheduled_for,
       latest_slot.scheduled_for::timestamptz AS latest_slot_scheduled_for,
       min(observations.collected_at)::timestamptz AS observed_from,
       max(observations.collected_at)::timestamptz AS observed_through,
       (SELECT count(*)::bigint FROM public.gfg_game_tracking_periods period
        WHERE snapshot.scheduled_for IS NOT NULL AND period.tracking_basis = 'explicit'
          AND period.tracked_from <= snapshot.scheduled_for
          AND (period.tracked_until IS NULL OR snapshot.scheduled_for < period.tracked_until)) AS population,
       count(observations.game_id)::bigint AS ranked
FROM latest_slot
LEFT JOIN snapshot ON true
LEFT JOIN observations ON true
GROUP BY snapshot.scheduled_for, latest_slot.scheduled_for
`

type GetGameInsightLatestPlayerRankingMetaRow struct {
	SnapshotScheduledFor   pgtype.Timestamptz `json:"snapshot_scheduled_for"`
	LatestSlotScheduledFor pgtype.Timestamptz `json:"latest_slot_scheduled_for"`
	ObservedFrom           pgtype.Timestamptz `json:"observed_from"`
	ObservedThrough        pgtype.Timestamptz `json:"observed_through"`
	Population             int64              `json:"population"`
	Ranked                 int64              `json:"ranked"`
}

func (q *Queries) GetGameInsightLatestPlayerRankingMeta(ctx context.Context) (GetGameInsightLatestPlayerRankingMetaRow, error) {
	row := q.db.QueryRow(ctx, getGameInsightLatestPlayerRankingMeta)
	var i GetGameInsightLatestPlayerRankingMetaRow
	err := row.Scan(
		&i.SnapshotScheduledFor,
		&i.LatestSlotScheduledFor,
		&i.ObservedFrom,
		&i.ObservedThrough,
		&i.Population,
		&i.Ranked,
	)
	return i, err
}

const getGameInsightMetricSliceAvailability = `-- name: GetGameInsightMetricSliceAvailability :one
WITH available AS (
    SELECT min(fact_date)::date AS available_from,
           max(fact_date)::date AS available_through
    FROM public.gfg_metric_daily
    WHERE metric_key = $3
      AND metric_version = $4
      AND dimension_key = $1
      AND dimension_value = $2
)
SELECT available.available_from,
       available.available_through,
       COALESCE(tag.name, '')::text AS label,
       COALESCE(tag.name_en, '')::text AS label_en
FROM available
LEFT JOIN public.gfg_tag tag
  ON $1::text IN ('primary_tag_id', 'tag_id')
 AND tag.id::text = $2::text
`

type GetGameInsightMetricSliceAvailabilityParams struct {
	DimensionKey   string `json:"dimension_key"`
	DimensionValue string `json:"dimension_value"`
	MetricKey      string `json:"metric_key"`
	MetricVersion  int32  `json:"metric_version"`
}

type GetGameInsightMetricSliceAvailabilityRow struct {
	AvailableFrom    pgtype.Date `json:"available_from"`
	AvailableThrough pgtype.Date `json:"available_through"`
	Label            string      `json:"label"`
	LabelEn          string      `json:"label_en"`
}

func (q *Queries) GetGameInsightMetricSliceAvailability(ctx context.Context, arg GetGameInsightMetricSliceAvailabilityParams) (GetGameInsightMetricSliceAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, getGameInsightMetricSliceAvailability,
		arg.DimensionKey,
		arg.DimensionValue,
		arg.MetricKey,
		arg.MetricVersion,
	)
	var i GetGameInsightMetricSliceAvailabilityRow
	err := row.Scan(
		&i.AvailableFrom,
		&i.AvailableThrough,
		&i.Label,
		&i.LabelEn,
	)
	return i, err
}

const getGameInsightMetricSummary = `-- name: GetGameInsightMetricSummary :one
WITH latest AS (
    SELECT fact_date, population_count, eligible_count, not_applicable_count,
           positive_count, negative_count, stale_count, not_probed_count,
           probe_failed_count, unknown_count
    FROM public.gfg_metric_daily
    WHERE metric_key = $1
      AND metric_version = $2
      AND dimension_key = 'global'
      AND dimension_value = 'all'
    ORDER BY fact_date DESC
    LIMIT 1
), available AS (
    SELECT min(fact_date)::date AS available_from
    FROM public.gfg_metric_daily
    WHERE metric_key = $1
      AND metric_version = $2
      AND dimension_key = 'global'
      AND dimension_value = 'all'
)
SELECT latest.fact_date,
       latest.population_count,
       latest.eligible_count,
       latest.not_applicable_count,
       latest.positive_count,
       latest.negative_count,
       latest.stale_count,
       latest.not_probed_count,
       latest.probe_failed_count,
       latest.unknown_count,
       previous.positive_count AS previous_positive_count,
       previous.negative_count AS previous_negative_count,
       available.available_from
FROM latest
CROSS JOIN available
LEFT JOIN public.gfg_metric_daily previous
  ON previous.metric_key = $1
 AND previous.metric_version = $2
 AND previous.dimension_key = 'global'
 AND previous.dimension_value = 'all'
 AND previous.fact_date = latest.fact_date - 30
`

type GetGameInsightMetricSummaryParams struct {
	MetricKey     string `json:"metric_key"`
	MetricVersion int32  `json:"metric_version"`
}

type GetGameInsightMetricSummaryRow struct {
	FactDate              pgtype.Date `json:"fact_date"`
	PopulationCount       int64       `json:"population_count"`
	EligibleCount         int64       `json:"eligible_count"`
	NotApplicableCount    int64       `json:"not_applicable_count"`
	PositiveCount         int64       `json:"positive_count"`
	NegativeCount         int64       `json:"negative_count"`
	StaleCount            int64       `json:"stale_count"`
	NotProbedCount        int64       `json:"not_probed_count"`
	ProbeFailedCount      int64       `json:"probe_failed_count"`
	UnknownCount          int64       `json:"unknown_count"`
	PreviousPositiveCount *int64      `json:"previous_positive_count"`
	PreviousNegativeCount *int64      `json:"previous_negative_count"`
	AvailableFrom         pgtype.Date `json:"available_from"`
}

func (q *Queries) GetGameInsightMetricSummary(ctx context.Context, arg GetGameInsightMetricSummaryParams) (GetGameInsightMetricSummaryRow, error) {
	row := q.db.QueryRow(ctx, getGameInsightMetricSummary, arg.MetricKey, arg.MetricVersion)
	var i GetGameInsightMetricSummaryRow
	err := row.Scan(
		&i.FactDate,
		&i.PopulationCount,
		&i.EligibleCount,
		&i.NotApplicableCount,
		&i.PositiveCount,
		&i.NegativeCount,
		&i.StaleCount,
		&i.NotProbedCount,
		&i.ProbeFailedCount,
		&i.UnknownCount,
		&i.PreviousPositiveCount,
		&i.PreviousNegativeCount,
		&i.AvailableFrom,
	)
	return i, err
}

const getGameInsightObservedLow = `-- name: GetGameInsightObservedLow :one
WITH RECURSIVE current_price AS (
    SELECT price.tracking_period_id, price.game_id, price.appid, price.region, price.fact_date, price.price_state, price.currency, price.initial_amount, price.final_amount, price.discount_percent, price.observed_at, price.materialization_source, price.projection_version, price.finalized_at, price.created_at, price.updated_at
    FROM public.gfg_game_price_daily price
    WHERE price.tracking_period_id = $1
      AND price.region = $2
      AND price.fact_date = $3::date
      AND price.finalized_at IS NOT NULL
      AND price.price_state = 'priced'
      AND price.currency IS NOT NULL
), identity AS (
    SELECT current_price.tracking_period_id, current_price.game_id, current_price.appid, current_price.region, current_price.fact_date, current_price.price_state, current_price.currency, current_price.initial_amount, current_price.final_amount, current_price.discount_percent, current_price.observed_at, current_price.materialization_source, current_price.projection_version, current_price.finalized_at, current_price.created_at, current_price.updated_at FROM current_price
    UNION ALL
    SELECT previous.tracking_period_id, previous.game_id, previous.appid, previous.region, previous.fact_date, previous.price_state, previous.currency, previous.initial_amount, previous.final_amount, previous.discount_percent, previous.observed_at, previous.materialization_source, previous.projection_version, previous.finalized_at, previous.created_at, previous.updated_at
    FROM identity next
    JOIN public.gfg_game_price_daily previous
      ON previous.tracking_period_id = next.tracking_period_id
     AND previous.region = next.region
     AND previous.fact_date = next.fact_date - 1
     AND previous.finalized_at IS NOT NULL
     AND previous.price_state = 'priced'
     AND previous.currency = next.currency
), low_amount AS (
    SELECT min(final_amount)::bigint AS amount, min(fact_date)::date AS observed_since
    FROM identity
), first_low AS (
    SELECT identity.tracking_period_id, identity.game_id, identity.appid, identity.region, identity.fact_date, identity.price_state, identity.currency, identity.initial_amount, identity.final_amount, identity.discount_percent, identity.observed_at, identity.materialization_source, identity.projection_version, identity.finalized_at, identity.created_at, identity.updated_at FROM identity CROSS JOIN low_amount
    WHERE identity.final_amount = low_amount.amount
    ORDER BY identity.fact_date ASC
    LIMIT 1
)
SELECT low_amount.amount, first_low.currency, first_low.fact_date AS first_seen,
       low_amount.observed_since, first_low.initial_amount, first_low.discount_percent
FROM low_amount
JOIN first_low ON true
`

type GetGameInsightObservedLowParams struct {
	TrackingPeriodID int64       `json:"tracking_period_id"`
	Region           string      `json:"region"`
	FactDate         pgtype.Date `json:"fact_date"`
}

type GetGameInsightObservedLowRow struct {
	Amount          int64       `json:"amount"`
	Currency        *string     `json:"currency"`
	FirstSeen       pgtype.Date `json:"first_seen"`
	ObservedSince   pgtype.Date `json:"observed_since"`
	InitialAmount   *int64      `json:"initial_amount"`
	DiscountPercent *int32      `json:"discount_percent"`
}

func (q *Queries) GetGameInsightObservedLow(ctx context.Context, arg GetGameInsightObservedLowParams) (GetGameInsightObservedLowRow, error) {
	row := q.db.QueryRow(ctx, getGameInsightObservedLow, arg.TrackingPeriodID, arg.Region, arg.FactDate)
	var i GetGameInsightObservedLowRow
	err := row.Scan(
		&i.Amount,
		&i.Currency,
		&i.FirstSeen,
		&i.ObservedSince,
		&i.InitialAmount,
		&i.DiscountPercent,
	)
	return i, err
}

const getGameInsightPlayer30dMeta = `-- name: GetGameInsightPlayer30dMeta :one
WITH horizon AS (
    SELECT processed_through FROM public.gfg_fact_rollup_checkpoints WHERE pipeline_key = 'game.player_facts'
), population AS (
    SELECT count(*)::bigint AS count
    FROM horizon
    JOIN public.gfg_game_tracking_periods period ON period.tracking_basis = 'explicit'
     AND period.tracked_from < (horizon.processed_through + 1)::timestamp AT TIME ZONE 'UTC'
     AND (period.tracked_until IS NULL OR period.tracked_until >= (horizon.processed_through + 1)::timestamp AT TIME ZONE 'UTC')
), ranked AS (
    SELECT count(DISTINCT daily.tracking_period_id)::bigint AS count
    FROM horizon
    JOIN public.gfg_game_tracking_periods period ON period.tracking_basis = 'explicit'
     AND period.tracked_from < (horizon.processed_through + 1)::timestamp AT TIME ZONE 'UTC'
     AND (period.tracked_until IS NULL OR period.tracked_until >= (horizon.processed_through + 1)::timestamp AT TIME ZONE 'UTC')
    JOIN public.gfg_game_player_daily daily ON daily.tracking_period_id = period.id
     AND daily.fact_date BETWEEN GREATEST(horizon.processed_through - 29, (period.tracked_from AT TIME ZONE 'UTC')::date) AND horizon.processed_through
     AND daily.finalized_at IS NOT NULL AND daily.successful_samples > 0
)
SELECT horizon.processed_through AS window_through,
       (horizon.processed_through - 29)::date AS window_from,
       population.count AS population, ranked.count AS ranked
FROM horizon CROSS JOIN population CROSS JOIN ranked
`

type GetGameInsightPlayer30dMetaRow struct {
	WindowThrough pgtype.Date `json:"window_through"`
	WindowFrom    pgtype.Date `json:"window_from"`
	Population    int64       `json:"population"`
	Ranked        int64       `json:"ranked"`
}

func (q *Queries) GetGameInsightPlayer30dMeta(ctx context.Context) (GetGameInsightPlayer30dMetaRow, error) {
	row := q.db.QueryRow(ctx, getGameInsightPlayer30dMeta)
	var i GetGameInsightPlayer30dMetaRow
	err := row.Scan(
		&i.WindowThrough,
		&i.WindowFrom,
		&i.Population,
		&i.Ranked,
	)
	return i, err
}

const getGameInsightPlayerSummary = `-- name: GetGameInsightPlayerSummary :one
WITH player_horizon AS (
    SELECT processed_through
    FROM public.gfg_fact_rollup_checkpoints
    WHERE pipeline_key = 'game.player_facts'
), quality AS (
    SELECT COALESCE(max(daily.max_players), 0)::bigint AS peak_30d,
           COALESCE(sum(daily.avg_players * daily.successful_samples)
             / NULLIF(sum(daily.successful_samples), 0), 0)::double precision AS average_30d,
           GREATEST(horizon.processed_through - 29, (period.tracked_from AT TIME ZONE 'UTC')::date)::date AS eligible_from,
           count(*) FILTER (WHERE daily.successful_samples > 0)::bigint AS observed_days,
           COALESCE(sum(daily.successful_samples), 0)::bigint AS successful_samples,
           CASE
             WHEN count(daily.*) = horizon.processed_through
                    - GREATEST(horizon.processed_through - 29, (period.tracked_from AT TIME ZONE 'UTC')::date) + 1
              AND bool_and(daily.expected_samples IS NOT NULL)
              AND sum(daily.expected_samples) > 0
             THEN sum(daily.successful_samples)::double precision / sum(daily.expected_samples)
             ELSE 0::double precision
           END::double precision AS sample_coverage,
           (count(daily.*) = horizon.processed_through
              - GREATEST(horizon.processed_through - 29, (period.tracked_from AT TIME ZONE 'UTC')::date) + 1
            AND bool_and(daily.expected_samples IS NOT NULL)
            AND sum(daily.expected_samples) > 0) AS has_sample_coverage,
           horizon.processed_through AS fact_through
    FROM player_horizon horizon
    JOIN public.gfg_game_tracking_periods period ON period.id = $1
    LEFT JOIN public.gfg_game_player_daily daily
      ON daily.tracking_period_id = period.id
     AND daily.fact_date BETWEEN GREATEST(horizon.processed_through - 29, (period.tracked_from AT TIME ZONE 'UTC')::date)
                             AND horizon.processed_through
     AND daily.finalized_at IS NOT NULL
    GROUP BY horizon.processed_through, period.tracked_from
)
SELECT EXISTS (
           SELECT 1
           FROM public.gfg_game_player_counts raw
	       JOIN public.gfg_game_tracking_periods period
	         ON period.id = $1
           WHERE raw.game_id = $2
             AND raw.appid = $3
             AND raw.status = 'success'
	         AND raw.collected_at >= period.tracked_from
	         AND (period.tracked_until IS NULL OR raw.collected_at < period.tracked_until)
       ) AS has_current,
       COALESCE((
           SELECT raw.count
           FROM public.gfg_game_player_counts raw
	       JOIN public.gfg_game_tracking_periods period
	         ON period.id = $1
           WHERE raw.game_id = $2
             AND raw.appid = $3
             AND raw.status = 'success'
	         AND raw.collected_at >= period.tracked_from
	         AND (period.tracked_until IS NULL OR raw.collected_at < period.tracked_until)
           ORDER BY raw.collected_at DESC, raw.id DESC
           LIMIT 1
       ), 0)::bigint AS current_players,
       (
           SELECT raw.collected_at
           FROM public.gfg_game_player_counts raw
	       JOIN public.gfg_game_tracking_periods period
	         ON period.id = $1
           WHERE raw.game_id = $2
             AND raw.appid = $3
             AND raw.status = 'success'
	         AND raw.collected_at >= period.tracked_from
	         AND (period.tracked_until IS NULL OR raw.collected_at < period.tracked_until)
           ORDER BY raw.collected_at DESC, raw.id DESC
           LIMIT 1
       ) AS current_as_of,
       quality.peak_30d,
       quality.average_30d,
       quality.fact_through,
       quality.eligible_from,
       quality.observed_days,
       quality.successful_samples,
       quality.sample_coverage,
       quality.has_sample_coverage
FROM quality
`

type GetGameInsightPlayerSummaryParams struct {
	TrackingPeriodID int64 `json:"tracking_period_id"`
	GameID           int64 `json:"game_id"`
	Appid            int64 `json:"appid"`
}

type GetGameInsightPlayerSummaryRow struct {
	HasCurrent        bool               `json:"has_current"`
	CurrentPlayers    int64              `json:"current_players"`
	CurrentAsOf       pgtype.Timestamptz `json:"current_as_of"`
	Peak30d           int64              `json:"peak_30d"`
	Average30d        float64            `json:"average_30d"`
	FactThrough       pgtype.Date        `json:"fact_through"`
	EligibleFrom      pgtype.Date        `json:"eligible_from"`
	ObservedDays      int64              `json:"observed_days"`
	SuccessfulSamples int64              `json:"successful_samples"`
	SampleCoverage    float64            `json:"sample_coverage"`
	HasSampleCoverage *bool              `json:"has_sample_coverage"`
}

func (q *Queries) GetGameInsightPlayerSummary(ctx context.Context, arg GetGameInsightPlayerSummaryParams) (GetGameInsightPlayerSummaryRow, error) {
	row := q.db.QueryRow(ctx, getGameInsightPlayerSummary, arg.TrackingPeriodID, arg.GameID, arg.Appid)
	var i GetGameInsightPlayerSummaryRow
	err := row.Scan(
		&i.HasCurrent,
		&i.CurrentPlayers,
		&i.CurrentAsOf,
		&i.Peak30d,
		&i.Average30d,
		&i.FactThrough,
		&i.EligibleFrom,
		&i.ObservedDays,
		&i.SuccessfulSamples,
		&i.SampleCoverage,
		&i.HasSampleCoverage,
	)
	return i, err
}

const getGameInsightPriceOverview = `-- name: GetGameInsightPriceOverview :one
WITH horizon AS (
    SELECT max(fact_date)::date AS as_of FROM public.gfg_game_daily
    WHERE finalized_at IS NOT NULL AND tracked_at_end
), cohort AS (
    SELECT fact.game_id, price.price_state, price.discount_percent
    FROM horizon JOIN public.gfg_game_daily fact ON fact.fact_date = horizon.as_of
      AND fact.finalized_at IS NOT NULL AND fact.tracked_at_end
    LEFT JOIN public.gfg_game_price_daily price
      ON price.tracking_period_id = fact.tracking_period_id AND price.fact_date = horizon.as_of
     AND price.region = $1 AND price.finalized_at IS NOT NULL
)
SELECT horizon.as_of, count(cohort.game_id)::bigint AS population,
       count(*) FILTER (WHERE price_state = 'priced')::bigint AS priced,
       count(*) FILTER (WHERE price_state = 'free')::bigint AS free,
       count(*) FILTER (WHERE price_state = 'unpriced')::bigint AS unpriced,
       count(*) FILTER (WHERE price_state = 'unknown')::bigint AS unknown,
       count(cohort.game_id) FILTER (WHERE price_state IS NULL)::bigint AS unavailable,
       count(*) FILTER (WHERE price_state = 'priced' AND discount_percent > 0)::bigint AS discounted
FROM horizon LEFT JOIN cohort ON true
GROUP BY horizon.as_of
`

type GetGameInsightPriceOverviewRow struct {
	AsOf        pgtype.Date `json:"as_of"`
	Population  int64       `json:"population"`
	Priced      int64       `json:"priced"`
	Free        int64       `json:"free"`
	Unpriced    int64       `json:"unpriced"`
	Unknown     int64       `json:"unknown"`
	Unavailable int64       `json:"unavailable"`
	Discounted  int64       `json:"discounted"`
}

func (q *Queries) GetGameInsightPriceOverview(ctx context.Context, region string) (GetGameInsightPriceOverviewRow, error) {
	row := q.db.QueryRow(ctx, getGameInsightPriceOverview, region)
	var i GetGameInsightPriceOverviewRow
	err := row.Scan(
		&i.AsOf,
		&i.Population,
		&i.Priced,
		&i.Free,
		&i.Unpriced,
		&i.Unknown,
		&i.Unavailable,
		&i.Discounted,
	)
	return i, err
}

const getGameInsightState = `-- name: GetGameInsightState :one
SELECT game_id, fact_date, tracking_period_id, appid, tracked_at_end,
       is_free, windows, mac, linux, release_availability
FROM public.gfg_game_daily
WHERE game_id = $1
  AND finalized_at IS NOT NULL
ORDER BY fact_date DESC
LIMIT 1
`

type GetGameInsightStateRow struct {
	GameID              int64       `json:"game_id"`
	FactDate            pgtype.Date `json:"fact_date"`
	TrackingPeriodID    int64       `json:"tracking_period_id"`
	Appid               int64       `json:"appid"`
	TrackedAtEnd        bool        `json:"tracked_at_end"`
	IsFree              *bool       `json:"is_free"`
	Windows             *bool       `json:"windows"`
	Mac                 *bool       `json:"mac"`
	Linux               *bool       `json:"linux"`
	ReleaseAvailability *string     `json:"release_availability"`
}

func (q *Queries) GetGameInsightState(ctx context.Context, gameID int64) (GetGameInsightStateRow, error) {
	row := q.db.QueryRow(ctx, getGameInsightState, gameID)
	var i GetGameInsightStateRow
	err := row.Scan(
		&i.GameID,
		&i.FactDate,
		&i.TrackingPeriodID,
		&i.Appid,
		&i.TrackedAtEnd,
		&i.IsFree,
		&i.Windows,
		&i.Mac,
		&i.Linux,
		&i.ReleaseAvailability,
	)
	return i, err
}

const listGameInsightCurrentDiscounts = `-- name: ListGameInsightCurrentDiscounts :many
WITH horizon AS (
    SELECT max(fact_date)::date AS as_of FROM public.gfg_game_daily
    WHERE finalized_at IS NOT NULL AND tracked_at_end
)
SELECT horizon.as_of, fact.game_id, fact.tracking_period_id,
       COALESCE(NULLIF(fact.name, ''), fact.name_en, '')::text AS game_name,
       price.currency, price.initial_amount, price.final_amount, price.discount_percent
FROM horizon
JOIN public.gfg_game_daily fact ON fact.fact_date = horizon.as_of
 AND fact.finalized_at IS NOT NULL AND fact.tracked_at_end
JOIN public.gfg_game_price_daily price ON price.tracking_period_id = fact.tracking_period_id
 AND price.fact_date = horizon.as_of AND price.region = $1
 AND price.finalized_at IS NOT NULL AND price.price_state = 'priced' AND price.discount_percent > 0
ORDER BY price.discount_percent DESC, fact.game_id ASC
LIMIT $2
`

type ListGameInsightCurrentDiscountsParams struct {
	Region     string `json:"region"`
	LimitCount int32  `json:"limit_count"`
}

type ListGameInsightCurrentDiscountsRow struct {
	AsOf             pgtype.Date `json:"as_of"`
	GameID           int64       `json:"game_id"`
	TrackingPeriodID int64       `json:"tracking_period_id"`
	GameName         string      `json:"game_name"`
	Currency         *string     `json:"currency"`
	InitialAmount    *int64      `json:"initial_amount"`
	FinalAmount      *int64      `json:"final_amount"`
	DiscountPercent  *int32      `json:"discount_percent"`
}

func (q *Queries) ListGameInsightCurrentDiscounts(ctx context.Context, arg ListGameInsightCurrentDiscountsParams) ([]ListGameInsightCurrentDiscountsRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightCurrentDiscounts, arg.Region, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightCurrentDiscountsRow{}
	for rows.Next() {
		var i ListGameInsightCurrentDiscountsRow
		if err := rows.Scan(
			&i.AsOf,
			&i.GameID,
			&i.TrackingPeriodID,
			&i.GameName,
			&i.Currency,
			&i.InitialAmount,
			&i.FinalAmount,
			&i.DiscountPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightExplorerChanges = `-- name: ListGameInsightExplorerChanges :many
SELECT event.game_id,
       COALESCE(NULLIF(history.name, ''), NULLIF(game.name, ''), '')::text AS game_name,
       event.detector_key,
       event.detector_version,
       event.event_code,
       event.projection_date,
       event.time_basis,
       event.event_at,
       CASE WHEN event.time_basis = 'day' THEN 0 ELSE 1 END::integer AS precision_rank,
       CASE
           WHEN event.time_basis = 'day' THEN event.projection_date::timestamp AT TIME ZONE 'UTC'
           ELSE event.event_at
       END::timestamptz AS event_sort_at,
       md5(event.event_key)::text AS opaque_tie
FROM public.gfg_change_events event
LEFT JOIN public.gfg_game_daily history
  ON history.game_id = event.game_id
 AND history.fact_date = event.projection_date
LEFT JOIN public.gfg_game game ON game.id = event.game_id
WHERE event.detector_key = ANY($1::text[])
  AND event.detector_key || '/' || event.detector_version::text || '/' || event.event_code
      = ANY($2::text[])
  AND (event.detector_key <> 'game_price_transition'
       OR (event.scope_kind = 'region' AND event.scope_key = 'CN'))
  AND event.projection_date <= $3::date
  AND (
      $4::integer = 0
      OR event.projection_date >= $3::date - ($4::integer - 1)
  )
  AND (
      NOT $5::boolean
      OR (
          event.projection_date,
          CASE WHEN event.time_basis = 'day' THEN 0 ELSE 1 END,
          CASE
              WHEN event.time_basis = 'day' THEN event.projection_date::timestamp AT TIME ZONE 'UTC'
              ELSE event.event_at
          END,
          md5(event.event_key)
      ) < (
          $6::date,
          $7::integer,
          $8::timestamptz,
          $9::text
      )
  )
ORDER BY event.projection_date DESC,
         precision_rank DESC,
         event_sort_at DESC,
         opaque_tie DESC
LIMIT $10
`

type ListGameInsightExplorerChangesParams struct {
	DetectorKeys   []string           `json:"detector_keys"`
	ContractIds    []string           `json:"contract_ids"`
	RangeThrough   pgtype.Date        `json:"range_through"`
	RangeDays      int32              `json:"range_days"`
	HasPosition    bool               `json:"has_position"`
	PositionDate   pgtype.Date        `json:"position_date"`
	PositionRank   int32              `json:"position_rank"`
	PositionSortAt pgtype.Timestamptz `json:"position_sort_at"`
	PositionTie    string             `json:"position_tie"`
	LimitCount     int32              `json:"limit_count"`
}

type ListGameInsightExplorerChangesRow struct {
	GameID          int64              `json:"game_id"`
	GameName        string             `json:"game_name"`
	DetectorKey     string             `json:"detector_key"`
	DetectorVersion int32              `json:"detector_version"`
	EventCode       string             `json:"event_code"`
	ProjectionDate  pgtype.Date        `json:"projection_date"`
	TimeBasis       string             `json:"time_basis"`
	EventAt         pgtype.Timestamptz `json:"event_at"`
	PrecisionRank   int32              `json:"precision_rank"`
	EventSortAt     pgtype.Timestamptz `json:"event_sort_at"`
	OpaqueTie       string             `json:"opaque_tie"`
}

func (q *Queries) ListGameInsightExplorerChanges(ctx context.Context, arg ListGameInsightExplorerChangesParams) ([]ListGameInsightExplorerChangesRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightExplorerChanges,
		arg.DetectorKeys,
		arg.ContractIds,
		arg.RangeThrough,
		arg.RangeDays,
		arg.HasPosition,
		arg.PositionDate,
		arg.PositionRank,
		arg.PositionSortAt,
		arg.PositionTie,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightExplorerChangesRow{}
	for rows.Next() {
		var i ListGameInsightExplorerChangesRow
		if err := rows.Scan(
			&i.GameID,
			&i.GameName,
			&i.DetectorKey,
			&i.DetectorVersion,
			&i.EventCode,
			&i.ProjectionDate,
			&i.TimeBasis,
			&i.EventAt,
			&i.PrecisionRank,
			&i.EventSortAt,
			&i.OpaqueTie,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightGameChanges = `-- name: ListGameInsightGameChanges :many
SELECT event.detector_key,
       event.detector_version,
       event.event_code,
       event.projection_date,
       event.time_basis,
       event.event_at
FROM public.gfg_change_events event
WHERE event.game_id = $1
  AND event.detector_key = ANY($2::text[])
  AND (event.detector_key <> 'game_price_transition'
       OR (event.scope_kind = 'region' AND event.scope_key = 'CN'))
  AND event.detector_key || '/' || event.detector_version::text || '/' || event.event_code
      = ANY($3::text[])
ORDER BY event.projection_date DESC,
         event.event_at DESC NULLS LAST,
         event.event_key DESC
LIMIT $4
`

type ListGameInsightGameChangesParams struct {
	GameID       int64    `json:"game_id"`
	DetectorKeys []string `json:"detector_keys"`
	ContractIds  []string `json:"contract_ids"`
	LimitCount   int32    `json:"limit_count"`
}

type ListGameInsightGameChangesRow struct {
	DetectorKey     string             `json:"detector_key"`
	DetectorVersion int32              `json:"detector_version"`
	EventCode       string             `json:"event_code"`
	ProjectionDate  pgtype.Date        `json:"projection_date"`
	TimeBasis       string             `json:"time_basis"`
	EventAt         pgtype.Timestamptz `json:"event_at"`
}

func (q *Queries) ListGameInsightGameChanges(ctx context.Context, arg ListGameInsightGameChangesParams) ([]ListGameInsightGameChangesRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightGameChanges,
		arg.GameID,
		arg.DetectorKeys,
		arg.ContractIds,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightGameChangesRow{}
	for rows.Next() {
		var i ListGameInsightGameChangesRow
		if err := rows.Scan(
			&i.DetectorKey,
			&i.DetectorVersion,
			&i.EventCode,
			&i.ProjectionDate,
			&i.TimeBasis,
			&i.EventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightLanguages = `-- name: ListGameInsightLanguages :many
WITH horizon AS (
    SELECT max(fact_date)::date AS as_of FROM public.gfg_game_daily
    WHERE finalized_at IS NOT NULL AND tracked_at_end
), fresh AS (
    SELECT fact.game_id, fact.fact_date, fact.tracking_period_id, fact.appid, fact.snapshot_at, fact.tracked_at_end, fact.name, fact.name_en, fact.view_count, fact.game_type, fact.is_free, fact.windows, fact.mac, fact.linux, fact.release_availability, fact.release_precision, fact.release_exact_date, fact.release_year, fact.release_month, fact.release_quarter, fact.release_window_start, fact.release_window_end, fact.release_observed_at, fact.first_available_precision, fact.first_available_exact_date, fact.first_available_year, fact.first_available_month, fact.first_available_quarter, fact.first_available_window_start, fact.first_available_window_end, fact.first_available_source, fact.first_available_inferred, fact.language_codes, fact.unknown_language_names, fact.full_audio_language_codes, fact.languages_observed_at, fact.developers, fact.publishers, fact.primary_tag_id, fact.secondary_tag_id, fact.tag_ids, fact.details_observed_at, fact.materialization_source, fact.projection_version, fact.finalized_at, fact.created_at, fact.updated_at FROM horizon JOIN public.gfg_game_daily fact ON fact.fact_date = horizon.as_of
    WHERE fact.finalized_at IS NOT NULL AND fact.tracked_at_end
      AND fact.languages_observed_at IS NOT NULL
      AND fact.languages_observed_at >= ((horizon.as_of + 1)::timestamp AT TIME ZONE 'UTC') - interval '259200 seconds'
), supported AS (
    SELECT DISTINCT fresh.game_id, code FROM fresh CROSS JOIN LATERAL unnest(COALESCE(fresh.language_codes, ARRAY[]::text[])) code
), audio AS (
    SELECT DISTINCT fresh.game_id, code FROM fresh CROSS JOIN LATERAL unnest(COALESCE(fresh.full_audio_language_codes, ARRAY[]::text[])) code
), names AS (
    SELECT language_code AS code, min(steam_name)::text AS steam_name
    FROM public.gfg_game_languages WHERE language_code IS NOT NULL GROUP BY language_code
), codes AS (
    SELECT code FROM supported UNION SELECT code FROM audio
)
SELECT codes.code::text AS code, COALESCE(names.steam_name, codes.code)::text AS steam_name,
       count(DISTINCT supported.game_id)::bigint AS supported_games,
       count(DISTINCT audio.game_id)::bigint AS explicit_full_audio_games
FROM codes LEFT JOIN supported ON supported.code = codes.code
LEFT JOIN audio ON audio.code = codes.code
LEFT JOIN names ON names.code = codes.code
GROUP BY codes.code, names.steam_name
ORDER BY supported_games DESC, codes.code ASC
`

type ListGameInsightLanguagesRow struct {
	Code                   string `json:"code"`
	SteamName              string `json:"steam_name"`
	SupportedGames         int64  `json:"supported_games"`
	ExplicitFullAudioGames int64  `json:"explicit_full_audio_games"`
}

func (q *Queries) ListGameInsightLanguages(ctx context.Context) ([]ListGameInsightLanguagesRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightLanguagesRow{}
	for rows.Next() {
		var i ListGameInsightLanguagesRow
		if err := rows.Scan(
			&i.Code,
			&i.SteamName,
			&i.SupportedGames,
			&i.ExplicitFullAudioGames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightLatestPlayerRanking = `-- name: ListGameInsightLatestPlayerRanking :many
WITH snapshot AS (
    SELECT id, scheduled_for
    FROM public.gfg_collection_jobs
    WHERE job_key = 'game.players' AND trigger = 'scheduled' AND scope_type = 'all'
      AND status IN ('success', 'partial')
    ORDER BY scheduled_for DESC, id DESC LIMIT 1
), observations AS (
    SELECT DISTINCT ON (raw.game_id) raw.game_id, raw.count AS player_count, raw.collected_at
    FROM snapshot
    JOIN public.gfg_collection_runs run ON run.job_id = snapshot.id
    JOIN public.gfg_game_player_counts raw ON raw.run_id = run.id AND raw.status = 'success'
    JOIN public.gfg_game_tracking_periods period
      ON period.game_id = raw.game_id AND period.tracking_basis = 'explicit'
     AND period.tracked_from <= snapshot.scheduled_for
     AND (period.tracked_until IS NULL OR snapshot.scheduled_for < period.tracked_until)
    ORDER BY raw.game_id, raw.collected_at DESC, raw.id DESC
)
SELECT observations.game_id, COALESCE(NULLIF(game.name, ''), game.name_en, '')::text AS game_name,
       observations.player_count, observations.collected_at
FROM observations
JOIN public.gfg_game game ON game.id = observations.game_id
ORDER BY observations.player_count DESC, observations.game_id ASC
LIMIT $1
`

type ListGameInsightLatestPlayerRankingRow struct {
	GameID      int64              `json:"game_id"`
	GameName    string             `json:"game_name"`
	PlayerCount int64              `json:"player_count"`
	CollectedAt pgtype.Timestamptz `json:"collected_at"`
}

func (q *Queries) ListGameInsightLatestPlayerRanking(ctx context.Context, limitCount int32) ([]ListGameInsightLatestPlayerRankingRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightLatestPlayerRanking, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightLatestPlayerRankingRow{}
	for rows.Next() {
		var i ListGameInsightLatestPlayerRankingRow
		if err := rows.Scan(
			&i.GameID,
			&i.GameName,
			&i.PlayerCount,
			&i.CollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightMetricBreakdown = `-- name: ListGameInsightMetricBreakdown :many
SELECT daily.dimension_value,
       COALESCE(tag.name, '')::text AS label,
       COALESCE(tag.name_en, '')::text AS label_en,
       daily.population_count,
       daily.eligible_count,
       daily.positive_count,
       daily.negative_count
FROM public.gfg_metric_daily daily
LEFT JOIN public.gfg_tag tag
  ON daily.dimension_key IN ('primary_tag_id', 'tag_id')
 AND tag.id::text = daily.dimension_value
WHERE daily.metric_key = $1
  AND daily.metric_version = $2
  AND daily.fact_date = $3::date
  AND daily.dimension_key = $4
ORDER BY daily.eligible_count DESC, daily.dimension_value ASC
`

type ListGameInsightMetricBreakdownParams struct {
	MetricKey     string      `json:"metric_key"`
	MetricVersion int32       `json:"metric_version"`
	FactDate      pgtype.Date `json:"fact_date"`
	DimensionKey  string      `json:"dimension_key"`
}

type ListGameInsightMetricBreakdownRow struct {
	DimensionValue  string `json:"dimension_value"`
	Label           string `json:"label"`
	LabelEn         string `json:"label_en"`
	PopulationCount int64  `json:"population_count"`
	EligibleCount   int64  `json:"eligible_count"`
	PositiveCount   int64  `json:"positive_count"`
	NegativeCount   int64  `json:"negative_count"`
}

func (q *Queries) ListGameInsightMetricBreakdown(ctx context.Context, arg ListGameInsightMetricBreakdownParams) ([]ListGameInsightMetricBreakdownRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightMetricBreakdown,
		arg.MetricKey,
		arg.MetricVersion,
		arg.FactDate,
		arg.DimensionKey,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightMetricBreakdownRow{}
	for rows.Next() {
		var i ListGameInsightMetricBreakdownRow
		if err := rows.Scan(
			&i.DimensionValue,
			&i.Label,
			&i.LabelEn,
			&i.PopulationCount,
			&i.EligibleCount,
			&i.PositiveCount,
			&i.NegativeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightMetricSliceTrend = `-- name: ListGameInsightMetricSliceTrend :many
SELECT daily.fact_date,
       daily.population_count,
       daily.eligible_count,
       daily.positive_count,
       daily.negative_count
FROM public.gfg_metric_daily daily
WHERE daily.metric_key = $1
  AND daily.metric_version = $2
  AND daily.dimension_key = $3
  AND daily.dimension_value = $4
  AND daily.fact_date <= $5::date
  AND (
      $6::integer = 0
      OR daily.fact_date >= $5::date - ($6::integer - 1)
  )
ORDER BY daily.fact_date
`

type ListGameInsightMetricSliceTrendParams struct {
	MetricKey      string      `json:"metric_key"`
	MetricVersion  int32       `json:"metric_version"`
	DimensionKey   string      `json:"dimension_key"`
	DimensionValue string      `json:"dimension_value"`
	ThroughDate    pgtype.Date `json:"through_date"`
	RangeDays      int32       `json:"range_days"`
}

type ListGameInsightMetricSliceTrendRow struct {
	FactDate        pgtype.Date `json:"fact_date"`
	PopulationCount int64       `json:"population_count"`
	EligibleCount   int64       `json:"eligible_count"`
	PositiveCount   int64       `json:"positive_count"`
	NegativeCount   int64       `json:"negative_count"`
}

func (q *Queries) ListGameInsightMetricSliceTrend(ctx context.Context, arg ListGameInsightMetricSliceTrendParams) ([]ListGameInsightMetricSliceTrendRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightMetricSliceTrend,
		arg.MetricKey,
		arg.MetricVersion,
		arg.DimensionKey,
		arg.DimensionValue,
		arg.ThroughDate,
		arg.RangeDays,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightMetricSliceTrendRow{}
	for rows.Next() {
		var i ListGameInsightMetricSliceTrendRow
		if err := rows.Scan(
			&i.FactDate,
			&i.PopulationCount,
			&i.EligibleCount,
			&i.PositiveCount,
			&i.NegativeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightMetricTrend = `-- name: ListGameInsightMetricTrend :many
WITH latest AS (
    SELECT max(fact_date)::date AS fact_date
    FROM public.gfg_metric_daily
    WHERE metric_key = $1
      AND metric_version = $2
      AND dimension_key = 'global'
      AND dimension_value = 'all'
)
SELECT daily.fact_date,
       daily.eligible_count,
       daily.positive_count,
       daily.negative_count
FROM public.gfg_metric_daily daily
CROSS JOIN latest
WHERE daily.metric_key = $1
  AND daily.metric_version = $2
  AND daily.dimension_key = 'global'
  AND daily.dimension_value = 'all'
  AND (
      $3::integer = 0
      OR daily.fact_date >= latest.fact_date - ($3::integer - 1)
  )
ORDER BY daily.fact_date
`

type ListGameInsightMetricTrendParams struct {
	MetricKey     string `json:"metric_key"`
	MetricVersion int32  `json:"metric_version"`
	RangeDays     int32  `json:"range_days"`
}

type ListGameInsightMetricTrendRow struct {
	FactDate      pgtype.Date `json:"fact_date"`
	EligibleCount int64       `json:"eligible_count"`
	PositiveCount int64       `json:"positive_count"`
	NegativeCount int64       `json:"negative_count"`
}

func (q *Queries) ListGameInsightMetricTrend(ctx context.Context, arg ListGameInsightMetricTrendParams) ([]ListGameInsightMetricTrendRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightMetricTrend, arg.MetricKey, arg.MetricVersion, arg.RangeDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightMetricTrendRow{}
	for rows.Next() {
		var i ListGameInsightMetricTrendRow
		if err := rows.Scan(
			&i.FactDate,
			&i.EligibleCount,
			&i.PositiveCount,
			&i.NegativeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightOverviewChanges = `-- name: ListGameInsightOverviewChanges :many
WITH newest AS (
    SELECT DISTINCT ON (event.game_id)
           event.game_id,
           event.detector_key,
           event.detector_version,
           event.event_code,
           event.projection_date,
           event.time_basis,
           event.event_at,
           event.event_key
    FROM public.gfg_change_events event
    WHERE event.detector_key = ANY($2::text[])
      AND (event.detector_key <> 'game_price_transition'
           OR (event.scope_kind = 'region' AND event.scope_key = 'CN'))
      AND event.detector_key || '/' || event.detector_version::text || '/' || event.event_code
          = ANY($3::text[])
    ORDER BY event.game_id, event.projection_date DESC,
             event.event_at DESC NULLS LAST, event.event_key DESC
)
SELECT newest.game_id,
       COALESCE(NULLIF(history.name, ''), NULLIF(game.name, ''), '')::text AS game_name,
       newest.detector_key,
       newest.detector_version,
       newest.event_code,
       newest.projection_date,
       newest.time_basis,
       newest.event_at
FROM newest
LEFT JOIN public.gfg_game_daily history
  ON history.game_id = newest.game_id
 AND history.fact_date = newest.projection_date
LEFT JOIN public.gfg_game game ON game.id = newest.game_id
ORDER BY newest.projection_date DESC,
         newest.event_at DESC NULLS LAST,
         newest.game_id DESC
LIMIT $1
`

type ListGameInsightOverviewChangesParams struct {
	LimitCount   int32    `json:"limit_count"`
	DetectorKeys []string `json:"detector_keys"`
	ContractIds  []string `json:"contract_ids"`
}

type ListGameInsightOverviewChangesRow struct {
	GameID          int64              `json:"game_id"`
	GameName        string             `json:"game_name"`
	DetectorKey     string             `json:"detector_key"`
	DetectorVersion int32              `json:"detector_version"`
	EventCode       string             `json:"event_code"`
	ProjectionDate  pgtype.Date        `json:"projection_date"`
	TimeBasis       string             `json:"time_basis"`
	EventAt         pgtype.Timestamptz `json:"event_at"`
}

func (q *Queries) ListGameInsightOverviewChanges(ctx context.Context, arg ListGameInsightOverviewChangesParams) ([]ListGameInsightOverviewChangesRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightOverviewChanges, arg.LimitCount, arg.DetectorKeys, arg.ContractIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightOverviewChangesRow{}
	for rows.Next() {
		var i ListGameInsightOverviewChangesRow
		if err := rows.Scan(
			&i.GameID,
			&i.GameName,
			&i.DetectorKey,
			&i.DetectorVersion,
			&i.EventCode,
			&i.ProjectionDate,
			&i.TimeBasis,
			&i.EventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightPlayer30dRanking = `-- name: ListGameInsightPlayer30dRanking :many
WITH horizon AS (
    SELECT processed_through FROM public.gfg_fact_rollup_checkpoints WHERE pipeline_key = 'game.player_facts'
), cohort AS (
    SELECT period.id, period.game_id,
           GREATEST(horizon.processed_through - 29, (period.tracked_from AT TIME ZONE 'UTC')::date)::date AS eligible_from,
           horizon.processed_through
    FROM horizon
    JOIN public.gfg_game_tracking_periods period ON period.tracking_basis = 'explicit'
     AND period.tracked_from < (horizon.processed_through + 1)::timestamp AT TIME ZONE 'UTC'
     AND (period.tracked_until IS NULL OR period.tracked_until >= (horizon.processed_through + 1)::timestamp AT TIME ZONE 'UTC')
), aggregate AS (
    SELECT cohort.game_id, cohort.eligible_from,
           max(daily.max_players)::bigint AS peak_30d,
           (sum(daily.avg_players * daily.successful_samples) / NULLIF(sum(daily.successful_samples), 0))::double precision AS average_30d,
           count(*) FILTER (WHERE daily.successful_samples > 0)::bigint AS observed_days,
           sum(daily.successful_samples)::bigint AS successful_samples,
           CASE WHEN count(*) = cohort.processed_through - cohort.eligible_from + 1
                  AND bool_and(daily.expected_samples IS NOT NULL) AND sum(daily.expected_samples) > 0
                THEN sum(daily.successful_samples)::double precision / sum(daily.expected_samples)
                ELSE 0::double precision END::double precision AS sample_coverage,
           (count(*) = cohort.processed_through - cohort.eligible_from + 1
             AND bool_and(daily.expected_samples IS NOT NULL) AND sum(daily.expected_samples) > 0) AS has_sample_coverage
    FROM cohort
    JOIN public.gfg_game_player_daily daily ON daily.tracking_period_id = cohort.id
     AND daily.fact_date BETWEEN cohort.eligible_from AND cohort.processed_through
     AND daily.finalized_at IS NOT NULL
    GROUP BY cohort.game_id, cohort.eligible_from, cohort.processed_through
    HAVING sum(daily.successful_samples) > 0
)
SELECT aggregate.game_id, COALESCE(NULLIF(game.name, ''), game.name_en, '')::text AS game_name,
       aggregate.peak_30d, aggregate.average_30d, aggregate.eligible_from,
       aggregate.observed_days, aggregate.successful_samples, aggregate.sample_coverage, aggregate.has_sample_coverage
FROM aggregate JOIN public.gfg_game game ON game.id = aggregate.game_id
ORDER BY CASE WHEN $1::boolean THEN aggregate.average_30d ELSE aggregate.peak_30d END DESC,
         aggregate.game_id ASC
LIMIT $2
`

type ListGameInsightPlayer30dRankingParams struct {
	UseAverage bool  `json:"use_average"`
	LimitCount int32 `json:"limit_count"`
}

type ListGameInsightPlayer30dRankingRow struct {
	GameID            int64       `json:"game_id"`
	GameName          string      `json:"game_name"`
	Peak30d           int64       `json:"peak_30d"`
	Average30d        float64     `json:"average_30d"`
	EligibleFrom      pgtype.Date `json:"eligible_from"`
	ObservedDays      int64       `json:"observed_days"`
	SuccessfulSamples int64       `json:"successful_samples"`
	SampleCoverage    float64     `json:"sample_coverage"`
	HasSampleCoverage *bool       `json:"has_sample_coverage"`
}

func (q *Queries) ListGameInsightPlayer30dRanking(ctx context.Context, arg ListGameInsightPlayer30dRankingParams) ([]ListGameInsightPlayer30dRankingRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightPlayer30dRanking, arg.UseAverage, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightPlayer30dRankingRow{}
	for rows.Next() {
		var i ListGameInsightPlayer30dRankingRow
		if err := rows.Scan(
			&i.GameID,
			&i.GameName,
			&i.Peak30d,
			&i.Average30d,
			&i.EligibleFrom,
			&i.ObservedDays,
			&i.SuccessfulSamples,
			&i.SampleCoverage,
			&i.HasSampleCoverage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightPlayerHistory = `-- name: ListGameInsightPlayerHistory :many
WITH latest AS (
    SELECT max(fact_date)::date AS fact_date
    FROM public.gfg_game_player_daily
    WHERE tracking_period_id = $1
      AND finalized_at IS NOT NULL
      AND successful_samples > 0
      AND max_players IS NOT NULL
)
SELECT daily.fact_date,
       daily.min_players,
       daily.max_players,
       daily.avg_players
FROM public.gfg_game_player_daily daily
CROSS JOIN latest
WHERE daily.tracking_period_id = $1
  AND daily.finalized_at IS NOT NULL
  AND daily.successful_samples > 0
  AND daily.max_players IS NOT NULL
  AND (
      $2::integer = 0
      OR daily.fact_date >= latest.fact_date - ($2::integer - 1)
  )
ORDER BY daily.fact_date
`

type ListGameInsightPlayerHistoryParams struct {
	TrackingPeriodID int64 `json:"tracking_period_id"`
	RangeDays        int32 `json:"range_days"`
}

type ListGameInsightPlayerHistoryRow struct {
	FactDate   pgtype.Date `json:"fact_date"`
	MinPlayers *int64      `json:"min_players"`
	MaxPlayers *int64      `json:"max_players"`
	AvgPlayers *float64    `json:"avg_players"`
}

func (q *Queries) ListGameInsightPlayerHistory(ctx context.Context, arg ListGameInsightPlayerHistoryParams) ([]ListGameInsightPlayerHistoryRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightPlayerHistory, arg.TrackingPeriodID, arg.RangeDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightPlayerHistoryRow{}
	for rows.Next() {
		var i ListGameInsightPlayerHistoryRow
		if err := rows.Scan(
			&i.FactDate,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.AvgPlayers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightPriceHistory = `-- name: ListGameInsightPriceHistory :many
SELECT daily.fact_date,
       daily.price_state,
       daily.currency,
       daily.initial_amount,
       daily.final_amount,
       daily.discount_percent
FROM public.gfg_game_price_daily daily
WHERE daily.tracking_period_id = $1
  AND daily.region = $2
  AND daily.finalized_at IS NOT NULL
  AND daily.fact_date <= $3::date
  AND (
      $4::integer = 0
      OR daily.fact_date >= $3::date - ($4::integer - 1)
  )
ORDER BY daily.fact_date
`

type ListGameInsightPriceHistoryParams struct {
	TrackingPeriodID int64       `json:"tracking_period_id"`
	Region           string      `json:"region"`
	ThroughDate      pgtype.Date `json:"through_date"`
	RangeDays        int32       `json:"range_days"`
}

type ListGameInsightPriceHistoryRow struct {
	FactDate        pgtype.Date `json:"fact_date"`
	PriceState      string      `json:"price_state"`
	Currency        *string     `json:"currency"`
	InitialAmount   *int64      `json:"initial_amount"`
	FinalAmount     *int64      `json:"final_amount"`
	DiscountPercent *int32      `json:"discount_percent"`
}

func (q *Queries) ListGameInsightPriceHistory(ctx context.Context, arg ListGameInsightPriceHistoryParams) ([]ListGameInsightPriceHistoryRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightPriceHistory,
		arg.TrackingPeriodID,
		arg.Region,
		arg.ThroughDate,
		arg.RangeDays,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightPriceHistoryRow{}
	for rows.Next() {
		var i ListGameInsightPriceHistoryRow
		if err := rows.Scan(
			&i.FactDate,
			&i.PriceState,
			&i.Currency,
			&i.InitialAmount,
			&i.FinalAmount,
			&i.DiscountPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightRegionalPrices = `-- name: ListGameInsightRegionalPrices :many
WITH regions AS (SELECT unnest(ARRAY['CN', 'US', 'HK']::text[]) AS region)
SELECT regions.region::text AS region,
       price.fact_date,
       price.price_state,
       price.currency,
       price.initial_amount,
       price.final_amount,
       price.discount_percent
FROM regions
LEFT JOIN public.gfg_game_price_daily price
  ON price.tracking_period_id = $1
 AND price.region = regions.region
 AND price.fact_date = $2::date
 AND price.finalized_at IS NOT NULL
ORDER BY CASE regions.region WHEN 'CN' THEN 1 WHEN 'US' THEN 2 ELSE 3 END
`

type ListGameInsightRegionalPricesParams struct {
	TrackingPeriodID int64       `json:"tracking_period_id"`
	FactDate         pgtype.Date `json:"fact_date"`
}

type ListGameInsightRegionalPricesRow struct {
	Region          string      `json:"region"`
	FactDate        pgtype.Date `json:"fact_date"`
	PriceState      *string     `json:"price_state"`
	Currency        *string     `json:"currency"`
	InitialAmount   *int64      `json:"initial_amount"`
	FinalAmount     *int64      `json:"final_amount"`
	DiscountPercent *int32      `json:"discount_percent"`
}

func (q *Queries) ListGameInsightRegionalPrices(ctx context.Context, arg ListGameInsightRegionalPricesParams) ([]ListGameInsightRegionalPricesRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightRegionalPrices, arg.TrackingPeriodID, arg.FactDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightRegionalPricesRow{}
	for rows.Next() {
		var i ListGameInsightRegionalPricesRow
		if err := rows.Scan(
			&i.Region,
			&i.FactDate,
			&i.PriceState,
			&i.Currency,
			&i.InitialAmount,
			&i.FinalAmount,
			&i.DiscountPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
