// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights_compare.sql

package gamesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGameInsightCompareFactHorizon = `-- name: GetGameInsightCompareFactHorizon :one
WITH requested AS (
    SELECT game_id
    FROM unnest($1::bigint[]) AS selected(game_id)
), complete_dates AS (
    SELECT daily.fact_date
    FROM public.gfg_game_daily daily
    JOIN requested ON requested.game_id = daily.game_id
    WHERE daily.finalized_at IS NOT NULL
      AND daily.tracked_at_end
    GROUP BY daily.fact_date
    HAVING count(*) = cardinality($1::bigint[])
)
SELECT max(fact_date)::date AS fact_date
FROM complete_dates
`

func (q *Queries) GetGameInsightCompareFactHorizon(ctx context.Context, gameIds []int64) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getGameInsightCompareFactHorizon, gameIds)
	var fact_date pgtype.Date
	err := row.Scan(&fact_date)
	return fact_date, err
}

const listGameInsightCompareCurrentPlayers = `-- name: ListGameInsightCompareCurrentPlayers :many
WITH requested AS (
    SELECT game_id, position
    FROM unnest($1::bigint[]) WITH ORDINALITY AS selected(game_id, position)
), snapshot AS (
    SELECT id, scheduled_for
    FROM public.gfg_collection_jobs
    WHERE job_key = 'game.players'
      AND trigger = 'scheduled'
      AND scope_type = 'all'
      AND status IN ('success', 'partial')
    ORDER BY scheduled_for DESC, id DESC
    LIMIT 1
), observations AS (
    SELECT DISTINCT ON (raw.game_id)
           raw.game_id,
           raw.count AS player_count,
           raw.collected_at
    FROM snapshot
    JOIN public.gfg_collection_runs run ON run.job_id = snapshot.id
    JOIN public.gfg_game_player_counts raw
      ON raw.run_id = run.id
     AND raw.status = 'success'
    ORDER BY raw.game_id, raw.collected_at DESC, raw.id DESC
)
SELECT requested.game_id::bigint AS game_id,
       snapshot.scheduled_for::timestamptz AS snapshot_scheduled_for,
       (observations.game_id IS NOT NULL)::boolean AS available,
       COALESCE(observations.player_count, 0)::bigint AS player_count,
       observations.collected_at
FROM requested
LEFT JOIN snapshot ON true
LEFT JOIN observations ON observations.game_id = requested.game_id
ORDER BY requested.position
`

type ListGameInsightCompareCurrentPlayersRow struct {
	GameID               int64              `json:"game_id"`
	SnapshotScheduledFor pgtype.Timestamptz `json:"snapshot_scheduled_for"`
	Available            bool               `json:"available"`
	PlayerCount          int64              `json:"player_count"`
	CollectedAt          pgtype.Timestamptz `json:"collected_at"`
}

func (q *Queries) ListGameInsightCompareCurrentPlayers(ctx context.Context, gameIds []int64) ([]ListGameInsightCompareCurrentPlayersRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightCompareCurrentPlayers, gameIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightCompareCurrentPlayersRow{}
	for rows.Next() {
		var i ListGameInsightCompareCurrentPlayersRow
		if err := rows.Scan(
			&i.GameID,
			&i.SnapshotScheduledFor,
			&i.Available,
			&i.PlayerCount,
			&i.CollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightCompareFacts = `-- name: ListGameInsightCompareFacts :many
WITH requested AS (
    SELECT game_id, position
    FROM unnest($3::bigint[]) WITH ORDINALITY AS selected(game_id, position)
)
SELECT daily.game_id,
       daily.tracking_period_id,
       daily.is_free,
       daily.windows,
       daily.mac,
       daily.linux,
       daily.release_availability,
       CASE
           WHEN daily.languages_observed_at IS NULL THEN 'unobserved'
           WHEN daily.languages_observed_at < ((daily.fact_date + 1)::timestamp AT TIME ZONE 'UTC') - interval '259200 seconds' THEN 'stale'
           ELSE 'fresh'
       END::text AS language_evidence,
       COALESCE(daily.language_codes, ARRAY[]::text[])::text[] AS language_codes,
       COALESCE(daily.full_audio_language_codes, ARRAY[]::text[])::text[] AS full_audio_language_codes,
       COALESCE(daily.unknown_language_names, ARRAY[]::text[])::text[] AS unknown_language_names,
       (price.fact_date IS NOT NULL)::boolean AS price_available,
       price.price_state,
       price.currency,
       price.initial_amount,
       price.final_amount,
       price.discount_percent
FROM requested
JOIN public.gfg_game_daily daily
  ON daily.game_id = requested.game_id
 AND daily.fact_date = $1::date
 AND daily.finalized_at IS NOT NULL
 AND daily.tracked_at_end
LEFT JOIN public.gfg_game_price_daily price
  ON price.tracking_period_id = daily.tracking_period_id
 AND price.fact_date = daily.fact_date
 AND price.region = $2
 AND price.finalized_at IS NOT NULL
ORDER BY requested.position
`

type ListGameInsightCompareFactsParams struct {
	FactDate pgtype.Date `json:"fact_date"`
	Region   string      `json:"region"`
	GameIds  []int64     `json:"game_ids"`
}

type ListGameInsightCompareFactsRow struct {
	GameID                 int64    `json:"game_id"`
	TrackingPeriodID       int64    `json:"tracking_period_id"`
	IsFree                 *bool    `json:"is_free"`
	Windows                *bool    `json:"windows"`
	Mac                    *bool    `json:"mac"`
	Linux                  *bool    `json:"linux"`
	ReleaseAvailability    *string  `json:"release_availability"`
	LanguageEvidence       string   `json:"language_evidence"`
	LanguageCodes          []string `json:"language_codes"`
	FullAudioLanguageCodes []string `json:"full_audio_language_codes"`
	UnknownLanguageNames   []string `json:"unknown_language_names"`
	PriceAvailable         bool     `json:"price_available"`
	PriceState             *string  `json:"price_state"`
	Currency               *string  `json:"currency"`
	InitialAmount          *int64   `json:"initial_amount"`
	FinalAmount            *int64   `json:"final_amount"`
	DiscountPercent        *int32   `json:"discount_percent"`
}

func (q *Queries) ListGameInsightCompareFacts(ctx context.Context, arg ListGameInsightCompareFactsParams) ([]ListGameInsightCompareFactsRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightCompareFacts, arg.FactDate, arg.Region, arg.GameIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightCompareFactsRow{}
	for rows.Next() {
		var i ListGameInsightCompareFactsRow
		if err := rows.Scan(
			&i.GameID,
			&i.TrackingPeriodID,
			&i.IsFree,
			&i.Windows,
			&i.Mac,
			&i.Linux,
			&i.ReleaseAvailability,
			&i.LanguageEvidence,
			&i.LanguageCodes,
			&i.FullAudioLanguageCodes,
			&i.UnknownLanguageNames,
			&i.PriceAvailable,
			&i.PriceState,
			&i.Currency,
			&i.InitialAmount,
			&i.FinalAmount,
			&i.DiscountPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInsightComparePlayer30d = `-- name: ListGameInsightComparePlayer30d :many
WITH requested AS (
    SELECT game_id, position
    FROM unnest($1::bigint[]) WITH ORDINALITY AS selected(game_id, position)
), horizon AS (
    SELECT processed_through
    FROM public.gfg_fact_rollup_checkpoints
    WHERE pipeline_key = 'game.player_facts'
), cohort AS (
    SELECT requested.game_id,
           requested.position,
           horizon.processed_through,
           period.id AS tracking_period_id,
           CASE WHEN period.id IS NULL OR horizon.processed_through IS NULL THEN NULL
                ELSE GREATEST(
                    horizon.processed_through - 29,
                    (period.tracked_from AT TIME ZONE 'UTC')::date
                )::date
           END AS eligible_from
    FROM requested
    LEFT JOIN horizon ON true
    LEFT JOIN LATERAL (
        SELECT candidate.id, candidate.tracked_from
        FROM public.gfg_game_tracking_periods candidate
        WHERE candidate.game_id = requested.game_id
          AND candidate.tracking_basis = 'explicit'
          AND candidate.tracked_from < (horizon.processed_through + 1)::timestamp AT TIME ZONE 'UTC'
          AND (
              candidate.tracked_until IS NULL
              OR candidate.tracked_until >= (horizon.processed_through + 1)::timestamp AT TIME ZONE 'UTC'
          )
        ORDER BY candidate.tracked_from DESC, candidate.id DESC
        LIMIT 1
    ) period ON true
)
SELECT cohort.game_id::bigint AS game_id,
       cohort.processed_through AS fact_through,
       cohort.eligible_from,
       COALESCE(max(daily.max_players) FILTER (WHERE daily.successful_samples > 0), 0)::bigint AS peak_30d,
       COALESCE((
           sum(daily.avg_players * daily.successful_samples) FILTER (WHERE daily.successful_samples > 0)
           / NULLIF(sum(daily.successful_samples) FILTER (WHERE daily.successful_samples > 0), 0)
       ), 0)::double precision AS average_30d,
       count(*) FILTER (WHERE daily.successful_samples > 0)::bigint AS observed_days,
       COALESCE(sum(daily.successful_samples), 0)::bigint AS successful_samples,
       CASE
           WHEN cohort.tracking_period_id IS NOT NULL
            AND count(daily.*) = cohort.processed_through - cohort.eligible_from + 1
            AND bool_and(daily.expected_samples IS NOT NULL)
            AND sum(daily.expected_samples) > 0
           THEN sum(daily.successful_samples)::double precision / sum(daily.expected_samples)
           ELSE 0::double precision
       END::double precision AS sample_coverage,
       COALESCE((
           cohort.tracking_period_id IS NOT NULL
           AND count(daily.*) = cohort.processed_through - cohort.eligible_from + 1
           AND bool_and(daily.expected_samples IS NOT NULL)
           AND sum(daily.expected_samples) > 0
       ), false)::boolean AS has_sample_coverage
FROM cohort
LEFT JOIN public.gfg_game_player_daily daily
  ON daily.tracking_period_id = cohort.tracking_period_id
 AND daily.fact_date BETWEEN cohort.eligible_from AND cohort.processed_through
 AND daily.finalized_at IS NOT NULL
GROUP BY cohort.game_id, cohort.position, cohort.processed_through,
         cohort.tracking_period_id, cohort.eligible_from
ORDER BY cohort.position
`

type ListGameInsightComparePlayer30dRow struct {
	GameID            int64       `json:"game_id"`
	FactThrough       pgtype.Date `json:"fact_through"`
	EligibleFrom      pgtype.Date `json:"eligible_from"`
	Peak30d           int64       `json:"peak_30d"`
	Average30d        float64     `json:"average_30d"`
	ObservedDays      int64       `json:"observed_days"`
	SuccessfulSamples int64       `json:"successful_samples"`
	SampleCoverage    float64     `json:"sample_coverage"`
	HasSampleCoverage bool        `json:"has_sample_coverage"`
}

func (q *Queries) ListGameInsightComparePlayer30d(ctx context.Context, gameIds []int64) ([]ListGameInsightComparePlayer30dRow, error) {
	rows, err := q.db.Query(ctx, listGameInsightComparePlayer30d, gameIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameInsightComparePlayer30dRow{}
	for rows.Next() {
		var i ListGameInsightComparePlayer30dRow
		if err := rows.Scan(
			&i.GameID,
			&i.FactThrough,
			&i.EligibleFrom,
			&i.Peak30d,
			&i.Average30d,
			&i.ObservedDays,
			&i.SuccessfulSamples,
			&i.SampleCoverage,
			&i.HasSampleCoverage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
