// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag_domain.sql

package gamesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSourceRecommendations = `-- name: DeleteSourceRecommendations :exec
DELETE FROM gfg_game_recommendations WHERE source_game_id=$1
`

func (q *Queries) DeleteSourceRecommendations(ctx context.Context, sourceGameID int64) error {
	_, err := q.db.Exec(ctx, deleteSourceRecommendations, sourceGameID)
	return err
}

const listPublicTagCategories = `-- name: ListPublicTagCategories :many
SELECT id,code,CASE WHEN $1::text='en' THEN COALESCE(NULLIF(name_en,''),name) ELSE COALESCE(NULLIF(name,''),name_en) END::text AS name
FROM gfg_tag_category WHERE archived_at IS NULL ORDER BY sort_order,id
`

type ListPublicTagCategoriesRow struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) ListPublicTagCategories(ctx context.Context, lang string) ([]ListPublicTagCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listPublicTagCategories, lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicTagCategoriesRow{}
	for rows.Next() {
		var i ListPublicTagCategoriesRow
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicTags = `-- name: ListPublicTags :many
SELECT t.id::text AS id,t.code,
 CASE WHEN $1::text='en' THEN COALESCE(NULLIF(t.name_en,''),t.name) ELSE COALESCE(NULLIF(t.name,''),t.name_en) END::text AS name,
 t.category_id::text AS category_id,c.code AS category_code,
 CASE WHEN $1::text='en' THEN COALESCE(NULLIF(c.name_en,''),c.name) ELSE COALESCE(NULLIF(c.name,''),c.name_en) END::text AS category_name,
 COALESCE(tc.game_count,0)::integer AS game_count
FROM gfg_tag t JOIN gfg_tag_category c ON c.id=t.category_id
LEFT JOIN (SELECT gt.tag_id,count(*) AS game_count FROM gfg_game_tag gt
 JOIN gfg_game_details d ON d.game_id=gt.game_id GROUP BY gt.tag_id) tc ON tc.tag_id=t.id
WHERE t.archived_at IS NULL AND c.archived_at IS NULL
ORDER BY game_count DESC,t.id
`

type ListPublicTagsRow struct {
	ID           string `json:"id"`
	Code         string `json:"code"`
	Name         string `json:"name"`
	CategoryID   string `json:"category_id"`
	CategoryCode string `json:"category_code"`
	CategoryName string `json:"category_name"`
	GameCount    int32  `json:"game_count"`
}

func (q *Queries) ListPublicTags(ctx context.Context, lang string) ([]ListPublicTagsRow, error) {
	rows, err := q.db.Query(ctx, listPublicTags, lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicTagsRow{}
	for rows.Next() {
		var i ListPublicTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CategoryID,
			&i.CategoryCode,
			&i.CategoryName,
			&i.GameCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRecommendationDomain = `-- name: LockRecommendationDomain :exec
SELECT pg_advisory_xact_lock(hashtextextended('gfg.tag-domain',0))
`

func (q *Queries) LockRecommendationDomain(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockRecommendationDomain)
	return err
}

const storeRecommendation = `-- name: StoreRecommendation :exec
INSERT INTO gfg_game_recommendations(source_game_id,target_game_id,score,display_score,rank,reason_json,algorithm_version,computed_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type StoreRecommendationParams struct {
	SourceGameID     int64              `json:"source_game_id"`
	TargetGameID     int64              `json:"target_game_id"`
	Score            float64            `json:"score"`
	DisplayScore     float64            `json:"display_score"`
	Rank             int32              `json:"rank"`
	ReasonJson       []byte             `json:"reason_json"`
	AlgorithmVersion string             `json:"algorithm_version"`
	ComputedAt       pgtype.Timestamptz `json:"computed_at"`
}

func (q *Queries) StoreRecommendation(ctx context.Context, arg StoreRecommendationParams) error {
	_, err := q.db.Exec(ctx, storeRecommendation,
		arg.SourceGameID,
		arg.TargetGameID,
		arg.Score,
		arg.DisplayScore,
		arg.Rank,
		arg.ReasonJson,
		arg.AlgorithmVersion,
		arg.ComputedAt,
	)
	return err
}
