// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collaboration.sql

package navsqlc

import (
	"context"
)

const getSiteForCollaborationLink = `-- name: GetSiteForCollaborationLink :one
SELECT id, name, name_en FROM gfn_site WHERE id = $1 AND deleted IS NOT TRUE
`

type GetSiteForCollaborationLinkRow struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	NameEn string `json:"name_en"`
}

func (q *Queries) GetSiteForCollaborationLink(ctx context.Context, id int64) (GetSiteForCollaborationLinkRow, error) {
	row := q.db.QueryRow(ctx, getSiteForCollaborationLink, id)
	var i GetSiteForCollaborationLinkRow
	err := row.Scan(&i.ID, &i.Name, &i.NameEn)
	return i, err
}

const listSitesByNormalizedHostsForCollaboration = `-- name: ListSitesByNormalizedHostsForCollaboration :many
SELECT DISTINCT site.id, site.name, site.name_en,
    regexp_replace(rtrim(regexp_replace(lower(btrim(COALESCE(target.prefix, '') || target.name)), ':[0-9]+$', ''), '.'), '^www\.', '')::text AS host
FROM gfn_site site
JOIN gfn_collector_domain target ON target.site_id = site.id AND target.deleted IS NOT TRUE
WHERE site.deleted IS NOT TRUE
AND regexp_replace(rtrim(regexp_replace(lower(btrim(COALESCE(target.prefix, '') || target.name)), ':[0-9]+$', ''), '.'), '^www\.', '') = ANY($1::text[])
ORDER BY site.id
`

type ListSitesByNormalizedHostsForCollaborationRow struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	NameEn string `json:"name_en"`
	Host   string `json:"host"`
}

// Collector targets store prefix and hostname separately. Preserve subdomains;
// strip only port, trailing dot and one leading www, as the Go normalizer does.
func (q *Queries) ListSitesByNormalizedHostsForCollaboration(ctx context.Context, hosts []string) ([]ListSitesByNormalizedHostsForCollaborationRow, error) {
	rows, err := q.db.Query(ctx, listSitesByNormalizedHostsForCollaboration, hosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSitesByNormalizedHostsForCollaborationRow{}
	for rows.Next() {
		var i ListSitesByNormalizedHostsForCollaborationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameEn,
			&i.Host,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
