// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: curation.sql

package navsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listGroupCuration = `-- name: ListGroupCuration :many
SELECT m.id, m.site_id, m.weight, s.name, s.deleted, s.update_time
FROM gfn_site_group_map m JOIN gfn_site s ON s.id=m.site_id
WHERE m.group_id=$1
ORDER BY s.deleted ASC, m.weight DESC, s.update_time DESC, s.id DESC
`

type ListGroupCurationRow struct {
	ID         int64            `json:"id"`
	SiteID     int64            `json:"site_id"`
	Weight     int64            `json:"weight"`
	Name       string           `json:"name"`
	Deleted    bool             `json:"deleted"`
	UpdateTime pgtype.Timestamp `json:"update_time"`
}

func (q *Queries) ListGroupCuration(ctx context.Context, groupID int64) ([]ListGroupCurationRow, error) {
	rows, err := q.db.Query(ctx, listGroupCuration, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupCurationRow{}
	for rows.Next() {
		var i ListGroupCurationRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Weight,
			&i.Name,
			&i.Deleted,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSiteGroupCuration = `-- name: LockSiteGroupCuration :exec
SELECT pg_advisory_xact_lock(hashtext('admin.site_group_curation')::bigint)
`

func (q *Queries) LockSiteGroupCuration(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSiteGroupCuration)
	return err
}

const updateGroupCurationWeight = `-- name: UpdateGroupCurationWeight :execrows
UPDATE gfn_site_group_map SET weight=$1, update_time=NOW()::timestamp(0)
WHERE group_id=$2 AND site_id=$3
`

type UpdateGroupCurationWeightParams struct {
	Weight  int64 `json:"weight"`
	GroupID int64 `json:"group_id"`
	SiteID  int64 `json:"site_id"`
}

func (q *Queries) UpdateGroupCurationWeight(ctx context.Context, arg UpdateGroupCurationWeightParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGroupCurationWeight, arg.Weight, arg.GroupID, arg.SiteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
