// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: historical_facts.sql

package navsqlc

import (
	"context"
)

const assignPrimaryTargetIfMissing = `-- name: AssignPrimaryTargetIfMissing :execrows
WITH candidates AS (
    SELECT target_period.id,
           target_period.site_id,
           count(*) OVER () AS target_count,
           row_number() OVER (
               ORDER BY CASE WHEN COALESCE(domain.prefix, '') = '' THEN 0 ELSE 1 END,
                        domain.id
           ) AS target_rank
    FROM gfn_target_tracking_periods target_period
    JOIN gfn_collector_domain domain
      ON domain.id = target_period.collector_domain_id
    WHERE target_period.site_id = $1
      AND target_period.tracked_until IS NULL
      AND NOT domain.deleted
)
INSERT INTO gfn_site_primary_target_periods (
    site_id, target_tracking_period_id, effective_from, basis
)
SELECT site_id,
       id,
       transaction_timestamp(),
       CASE WHEN target_count = 1
            THEN 'single_target_inferred'
            ELSE 'deterministic_fallback'
       END
FROM candidates
WHERE target_rank = 1
  AND NOT EXISTS (
      SELECT 1 FROM gfn_site_primary_target_periods current_primary
      WHERE current_primary.site_id = $1
        AND current_primary.effective_until IS NULL
  )
ON CONFLICT (site_id) WHERE effective_until IS NULL DO NOTHING
`

func (q *Queries) AssignPrimaryTargetIfMissing(ctx context.Context, siteID int64) (int64, error) {
	result, err := q.db.Exec(ctx, assignPrimaryTargetIfMissing, siteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closePrimaryTargetBySite = `-- name: ClosePrimaryTargetBySite :execrows
UPDATE gfn_site_primary_target_periods
SET effective_until = GREATEST(transaction_timestamp(), effective_from + interval '1 microsecond'),
    updated_at = transaction_timestamp()
WHERE site_id = $1 AND effective_until IS NULL
`

func (q *Queries) ClosePrimaryTargetBySite(ctx context.Context, siteID int64) (int64, error) {
	result, err := q.db.Exec(ctx, closePrimaryTargetBySite, siteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeTargetTrackingPeriod = `-- name: CloseTargetTrackingPeriod :one
UPDATE gfn_target_tracking_periods
SET tracked_until = GREATEST(transaction_timestamp(), tracked_from + interval '1 microsecond'),
    closed_reason = $1,
    updated_at = transaction_timestamp()
WHERE id = $2 AND tracked_until IS NULL
RETURNING id, collector_domain_id, site_id, target, tracked_from, tracked_until, tracking_basis, opened_reason, closed_reason, created_at, updated_at
`

type CloseTargetTrackingPeriodParams struct {
	ClosedReason *string `json:"closed_reason"`
	ID           int64   `json:"id"`
}

func (q *Queries) CloseTargetTrackingPeriod(ctx context.Context, arg CloseTargetTrackingPeriodParams) (GfnTargetTrackingPeriod, error) {
	row := q.db.QueryRow(ctx, closeTargetTrackingPeriod, arg.ClosedReason, arg.ID)
	var i GfnTargetTrackingPeriod
	err := row.Scan(
		&i.ID,
		&i.CollectorDomainID,
		&i.SiteID,
		&i.Target,
		&i.TrackedFrom,
		&i.TrackedUntil,
		&i.TrackingBasis,
		&i.OpenedReason,
		&i.ClosedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeTargetTrackingPeriodsBySite = `-- name: CloseTargetTrackingPeriodsBySite :execrows
UPDATE gfn_target_tracking_periods
SET tracked_until = GREATEST(transaction_timestamp(), tracked_from + interval '1 microsecond'),
    closed_reason = $1,
    updated_at = transaction_timestamp()
WHERE site_id = $2 AND tracked_until IS NULL
`

type CloseTargetTrackingPeriodsBySiteParams struct {
	ClosedReason *string `json:"closed_reason"`
	SiteID       int64   `json:"site_id"`
}

func (q *Queries) CloseTargetTrackingPeriodsBySite(ctx context.Context, arg CloseTargetTrackingPeriodsBySiteParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeTargetTrackingPeriodsBySite, arg.ClosedReason, arg.SiteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countConflictingActiveTarget = `-- name: CountConflictingActiveTarget :one
SELECT count(*)::bigint
FROM gfn_target_tracking_periods
WHERE site_id = $1
  AND lower(target) = lower($2::text)
  AND tracked_until IS NULL
  AND ($3::bigint IS NULL
       OR collector_domain_id IS NULL
       OR collector_domain_id <> $3::bigint)
`

type CountConflictingActiveTargetParams struct {
	SiteID          int64  `json:"site_id"`
	Target          string `json:"target"`
	ExcludeDomainID *int64 `json:"exclude_domain_id"`
}

func (q *Queries) CountConflictingActiveTarget(ctx context.Context, arg CountConflictingActiveTargetParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConflictingActiveTarget, arg.SiteID, arg.Target, arg.ExcludeDomainID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getActivePrimaryTarget = `-- name: GetActivePrimaryTarget :one
SELECT primary_period.id,
       primary_period.site_id,
       primary_period.target_tracking_period_id,
       primary_period.basis,
       target_period.collector_domain_id,
       target_period.target
FROM gfn_site_primary_target_periods primary_period
JOIN gfn_target_tracking_periods target_period
  ON target_period.id = primary_period.target_tracking_period_id
WHERE primary_period.site_id = $1
  AND primary_period.effective_until IS NULL
FOR UPDATE OF primary_period
`

type GetActivePrimaryTargetRow struct {
	ID                     int64  `json:"id"`
	SiteID                 int64  `json:"site_id"`
	TargetTrackingPeriodID int64  `json:"target_tracking_period_id"`
	Basis                  string `json:"basis"`
	CollectorDomainID      *int64 `json:"collector_domain_id"`
	Target                 string `json:"target"`
}

func (q *Queries) GetActivePrimaryTarget(ctx context.Context, siteID int64) (GetActivePrimaryTargetRow, error) {
	row := q.db.QueryRow(ctx, getActivePrimaryTarget, siteID)
	var i GetActivePrimaryTargetRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.TargetTrackingPeriodID,
		&i.Basis,
		&i.CollectorDomainID,
		&i.Target,
	)
	return i, err
}

const getActiveTargetPeriodByDomain = `-- name: GetActiveTargetPeriodByDomain :one
SELECT id, collector_domain_id, site_id, target, tracked_from, tracked_until, tracking_basis, opened_reason, closed_reason, created_at, updated_at
FROM gfn_target_tracking_periods
WHERE collector_domain_id = $1
  AND tracked_until IS NULL
FOR UPDATE
`

func (q *Queries) GetActiveTargetPeriodByDomain(ctx context.Context, collectorDomainID *int64) (GfnTargetTrackingPeriod, error) {
	row := q.db.QueryRow(ctx, getActiveTargetPeriodByDomain, collectorDomainID)
	var i GfnTargetTrackingPeriod
	err := row.Scan(
		&i.ID,
		&i.CollectorDomainID,
		&i.SiteID,
		&i.Target,
		&i.TrackedFrom,
		&i.TrackedUntil,
		&i.TrackingBasis,
		&i.OpenedReason,
		&i.ClosedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockCollectorDomainForUpdate = `-- name: LockCollectorDomainForUpdate :one
SELECT id, name, proxy, prefix, tls, site_id, deleted
FROM gfn_collector_domain
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockCollectorDomainForUpdate(ctx context.Context, id int64) (GfnCollectorDomain, error) {
	row := q.db.QueryRow(ctx, lockCollectorDomainForUpdate, id)
	var i GfnCollectorDomain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Proxy,
		&i.Prefix,
		&i.Tls,
		&i.SiteID,
		&i.Deleted,
	)
	return i, err
}

const lockSiteForUpdate = `-- name: LockSiteForUpdate :one
SELECT id, name, name_en, info, info_en, create_time, update_time, country,
       nsfw, welfare, icon, deleted, view_count, deleted_at
FROM gfn_site
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockSiteForUpdate(ctx context.Context, id int64) (GfnSite, error) {
	row := q.db.QueryRow(ctx, lockSiteForUpdate, id)
	var i GfnSite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Country,
		&i.Nsfw,
		&i.Welfare,
		&i.Icon,
		&i.Deleted,
		&i.ViewCount,
		&i.DeletedAt,
	)
	return i, err
}

const openPrimaryTarget = `-- name: OpenPrimaryTarget :one
INSERT INTO gfn_site_primary_target_periods (
    site_id, target_tracking_period_id, effective_from, basis
)
VALUES (
    $1, $2,
    transaction_timestamp(), $3
)
RETURNING id, site_id, target_tracking_period_id, effective_from, effective_until, basis, created_at, updated_at
`

type OpenPrimaryTargetParams struct {
	SiteID                 int64  `json:"site_id"`
	TargetTrackingPeriodID int64  `json:"target_tracking_period_id"`
	Basis                  string `json:"basis"`
}

func (q *Queries) OpenPrimaryTarget(ctx context.Context, arg OpenPrimaryTargetParams) (GfnSitePrimaryTargetPeriod, error) {
	row := q.db.QueryRow(ctx, openPrimaryTarget, arg.SiteID, arg.TargetTrackingPeriodID, arg.Basis)
	var i GfnSitePrimaryTargetPeriod
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.TargetTrackingPeriodID,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Basis,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const openTargetTrackingPeriod = `-- name: OpenTargetTrackingPeriod :one
INSERT INTO gfn_target_tracking_periods (
    collector_domain_id, site_id, target, tracked_from,
    tracking_basis, opened_reason
)
VALUES (
    $1, $2, $3,
    transaction_timestamp(), 'explicit', $4
)
RETURNING id, collector_domain_id, site_id, target, tracked_from, tracked_until, tracking_basis, opened_reason, closed_reason, created_at, updated_at
`

type OpenTargetTrackingPeriodParams struct {
	CollectorDomainID *int64 `json:"collector_domain_id"`
	SiteID            int64  `json:"site_id"`
	Target            string `json:"target"`
	OpenedReason      string `json:"opened_reason"`
}

func (q *Queries) OpenTargetTrackingPeriod(ctx context.Context, arg OpenTargetTrackingPeriodParams) (GfnTargetTrackingPeriod, error) {
	row := q.db.QueryRow(ctx, openTargetTrackingPeriod,
		arg.CollectorDomainID,
		arg.SiteID,
		arg.Target,
		arg.OpenedReason,
	)
	var i GfnTargetTrackingPeriod
	err := row.Scan(
		&i.ID,
		&i.CollectorDomainID,
		&i.SiteID,
		&i.Target,
		&i.TrackedFrom,
		&i.TrackedUntil,
		&i.TrackingBasis,
		&i.OpenedReason,
		&i.ClosedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refreshCurrentSiteDaily = `-- name: RefreshCurrentSiteDaily :exec
SELECT gfn_refresh_current_site_daily($1::bigint)
`

func (q *Queries) RefreshCurrentSiteDaily(ctx context.Context, siteID int64) error {
	_, err := q.db.Exec(ctx, refreshCurrentSiteDaily, siteID)
	return err
}
