// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights.sql

package navsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNavInsightOverviewChanges = `-- name: CountNavInsightOverviewChanges :one
SELECT count(*)::bigint
FROM public.gfn_change_events event
WHERE event.projection_date >= (now() AT TIME ZONE 'UTC')::date - 6
  AND event.detector_key = ANY($1::text[])
  AND event.detector_key || '/' || event.detector_version::text || '/' || event.event_code
      = ANY($2::text[])
`

type CountNavInsightOverviewChangesParams struct {
	DetectorKeys []string `json:"detector_keys"`
	ContractIds  []string `json:"contract_ids"`
}

func (q *Queries) CountNavInsightOverviewChanges(ctx context.Context, arg CountNavInsightOverviewChangesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNavInsightOverviewChanges, arg.DetectorKeys, arg.ContractIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countNavInsightSites = `-- name: CountNavInsightSites :one
SELECT count(*)::bigint
FROM public.gfn_site
WHERE deleted IS NOT TRUE
`

func (q *Queries) CountNavInsightSites(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNavInsightSites)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getNavInsightMetricSummary = `-- name: GetNavInsightMetricSummary :one
WITH latest AS (
    SELECT fact_date, population_count, eligible_count, not_applicable_count,
           positive_count, negative_count, stale_count, not_probed_count,
           probe_failed_count, unknown_count
    FROM public.gfn_metric_daily
    WHERE metric_key = $1
      AND metric_version = $2
      AND dimension_key = 'global'
      AND dimension_value = 'all'
    ORDER BY fact_date DESC
    LIMIT 1
), available AS (
    SELECT min(fact_date)::date AS available_from
    FROM public.gfn_metric_daily
    WHERE metric_key = $1
      AND metric_version = $2
      AND dimension_key = 'global'
      AND dimension_value = 'all'
)
SELECT latest.fact_date,
       latest.population_count,
       latest.eligible_count,
       latest.not_applicable_count,
       latest.positive_count,
       latest.negative_count,
       latest.stale_count,
       latest.not_probed_count,
       latest.probe_failed_count,
       latest.unknown_count,
       previous.positive_count AS previous_positive_count,
       previous.negative_count AS previous_negative_count,
       available.available_from
FROM latest
CROSS JOIN available
LEFT JOIN public.gfn_metric_daily previous
  ON previous.metric_key = $1
 AND previous.metric_version = $2
 AND previous.dimension_key = 'global'
 AND previous.dimension_value = 'all'
 AND previous.fact_date = latest.fact_date - 30
`

type GetNavInsightMetricSummaryParams struct {
	MetricKey     string `json:"metric_key"`
	MetricVersion int32  `json:"metric_version"`
}

type GetNavInsightMetricSummaryRow struct {
	FactDate              pgtype.Date `json:"fact_date"`
	PopulationCount       int64       `json:"population_count"`
	EligibleCount         int64       `json:"eligible_count"`
	NotApplicableCount    int64       `json:"not_applicable_count"`
	PositiveCount         int64       `json:"positive_count"`
	NegativeCount         int64       `json:"negative_count"`
	StaleCount            int64       `json:"stale_count"`
	NotProbedCount        int64       `json:"not_probed_count"`
	ProbeFailedCount      int64       `json:"probe_failed_count"`
	UnknownCount          int64       `json:"unknown_count"`
	PreviousPositiveCount *int64      `json:"previous_positive_count"`
	PreviousNegativeCount *int64      `json:"previous_negative_count"`
	AvailableFrom         pgtype.Date `json:"available_from"`
}

func (q *Queries) GetNavInsightMetricSummary(ctx context.Context, arg GetNavInsightMetricSummaryParams) (GetNavInsightMetricSummaryRow, error) {
	row := q.db.QueryRow(ctx, getNavInsightMetricSummary, arg.MetricKey, arg.MetricVersion)
	var i GetNavInsightMetricSummaryRow
	err := row.Scan(
		&i.FactDate,
		&i.PopulationCount,
		&i.EligibleCount,
		&i.NotApplicableCount,
		&i.PositiveCount,
		&i.NegativeCount,
		&i.StaleCount,
		&i.NotProbedCount,
		&i.ProbeFailedCount,
		&i.UnknownCount,
		&i.PreviousPositiveCount,
		&i.PreviousNegativeCount,
		&i.AvailableFrom,
	)
	return i, err
}

const getNavInsightSite = `-- name: GetNavInsightSite :one
SELECT id, name, name_en
FROM public.gfn_site
WHERE id = $1
  AND deleted IS NOT TRUE
`

type GetNavInsightSiteRow struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	NameEn string `json:"name_en"`
}

func (q *Queries) GetNavInsightSite(ctx context.Context, siteID int64) (GetNavInsightSiteRow, error) {
	row := q.db.QueryRow(ctx, getNavInsightSite, siteID)
	var i GetNavInsightSiteRow
	err := row.Scan(&i.ID, &i.Name, &i.NameEn)
	return i, err
}

const getNavInsightSiteMetric = `-- name: GetNavInsightSiteMetric :one
SELECT entity.fact_date,
       entity.state,
       global.eligible_count,
       global.positive_count,
       global.negative_count
FROM public.gfn_metric_entity_daily entity
JOIN public.gfn_metric_daily global
  ON global.metric_key = entity.metric_key
 AND global.metric_version = entity.metric_version
 AND global.fact_date = entity.fact_date
 AND global.dimension_key = 'global'
 AND global.dimension_value = 'all'
WHERE entity.metric_key = $1
  AND entity.metric_version = $2
  AND entity.site_id = $3
ORDER BY entity.fact_date DESC
LIMIT 1
`

type GetNavInsightSiteMetricParams struct {
	MetricKey     string `json:"metric_key"`
	MetricVersion int32  `json:"metric_version"`
	SiteID        int64  `json:"site_id"`
}

type GetNavInsightSiteMetricRow struct {
	FactDate      pgtype.Date `json:"fact_date"`
	State         string      `json:"state"`
	EligibleCount int64       `json:"eligible_count"`
	PositiveCount int64       `json:"positive_count"`
	NegativeCount int64       `json:"negative_count"`
}

func (q *Queries) GetNavInsightSiteMetric(ctx context.Context, arg GetNavInsightSiteMetricParams) (GetNavInsightSiteMetricRow, error) {
	row := q.db.QueryRow(ctx, getNavInsightSiteMetric, arg.MetricKey, arg.MetricVersion, arg.SiteID)
	var i GetNavInsightSiteMetricRow
	err := row.Scan(
		&i.FactDate,
		&i.State,
		&i.EligibleCount,
		&i.PositiveCount,
		&i.NegativeCount,
	)
	return i, err
}

const listNavInsightMetricTrend = `-- name: ListNavInsightMetricTrend :many
WITH latest AS (
    SELECT max(fact_date)::date AS fact_date
    FROM public.gfn_metric_daily
    WHERE metric_key = $1
      AND metric_version = $2
      AND dimension_key = 'global'
      AND dimension_value = 'all'
)
SELECT daily.fact_date,
       daily.eligible_count,
       daily.positive_count,
       daily.negative_count
FROM public.gfn_metric_daily daily
CROSS JOIN latest
WHERE daily.metric_key = $1
  AND daily.metric_version = $2
  AND daily.dimension_key = 'global'
  AND daily.dimension_value = 'all'
  AND (
      $3::integer = 0
      OR daily.fact_date >= latest.fact_date - ($3::integer - 1)
  )
ORDER BY daily.fact_date
`

type ListNavInsightMetricTrendParams struct {
	MetricKey     string `json:"metric_key"`
	MetricVersion int32  `json:"metric_version"`
	RangeDays     int32  `json:"range_days"`
}

type ListNavInsightMetricTrendRow struct {
	FactDate      pgtype.Date `json:"fact_date"`
	EligibleCount int64       `json:"eligible_count"`
	PositiveCount int64       `json:"positive_count"`
	NegativeCount int64       `json:"negative_count"`
}

func (q *Queries) ListNavInsightMetricTrend(ctx context.Context, arg ListNavInsightMetricTrendParams) ([]ListNavInsightMetricTrendRow, error) {
	rows, err := q.db.Query(ctx, listNavInsightMetricTrend, arg.MetricKey, arg.MetricVersion, arg.RangeDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavInsightMetricTrendRow{}
	for rows.Next() {
		var i ListNavInsightMetricTrendRow
		if err := rows.Scan(
			&i.FactDate,
			&i.EligibleCount,
			&i.PositiveCount,
			&i.NegativeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavInsightOverviewChanges = `-- name: ListNavInsightOverviewChanges :many
WITH newest AS (
    SELECT DISTINCT ON (event.site_id)
           event.site_id,
           event.detector_key,
           event.detector_version,
           event.event_code,
           event.projection_date,
           event.time_basis,
           event.event_at,
           event.event_key
    FROM public.gfn_change_events event
    WHERE event.detector_key = ANY($2::text[])
      AND event.detector_key || '/' || event.detector_version::text || '/' || event.event_code
          = ANY($3::text[])
    ORDER BY event.site_id, event.projection_date DESC,
             event.event_at DESC NULLS LAST, event.event_key DESC
)
SELECT newest.site_id,
       COALESCE(NULLIF(history.name, ''), NULLIF(site.name, ''), '')::text AS site_name,
       newest.detector_key,
       newest.detector_version,
       newest.event_code,
       newest.projection_date,
       newest.time_basis,
       newest.event_at
FROM newest
LEFT JOIN public.gfn_site_daily history
  ON history.site_id = newest.site_id
 AND history.fact_date = newest.projection_date
LEFT JOIN public.gfn_site site ON site.id = newest.site_id
ORDER BY newest.projection_date DESC,
         newest.event_at DESC NULLS LAST,
         newest.site_id DESC
LIMIT $1
`

type ListNavInsightOverviewChangesParams struct {
	LimitCount   int32    `json:"limit_count"`
	DetectorKeys []string `json:"detector_keys"`
	ContractIds  []string `json:"contract_ids"`
}

type ListNavInsightOverviewChangesRow struct {
	SiteID          int64              `json:"site_id"`
	SiteName        string             `json:"site_name"`
	DetectorKey     string             `json:"detector_key"`
	DetectorVersion int32              `json:"detector_version"`
	EventCode       string             `json:"event_code"`
	ProjectionDate  pgtype.Date        `json:"projection_date"`
	TimeBasis       string             `json:"time_basis"`
	EventAt         pgtype.Timestamptz `json:"event_at"`
}

func (q *Queries) ListNavInsightOverviewChanges(ctx context.Context, arg ListNavInsightOverviewChangesParams) ([]ListNavInsightOverviewChangesRow, error) {
	rows, err := q.db.Query(ctx, listNavInsightOverviewChanges, arg.LimitCount, arg.DetectorKeys, arg.ContractIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavInsightOverviewChangesRow{}
	for rows.Next() {
		var i ListNavInsightOverviewChangesRow
		if err := rows.Scan(
			&i.SiteID,
			&i.SiteName,
			&i.DetectorKey,
			&i.DetectorVersion,
			&i.EventCode,
			&i.ProjectionDate,
			&i.TimeBasis,
			&i.EventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavInsightSiteChanges = `-- name: ListNavInsightSiteChanges :many
SELECT event.detector_key,
       event.detector_version,
       event.event_code,
       event.projection_date,
       event.time_basis,
       event.event_at
FROM public.gfn_change_events event
WHERE event.site_id = $1
  AND event.detector_key = ANY($2::text[])
  AND event.detector_key || '/' || event.detector_version::text || '/' || event.event_code
      = ANY($3::text[])
ORDER BY event.projection_date DESC,
         event.event_at DESC NULLS LAST,
         event.event_key DESC
LIMIT $4
`

type ListNavInsightSiteChangesParams struct {
	SiteID       int64    `json:"site_id"`
	DetectorKeys []string `json:"detector_keys"`
	ContractIds  []string `json:"contract_ids"`
	LimitCount   int32    `json:"limit_count"`
}

type ListNavInsightSiteChangesRow struct {
	DetectorKey     string             `json:"detector_key"`
	DetectorVersion int32              `json:"detector_version"`
	EventCode       string             `json:"event_code"`
	ProjectionDate  pgtype.Date        `json:"projection_date"`
	TimeBasis       string             `json:"time_basis"`
	EventAt         pgtype.Timestamptz `json:"event_at"`
}

func (q *Queries) ListNavInsightSiteChanges(ctx context.Context, arg ListNavInsightSiteChangesParams) ([]ListNavInsightSiteChangesRow, error) {
	rows, err := q.db.Query(ctx, listNavInsightSiteChanges,
		arg.SiteID,
		arg.DetectorKeys,
		arg.ContractIds,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavInsightSiteChangesRow{}
	for rows.Next() {
		var i ListNavInsightSiteChangesRow
		if err := rows.Scan(
			&i.DetectorKey,
			&i.DetectorVersion,
			&i.EventCode,
			&i.ProjectionDate,
			&i.TimeBasis,
			&i.EventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
