// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights.sql

package navsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNavInsightOverviewChanges = `-- name: CountNavInsightOverviewChanges :one
SELECT count(*)::bigint
FROM public.gfn_change_events event
WHERE event.projection_date >= (now() AT TIME ZONE 'UTC')::date - 6
  AND event.detector_key = ANY($1::text[])
  AND event.detector_key || '/' || event.detector_version::text || '/' || event.event_code
      = ANY($2::text[])
`

type CountNavInsightOverviewChangesParams struct {
	DetectorKeys []string `json:"detector_keys"`
	ContractIds  []string `json:"contract_ids"`
}

func (q *Queries) CountNavInsightOverviewChanges(ctx context.Context, arg CountNavInsightOverviewChangesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNavInsightOverviewChanges, arg.DetectorKeys, arg.ContractIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countNavInsightSites = `-- name: CountNavInsightSites :one
SELECT count(*)::bigint
FROM public.gfn_site
WHERE deleted IS NOT TRUE
`

func (q *Queries) CountNavInsightSites(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNavInsightSites)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getNavInsightMetricSliceAvailability = `-- name: GetNavInsightMetricSliceAvailability :one
WITH available AS (
    SELECT min(fact_date)::date AS available_from,
           max(fact_date)::date AS available_through
    FROM public.gfn_metric_daily
    WHERE metric_key = $3
      AND metric_version = $4
      AND dimension_key = $1
      AND dimension_value = $2
)
SELECT available.available_from,
       available.available_through,
       COALESCE(CASE WHEN $1::text = 'group_id' THEN site_group.name END, '')::text AS label,
       COALESCE(CASE WHEN $1::text = 'group_id' THEN site_group.name_en END, '')::text AS label_en
FROM available
LEFT JOIN public.gfn_site_group site_group
  ON $1::text = 'group_id'
 AND site_group.id::text = $2::text
`

type GetNavInsightMetricSliceAvailabilityParams struct {
	DimensionKey   string `json:"dimension_key"`
	DimensionValue string `json:"dimension_value"`
	MetricKey      string `json:"metric_key"`
	MetricVersion  int32  `json:"metric_version"`
}

type GetNavInsightMetricSliceAvailabilityRow struct {
	AvailableFrom    pgtype.Date `json:"available_from"`
	AvailableThrough pgtype.Date `json:"available_through"`
	Label            string      `json:"label"`
	LabelEn          string      `json:"label_en"`
}

func (q *Queries) GetNavInsightMetricSliceAvailability(ctx context.Context, arg GetNavInsightMetricSliceAvailabilityParams) (GetNavInsightMetricSliceAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, getNavInsightMetricSliceAvailability,
		arg.DimensionKey,
		arg.DimensionValue,
		arg.MetricKey,
		arg.MetricVersion,
	)
	var i GetNavInsightMetricSliceAvailabilityRow
	err := row.Scan(
		&i.AvailableFrom,
		&i.AvailableThrough,
		&i.Label,
		&i.LabelEn,
	)
	return i, err
}

const getNavInsightMetricSummary = `-- name: GetNavInsightMetricSummary :one
WITH latest AS (
    SELECT fact_date, population_count, eligible_count, not_applicable_count,
           positive_count, negative_count, stale_count, not_probed_count,
           probe_failed_count, unknown_count
    FROM public.gfn_metric_daily
    WHERE metric_key = $1
      AND metric_version = $2
      AND dimension_key = 'global'
      AND dimension_value = 'all'
    ORDER BY fact_date DESC
    LIMIT 1
), available AS (
    SELECT min(fact_date)::date AS available_from
    FROM public.gfn_metric_daily
    WHERE metric_key = $1
      AND metric_version = $2
      AND dimension_key = 'global'
      AND dimension_value = 'all'
)
SELECT latest.fact_date,
       latest.population_count,
       latest.eligible_count,
       latest.not_applicable_count,
       latest.positive_count,
       latest.negative_count,
       latest.stale_count,
       latest.not_probed_count,
       latest.probe_failed_count,
       latest.unknown_count,
       previous.positive_count AS previous_positive_count,
       previous.negative_count AS previous_negative_count,
       available.available_from
FROM latest
CROSS JOIN available
LEFT JOIN public.gfn_metric_daily previous
  ON previous.metric_key = $1
 AND previous.metric_version = $2
 AND previous.dimension_key = 'global'
 AND previous.dimension_value = 'all'
 AND previous.fact_date = latest.fact_date - 30
`

type GetNavInsightMetricSummaryParams struct {
	MetricKey     string `json:"metric_key"`
	MetricVersion int32  `json:"metric_version"`
}

type GetNavInsightMetricSummaryRow struct {
	FactDate              pgtype.Date `json:"fact_date"`
	PopulationCount       int64       `json:"population_count"`
	EligibleCount         int64       `json:"eligible_count"`
	NotApplicableCount    int64       `json:"not_applicable_count"`
	PositiveCount         int64       `json:"positive_count"`
	NegativeCount         int64       `json:"negative_count"`
	StaleCount            int64       `json:"stale_count"`
	NotProbedCount        int64       `json:"not_probed_count"`
	ProbeFailedCount      int64       `json:"probe_failed_count"`
	UnknownCount          int64       `json:"unknown_count"`
	PreviousPositiveCount *int64      `json:"previous_positive_count"`
	PreviousNegativeCount *int64      `json:"previous_negative_count"`
	AvailableFrom         pgtype.Date `json:"available_from"`
}

func (q *Queries) GetNavInsightMetricSummary(ctx context.Context, arg GetNavInsightMetricSummaryParams) (GetNavInsightMetricSummaryRow, error) {
	row := q.db.QueryRow(ctx, getNavInsightMetricSummary, arg.MetricKey, arg.MetricVersion)
	var i GetNavInsightMetricSummaryRow
	err := row.Scan(
		&i.FactDate,
		&i.PopulationCount,
		&i.EligibleCount,
		&i.NotApplicableCount,
		&i.PositiveCount,
		&i.NegativeCount,
		&i.StaleCount,
		&i.NotProbedCount,
		&i.ProbeFailedCount,
		&i.UnknownCount,
		&i.PreviousPositiveCount,
		&i.PreviousNegativeCount,
		&i.AvailableFrom,
	)
	return i, err
}

const getNavInsightSite = `-- name: GetNavInsightSite :one
SELECT id, name, name_en
FROM public.gfn_site
WHERE id = $1
  AND deleted IS NOT TRUE
`

type GetNavInsightSiteRow struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	NameEn string `json:"name_en"`
}

func (q *Queries) GetNavInsightSite(ctx context.Context, siteID int64) (GetNavInsightSiteRow, error) {
	row := q.db.QueryRow(ctx, getNavInsightSite, siteID)
	var i GetNavInsightSiteRow
	err := row.Scan(&i.ID, &i.Name, &i.NameEn)
	return i, err
}

const getNavInsightSiteMetric = `-- name: GetNavInsightSiteMetric :one
SELECT entity.fact_date,
       entity.state,
       global.eligible_count,
       global.positive_count,
       global.negative_count
FROM public.gfn_metric_entity_daily entity
JOIN public.gfn_metric_daily global
  ON global.metric_key = entity.metric_key
 AND global.metric_version = entity.metric_version
 AND global.fact_date = entity.fact_date
 AND global.dimension_key = 'global'
 AND global.dimension_value = 'all'
WHERE entity.metric_key = $1
  AND entity.metric_version = $2
  AND entity.site_id = $3
ORDER BY entity.fact_date DESC
LIMIT 1
`

type GetNavInsightSiteMetricParams struct {
	MetricKey     string `json:"metric_key"`
	MetricVersion int32  `json:"metric_version"`
	SiteID        int64  `json:"site_id"`
}

type GetNavInsightSiteMetricRow struct {
	FactDate      pgtype.Date `json:"fact_date"`
	State         string      `json:"state"`
	EligibleCount int64       `json:"eligible_count"`
	PositiveCount int64       `json:"positive_count"`
	NegativeCount int64       `json:"negative_count"`
}

func (q *Queries) GetNavInsightSiteMetric(ctx context.Context, arg GetNavInsightSiteMetricParams) (GetNavInsightSiteMetricRow, error) {
	row := q.db.QueryRow(ctx, getNavInsightSiteMetric, arg.MetricKey, arg.MetricVersion, arg.SiteID)
	var i GetNavInsightSiteMetricRow
	err := row.Scan(
		&i.FactDate,
		&i.State,
		&i.EligibleCount,
		&i.PositiveCount,
		&i.NegativeCount,
	)
	return i, err
}

const listNavInsightExplorerChanges = `-- name: ListNavInsightExplorerChanges :many
SELECT event.site_id,
       COALESCE(NULLIF(history.name, ''), NULLIF(site.name, ''), '')::text AS site_name,
       event.detector_key,
       event.detector_version,
       event.event_code,
       event.projection_date,
       event.time_basis,
       event.event_at,
       CASE WHEN event.time_basis = 'day' THEN 0 ELSE 1 END::integer AS precision_rank,
       CASE
           WHEN event.time_basis = 'day' THEN event.projection_date::timestamp AT TIME ZONE 'UTC'
           ELSE event.event_at
       END::timestamptz AS event_sort_at,
       md5(event.event_key)::text AS opaque_tie
FROM public.gfn_change_events event
LEFT JOIN public.gfn_site_daily history
  ON history.site_id = event.site_id
 AND history.fact_date = event.projection_date
LEFT JOIN public.gfn_site site ON site.id = event.site_id
WHERE event.detector_key = ANY($1::text[])
  AND event.detector_key || '/' || event.detector_version::text || '/' || event.event_code
      = ANY($2::text[])
  AND event.projection_date <= $3::date
  AND (
      $4::integer = 0
      OR event.projection_date >= $3::date - ($4::integer - 1)
  )
  AND (
      NOT $5::boolean
      OR (
          event.projection_date,
          CASE WHEN event.time_basis = 'day' THEN 0 ELSE 1 END,
          CASE
              WHEN event.time_basis = 'day' THEN event.projection_date::timestamp AT TIME ZONE 'UTC'
              ELSE event.event_at
          END,
          md5(event.event_key)
      ) < (
          $6::date,
          $7::integer,
          $8::timestamptz,
          $9::text
      )
  )
ORDER BY event.projection_date DESC,
         precision_rank DESC,
         event_sort_at DESC,
         opaque_tie DESC
LIMIT $10
`

type ListNavInsightExplorerChangesParams struct {
	DetectorKeys   []string           `json:"detector_keys"`
	ContractIds    []string           `json:"contract_ids"`
	RangeThrough   pgtype.Date        `json:"range_through"`
	RangeDays      int32              `json:"range_days"`
	HasPosition    bool               `json:"has_position"`
	PositionDate   pgtype.Date        `json:"position_date"`
	PositionRank   int32              `json:"position_rank"`
	PositionSortAt pgtype.Timestamptz `json:"position_sort_at"`
	PositionTie    string             `json:"position_tie"`
	LimitCount     int32              `json:"limit_count"`
}

type ListNavInsightExplorerChangesRow struct {
	SiteID          int64              `json:"site_id"`
	SiteName        string             `json:"site_name"`
	DetectorKey     string             `json:"detector_key"`
	DetectorVersion int32              `json:"detector_version"`
	EventCode       string             `json:"event_code"`
	ProjectionDate  pgtype.Date        `json:"projection_date"`
	TimeBasis       string             `json:"time_basis"`
	EventAt         pgtype.Timestamptz `json:"event_at"`
	PrecisionRank   int32              `json:"precision_rank"`
	EventSortAt     pgtype.Timestamptz `json:"event_sort_at"`
	OpaqueTie       string             `json:"opaque_tie"`
}

func (q *Queries) ListNavInsightExplorerChanges(ctx context.Context, arg ListNavInsightExplorerChangesParams) ([]ListNavInsightExplorerChangesRow, error) {
	rows, err := q.db.Query(ctx, listNavInsightExplorerChanges,
		arg.DetectorKeys,
		arg.ContractIds,
		arg.RangeThrough,
		arg.RangeDays,
		arg.HasPosition,
		arg.PositionDate,
		arg.PositionRank,
		arg.PositionSortAt,
		arg.PositionTie,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavInsightExplorerChangesRow{}
	for rows.Next() {
		var i ListNavInsightExplorerChangesRow
		if err := rows.Scan(
			&i.SiteID,
			&i.SiteName,
			&i.DetectorKey,
			&i.DetectorVersion,
			&i.EventCode,
			&i.ProjectionDate,
			&i.TimeBasis,
			&i.EventAt,
			&i.PrecisionRank,
			&i.EventSortAt,
			&i.OpaqueTie,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavInsightMetricBreakdown = `-- name: ListNavInsightMetricBreakdown :many
SELECT daily.dimension_value,
       COALESCE(CASE WHEN daily.dimension_key = 'group_id' THEN site_group.name END, '')::text AS label,
       COALESCE(CASE WHEN daily.dimension_key = 'group_id' THEN site_group.name_en END, '')::text AS label_en,
       daily.population_count,
       daily.eligible_count,
       daily.positive_count,
       daily.negative_count
FROM public.gfn_metric_daily daily
LEFT JOIN public.gfn_site_group site_group
  ON daily.dimension_key = 'group_id'
 AND site_group.id::text = daily.dimension_value
WHERE daily.metric_key = $1
  AND daily.metric_version = $2
  AND daily.fact_date = $3::date
  AND daily.dimension_key = $4
ORDER BY daily.eligible_count DESC, daily.dimension_value ASC
`

type ListNavInsightMetricBreakdownParams struct {
	MetricKey     string      `json:"metric_key"`
	MetricVersion int32       `json:"metric_version"`
	FactDate      pgtype.Date `json:"fact_date"`
	DimensionKey  string      `json:"dimension_key"`
}

type ListNavInsightMetricBreakdownRow struct {
	DimensionValue  string `json:"dimension_value"`
	Label           string `json:"label"`
	LabelEn         string `json:"label_en"`
	PopulationCount int64  `json:"population_count"`
	EligibleCount   int64  `json:"eligible_count"`
	PositiveCount   int64  `json:"positive_count"`
	NegativeCount   int64  `json:"negative_count"`
}

func (q *Queries) ListNavInsightMetricBreakdown(ctx context.Context, arg ListNavInsightMetricBreakdownParams) ([]ListNavInsightMetricBreakdownRow, error) {
	rows, err := q.db.Query(ctx, listNavInsightMetricBreakdown,
		arg.MetricKey,
		arg.MetricVersion,
		arg.FactDate,
		arg.DimensionKey,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavInsightMetricBreakdownRow{}
	for rows.Next() {
		var i ListNavInsightMetricBreakdownRow
		if err := rows.Scan(
			&i.DimensionValue,
			&i.Label,
			&i.LabelEn,
			&i.PopulationCount,
			&i.EligibleCount,
			&i.PositiveCount,
			&i.NegativeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavInsightMetricSliceTrend = `-- name: ListNavInsightMetricSliceTrend :many
SELECT daily.fact_date,
       daily.population_count,
       daily.eligible_count,
       daily.positive_count,
       daily.negative_count
FROM public.gfn_metric_daily daily
WHERE daily.metric_key = $1
  AND daily.metric_version = $2
  AND daily.dimension_key = $3
  AND daily.dimension_value = $4
  AND daily.fact_date <= $5::date
  AND (
      $6::integer = 0
      OR daily.fact_date >= $5::date - ($6::integer - 1)
  )
ORDER BY daily.fact_date
`

type ListNavInsightMetricSliceTrendParams struct {
	MetricKey      string      `json:"metric_key"`
	MetricVersion  int32       `json:"metric_version"`
	DimensionKey   string      `json:"dimension_key"`
	DimensionValue string      `json:"dimension_value"`
	ThroughDate    pgtype.Date `json:"through_date"`
	RangeDays      int32       `json:"range_days"`
}

type ListNavInsightMetricSliceTrendRow struct {
	FactDate        pgtype.Date `json:"fact_date"`
	PopulationCount int64       `json:"population_count"`
	EligibleCount   int64       `json:"eligible_count"`
	PositiveCount   int64       `json:"positive_count"`
	NegativeCount   int64       `json:"negative_count"`
}

func (q *Queries) ListNavInsightMetricSliceTrend(ctx context.Context, arg ListNavInsightMetricSliceTrendParams) ([]ListNavInsightMetricSliceTrendRow, error) {
	rows, err := q.db.Query(ctx, listNavInsightMetricSliceTrend,
		arg.MetricKey,
		arg.MetricVersion,
		arg.DimensionKey,
		arg.DimensionValue,
		arg.ThroughDate,
		arg.RangeDays,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavInsightMetricSliceTrendRow{}
	for rows.Next() {
		var i ListNavInsightMetricSliceTrendRow
		if err := rows.Scan(
			&i.FactDate,
			&i.PopulationCount,
			&i.EligibleCount,
			&i.PositiveCount,
			&i.NegativeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavInsightMetricTrend = `-- name: ListNavInsightMetricTrend :many
WITH latest AS (
    SELECT max(fact_date)::date AS fact_date
    FROM public.gfn_metric_daily
    WHERE metric_key = $1
      AND metric_version = $2
      AND dimension_key = 'global'
      AND dimension_value = 'all'
)
SELECT daily.fact_date,
       daily.eligible_count,
       daily.positive_count,
       daily.negative_count
FROM public.gfn_metric_daily daily
CROSS JOIN latest
WHERE daily.metric_key = $1
  AND daily.metric_version = $2
  AND daily.dimension_key = 'global'
  AND daily.dimension_value = 'all'
  AND (
      $3::integer = 0
      OR daily.fact_date >= latest.fact_date - ($3::integer - 1)
  )
ORDER BY daily.fact_date
`

type ListNavInsightMetricTrendParams struct {
	MetricKey     string `json:"metric_key"`
	MetricVersion int32  `json:"metric_version"`
	RangeDays     int32  `json:"range_days"`
}

type ListNavInsightMetricTrendRow struct {
	FactDate      pgtype.Date `json:"fact_date"`
	EligibleCount int64       `json:"eligible_count"`
	PositiveCount int64       `json:"positive_count"`
	NegativeCount int64       `json:"negative_count"`
}

func (q *Queries) ListNavInsightMetricTrend(ctx context.Context, arg ListNavInsightMetricTrendParams) ([]ListNavInsightMetricTrendRow, error) {
	rows, err := q.db.Query(ctx, listNavInsightMetricTrend, arg.MetricKey, arg.MetricVersion, arg.RangeDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavInsightMetricTrendRow{}
	for rows.Next() {
		var i ListNavInsightMetricTrendRow
		if err := rows.Scan(
			&i.FactDate,
			&i.EligibleCount,
			&i.PositiveCount,
			&i.NegativeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavInsightOverviewChanges = `-- name: ListNavInsightOverviewChanges :many
WITH newest AS (
    SELECT DISTINCT ON (event.site_id)
           event.site_id,
           event.detector_key,
           event.detector_version,
           event.event_code,
           event.projection_date,
           event.time_basis,
           event.event_at,
           event.event_key
    FROM public.gfn_change_events event
    WHERE event.detector_key = ANY($2::text[])
      AND event.detector_key || '/' || event.detector_version::text || '/' || event.event_code
          = ANY($3::text[])
    ORDER BY event.site_id, event.projection_date DESC,
             event.event_at DESC NULLS LAST, event.event_key DESC
)
SELECT newest.site_id,
       COALESCE(NULLIF(history.name, ''), NULLIF(site.name, ''), '')::text AS site_name,
       newest.detector_key,
       newest.detector_version,
       newest.event_code,
       newest.projection_date,
       newest.time_basis,
       newest.event_at
FROM newest
LEFT JOIN public.gfn_site_daily history
  ON history.site_id = newest.site_id
 AND history.fact_date = newest.projection_date
LEFT JOIN public.gfn_site site ON site.id = newest.site_id
ORDER BY newest.projection_date DESC,
         newest.event_at DESC NULLS LAST,
         newest.site_id DESC
LIMIT $1
`

type ListNavInsightOverviewChangesParams struct {
	LimitCount   int32    `json:"limit_count"`
	DetectorKeys []string `json:"detector_keys"`
	ContractIds  []string `json:"contract_ids"`
}

type ListNavInsightOverviewChangesRow struct {
	SiteID          int64              `json:"site_id"`
	SiteName        string             `json:"site_name"`
	DetectorKey     string             `json:"detector_key"`
	DetectorVersion int32              `json:"detector_version"`
	EventCode       string             `json:"event_code"`
	ProjectionDate  pgtype.Date        `json:"projection_date"`
	TimeBasis       string             `json:"time_basis"`
	EventAt         pgtype.Timestamptz `json:"event_at"`
}

func (q *Queries) ListNavInsightOverviewChanges(ctx context.Context, arg ListNavInsightOverviewChangesParams) ([]ListNavInsightOverviewChangesRow, error) {
	rows, err := q.db.Query(ctx, listNavInsightOverviewChanges, arg.LimitCount, arg.DetectorKeys, arg.ContractIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavInsightOverviewChangesRow{}
	for rows.Next() {
		var i ListNavInsightOverviewChangesRow
		if err := rows.Scan(
			&i.SiteID,
			&i.SiteName,
			&i.DetectorKey,
			&i.DetectorVersion,
			&i.EventCode,
			&i.ProjectionDate,
			&i.TimeBasis,
			&i.EventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavInsightSiteChanges = `-- name: ListNavInsightSiteChanges :many
SELECT event.detector_key,
       event.detector_version,
       event.event_code,
       event.projection_date,
       event.time_basis,
       event.event_at
FROM public.gfn_change_events event
WHERE event.site_id = $1
  AND event.detector_key = ANY($2::text[])
  AND event.detector_key || '/' || event.detector_version::text || '/' || event.event_code
      = ANY($3::text[])
ORDER BY event.projection_date DESC,
         event.event_at DESC NULLS LAST,
         event.event_key DESC
LIMIT $4
`

type ListNavInsightSiteChangesParams struct {
	SiteID       int64    `json:"site_id"`
	DetectorKeys []string `json:"detector_keys"`
	ContractIds  []string `json:"contract_ids"`
	LimitCount   int32    `json:"limit_count"`
}

type ListNavInsightSiteChangesRow struct {
	DetectorKey     string             `json:"detector_key"`
	DetectorVersion int32              `json:"detector_version"`
	EventCode       string             `json:"event_code"`
	ProjectionDate  pgtype.Date        `json:"projection_date"`
	TimeBasis       string             `json:"time_basis"`
	EventAt         pgtype.Timestamptz `json:"event_at"`
}

func (q *Queries) ListNavInsightSiteChanges(ctx context.Context, arg ListNavInsightSiteChangesParams) ([]ListNavInsightSiteChangesRow, error) {
	rows, err := q.db.Query(ctx, listNavInsightSiteChanges,
		arg.SiteID,
		arg.DetectorKeys,
		arg.ContractIds,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavInsightSiteChangesRow{}
	for rows.Next() {
		var i ListNavInsightSiteChangesRow
		if err := rows.Scan(
			&i.DetectorKey,
			&i.DetectorVersion,
			&i.EventCode,
			&i.ProjectionDate,
			&i.TimeBasis,
			&i.EventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
