// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collection_control.sql

package navsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextNavCollectionJob = `-- name: ClaimNextNavCollectionJob :one
WITH candidate AS (
    SELECT queued.id
    FROM gfn_collection_jobs queued
    WHERE queued.status = 'queued'
      AND (queued.scheduled_for IS NULL OR queued.scheduled_for <= now())
      AND NOT EXISTS (
          SELECT 1 FROM gfn_collection_jobs active
          WHERE active.status = 'running'
            AND active.concurrency_key = queued.concurrency_key
      )
    ORDER BY queued.priority DESC, queued.created_at ASC, queued.id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE gfn_collection_jobs job
SET status = 'running', claimed_by = $1,
    lease_until = now() + $2::bigint * interval '1 second',
    updated_at = now()
FROM candidate
WHERE job.id = candidate.id
RETURNING job.id, job.schedule_id, job.schedule_version, job.job_key, job.trigger, job.scope_type, job.scope_id, job.target, job.tasks, job.priority, job.concurrency_key, job.scheduled_for, job.status, job.requested_by, job.dedupe_key, job.claimed_by, job.lease_until, job.cancel_requested_at, job.created_at, job.updated_at, job.completed_at
`

type ClaimNextNavCollectionJobParams struct {
	InstanceID   *string `json:"instance_id"`
	LeaseSeconds int64   `json:"lease_seconds"`
}

func (q *Queries) ClaimNextNavCollectionJob(ctx context.Context, arg ClaimNextNavCollectionJobParams) (GfnCollectionJob, error) {
	row := q.db.QueryRow(ctx, claimNextNavCollectionJob, arg.InstanceID, arg.LeaseSeconds)
	var i GfnCollectionJob
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.ScheduleVersion,
		&i.JobKey,
		&i.Trigger,
		&i.ScopeType,
		&i.ScopeID,
		&i.Target,
		&i.Tasks,
		&i.Priority,
		&i.ConcurrencyKey,
		&i.ScheduledFor,
		&i.Status,
		&i.RequestedBy,
		&i.DedupeKey,
		&i.ClaimedBy,
		&i.LeaseUntil,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteNavCollectionTaskResultsOlderThan = `-- name: DeleteNavCollectionTaskResultsOlderThan :execrows
DELETE FROM gfn_collection_task_results
WHERE started_at < now() - $1::bigint * interval '1 day'
`

func (q *Queries) DeleteNavCollectionTaskResultsOlderThan(ctx context.Context, retentionDays int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNavCollectionTaskResultsOlderThan, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureNavCollectionSchedule = `-- name: EnsureNavCollectionSchedule :exec
INSERT INTO gfn_collection_schedules (
    job_key, name, enabled, schedule_kind, cron_expression, interval_seconds,
    anchor_at, timezone, misfire_policy, misfire_grace_seconds, overlap_policy,
    priority, concurrency_key, effective_from, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    'skip', $11, $12, now(), now(), now()
)
ON CONFLICT (job_key) DO NOTHING
`

type EnsureNavCollectionScheduleParams struct {
	JobKey              string             `json:"job_key"`
	Name                string             `json:"name"`
	Enabled             bool               `json:"enabled"`
	ScheduleKind        string             `json:"schedule_kind"`
	CronExpression      *string            `json:"cron_expression"`
	IntervalSeconds     *int64             `json:"interval_seconds"`
	AnchorAt            pgtype.Timestamptz `json:"anchor_at"`
	Timezone            string             `json:"timezone"`
	MisfirePolicy       string             `json:"misfire_policy"`
	MisfireGraceSeconds int32              `json:"misfire_grace_seconds"`
	Priority            int32              `json:"priority"`
	ConcurrencyKey      string             `json:"concurrency_key"`
}

func (q *Queries) EnsureNavCollectionSchedule(ctx context.Context, arg EnsureNavCollectionScheduleParams) error {
	_, err := q.db.Exec(ctx, ensureNavCollectionSchedule,
		arg.JobKey,
		arg.Name,
		arg.Enabled,
		arg.ScheduleKind,
		arg.CronExpression,
		arg.IntervalSeconds,
		arg.AnchorAt,
		arg.Timezone,
		arg.MisfirePolicy,
		arg.MisfireGraceSeconds,
		arg.Priority,
		arg.ConcurrencyKey,
	)
	return err
}

const failLostNavCollectionJob = `-- name: FailLostNavCollectionJob :execrows
UPDATE gfn_collection_jobs
SET status = 'failed', completed_at = now(), updated_at = now(), lease_until = NULL
WHERE id = $1 AND status = 'running'
`

func (q *Queries) FailLostNavCollectionJob(ctx context.Context, jobID int64) (int64, error) {
	result, err := q.db.Exec(ctx, failLostNavCollectionJob, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failLostNavCollectionRun = `-- name: FailLostNavCollectionRun :execrows
UPDATE gfn_collection_runs
SET status = 'failed', ended_at = now(),
    duration_ms = GREATEST(0, (extract(epoch FROM (now() - started_at)) * 1000)::bigint),
    error_kind = 'worker_lost', error_message = 'Collector lease expired.'
WHERE id = $1 AND status = 'running'
`

func (q *Queries) FailLostNavCollectionRun(ctx context.Context, runID string) (int64, error) {
	result, err := q.db.Exec(ctx, failLostNavCollectionRun, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeNavCollectionJob = `-- name: FinalizeNavCollectionJob :execrows
UPDATE gfn_collection_jobs
SET status = $1, completed_at = now(), updated_at = now(), lease_until = NULL
WHERE id = $2 AND claimed_by = $3 AND status = 'running'
`

type FinalizeNavCollectionJobParams struct {
	Status     string  `json:"status"`
	ID         int64   `json:"id"`
	InstanceID *string `json:"instance_id"`
}

func (q *Queries) FinalizeNavCollectionJob(ctx context.Context, arg FinalizeNavCollectionJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeNavCollectionJob, arg.Status, arg.ID, arg.InstanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeNavCollectionRun = `-- name: FinalizeNavCollectionRun :execrows
UPDATE gfn_collection_runs
SET status = $1, ended_at = now(),
    attempted_count = $2, success_count = $3,
    partial_count = $4, failure_count = $5,
    skipped_count = $6,
    duration_ms = GREATEST(0, (extract(epoch FROM (now() - started_at)) * 1000)::bigint),
    error_kind = $7, error_message = $8
WHERE id = $9 AND status = 'running'
`

type FinalizeNavCollectionRunParams struct {
	Status         string `json:"status"`
	AttemptedCount int32  `json:"attempted_count"`
	SuccessCount   int32  `json:"success_count"`
	PartialCount   int32  `json:"partial_count"`
	FailureCount   int32  `json:"failure_count"`
	SkippedCount   int32  `json:"skipped_count"`
	ErrorKind      string `json:"error_kind"`
	ErrorMessage   string `json:"error_message"`
	ID             string `json:"id"`
}

func (q *Queries) FinalizeNavCollectionRun(ctx context.Context, arg FinalizeNavCollectionRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeNavCollectionRun,
		arg.Status,
		arg.AttemptedCount,
		arg.SuccessCount,
		arg.PartialCount,
		arg.FailureCount,
		arg.SkippedCount,
		arg.ErrorKind,
		arg.ErrorMessage,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNavCollectionScheduleForUpdate = `-- name: GetNavCollectionScheduleForUpdate :one
SELECT id, job_key, name, enabled, schedule_kind, cron_expression, interval_seconds, anchor_at, timezone, misfire_policy, misfire_grace_seconds, overlap_policy, priority, concurrency_key, version, effective_from, last_materialized_for, next_scheduled_for, created_at, updated_at FROM gfn_collection_schedules WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetNavCollectionScheduleForUpdate(ctx context.Context, id int64) (GfnCollectionSchedule, error) {
	row := q.db.QueryRow(ctx, getNavCollectionScheduleForUpdate, id)
	var i GfnCollectionSchedule
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.Name,
		&i.Enabled,
		&i.ScheduleKind,
		&i.CronExpression,
		&i.IntervalSeconds,
		&i.AnchorAt,
		&i.Timezone,
		&i.MisfirePolicy,
		&i.MisfireGraceSeconds,
		&i.OverlapPolicy,
		&i.Priority,
		&i.ConcurrencyKey,
		&i.Version,
		&i.EffectiveFrom,
		&i.LastMaterializedFor,
		&i.NextScheduledFor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatNavCollectorInstance = `-- name: HeartbeatNavCollectorInstance :execrows
UPDATE gfn_collector_instances SET last_heartbeat_at = now()
WHERE instance_id = $1 AND stopped_at IS NULL
`

func (q *Queries) HeartbeatNavCollectorInstance(ctx context.Context, instanceID string) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatNavCollectorInstance, instanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNavCollectionRun = `-- name: InsertNavCollectionRun :one
INSERT INTO gfn_collection_runs (
    id, job_id, attempt_no, collector_instance_id, status, scheduled_for,
    started_at, expected_count, attempted_count, success_count, partial_count,
    failure_count, skipped_count, schedule_delay_ms, duration_ms
) VALUES (
    $1, $2, $3,
    $4, 'running', $5, now(),
    $6, 0, 0, 0, 0, 0, $7, 0
)
RETURNING id, job_id, attempt_no, collector_instance_id, status, scheduled_for, started_at, ended_at, expected_count, attempted_count, success_count, partial_count, failure_count, skipped_count, schedule_delay_ms, duration_ms, error_kind, error_message
`

type InsertNavCollectionRunParams struct {
	ID                  string             `json:"id"`
	JobID               int64              `json:"job_id"`
	AttemptNo           int32              `json:"attempt_no"`
	CollectorInstanceID string             `json:"collector_instance_id"`
	ScheduledFor        pgtype.Timestamptz `json:"scheduled_for"`
	ExpectedCount       int32              `json:"expected_count"`
	ScheduleDelayMs     int64              `json:"schedule_delay_ms"`
}

func (q *Queries) InsertNavCollectionRun(ctx context.Context, arg InsertNavCollectionRunParams) (GfnCollectionRun, error) {
	row := q.db.QueryRow(ctx, insertNavCollectionRun,
		arg.ID,
		arg.JobID,
		arg.AttemptNo,
		arg.CollectorInstanceID,
		arg.ScheduledFor,
		arg.ExpectedCount,
		arg.ScheduleDelayMs,
	)
	var i GfnCollectionRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNo,
		&i.CollectorInstanceID,
		&i.Status,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.EndedAt,
		&i.ExpectedCount,
		&i.AttemptedCount,
		&i.SuccessCount,
		&i.PartialCount,
		&i.FailureCount,
		&i.SkippedCount,
		&i.ScheduleDelayMs,
		&i.DurationMs,
		&i.ErrorKind,
		&i.ErrorMessage,
	)
	return i, err
}

const insertNavCollectionTaskResult = `-- name: InsertNavCollectionTaskResult :exec
INSERT INTO gfn_collection_task_results (
    run_id, protocol, site_id, target, status, observation_id, duration_ms,
    error_kind, error_message, started_at, ended_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11
)
ON CONFLICT (run_id, protocol, site_id, target) DO UPDATE SET
    status = EXCLUDED.status, observation_id = EXCLUDED.observation_id,
    duration_ms = EXCLUDED.duration_ms, error_kind = EXCLUDED.error_kind,
    error_message = EXCLUDED.error_message, started_at = EXCLUDED.started_at,
    ended_at = EXCLUDED.ended_at
`

type InsertNavCollectionTaskResultParams struct {
	RunID         string             `json:"run_id"`
	Protocol      string             `json:"protocol"`
	SiteID        int64              `json:"site_id"`
	Target        string             `json:"target"`
	Status        string             `json:"status"`
	ObservationID *int64             `json:"observation_id"`
	DurationMs    int64              `json:"duration_ms"`
	ErrorKind     string             `json:"error_kind"`
	ErrorMessage  string             `json:"error_message"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) InsertNavCollectionTaskResult(ctx context.Context, arg InsertNavCollectionTaskResultParams) error {
	_, err := q.db.Exec(ctx, insertNavCollectionTaskResult,
		arg.RunID,
		arg.Protocol,
		arg.SiteID,
		arg.Target,
		arg.Status,
		arg.ObservationID,
		arg.DurationMs,
		arg.ErrorKind,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.EndedAt,
	)
	return err
}

const insertNavScheduledJob = `-- name: InsertNavScheduledJob :execrows
INSERT INTO gfn_collection_jobs (
    schedule_id, schedule_version, job_key, trigger, scope_type, tasks,
    priority, concurrency_key, scheduled_for, status, requested_by,
    created_at, updated_at, completed_at
) VALUES (
    $1, $2, $3,
    $4, 'all', $5, $6,
    $7, $8, $9,
    $10, now(), now(),
    CASE WHEN $9::text IN ('missed', 'skipped') THEN now() ELSE NULL END
)
ON CONFLICT (schedule_id, scheduled_for)
    WHERE schedule_id IS NOT NULL AND scheduled_for IS NOT NULL
DO NOTHING
`

type InsertNavScheduledJobParams struct {
	ScheduleID      *int64             `json:"schedule_id"`
	ScheduleVersion *int64             `json:"schedule_version"`
	JobKey          string             `json:"job_key"`
	Trigger         string             `json:"trigger"`
	Tasks           []string           `json:"tasks"`
	Priority        int32              `json:"priority"`
	ConcurrencyKey  string             `json:"concurrency_key"`
	ScheduledFor    pgtype.Timestamptz `json:"scheduled_for"`
	Status          string             `json:"status"`
	RequestedBy     string             `json:"requested_by"`
}

func (q *Queries) InsertNavScheduledJob(ctx context.Context, arg InsertNavScheduledJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNavScheduledJob,
		arg.ScheduleID,
		arg.ScheduleVersion,
		arg.JobKey,
		arg.Trigger,
		arg.Tasks,
		arg.Priority,
		arg.ConcurrencyKey,
		arg.ScheduledFor,
		arg.Status,
		arg.RequestedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listExpiredNavCollectionJobs = `-- name: ListExpiredNavCollectionJobs :many
SELECT j.id AS job_id, r.id AS run_id
FROM gfn_collection_jobs j
JOIN gfn_collection_runs r ON r.job_id = j.id AND r.status = 'running'
WHERE j.status = 'running' AND j.lease_until < now()
ORDER BY j.lease_until
FOR UPDATE OF j SKIP LOCKED
`

type ListExpiredNavCollectionJobsRow struct {
	JobID int64  `json:"job_id"`
	RunID string `json:"run_id"`
}

func (q *Queries) ListExpiredNavCollectionJobs(ctx context.Context) ([]ListExpiredNavCollectionJobsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredNavCollectionJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredNavCollectionJobsRow{}
	for rows.Next() {
		var i ListExpiredNavCollectionJobsRow
		if err := rows.Scan(&i.JobID, &i.RunID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavCollectionSchedules = `-- name: ListNavCollectionSchedules :many
SELECT id, job_key, name, enabled, schedule_kind, cron_expression, interval_seconds, anchor_at, timezone, misfire_policy, misfire_grace_seconds, overlap_policy, priority, concurrency_key, version, effective_from, last_materialized_for, next_scheduled_for, created_at, updated_at FROM gfn_collection_schedules ORDER BY job_key
`

func (q *Queries) ListNavCollectionSchedules(ctx context.Context) ([]GfnCollectionSchedule, error) {
	rows, err := q.db.Query(ctx, listNavCollectionSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfnCollectionSchedule{}
	for rows.Next() {
		var i GfnCollectionSchedule
		if err := rows.Scan(
			&i.ID,
			&i.JobKey,
			&i.Name,
			&i.Enabled,
			&i.ScheduleKind,
			&i.CronExpression,
			&i.IntervalSeconds,
			&i.AnchorAt,
			&i.Timezone,
			&i.MisfirePolicy,
			&i.MisfireGraceSeconds,
			&i.OverlapPolicy,
			&i.Priority,
			&i.ConcurrencyKey,
			&i.Version,
			&i.EffectiveFrom,
			&i.LastMaterializedFor,
			&i.NextScheduledFor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavCollectionTargets = `-- name: ListNavCollectionTargets :many
SELECT DISTINCT cd.site_id::bigint AS site_id,
       (COALESCE(cd.prefix, '') || cd.name)::text AS target
FROM gfn_collector_domain cd
JOIN gfn_site site ON site.id = cd.site_id
WHERE cd.deleted IS NOT TRUE
  AND site.deleted IS NOT TRUE
  AND cd.site_id > 0
  AND (
      $1::text = 'all'
      OR cd.site_id = $2
  )
  AND (
      $1::text <> 'target'
      OR lower(COALESCE(cd.prefix, '') || cd.name) = lower($3::text)
  )
ORDER BY site_id, target
`

type ListNavCollectionTargetsParams struct {
	ScopeType string  `json:"scope_type"`
	ScopeID   *int64  `json:"scope_id"`
	Target    *string `json:"target"`
}

type ListNavCollectionTargetsRow struct {
	SiteID int64  `json:"site_id"`
	Target string `json:"target"`
}

func (q *Queries) ListNavCollectionTargets(ctx context.Context, arg ListNavCollectionTargetsParams) ([]ListNavCollectionTargetsRow, error) {
	rows, err := q.db.Query(ctx, listNavCollectionTargets, arg.ScopeType, arg.ScopeID, arg.Target)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavCollectionTargetsRow{}
	for rows.Next() {
		var i ListNavCollectionTargetsRow
		if err := rows.Scan(&i.SiteID, &i.Target); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const navCollectionCancelRequested = `-- name: NavCollectionCancelRequested :one
SELECT cancel_requested_at
FROM gfn_collection_jobs
WHERE id = $1 AND claimed_by = $2 AND status = 'running'
`

type NavCollectionCancelRequestedParams struct {
	JobID      int64   `json:"job_id"`
	InstanceID *string `json:"instance_id"`
}

func (q *Queries) NavCollectionCancelRequested(ctx context.Context, arg NavCollectionCancelRequestedParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, navCollectionCancelRequested, arg.JobID, arg.InstanceID)
	var cancel_requested_at pgtype.Timestamptz
	err := row.Scan(&cancel_requested_at)
	return cancel_requested_at, err
}

const navCollectionClock = `-- name: NavCollectionClock :one
SELECT now()::timestamptz AS control_now
`

func (q *Queries) NavCollectionClock(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, navCollectionClock)
	var control_now pgtype.Timestamptz
	err := row.Scan(&control_now)
	return control_now, err
}

const navCollectionLaneActive = `-- name: NavCollectionLaneActive :one
SELECT EXISTS (
    SELECT 1 FROM gfn_collection_jobs
    WHERE concurrency_key = $1 AND status = 'running'
)::boolean
`

func (q *Queries) NavCollectionLaneActive(ctx context.Context, concurrencyKey string) (bool, error) {
	row := q.db.QueryRow(ctx, navCollectionLaneActive, concurrencyKey)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const nextNavCollectionAttempt = `-- name: NextNavCollectionAttempt :one
SELECT COALESCE(max(attempt_no), 0)::integer + 1
FROM gfn_collection_runs WHERE job_id = $1
`

func (q *Queries) NextNavCollectionAttempt(ctx context.Context, jobID int64) (int32, error) {
	row := q.db.QueryRow(ctx, nextNavCollectionAttempt, jobID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const registerNavCollectorInstance = `-- name: RegisterNavCollectorInstance :exec
INSERT INTO gfn_collector_instances (
    instance_id, collector_id, hostname, version, commit_sha, capabilities,
    started_at, last_heartbeat_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, now(), now()
)
`

type RegisterNavCollectorInstanceParams struct {
	InstanceID   string   `json:"instance_id"`
	CollectorID  string   `json:"collector_id"`
	Hostname     string   `json:"hostname"`
	Version      string   `json:"version"`
	CommitSha    string   `json:"commit_sha"`
	Capabilities []string `json:"capabilities"`
}

func (q *Queries) RegisterNavCollectorInstance(ctx context.Context, arg RegisterNavCollectorInstanceParams) error {
	_, err := q.db.Exec(ctx, registerNavCollectorInstance,
		arg.InstanceID,
		arg.CollectorID,
		arg.Hostname,
		arg.Version,
		arg.CommitSha,
		arg.Capabilities,
	)
	return err
}

const renewNavCollectionLease = `-- name: RenewNavCollectionLease :execrows
UPDATE gfn_collection_jobs
SET lease_until = now() + $1::bigint * interval '1 second', updated_at = now()
WHERE id = $2 AND claimed_by = $3 AND status = 'running'
`

type RenewNavCollectionLeaseParams struct {
	LeaseSeconds int64   `json:"lease_seconds"`
	JobID        int64   `json:"job_id"`
	InstanceID   *string `json:"instance_id"`
}

func (q *Queries) RenewNavCollectionLease(ctx context.Context, arg RenewNavCollectionLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewNavCollectionLease, arg.LeaseSeconds, arg.JobID, arg.InstanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const skipOverlappingNavPointInTimeJobs = `-- name: SkipOverlappingNavPointInTimeJobs :execrows
UPDATE gfn_collection_jobs queued
SET status = 'skipped', completed_at = now(), updated_at = now()
WHERE queued.status = 'queued'
  AND queued.trigger = 'scheduled'
  AND queued.job_key IN ('nav.ping', 'nav.http', 'nav.dns', 'nav.port_check')
  AND EXISTS (
      SELECT 1
      FROM gfn_collection_jobs active
      WHERE active.status = 'running'
        AND active.concurrency_key = queued.concurrency_key
  )
`

func (q *Queries) SkipOverlappingNavPointInTimeJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, skipOverlappingNavPointInTimeJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopNavCollectorInstance = `-- name: StopNavCollectorInstance :execrows
UPDATE gfn_collector_instances SET last_heartbeat_at = now(), stopped_at = now()
WHERE instance_id = $1 AND stopped_at IS NULL
`

func (q *Queries) StopNavCollectorInstance(ctx context.Context, instanceID string) (int64, error) {
	result, err := q.db.Exec(ctx, stopNavCollectorInstance, instanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNavCollectionScheduleCursor = `-- name: UpdateNavCollectionScheduleCursor :exec
UPDATE gfn_collection_schedules
SET last_materialized_for = $1,
    next_scheduled_for = $2, updated_at = now()
WHERE id = $3 AND version = $4
`

type UpdateNavCollectionScheduleCursorParams struct {
	LastMaterializedFor pgtype.Timestamptz `json:"last_materialized_for"`
	NextScheduledFor    pgtype.Timestamptz `json:"next_scheduled_for"`
	ID                  int64              `json:"id"`
	Version             int64              `json:"version"`
}

func (q *Queries) UpdateNavCollectionScheduleCursor(ctx context.Context, arg UpdateNavCollectionScheduleCursorParams) error {
	_, err := q.db.Exec(ctx, updateNavCollectionScheduleCursor,
		arg.LastMaterializedFor,
		arg.NextScheduledFor,
		arg.ID,
		arg.Version,
	)
	return err
}
