// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package navsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceNavMetricCheckpoint = `-- name: AdvanceNavMetricCheckpoint :execrows
UPDATE gfn_metric_checkpoints
SET processed_through = $1,
    updated_at = transaction_timestamp()
WHERE metric_key = $2
  AND metric_version = $3
  AND (processed_through IS NULL OR processed_through < $1)
`

type AdvanceNavMetricCheckpointParams struct {
	ProcessedThrough pgtype.Date `json:"processed_through"`
	MetricKey        string      `json:"metric_key"`
	MetricVersion    int32       `json:"metric_version"`
}

func (q *Queries) AdvanceNavMetricCheckpoint(ctx context.Context, arg AdvanceNavMetricCheckpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceNavMetricCheckpoint, arg.ProcessedThrough, arg.MetricKey, arg.MetricVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countNavMetricPopulation = `-- name: CountNavMetricPopulation :one
SELECT count(*)::bigint
FROM gfn_site_daily
WHERE fact_date = $1
  AND finalized_at IS NOT NULL
  AND tracked_at_end
`

func (q *Queries) CountNavMetricPopulation(ctx context.Context, factDate pgtype.Date) (int64, error) {
	row := q.db.QueryRow(ctx, countNavMetricPopulation, factDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getNavMetricGlobalDaily = `-- name: GetNavMetricGlobalDaily :one
SELECT population_count, eligible_count, not_applicable_count,
       positive_count, negative_count, stale_count, not_probed_count,
       probe_failed_count, unknown_count, computed_at
FROM gfn_metric_daily
WHERE metric_key = $1
  AND metric_version = $2
  AND fact_date = $3
  AND dimension_key = 'global'
  AND dimension_value = 'all'
`

type GetNavMetricGlobalDailyParams struct {
	MetricKey     string      `json:"metric_key"`
	MetricVersion int32       `json:"metric_version"`
	FactDate      pgtype.Date `json:"fact_date"`
}

type GetNavMetricGlobalDailyRow struct {
	PopulationCount    int64              `json:"population_count"`
	EligibleCount      int64              `json:"eligible_count"`
	NotApplicableCount int64              `json:"not_applicable_count"`
	PositiveCount      int64              `json:"positive_count"`
	NegativeCount      int64              `json:"negative_count"`
	StaleCount         int64              `json:"stale_count"`
	NotProbedCount     int64              `json:"not_probed_count"`
	ProbeFailedCount   int64              `json:"probe_failed_count"`
	UnknownCount       int64              `json:"unknown_count"`
	ComputedAt         pgtype.Timestamptz `json:"computed_at"`
}

func (q *Queries) GetNavMetricGlobalDaily(ctx context.Context, arg GetNavMetricGlobalDailyParams) (GetNavMetricGlobalDailyRow, error) {
	row := q.db.QueryRow(ctx, getNavMetricGlobalDaily, arg.MetricKey, arg.MetricVersion, arg.FactDate)
	var i GetNavMetricGlobalDailyRow
	err := row.Scan(
		&i.PopulationCount,
		&i.EligibleCount,
		&i.NotApplicableCount,
		&i.PositiveCount,
		&i.NegativeCount,
		&i.StaleCount,
		&i.NotProbedCount,
		&i.ProbeFailedCount,
		&i.UnknownCount,
		&i.ComputedAt,
	)
	return i, err
}

const listNavMetricCheckpoints = `-- name: ListNavMetricCheckpoints :many
SELECT registry.metric_key,
       registry.metric_version,
       registry.status,
       checkpoint.source_start_date,
       checkpoint.processed_through,
       target.processed_through AS target_processed_through,
       site.processed_through AS site_processed_through,
       checkpoint.created_at,
       checkpoint.updated_at
FROM gfn_metric_registry registry
JOIN gfn_metric_checkpoints checkpoint
  ON checkpoint.metric_key = registry.metric_key
 AND checkpoint.metric_version = registry.metric_version
LEFT JOIN gfn_fact_rollup_checkpoints target
  ON target.pipeline_key = 'nav.target_facts'
LEFT JOIN gfn_fact_rollup_checkpoints site
  ON site.pipeline_key = 'nav.site_facts'
ORDER BY registry.metric_key, registry.metric_version
`

type ListNavMetricCheckpointsRow struct {
	MetricKey              string             `json:"metric_key"`
	MetricVersion          int32              `json:"metric_version"`
	Status                 string             `json:"status"`
	SourceStartDate        pgtype.Date        `json:"source_start_date"`
	ProcessedThrough       pgtype.Date        `json:"processed_through"`
	TargetProcessedThrough pgtype.Date        `json:"target_processed_through"`
	SiteProcessedThrough   pgtype.Date        `json:"site_processed_through"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListNavMetricCheckpoints(ctx context.Context) ([]ListNavMetricCheckpointsRow, error) {
	rows, err := q.db.Query(ctx, listNavMetricCheckpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavMetricCheckpointsRow{}
	for rows.Next() {
		var i ListNavMetricCheckpointsRow
		if err := rows.Scan(
			&i.MetricKey,
			&i.MetricVersion,
			&i.Status,
			&i.SourceStartDate,
			&i.ProcessedThrough,
			&i.TargetProcessedThrough,
			&i.SiteProcessedThrough,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavMetricRegistry = `-- name: ListNavMetricRegistry :many
SELECT metric_key, metric_version, metric_kind, entity_level, time_grain,
       source_facts, eligibility_policy, state_policy, coverage_policy,
       freshness_seconds, allowed_dimensions, status, description,
       created_at, retired_at
FROM gfn_metric_registry
ORDER BY metric_key, metric_version
`

func (q *Queries) ListNavMetricRegistry(ctx context.Context) ([]GfnMetricRegistry, error) {
	rows, err := q.db.Query(ctx, listNavMetricRegistry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfnMetricRegistry{}
	for rows.Next() {
		var i GfnMetricRegistry
		if err := rows.Scan(
			&i.MetricKey,
			&i.MetricVersion,
			&i.MetricKind,
			&i.EntityLevel,
			&i.TimeGrain,
			&i.SourceFacts,
			&i.EligibilityPolicy,
			&i.StatePolicy,
			&i.CoveragePolicy,
			&i.FreshnessSeconds,
			&i.AllowedDimensions,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNavMetricCheckpoint = `-- name: LockNavMetricCheckpoint :one
SELECT checkpoint.metric_key,
       checkpoint.metric_version,
       checkpoint.source_start_date,
       checkpoint.processed_through,
       registry.status
FROM gfn_metric_checkpoints checkpoint
JOIN gfn_metric_registry registry
  ON registry.metric_key = checkpoint.metric_key
 AND registry.metric_version = checkpoint.metric_version
WHERE checkpoint.metric_key = $1
  AND checkpoint.metric_version = $2
FOR UPDATE OF checkpoint
`

type LockNavMetricCheckpointParams struct {
	MetricKey     string `json:"metric_key"`
	MetricVersion int32  `json:"metric_version"`
}

type LockNavMetricCheckpointRow struct {
	MetricKey        string      `json:"metric_key"`
	MetricVersion    int32       `json:"metric_version"`
	SourceStartDate  pgtype.Date `json:"source_start_date"`
	ProcessedThrough pgtype.Date `json:"processed_through"`
	Status           string      `json:"status"`
}

func (q *Queries) LockNavMetricCheckpoint(ctx context.Context, arg LockNavMetricCheckpointParams) (LockNavMetricCheckpointRow, error) {
	row := q.db.QueryRow(ctx, lockNavMetricCheckpoint, arg.MetricKey, arg.MetricVersion)
	var i LockNavMetricCheckpointRow
	err := row.Scan(
		&i.MetricKey,
		&i.MetricVersion,
		&i.SourceStartDate,
		&i.ProcessedThrough,
		&i.Status,
	)
	return i, err
}

const navMetricUpstreamProcessedThrough = `-- name: NavMetricUpstreamProcessedThrough :one
SELECT target.processed_through AS target_processed_through,
       site.processed_through AS site_processed_through
FROM gfn_fact_rollup_checkpoints target
CROSS JOIN gfn_fact_rollup_checkpoints site
WHERE target.pipeline_key = 'nav.target_facts'
  AND site.pipeline_key = 'nav.site_facts'
`

type NavMetricUpstreamProcessedThroughRow struct {
	TargetProcessedThrough pgtype.Date `json:"target_processed_through"`
	SiteProcessedThrough   pgtype.Date `json:"site_processed_through"`
}

func (q *Queries) NavMetricUpstreamProcessedThrough(ctx context.Context) (NavMetricUpstreamProcessedThroughRow, error) {
	row := q.db.QueryRow(ctx, navMetricUpstreamProcessedThrough)
	var i NavMetricUpstreamProcessedThroughRow
	err := row.Scan(&i.TargetProcessedThrough, &i.SiteProcessedThrough)
	return i, err
}

const projectNavMetricDay = `-- name: ProjectNavMetricDay :one
SELECT CASE
    WHEN $1::integer = 2 THEN gfn_project_metric_day_v2(
        $2::text,
        $1::integer,
        $3::date
    )
    ELSE gfn_project_metric_day(
        $2::text,
        $1::integer,
        $3::date
    )
END::bigint
`

type ProjectNavMetricDayParams struct {
	MetricVersion int32       `json:"metric_version"`
	MetricKey     string      `json:"metric_key"`
	FactDate      pgtype.Date `json:"fact_date"`
}

func (q *Queries) ProjectNavMetricDay(ctx context.Context, arg ProjectNavMetricDayParams) (int64, error) {
	row := q.db.QueryRow(ctx, projectNavMetricDay, arg.MetricVersion, arg.MetricKey, arg.FactDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
