package schema

import (
	"fmt"
	"strings"
)

func BaselineSQL(database string, version int64, snapshot Snapshot) string {
	var out strings.Builder
	fmt.Fprintf(&out, "-- Canonical %s baseline, version %d.\n", database, version)
	out.WriteString("-- Derived from the audited production schema and normalized to omit owners, ACLs, and data.\n")
	out.WriteString("-- +goose Up\n\n")

	for _, extension := range snapshot.Extensions {
		fmt.Fprintf(&out, "CREATE EXTENSION IF NOT EXISTS %s WITH SCHEMA %s;\n\n", ident(extension.Name), ident(extension.Schema))
	}
	for _, sequence := range snapshot.Sequences {
		fmt.Fprintf(&out, "CREATE SEQUENCE public.%s\n", ident(sequence.Name))
		fmt.Fprintf(&out, "    AS %s\n", sequence.DataType)
		fmt.Fprintf(&out, "    START WITH %d\n", sequence.Start)
		fmt.Fprintf(&out, "    INCREMENT BY %d\n", sequence.Increment)
		fmt.Fprintf(&out, "    MINVALUE %d\n", sequence.Minimum)
		fmt.Fprintf(&out, "    MAXVALUE %d\n", sequence.Maximum)
		fmt.Fprintf(&out, "    CACHE %d", sequence.Cache)
		if sequence.Cycle {
			out.WriteString("\n    CYCLE")
		}
		out.WriteString(";\n\n")
	}

	for _, table := range snapshot.Tables {
		fmt.Fprintf(&out, "CREATE TABLE public.%s (\n", ident(table.Name))
		for i, column := range table.Columns {
			out.WriteString("    ")
			out.WriteString(ident(column.Name))
			out.WriteByte(' ')
			out.WriteString(column.DataType)
			if column.Collation != "" {
				out.WriteString(" COLLATE ")
				out.WriteString(column.Collation)
			}
			switch column.Identity {
			case "a":
				out.WriteString(" GENERATED ALWAYS AS IDENTITY")
			case "d":
				out.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
			}
			if column.Generated == "s" {
				fmt.Fprintf(&out, " GENERATED ALWAYS AS (%s) STORED", column.Default)
			} else if column.HasDefault && column.Identity == "" {
				out.WriteString(" DEFAULT ")
				out.WriteString(column.Default)
			}
			if column.NotNull {
				out.WriteString(" NOT NULL")
			}
			if i+1 < len(table.Columns) {
				out.WriteByte(',')
			}
			out.WriteByte('\n')
		}
		out.WriteString(");\n\n")
	}

	for _, sequence := range snapshot.Sequences {
		if sequence.OwnedTable != "" {
			fmt.Fprintf(&out, "ALTER SEQUENCE public.%s OWNED BY public.%s.%s;\n", ident(sequence.Name), ident(sequence.OwnedTable), ident(sequence.OwnedColumn))
		}
	}
	if len(snapshot.Sequences) > 0 {
		out.WriteByte('\n')
	}

	for _, table := range snapshot.Tables {
		for _, constraint := range table.Constraints {
			// PostgreSQL 18 exposes column NOT NULL attributes as named
			// constraints. The column clause recreates those canonical
			// constraints; repeating the PG18-only ALTER form is redundant and
			// is not yet understood by sqlc's PostgreSQL parser.
			if strings.HasPrefix(constraint.Definition, "NOT NULL ") {
				continue
			}
			fmt.Fprintf(&out, "ALTER TABLE ONLY public.%s ADD CONSTRAINT %s %s;\n", ident(table.Name), ident(constraint.Name), constraint.Definition)
		}
	}
	out.WriteByte('\n')
	for _, table := range snapshot.Tables {
		for _, index := range table.Indexes {
			out.WriteString(index.Definition)
			out.WriteString(";\n")
		}
	}
	out.WriteByte('\n')

	for _, table := range snapshot.Tables {
		if table.Comment != "" {
			fmt.Fprintf(&out, "COMMENT ON TABLE public.%s IS %s;\n", ident(table.Name), literal(table.Comment))
		}
		for _, column := range table.Columns {
			if column.Comment != "" {
				fmt.Fprintf(&out, "COMMENT ON COLUMN public.%s.%s IS %s;\n", ident(table.Name), ident(column.Name), literal(column.Comment))
			}
		}
		for _, constraint := range table.Constraints {
			if constraint.Comment != "" {
				fmt.Fprintf(&out, "COMMENT ON CONSTRAINT %s ON public.%s IS %s;\n", ident(constraint.Name), ident(table.Name), literal(constraint.Comment))
			}
		}
		for _, index := range table.Indexes {
			if index.Comment != "" {
				fmt.Fprintf(&out, "COMMENT ON INDEX public.%s IS %s;\n", ident(index.Name), literal(index.Comment))
			}
		}
	}
	for _, sequence := range snapshot.Sequences {
		if sequence.Comment != "" {
			fmt.Fprintf(&out, "COMMENT ON SEQUENCE public.%s IS %s;\n", ident(sequence.Name), literal(sequence.Comment))
		}
	}
	out.WriteByte('\n')

	for _, function := range snapshot.Functions {
		out.WriteString("-- +goose StatementBegin\n")
		out.WriteString(strings.TrimSpace(function.Definition))
		if !strings.HasSuffix(strings.TrimSpace(function.Definition), ";") {
			out.WriteByte(';')
		}
		out.WriteString("\n-- +goose StatementEnd\n")
		if function.Comment != "" {
			fmt.Fprintf(&out, "COMMENT ON FUNCTION public.%s IS %s;\n", function.Identity, literal(function.Comment))
		}
		out.WriteByte('\n')
	}
	for _, table := range snapshot.Tables {
		for _, trigger := range table.Triggers {
			out.WriteString(trigger.Definition)
			out.WriteString(";\n")
			if trigger.Comment != "" {
				fmt.Fprintf(&out, "COMMENT ON TRIGGER %s ON public.%s IS %s;\n", ident(trigger.Name), ident(table.Name), literal(trigger.Comment))
			}
		}
	}

	out.WriteString("\n-- Baseline intentionally has no Down section: dropping an application schema is not a safe rollback.\n")
	return out.String()
}

func ident(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `""`) + `"`
}

func literal(value string) string {
	return `'` + strings.ReplaceAll(value, `'`, `''`) + `'`
}
