// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collection_control.sql

package gamesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCancelGameCollectionJob = `-- name: AdminCancelGameCollectionJob :one
UPDATE gfg_collection_jobs
SET status = CASE WHEN status = 'queued' THEN 'canceled' ELSE status END,
    cancel_requested_at = CASE WHEN status = 'running' THEN now() ELSE cancel_requested_at END,
    completed_at = CASE WHEN status = 'queued' THEN now() ELSE completed_at END,
    updated_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING id, schedule_id, schedule_version, job_key, trigger, scope_type, scope_id, target, tasks, priority, concurrency_key, scheduled_for, status, requested_by, dedupe_key, claimed_by, lease_until, cancel_requested_at, created_at, updated_at, completed_at
`

func (q *Queries) AdminCancelGameCollectionJob(ctx context.Context, id int64) (GfgCollectionJob, error) {
	row := q.db.QueryRow(ctx, adminCancelGameCollectionJob, id)
	var i GfgCollectionJob
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.ScheduleVersion,
		&i.JobKey,
		&i.Trigger,
		&i.ScopeType,
		&i.ScopeID,
		&i.Target,
		&i.Tasks,
		&i.Priority,
		&i.ConcurrencyKey,
		&i.ScheduledFor,
		&i.Status,
		&i.RequestedBy,
		&i.DedupeKey,
		&i.ClaimedBy,
		&i.LeaseUntil,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const adminGameCollectionClock = `-- name: AdminGameCollectionClock :one
SELECT now()::timestamptz AS control_now
`

func (q *Queries) AdminGameCollectionClock(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, adminGameCollectionClock)
	var control_now pgtype.Timestamptz
	err := row.Scan(&control_now)
	return control_now, err
}

const adminGameCollectionCounts = `-- name: AdminGameCollectionCounts :one
SELECT
    count(*) FILTER (WHERE status = 'running')::bigint AS running_count,
    count(*) FILTER (WHERE status = 'queued')::bigint AS queued_count,
    count(*) FILTER (WHERE status = 'failed' AND created_at >= now() - interval '24 hours')::bigint AS failed_24h,
    count(*) FILTER (WHERE status = 'missed' AND created_at >= now() - interval '24 hours')::bigint AS missed_24h
FROM gfg_collection_jobs
`

type AdminGameCollectionCountsRow struct {
	RunningCount int64 `json:"running_count"`
	QueuedCount  int64 `json:"queued_count"`
	Failed24h    int64 `json:"failed_24h"`
	Missed24h    int64 `json:"missed_24h"`
}

func (q *Queries) AdminGameCollectionCounts(ctx context.Context) (AdminGameCollectionCountsRow, error) {
	row := q.db.QueryRow(ctx, adminGameCollectionCounts)
	var i AdminGameCollectionCountsRow
	err := row.Scan(
		&i.RunningCount,
		&i.QueuedCount,
		&i.Failed24h,
		&i.Missed24h,
	)
	return i, err
}

const adminGameCollectionTargetExists = `-- name: AdminGameCollectionTargetExists :one
SELECT EXISTS (SELECT 1 FROM gfg_game WHERE id = $1)::boolean
`

func (q *Queries) AdminGameCollectionTargetExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, adminGameCollectionTargetExists, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const adminGetGameCollectionJob = `-- name: AdminGetGameCollectionJob :one
SELECT id, schedule_id, schedule_version, job_key, trigger, scope_type, scope_id, target, tasks, priority, concurrency_key, scheduled_for, status, requested_by, dedupe_key, claimed_by, lease_until, cancel_requested_at, created_at, updated_at, completed_at FROM gfg_collection_jobs WHERE id = $1
`

func (q *Queries) AdminGetGameCollectionJob(ctx context.Context, id int64) (GfgCollectionJob, error) {
	row := q.db.QueryRow(ctx, adminGetGameCollectionJob, id)
	var i GfgCollectionJob
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.ScheduleVersion,
		&i.JobKey,
		&i.Trigger,
		&i.ScopeType,
		&i.ScopeID,
		&i.Target,
		&i.Tasks,
		&i.Priority,
		&i.ConcurrencyKey,
		&i.ScheduledFor,
		&i.Status,
		&i.RequestedBy,
		&i.DedupeKey,
		&i.ClaimedBy,
		&i.LeaseUntil,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const adminGetGameCollectionRun = `-- name: AdminGetGameCollectionRun :one
SELECT run.id, run.job_id, run.attempt_no, run.collector_instance_id, run.status, run.scheduled_for, run.started_at, run.ended_at, run.expected_count, run.attempted_count, run.success_count, run.partial_count, run.failure_count, run.skipped_count, run.schedule_delay_ms, run.duration_ms, run.error_kind, run.error_message, job.job_key, job.trigger, job.scope_type, job.scope_id, job.target
FROM gfg_collection_runs run JOIN gfg_collection_jobs job ON job.id = run.job_id
WHERE run.id = $1
`

type AdminGetGameCollectionRunRow struct {
	ID                  string             `json:"id"`
	JobID               int64              `json:"job_id"`
	AttemptNo           int32              `json:"attempt_no"`
	CollectorInstanceID string             `json:"collector_instance_id"`
	Status              string             `json:"status"`
	ScheduledFor        pgtype.Timestamptz `json:"scheduled_for"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	EndedAt             pgtype.Timestamptz `json:"ended_at"`
	ExpectedCount       int32              `json:"expected_count"`
	AttemptedCount      int32              `json:"attempted_count"`
	SuccessCount        int32              `json:"success_count"`
	PartialCount        int32              `json:"partial_count"`
	FailureCount        int32              `json:"failure_count"`
	SkippedCount        int32              `json:"skipped_count"`
	ScheduleDelayMs     int64              `json:"schedule_delay_ms"`
	DurationMs          int64              `json:"duration_ms"`
	ErrorKind           string             `json:"error_kind"`
	ErrorMessage        string             `json:"error_message"`
	JobKey              string             `json:"job_key"`
	Trigger             string             `json:"trigger"`
	ScopeType           string             `json:"scope_type"`
	ScopeID             *int64             `json:"scope_id"`
	Target              *string            `json:"target"`
}

func (q *Queries) AdminGetGameCollectionRun(ctx context.Context, id string) (AdminGetGameCollectionRunRow, error) {
	row := q.db.QueryRow(ctx, adminGetGameCollectionRun, id)
	var i AdminGetGameCollectionRunRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNo,
		&i.CollectorInstanceID,
		&i.Status,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.EndedAt,
		&i.ExpectedCount,
		&i.AttemptedCount,
		&i.SuccessCount,
		&i.PartialCount,
		&i.FailureCount,
		&i.SkippedCount,
		&i.ScheduleDelayMs,
		&i.DurationMs,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.JobKey,
		&i.Trigger,
		&i.ScopeType,
		&i.ScopeID,
		&i.Target,
	)
	return i, err
}

const adminGetGameCollectionSchedule = `-- name: AdminGetGameCollectionSchedule :one
SELECT id, job_key, name, enabled, schedule_kind, cron_expression, interval_seconds, anchor_at, timezone, misfire_policy, misfire_grace_seconds, overlap_policy, priority, concurrency_key, version, effective_from, last_materialized_for, next_scheduled_for, created_at, updated_at FROM gfg_collection_schedules WHERE id = $1
`

func (q *Queries) AdminGetGameCollectionSchedule(ctx context.Context, id int64) (GfgCollectionSchedule, error) {
	row := q.db.QueryRow(ctx, adminGetGameCollectionSchedule, id)
	var i GfgCollectionSchedule
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.Name,
		&i.Enabled,
		&i.ScheduleKind,
		&i.CronExpression,
		&i.IntervalSeconds,
		&i.AnchorAt,
		&i.Timezone,
		&i.MisfirePolicy,
		&i.MisfireGraceSeconds,
		&i.OverlapPolicy,
		&i.Priority,
		&i.ConcurrencyKey,
		&i.Version,
		&i.EffectiveFrom,
		&i.LastMaterializedFor,
		&i.NextScheduledFor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminInsertGameManualJob = `-- name: AdminInsertGameManualJob :one
INSERT INTO gfg_collection_jobs (
    job_key, trigger, scope_type, scope_id, tasks, priority, concurrency_key,
    status, requested_by, dedupe_key, created_at, updated_at
) VALUES (
    $1, 'manual', $2, $3,
    $4, 200, 'steam', 'queued', $5,
    $6, now(), now()
)
ON CONFLICT (dedupe_key)
    WHERE dedupe_key IS NOT NULL AND status IN ('queued', 'running')
DO UPDATE SET dedupe_key = EXCLUDED.dedupe_key
RETURNING id, schedule_id, schedule_version, job_key, trigger, scope_type, scope_id, target, tasks, priority, concurrency_key, scheduled_for, status, requested_by, dedupe_key, claimed_by, lease_until, cancel_requested_at, created_at, updated_at, completed_at
`

type AdminInsertGameManualJobParams struct {
	JobKey      string   `json:"job_key"`
	ScopeType   string   `json:"scope_type"`
	ScopeID     *int64   `json:"scope_id"`
	Tasks       []string `json:"tasks"`
	RequestedBy string   `json:"requested_by"`
	DedupeKey   *string  `json:"dedupe_key"`
}

func (q *Queries) AdminInsertGameManualJob(ctx context.Context, arg AdminInsertGameManualJobParams) (GfgCollectionJob, error) {
	row := q.db.QueryRow(ctx, adminInsertGameManualJob,
		arg.JobKey,
		arg.ScopeType,
		arg.ScopeID,
		arg.Tasks,
		arg.RequestedBy,
		arg.DedupeKey,
	)
	var i GfgCollectionJob
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.ScheduleVersion,
		&i.JobKey,
		&i.Trigger,
		&i.ScopeType,
		&i.ScopeID,
		&i.Target,
		&i.Tasks,
		&i.Priority,
		&i.ConcurrencyKey,
		&i.ScheduledFor,
		&i.Status,
		&i.RequestedBy,
		&i.DedupeKey,
		&i.ClaimedBy,
		&i.LeaseUntil,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const adminListGameCollectionChartRows = `-- name: AdminListGameCollectionChartRows :many
SELECT job.id AS job_id, job.job_key, job.status AS job_status, job.scheduled_for,
       job.created_at, COALESCE(run.id, '') AS run_id, COALESCE(run.status, '') AS run_status,
       COALESCE(run.expected_count, 0)::integer AS expected_count,
       COALESCE(run.attempted_count, 0)::integer AS attempted_count,
       COALESCE(run.success_count, 0)::integer AS success_count,
       COALESCE(run.partial_count, 0)::integer AS partial_count,
       COALESCE(run.failure_count, 0)::integer AS failure_count,
       COALESCE(run.skipped_count, 0)::integer AS skipped_count,
       COALESCE(run.schedule_delay_ms, 0)::bigint AS schedule_delay_ms,
       COALESCE(run.duration_ms, 0)::bigint AS duration_ms, run.started_at
FROM gfg_collection_jobs job
LEFT JOIN LATERAL (
    SELECT id, job_id, attempt_no, collector_instance_id, status, scheduled_for, started_at, ended_at, expected_count, attempted_count, success_count, partial_count, failure_count, skipped_count, schedule_delay_ms, duration_ms, error_kind, error_message FROM gfg_collection_runs candidate
    WHERE candidate.job_id = job.id ORDER BY candidate.attempt_no DESC LIMIT 1
) run ON true
WHERE job.created_at >= $1
  AND ($2::text = '' OR job.job_key = $2)
ORDER BY job.created_at
`

type AdminListGameCollectionChartRowsParams struct {
	Since  pgtype.Timestamptz `json:"since"`
	JobKey string             `json:"job_key"`
}

type AdminListGameCollectionChartRowsRow struct {
	JobID           int64              `json:"job_id"`
	JobKey          string             `json:"job_key"`
	JobStatus       string             `json:"job_status"`
	ScheduledFor    pgtype.Timestamptz `json:"scheduled_for"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RunID           string             `json:"run_id"`
	RunStatus       string             `json:"run_status"`
	ExpectedCount   int32              `json:"expected_count"`
	AttemptedCount  int32              `json:"attempted_count"`
	SuccessCount    int32              `json:"success_count"`
	PartialCount    int32              `json:"partial_count"`
	FailureCount    int32              `json:"failure_count"`
	SkippedCount    int32              `json:"skipped_count"`
	ScheduleDelayMs int64              `json:"schedule_delay_ms"`
	DurationMs      int64              `json:"duration_ms"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) AdminListGameCollectionChartRows(ctx context.Context, arg AdminListGameCollectionChartRowsParams) ([]AdminListGameCollectionChartRowsRow, error) {
	rows, err := q.db.Query(ctx, adminListGameCollectionChartRows, arg.Since, arg.JobKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListGameCollectionChartRowsRow{}
	for rows.Next() {
		var i AdminListGameCollectionChartRowsRow
		if err := rows.Scan(
			&i.JobID,
			&i.JobKey,
			&i.JobStatus,
			&i.ScheduledFor,
			&i.CreatedAt,
			&i.RunID,
			&i.RunStatus,
			&i.ExpectedCount,
			&i.AttemptedCount,
			&i.SuccessCount,
			&i.PartialCount,
			&i.FailureCount,
			&i.SkippedCount,
			&i.ScheduleDelayMs,
			&i.DurationMs,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListGameCollectionJobs = `-- name: AdminListGameCollectionJobs :many
SELECT job.id, job.schedule_id, job.schedule_version, job.job_key, job.trigger, job.scope_type, job.scope_id, job.target, job.tasks, job.priority, job.concurrency_key, job.scheduled_for, job.status, job.requested_by, job.dedupe_key, job.claimed_by, job.lease_until, job.cancel_requested_at, job.created_at, job.updated_at, job.completed_at, COALESCE(latest.id, '') AS run_id
FROM gfg_collection_jobs job
LEFT JOIN LATERAL (
    SELECT id FROM gfg_collection_runs run WHERE run.job_id = job.id ORDER BY attempt_no DESC LIMIT 1
) latest ON true
WHERE ($1::text = '' OR job.status = $1)
  AND ($2::text = '' OR job.job_key = $2)
  AND ($3::text = '' OR job.trigger = $3)
ORDER BY CASE WHEN job.status = 'running' THEN 0 WHEN job.status = 'queued' THEN 1 ELSE 2 END,
         job.priority DESC, job.created_at DESC
LIMIT $5 OFFSET $4
`

type AdminListGameCollectionJobsParams struct {
	Status    string `json:"status"`
	JobKey    string `json:"job_key"`
	Trigger   string `json:"trigger"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

type AdminListGameCollectionJobsRow struct {
	ID                int64              `json:"id"`
	ScheduleID        *int64             `json:"schedule_id"`
	ScheduleVersion   *int64             `json:"schedule_version"`
	JobKey            string             `json:"job_key"`
	Trigger           string             `json:"trigger"`
	ScopeType         string             `json:"scope_type"`
	ScopeID           *int64             `json:"scope_id"`
	Target            *string            `json:"target"`
	Tasks             []string           `json:"tasks"`
	Priority          int32              `json:"priority"`
	ConcurrencyKey    string             `json:"concurrency_key"`
	ScheduledFor      pgtype.Timestamptz `json:"scheduled_for"`
	Status            string             `json:"status"`
	RequestedBy       string             `json:"requested_by"`
	DedupeKey         *string            `json:"dedupe_key"`
	ClaimedBy         *string            `json:"claimed_by"`
	LeaseUntil        pgtype.Timestamptz `json:"lease_until"`
	CancelRequestedAt pgtype.Timestamptz `json:"cancel_requested_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	RunID             string             `json:"run_id"`
}

func (q *Queries) AdminListGameCollectionJobs(ctx context.Context, arg AdminListGameCollectionJobsParams) ([]AdminListGameCollectionJobsRow, error) {
	rows, err := q.db.Query(ctx, adminListGameCollectionJobs,
		arg.Status,
		arg.JobKey,
		arg.Trigger,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListGameCollectionJobsRow{}
	for rows.Next() {
		var i AdminListGameCollectionJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.ScheduleVersion,
			&i.JobKey,
			&i.Trigger,
			&i.ScopeType,
			&i.ScopeID,
			&i.Target,
			&i.Tasks,
			&i.Priority,
			&i.ConcurrencyKey,
			&i.ScheduledFor,
			&i.Status,
			&i.RequestedBy,
			&i.DedupeKey,
			&i.ClaimedBy,
			&i.LeaseUntil,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListGameCollectionResults = `-- name: AdminListGameCollectionResults :many
SELECT id, run_id, task_type, game_id, appid, status, upstream_status_code, traffic_bucket, retry_count, duration_ms, error_kind, error_message, started_at, ended_at FROM gfg_collection_task_results
WHERE run_id = $1
  AND ($2::bigint IS NULL OR game_id = $2)
  AND ($3::bigint IS NULL OR appid = $3)
ORDER BY started_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type AdminListGameCollectionResultsParams struct {
	RunID     string `json:"run_id"`
	GameID    *int64 `json:"game_id"`
	Appid     *int64 `json:"appid"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

func (q *Queries) AdminListGameCollectionResults(ctx context.Context, arg AdminListGameCollectionResultsParams) ([]GfgCollectionTaskResult, error) {
	rows, err := q.db.Query(ctx, adminListGameCollectionResults,
		arg.RunID,
		arg.GameID,
		arg.Appid,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfgCollectionTaskResult{}
	for rows.Next() {
		var i GfgCollectionTaskResult
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TaskType,
			&i.GameID,
			&i.Appid,
			&i.Status,
			&i.UpstreamStatusCode,
			&i.TrafficBucket,
			&i.RetryCount,
			&i.DurationMs,
			&i.ErrorKind,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListGameCollectionRuns = `-- name: AdminListGameCollectionRuns :many
SELECT run.id, run.job_id, run.attempt_no, run.collector_instance_id, run.status, run.scheduled_for, run.started_at, run.ended_at, run.expected_count, run.attempted_count, run.success_count, run.partial_count, run.failure_count, run.skipped_count, run.schedule_delay_ms, run.duration_ms, run.error_kind, run.error_message, job.job_key, job.trigger, job.scope_type, job.scope_id, job.target
FROM gfg_collection_runs run
JOIN gfg_collection_jobs job ON job.id = run.job_id
WHERE ($1::text = '' OR run.status = $1)
  AND ($2::text = '' OR job.job_key = $2)
  AND ($3::text = '' OR job.trigger = $3)
  AND ($4::timestamptz IS NULL OR run.started_at >= $4)
  AND ($5::timestamptz IS NULL OR run.started_at <= $5)
ORDER BY run.started_at DESC
LIMIT $7 OFFSET $6
`

type AdminListGameCollectionRunsParams struct {
	Status    string             `json:"status"`
	JobKey    string             `json:"job_key"`
	Trigger   string             `json:"trigger"`
	Since     pgtype.Timestamptz `json:"since"`
	Until     pgtype.Timestamptz `json:"until"`
	RowOffset int32              `json:"row_offset"`
	RowLimit  int32              `json:"row_limit"`
}

type AdminListGameCollectionRunsRow struct {
	ID                  string             `json:"id"`
	JobID               int64              `json:"job_id"`
	AttemptNo           int32              `json:"attempt_no"`
	CollectorInstanceID string             `json:"collector_instance_id"`
	Status              string             `json:"status"`
	ScheduledFor        pgtype.Timestamptz `json:"scheduled_for"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	EndedAt             pgtype.Timestamptz `json:"ended_at"`
	ExpectedCount       int32              `json:"expected_count"`
	AttemptedCount      int32              `json:"attempted_count"`
	SuccessCount        int32              `json:"success_count"`
	PartialCount        int32              `json:"partial_count"`
	FailureCount        int32              `json:"failure_count"`
	SkippedCount        int32              `json:"skipped_count"`
	ScheduleDelayMs     int64              `json:"schedule_delay_ms"`
	DurationMs          int64              `json:"duration_ms"`
	ErrorKind           string             `json:"error_kind"`
	ErrorMessage        string             `json:"error_message"`
	JobKey              string             `json:"job_key"`
	Trigger             string             `json:"trigger"`
	ScopeType           string             `json:"scope_type"`
	ScopeID             *int64             `json:"scope_id"`
	Target              *string            `json:"target"`
}

func (q *Queries) AdminListGameCollectionRuns(ctx context.Context, arg AdminListGameCollectionRunsParams) ([]AdminListGameCollectionRunsRow, error) {
	rows, err := q.db.Query(ctx, adminListGameCollectionRuns,
		arg.Status,
		arg.JobKey,
		arg.Trigger,
		arg.Since,
		arg.Until,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListGameCollectionRunsRow{}
	for rows.Next() {
		var i AdminListGameCollectionRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptNo,
			&i.CollectorInstanceID,
			&i.Status,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.EndedAt,
			&i.ExpectedCount,
			&i.AttemptedCount,
			&i.SuccessCount,
			&i.PartialCount,
			&i.FailureCount,
			&i.SkippedCount,
			&i.ScheduleDelayMs,
			&i.DurationMs,
			&i.ErrorKind,
			&i.ErrorMessage,
			&i.JobKey,
			&i.Trigger,
			&i.ScopeType,
			&i.ScopeID,
			&i.Target,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListGameCollectionSchedules = `-- name: AdminListGameCollectionSchedules :many
SELECT schedule.id, schedule.job_key, schedule.name, schedule.enabled, schedule.schedule_kind, schedule.cron_expression, schedule.interval_seconds, schedule.anchor_at, schedule.timezone, schedule.misfire_policy, schedule.misfire_grace_seconds, schedule.overlap_policy, schedule.priority, schedule.concurrency_key, schedule.version, schedule.effective_from, schedule.last_materialized_for, schedule.next_scheduled_for, schedule.created_at, schedule.updated_at,
       COALESCE(latest.status, '') AS last_status,
       latest.success_count AS last_success_count,
       latest.expected_count AS last_expected_count
FROM gfg_collection_schedules schedule
LEFT JOIN LATERAL (
    SELECT job.status, run.success_count, run.expected_count
    FROM gfg_collection_jobs job
    LEFT JOIN gfg_collection_runs run ON run.job_id = job.id
    WHERE job.schedule_id = schedule.id
    ORDER BY job.created_at DESC, run.attempt_no DESC NULLS LAST
    LIMIT 1
) latest ON true
ORDER BY schedule.job_key
`

type AdminListGameCollectionSchedulesRow struct {
	ID                  int64              `json:"id"`
	JobKey              string             `json:"job_key"`
	Name                string             `json:"name"`
	Enabled             bool               `json:"enabled"`
	ScheduleKind        string             `json:"schedule_kind"`
	CronExpression      *string            `json:"cron_expression"`
	IntervalSeconds     *int64             `json:"interval_seconds"`
	AnchorAt            pgtype.Timestamptz `json:"anchor_at"`
	Timezone            string             `json:"timezone"`
	MisfirePolicy       string             `json:"misfire_policy"`
	MisfireGraceSeconds int32              `json:"misfire_grace_seconds"`
	OverlapPolicy       string             `json:"overlap_policy"`
	Priority            int32              `json:"priority"`
	ConcurrencyKey      string             `json:"concurrency_key"`
	Version             int64              `json:"version"`
	EffectiveFrom       pgtype.Timestamptz `json:"effective_from"`
	LastMaterializedFor pgtype.Timestamptz `json:"last_materialized_for"`
	NextScheduledFor    pgtype.Timestamptz `json:"next_scheduled_for"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LastStatus          string             `json:"last_status"`
	LastSuccessCount    *int32             `json:"last_success_count"`
	LastExpectedCount   *int32             `json:"last_expected_count"`
}

func (q *Queries) AdminListGameCollectionSchedules(ctx context.Context) ([]AdminListGameCollectionSchedulesRow, error) {
	rows, err := q.db.Query(ctx, adminListGameCollectionSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListGameCollectionSchedulesRow{}
	for rows.Next() {
		var i AdminListGameCollectionSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.JobKey,
			&i.Name,
			&i.Enabled,
			&i.ScheduleKind,
			&i.CronExpression,
			&i.IntervalSeconds,
			&i.AnchorAt,
			&i.Timezone,
			&i.MisfirePolicy,
			&i.MisfireGraceSeconds,
			&i.OverlapPolicy,
			&i.Priority,
			&i.ConcurrencyKey,
			&i.Version,
			&i.EffectiveFrom,
			&i.LastMaterializedFor,
			&i.NextScheduledFor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastStatus,
			&i.LastSuccessCount,
			&i.LastExpectedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListGameCollectorInstances = `-- name: AdminListGameCollectorInstances :many
SELECT instance.instance_id, instance.collector_id, instance.hostname, instance.version, instance.commit_sha, instance.capabilities, instance.started_at, instance.last_heartbeat_at, instance.stopped_at,
       GREATEST(0, extract(epoch FROM (now() - last_heartbeat_at)))::bigint AS heartbeat_age_seconds
FROM gfg_collector_instances instance
ORDER BY last_heartbeat_at DESC
LIMIT $1
`

type AdminListGameCollectorInstancesRow struct {
	InstanceID          string             `json:"instance_id"`
	CollectorID         string             `json:"collector_id"`
	Hostname            string             `json:"hostname"`
	Version             string             `json:"version"`
	CommitSha           string             `json:"commit_sha"`
	Capabilities        []string           `json:"capabilities"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	LastHeartbeatAt     pgtype.Timestamptz `json:"last_heartbeat_at"`
	StoppedAt           pgtype.Timestamptz `json:"stopped_at"`
	HeartbeatAgeSeconds int64              `json:"heartbeat_age_seconds"`
}

func (q *Queries) AdminListGameCollectorInstances(ctx context.Context, rowLimit int32) ([]AdminListGameCollectorInstancesRow, error) {
	rows, err := q.db.Query(ctx, adminListGameCollectorInstances, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListGameCollectorInstancesRow{}
	for rows.Next() {
		var i AdminListGameCollectorInstancesRow
		if err := rows.Scan(
			&i.InstanceID,
			&i.CollectorID,
			&i.Hostname,
			&i.Version,
			&i.CommitSha,
			&i.Capabilities,
			&i.StartedAt,
			&i.LastHeartbeatAt,
			&i.StoppedAt,
			&i.HeartbeatAgeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRetryGameCollectionJob = `-- name: AdminRetryGameCollectionJob :one
UPDATE gfg_collection_jobs
SET status = 'queued', claimed_by = NULL, lease_until = NULL,
    cancel_requested_at = NULL, completed_at = NULL,
    requested_by = $1, updated_at = now()
WHERE id = $2 AND status IN ('success', 'partial', 'failed', 'canceled')
RETURNING id, schedule_id, schedule_version, job_key, trigger, scope_type, scope_id, target, tasks, priority, concurrency_key, scheduled_for, status, requested_by, dedupe_key, claimed_by, lease_until, cancel_requested_at, created_at, updated_at, completed_at
`

type AdminRetryGameCollectionJobParams struct {
	RequestedBy string `json:"requested_by"`
	ID          int64  `json:"id"`
}

func (q *Queries) AdminRetryGameCollectionJob(ctx context.Context, arg AdminRetryGameCollectionJobParams) (GfgCollectionJob, error) {
	row := q.db.QueryRow(ctx, adminRetryGameCollectionJob, arg.RequestedBy, arg.ID)
	var i GfgCollectionJob
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.ScheduleVersion,
		&i.JobKey,
		&i.Trigger,
		&i.ScopeType,
		&i.ScopeID,
		&i.Target,
		&i.Tasks,
		&i.Priority,
		&i.ConcurrencyKey,
		&i.ScheduledFor,
		&i.Status,
		&i.RequestedBy,
		&i.DedupeKey,
		&i.ClaimedBy,
		&i.LeaseUntil,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const adminUpdateGameCollectionSchedule = `-- name: AdminUpdateGameCollectionSchedule :one
UPDATE gfg_collection_schedules
SET enabled = $1, schedule_kind = $2,
    cron_expression = $3, interval_seconds = $4,
    anchor_at = $5, timezone = $6,
    misfire_policy = $7,
    misfire_grace_seconds = $8,
    version = version + 1, effective_from = now(), last_materialized_for = now(),
    next_scheduled_for = NULL, updated_at = now()
WHERE id = $9
RETURNING id, job_key, name, enabled, schedule_kind, cron_expression, interval_seconds, anchor_at, timezone, misfire_policy, misfire_grace_seconds, overlap_policy, priority, concurrency_key, version, effective_from, last_materialized_for, next_scheduled_for, created_at, updated_at
`

type AdminUpdateGameCollectionScheduleParams struct {
	Enabled             bool               `json:"enabled"`
	ScheduleKind        string             `json:"schedule_kind"`
	CronExpression      *string            `json:"cron_expression"`
	IntervalSeconds     *int64             `json:"interval_seconds"`
	AnchorAt            pgtype.Timestamptz `json:"anchor_at"`
	Timezone            string             `json:"timezone"`
	MisfirePolicy       string             `json:"misfire_policy"`
	MisfireGraceSeconds int32              `json:"misfire_grace_seconds"`
	ID                  int64              `json:"id"`
}

func (q *Queries) AdminUpdateGameCollectionSchedule(ctx context.Context, arg AdminUpdateGameCollectionScheduleParams) (GfgCollectionSchedule, error) {
	row := q.db.QueryRow(ctx, adminUpdateGameCollectionSchedule,
		arg.Enabled,
		arg.ScheduleKind,
		arg.CronExpression,
		arg.IntervalSeconds,
		arg.AnchorAt,
		arg.Timezone,
		arg.MisfirePolicy,
		arg.MisfireGraceSeconds,
		arg.ID,
	)
	var i GfgCollectionSchedule
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.Name,
		&i.Enabled,
		&i.ScheduleKind,
		&i.CronExpression,
		&i.IntervalSeconds,
		&i.AnchorAt,
		&i.Timezone,
		&i.MisfirePolicy,
		&i.MisfireGraceSeconds,
		&i.OverlapPolicy,
		&i.Priority,
		&i.ConcurrencyKey,
		&i.Version,
		&i.EffectiveFrom,
		&i.LastMaterializedFor,
		&i.NextScheduledFor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueGameEntityCollectionJob = `-- name: EnqueueGameEntityCollectionJob :execrows
INSERT INTO gfg_collection_jobs (
    job_key, trigger, scope_type, scope_id, tasks, priority, concurrency_key,
    status, requested_by, dedupe_key, created_at, updated_at
) VALUES (
    'game.metadata', $1, 'game', $2::bigint,
    ARRAY['details', 'news']::text[], 300, 'steam', 'queued',
    $3,
    'game:' || ($2::bigint)::text || ':metadata:' || ($4::bigint)::text,
    now(), now()
)
ON CONFLICT (dedupe_key)
    WHERE dedupe_key IS NOT NULL AND status IN ('queued', 'running')
DO NOTHING
`

type EnqueueGameEntityCollectionJobParams struct {
	Trigger     string `json:"trigger"`
	GameID      int64  `json:"game_id"`
	RequestedBy string `json:"requested_by"`
	Appid       int64  `json:"appid"`
}

func (q *Queries) EnqueueGameEntityCollectionJob(ctx context.Context, arg EnqueueGameEntityCollectionJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueGameEntityCollectionJob,
		arg.Trigger,
		arg.GameID,
		arg.RequestedBy,
		arg.Appid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
