// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foundation.sql

package gamesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGameComments = `-- name: CountGameComments :one
SELECT COUNT(*)::bigint FROM gfg_game_comment WHERE $1::text='' OR content ILIKE '%'||$1||'%'
 OR region ILIKE '%'||$1||'%' OR name ILIKE '%'||$1||'%' OR ip ILIKE '%'||$1||'%'
 OR id::text ILIKE '%'||$1||'%' OR game_id::text ILIKE '%'||$1||'%'
`

func (q *Queries) CountGameComments(ctx context.Context, keyword string) (int64, error) {
	row := q.db.QueryRow(ctx, countGameComments, keyword)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countGameOptions = `-- name: CountGameOptions :one
SELECT COUNT(*)::bigint FROM gfg_game WHERE $1::text='' OR name ILIKE '%'||$1||'%' OR name_en ILIKE '%'||$1||'%' OR appid::text ILIKE '%'||$1||'%' OR id::text ILIKE '%'||$1||'%'
`

func (q *Queries) CountGameOptions(ctx context.Context, keyword string) (int64, error) {
	row := q.db.QueryRow(ctx, countGameOptions, keyword)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countGames = `-- name: CountGames :one
SELECT COUNT(*)::bigint FROM gfg_game WHERE $1::text='' OR name ILIKE '%'||$1||'%'
 OR name_en ILIKE '%'||$1||'%' OR info ILIKE '%'||$1||'%' OR info_en ILIKE '%'||$1||'%'
 OR id::text ILIKE '%'||$1||'%'
`

func (q *Queries) CountGames(ctx context.Context, keyword string) (int64, error) {
	row := q.db.QueryRow(ctx, countGames, keyword)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPrizes = `-- name: CountPrizes :one
SELECT COUNT(*)::bigint FROM gfg_prize WHERE $1::text='' OR title ILIKE '%'||$1||'%'
 OR "desc" ILIKE '%'||$1||'%' OR id::text ILIKE '%'||$1||'%'
`

func (q *Queries) CountPrizes(ctx context.Context, keyword string) (int64, error) {
	row := q.db.QueryRow(ctx, countPrizes, keyword)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTagOptions = `-- name: CountTagOptions :one
SELECT count(*) FROM gfg_tag t JOIN gfg_tag_category c ON c.id=t.category_id
WHERE t.archived_at IS NULL AND c.archived_at IS NULL AND
($1::text='' OR t.name ILIKE '%'||$1||'%' OR t.name_en ILIKE '%'||$1||'%' OR t.code ILIKE '%'||$1||'%' OR t.id::text ILIKE '%'||$1||'%')
`

func (q *Queries) CountTagOptions(ctx context.Context, keyword string) (int64, error) {
	row := q.db.QueryRow(ctx, countTagOptions, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGame = `-- name: DeleteGame :execrows
DELETE FROM gfg_game WHERE id=$1
`

func (q *Queries) DeleteGame(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGame, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGameComment = `-- name: DeleteGameComment :execrows
DELETE FROM gfg_game_comment WHERE id=$1
`

func (q *Queries) DeleteGameComment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGameComment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePrize = `-- name: DeletePrize :execrows
DELETE FROM gfg_prize WHERE id=$1
`

func (q *Queries) DeletePrize(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePrize, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findGameByAppIDExcluding = `-- name: FindGameByAppIDExcluding :one
SELECT id,name,appid FROM gfg_game WHERE appid=$1 AND id<>$2 LIMIT 1
`

type FindGameByAppIDExcludingParams struct {
	Appid     int64 `json:"appid"`
	ExcludeID int64 `json:"exclude_id"`
}

type FindGameByAppIDExcludingRow struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Appid int64  `json:"appid"`
}

func (q *Queries) FindGameByAppIDExcluding(ctx context.Context, arg FindGameByAppIDExcludingParams) (FindGameByAppIDExcludingRow, error) {
	row := q.db.QueryRow(ctx, findGameByAppIDExcluding, arg.Appid, arg.ExcludeID)
	var i FindGameByAppIDExcludingRow
	err := row.Scan(&i.ID, &i.Name, &i.Appid)
	return i, err
}

const foundationPing = `-- name: FoundationPing :one
SELECT 1::bigint AS value
`

func (q *Queries) FoundationPing(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, foundationPing)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const getGame = `-- name: GetGame :one
SELECT id,name,name_en,info,info_en,create_time,update_time,resources,groups,developers,publishers,appid,header,links,weight,view_count,
 COALESCE((SELECT tag_id FROM gfg_game_tag WHERE game_id=gfg_game.id AND role='primary'),0)::bigint AS primary_tag,
 COALESCE((SELECT tag_id FROM gfg_game_tag WHERE game_id=gfg_game.id AND role='secondary'),0)::bigint AS secondary_tag FROM gfg_game WHERE id=$1
`

type GetGameRow struct {
	ID           int64            `json:"id"`
	Name         string           `json:"name"`
	NameEn       string           `json:"name_en"`
	Info         string           `json:"info"`
	InfoEn       string           `json:"info_en"`
	CreateTime   pgtype.Timestamp `json:"create_time"`
	UpdateTime   pgtype.Timestamp `json:"update_time"`
	Resources    []byte           `json:"resources"`
	Groups       []byte           `json:"groups"`
	Developers   []byte           `json:"developers"`
	Publishers   []byte           `json:"publishers"`
	Appid        int64            `json:"appid"`
	Header       string           `json:"header"`
	Links        []byte           `json:"links"`
	Weight       int64            `json:"weight"`
	ViewCount    int64            `json:"view_count"`
	PrimaryTag   int64            `json:"primary_tag"`
	SecondaryTag int64            `json:"secondary_tag"`
}

func (q *Queries) GetGame(ctx context.Context, id int64) (GetGameRow, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i GetGameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Resources,
		&i.Groups,
		&i.Developers,
		&i.Publishers,
		&i.Appid,
		&i.Header,
		&i.Links,
		&i.Weight,
		&i.ViewCount,
		&i.PrimaryTag,
		&i.SecondaryTag,
	)
	return i, err
}

const getGameComment = `-- name: GetGameComment :one
SELECT id,region,content,score,create_time,game_id,ip,name FROM gfg_game_comment WHERE id=$1
`

func (q *Queries) GetGameComment(ctx context.Context, id int64) (GfgGameComment, error) {
	row := q.db.QueryRow(ctx, getGameComment, id)
	var i GfgGameComment
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.Content,
		&i.Score,
		&i.CreateTime,
		&i.GameID,
		&i.Ip,
		&i.Name,
	)
	return i, err
}

const getPrize = `-- name: GetPrize :one
SELECT id,title,"desc",prize,"key",start_time,end_time,create_time,status FROM gfg_prize WHERE id=$1
`

func (q *Queries) GetPrize(ctx context.Context, id int64) (GfgPrize, error) {
	row := q.db.QueryRow(ctx, getPrize, id)
	var i GfgPrize
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Desc,
		&i.Prize,
		&i.Key,
		&i.StartTime,
		&i.EndTime,
		&i.CreateTime,
		&i.Status,
	)
	return i, err
}

const insertGame = `-- name: InsertGame :one
INSERT INTO gfg_game (id,name,name_en,info,info_en,create_time,update_time,resources,groups,developers,publishers,appid,header,links,weight,view_count)
VALUES ($1,$2,$3,$4,$5,NOW()::timestamp(0),NOW()::timestamp(0),$6,$7,$8,$9,$10,$11,$12,$13,0)
RETURNING id,name,name_en,info,info_en,create_time,update_time,resources,groups,developers,publishers,appid,header,links,weight,view_count,
 COALESCE((SELECT tag_id FROM gfg_game_tag WHERE game_id=gfg_game.id AND role='primary'),0)::bigint AS primary_tag,
 COALESCE((SELECT tag_id FROM gfg_game_tag WHERE game_id=gfg_game.id AND role='secondary'),0)::bigint AS secondary_tag
`

type InsertGameParams struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	NameEn     string `json:"name_en"`
	Info       string `json:"info"`
	InfoEn     string `json:"info_en"`
	Resources  []byte `json:"resources"`
	Groups     []byte `json:"groups"`
	Developers []byte `json:"developers"`
	Publishers []byte `json:"publishers"`
	Appid      int64  `json:"appid"`
	Header     string `json:"header"`
	Links      []byte `json:"links"`
	Weight     int64  `json:"weight"`
}

type InsertGameRow struct {
	ID           int64            `json:"id"`
	Name         string           `json:"name"`
	NameEn       string           `json:"name_en"`
	Info         string           `json:"info"`
	InfoEn       string           `json:"info_en"`
	CreateTime   pgtype.Timestamp `json:"create_time"`
	UpdateTime   pgtype.Timestamp `json:"update_time"`
	Resources    []byte           `json:"resources"`
	Groups       []byte           `json:"groups"`
	Developers   []byte           `json:"developers"`
	Publishers   []byte           `json:"publishers"`
	Appid        int64            `json:"appid"`
	Header       string           `json:"header"`
	Links        []byte           `json:"links"`
	Weight       int64            `json:"weight"`
	ViewCount    int64            `json:"view_count"`
	PrimaryTag   int64            `json:"primary_tag"`
	SecondaryTag int64            `json:"secondary_tag"`
}

func (q *Queries) InsertGame(ctx context.Context, arg InsertGameParams) (InsertGameRow, error) {
	row := q.db.QueryRow(ctx, insertGame,
		arg.ID,
		arg.Name,
		arg.NameEn,
		arg.Info,
		arg.InfoEn,
		arg.Resources,
		arg.Groups,
		arg.Developers,
		arg.Publishers,
		arg.Appid,
		arg.Header,
		arg.Links,
		arg.Weight,
	)
	var i InsertGameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Resources,
		&i.Groups,
		&i.Developers,
		&i.Publishers,
		&i.Appid,
		&i.Header,
		&i.Links,
		&i.Weight,
		&i.ViewCount,
		&i.PrimaryTag,
		&i.SecondaryTag,
	)
	return i, err
}

const insertGameComment = `-- name: InsertGameComment :one
INSERT INTO gfg_game_comment (id,region,content,score,create_time,game_id,ip,name)
VALUES ($1,$2,$3,$4,NOW()::timestamp(0),$5,$6,$7)
RETURNING id,region,content,score,create_time,game_id,ip,name
`

type InsertGameCommentParams struct {
	ID      int64   `json:"id"`
	Region  string  `json:"region"`
	Content string  `json:"content"`
	Score   float64 `json:"score"`
	GameID  int64   `json:"game_id"`
	Ip      string  `json:"ip"`
	Name    string  `json:"name"`
}

func (q *Queries) InsertGameComment(ctx context.Context, arg InsertGameCommentParams) (GfgGameComment, error) {
	row := q.db.QueryRow(ctx, insertGameComment,
		arg.ID,
		arg.Region,
		arg.Content,
		arg.Score,
		arg.GameID,
		arg.Ip,
		arg.Name,
	)
	var i GfgGameComment
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.Content,
		&i.Score,
		&i.CreateTime,
		&i.GameID,
		&i.Ip,
		&i.Name,
	)
	return i, err
}

const insertPrize = `-- name: InsertPrize :one
INSERT INTO gfg_prize (id,title,"desc",prize,"key",start_time,end_time,create_time,status)
VALUES ($1,$2,$3,$4,$5,$6,$7,NOW()::timestamp(0),$8)
RETURNING id,title,"desc",prize,"key",start_time,end_time,create_time,status
`

type InsertPrizeParams struct {
	ID          int64            `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Prize       []byte           `json:"prize"`
	Key         string           `json:"key"`
	StartTime   pgtype.Timestamp `json:"start_time"`
	EndTime     pgtype.Timestamp `json:"end_time"`
	Status      bool             `json:"status"`
}

func (q *Queries) InsertPrize(ctx context.Context, arg InsertPrizeParams) (GfgPrize, error) {
	row := q.db.QueryRow(ctx, insertPrize,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Prize,
		arg.Key,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var i GfgPrize
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Desc,
		&i.Prize,
		&i.Key,
		&i.StartTime,
		&i.EndTime,
		&i.CreateTime,
		&i.Status,
	)
	return i, err
}

const listGameComments = `-- name: ListGameComments :many
SELECT id,region,content,score,create_time,game_id,ip,name FROM gfg_game_comment
WHERE $1::text='' OR content ILIKE '%'||$1||'%' OR region ILIKE '%'||$1||'%'
 OR name ILIKE '%'||$1||'%' OR ip ILIKE '%'||$1||'%' OR id::text ILIKE '%'||$1||'%'
 OR game_id::text ILIKE '%'||$1||'%' ORDER BY id DESC LIMIT $3 OFFSET $2
`

type ListGameCommentsParams struct {
	Keyword   string `json:"keyword"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

func (q *Queries) ListGameComments(ctx context.Context, arg ListGameCommentsParams) ([]GfgGameComment, error) {
	rows, err := q.db.Query(ctx, listGameComments, arg.Keyword, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfgGameComment{}
	for rows.Next() {
		var i GfgGameComment
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Content,
			&i.Score,
			&i.CreateTime,
			&i.GameID,
			&i.Ip,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameOptions = `-- name: ListGameOptions :many
SELECT id,name,name_en,appid FROM gfg_game WHERE $1::text='' OR name ILIKE '%'||$1||'%' OR name_en ILIKE '%'||$1||'%' OR appid::text ILIKE '%'||$1||'%' OR id::text ILIKE '%'||$1||'%'
ORDER BY id DESC LIMIT $3 OFFSET $2
`

type ListGameOptionsParams struct {
	Keyword   string `json:"keyword"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

type ListGameOptionsRow struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	NameEn string `json:"name_en"`
	Appid  int64  `json:"appid"`
}

func (q *Queries) ListGameOptions(ctx context.Context, arg ListGameOptionsParams) ([]ListGameOptionsRow, error) {
	rows, err := q.db.Query(ctx, listGameOptions, arg.Keyword, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameOptionsRow{}
	for rows.Next() {
		var i ListGameOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameEn,
			&i.Appid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameWorkspaceTags = `-- name: ListGameWorkspaceTags :many
SELECT m.game_id,m.tag_id,t.name::text AS tag_name,t.code,c.code AS category_code,m.role
FROM gfg_game_tag m JOIN gfg_tag t ON t.id=m.tag_id JOIN gfg_tag_category c ON c.id=t.category_id
WHERE m.game_id=$1 ORDER BY m.tag_id
`

type ListGameWorkspaceTagsRow struct {
	GameID       int64  `json:"game_id"`
	TagID        int64  `json:"tag_id"`
	TagName      string `json:"tag_name"`
	Code         string `json:"code"`
	CategoryCode string `json:"category_code"`
	Role         string `json:"role"`
}

func (q *Queries) ListGameWorkspaceTags(ctx context.Context, gameID int64) ([]ListGameWorkspaceTagsRow, error) {
	rows, err := q.db.Query(ctx, listGameWorkspaceTags, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameWorkspaceTagsRow{}
	for rows.Next() {
		var i ListGameWorkspaceTagsRow
		if err := rows.Scan(
			&i.GameID,
			&i.TagID,
			&i.TagName,
			&i.Code,
			&i.CategoryCode,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGames = `-- name: ListGames :many
SELECT id,name,name_en,info,info_en,create_time,update_time,resources,groups,developers,publishers,appid,header,links,weight,view_count,
 COALESCE((SELECT tag_id FROM gfg_game_tag WHERE game_id=gfg_game.id AND role='primary'),0)::bigint AS primary_tag,
 COALESCE((SELECT tag_id FROM gfg_game_tag WHERE game_id=gfg_game.id AND role='secondary'),0)::bigint AS secondary_tag FROM gfg_game
WHERE $1::text='' OR name ILIKE '%'||$1||'%' OR name_en ILIKE '%'||$1||'%'
 OR info ILIKE '%'||$1||'%' OR info_en ILIKE '%'||$1||'%' OR id::text ILIKE '%'||$1||'%'
ORDER BY id DESC LIMIT $3 OFFSET $2
`

type ListGamesParams struct {
	Keyword   string `json:"keyword"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

type ListGamesRow struct {
	ID           int64            `json:"id"`
	Name         string           `json:"name"`
	NameEn       string           `json:"name_en"`
	Info         string           `json:"info"`
	InfoEn       string           `json:"info_en"`
	CreateTime   pgtype.Timestamp `json:"create_time"`
	UpdateTime   pgtype.Timestamp `json:"update_time"`
	Resources    []byte           `json:"resources"`
	Groups       []byte           `json:"groups"`
	Developers   []byte           `json:"developers"`
	Publishers   []byte           `json:"publishers"`
	Appid        int64            `json:"appid"`
	Header       string           `json:"header"`
	Links        []byte           `json:"links"`
	Weight       int64            `json:"weight"`
	ViewCount    int64            `json:"view_count"`
	PrimaryTag   int64            `json:"primary_tag"`
	SecondaryTag int64            `json:"secondary_tag"`
}

func (q *Queries) ListGames(ctx context.Context, arg ListGamesParams) ([]ListGamesRow, error) {
	rows, err := q.db.Query(ctx, listGames, arg.Keyword, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGamesRow{}
	for rows.Next() {
		var i ListGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameEn,
			&i.Info,
			&i.InfoEn,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Resources,
			&i.Groups,
			&i.Developers,
			&i.Publishers,
			&i.Appid,
			&i.Header,
			&i.Links,
			&i.Weight,
			&i.ViewCount,
			&i.PrimaryTag,
			&i.SecondaryTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrizes = `-- name: ListPrizes :many
SELECT id,title,"desc",prize,"key",start_time,end_time,create_time,status FROM gfg_prize
WHERE $1::text='' OR title ILIKE '%'||$1||'%' OR "desc" ILIKE '%'||$1||'%'
 OR id::text ILIKE '%'||$1||'%' ORDER BY id DESC LIMIT $3 OFFSET $2
`

type ListPrizesParams struct {
	Keyword   string `json:"keyword"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

func (q *Queries) ListPrizes(ctx context.Context, arg ListPrizesParams) ([]GfgPrize, error) {
	rows, err := q.db.Query(ctx, listPrizes, arg.Keyword, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfgPrize{}
	for rows.Next() {
		var i GfgPrize
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Desc,
			&i.Prize,
			&i.Key,
			&i.StartTime,
			&i.EndTime,
			&i.CreateTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagOptions = `-- name: ListTagOptions :many
SELECT t.id,t.name,t.name_en FROM gfg_tag t JOIN gfg_tag_category c ON c.id=t.category_id
WHERE t.archived_at IS NULL AND c.archived_at IS NULL AND
($1::text='' OR t.name ILIKE '%'||$1||'%' OR t.name_en ILIKE '%'||$1||'%' OR t.code ILIKE '%'||$1||'%' OR t.id::text ILIKE '%'||$1||'%')
ORDER BY t.id DESC LIMIT $3 OFFSET $2
`

type ListTagOptionsParams struct {
	Keyword   string `json:"keyword"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

type ListTagOptionsRow struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	NameEn string `json:"name_en"`
}

func (q *Queries) ListTagOptions(ctx context.Context, arg ListTagOptionsParams) ([]ListTagOptionsRow, error) {
	rows, err := q.db.Query(ctx, listTagOptions, arg.Keyword, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagOptionsRow{}
	for rows.Next() {
		var i ListTagOptionsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.NameEn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextGameID = `-- name: NextGameID :one
SELECT nextval('gfg_game_id_seq')::bigint
`

func (q *Queries) NextGameID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextGameID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextPrizeID = `-- name: NextPrizeID :one
WITH lock_row AS MATERIALIZED (SELECT pg_advisory_xact_lock(hashtext('gfg_prize')::bigint))
SELECT (COALESCE(MAX(id),0)+1)::bigint FROM gfg_prize CROSS JOIN lock_row
`

func (q *Queries) NextPrizeID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextPrizeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateGame = `-- name: UpdateGame :one
UPDATE gfg_game SET name=$1,name_en=$2,info=$3,info_en=$4,resources=$5,groups=$6,developers=$7,publishers=$8,appid=$9,header=$10,links=$11,update_time=NOW()::timestamp(0)
WHERE id=$12
RETURNING id,name,name_en,info,info_en,create_time,update_time,resources,groups,developers,publishers,appid,header,links,weight,view_count,
 COALESCE((SELECT tag_id FROM gfg_game_tag WHERE game_id=gfg_game.id AND role='primary'),0)::bigint AS primary_tag,
 COALESCE((SELECT tag_id FROM gfg_game_tag WHERE game_id=gfg_game.id AND role='secondary'),0)::bigint AS secondary_tag
`

type UpdateGameParams struct {
	Name       string `json:"name"`
	NameEn     string `json:"name_en"`
	Info       string `json:"info"`
	InfoEn     string `json:"info_en"`
	Resources  []byte `json:"resources"`
	Groups     []byte `json:"groups"`
	Developers []byte `json:"developers"`
	Publishers []byte `json:"publishers"`
	Appid      int64  `json:"appid"`
	Header     string `json:"header"`
	Links      []byte `json:"links"`
	ID         int64  `json:"id"`
}

type UpdateGameRow struct {
	ID           int64            `json:"id"`
	Name         string           `json:"name"`
	NameEn       string           `json:"name_en"`
	Info         string           `json:"info"`
	InfoEn       string           `json:"info_en"`
	CreateTime   pgtype.Timestamp `json:"create_time"`
	UpdateTime   pgtype.Timestamp `json:"update_time"`
	Resources    []byte           `json:"resources"`
	Groups       []byte           `json:"groups"`
	Developers   []byte           `json:"developers"`
	Publishers   []byte           `json:"publishers"`
	Appid        int64            `json:"appid"`
	Header       string           `json:"header"`
	Links        []byte           `json:"links"`
	Weight       int64            `json:"weight"`
	ViewCount    int64            `json:"view_count"`
	PrimaryTag   int64            `json:"primary_tag"`
	SecondaryTag int64            `json:"secondary_tag"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (UpdateGameRow, error) {
	row := q.db.QueryRow(ctx, updateGame,
		arg.Name,
		arg.NameEn,
		arg.Info,
		arg.InfoEn,
		arg.Resources,
		arg.Groups,
		arg.Developers,
		arg.Publishers,
		arg.Appid,
		arg.Header,
		arg.Links,
		arg.ID,
	)
	var i UpdateGameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Resources,
		&i.Groups,
		&i.Developers,
		&i.Publishers,
		&i.Appid,
		&i.Header,
		&i.Links,
		&i.Weight,
		&i.ViewCount,
		&i.PrimaryTag,
		&i.SecondaryTag,
	)
	return i, err
}

const updateGameComment = `-- name: UpdateGameComment :one
UPDATE gfg_game_comment SET region=$1,content=$2,score=$3,game_id=$4,ip=$5,name=$6
WHERE id=$7 RETURNING id,region,content,score,create_time,game_id,ip,name
`

type UpdateGameCommentParams struct {
	Region  string  `json:"region"`
	Content string  `json:"content"`
	Score   float64 `json:"score"`
	GameID  int64   `json:"game_id"`
	Ip      string  `json:"ip"`
	Name    string  `json:"name"`
	ID      int64   `json:"id"`
}

func (q *Queries) UpdateGameComment(ctx context.Context, arg UpdateGameCommentParams) (GfgGameComment, error) {
	row := q.db.QueryRow(ctx, updateGameComment,
		arg.Region,
		arg.Content,
		arg.Score,
		arg.GameID,
		arg.Ip,
		arg.Name,
		arg.ID,
	)
	var i GfgGameComment
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.Content,
		&i.Score,
		&i.CreateTime,
		&i.GameID,
		&i.Ip,
		&i.Name,
	)
	return i, err
}

const updatePrize = `-- name: UpdatePrize :one
UPDATE gfg_prize SET title=$1,"desc"=$2,prize=$3,"key"=$4,start_time=$5,end_time=$6,status=$7
WHERE id=$8 RETURNING id,title,"desc",prize,"key",start_time,end_time,create_time,status
`

type UpdatePrizeParams struct {
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Prize       []byte           `json:"prize"`
	Key         string           `json:"key"`
	StartTime   pgtype.Timestamp `json:"start_time"`
	EndTime     pgtype.Timestamp `json:"end_time"`
	Status      bool             `json:"status"`
	ID          int64            `json:"id"`
}

func (q *Queries) UpdatePrize(ctx context.Context, arg UpdatePrizeParams) (GfgPrize, error) {
	row := q.db.QueryRow(ctx, updatePrize,
		arg.Title,
		arg.Description,
		arg.Prize,
		arg.Key,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.ID,
	)
	var i GfgPrize
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Desc,
		&i.Prize,
		&i.Key,
		&i.StartTime,
		&i.EndTime,
		&i.CreateTime,
		&i.Status,
	)
	return i, err
}
