// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_collections.sql

package gamesqlc

import (
	"context"
)

const bumpCuratedCollectionVersion = `-- name: BumpCuratedCollectionVersion :exec
UPDATE gfg_game_collection SET version=version+1,updated_at=now() WHERE id=$1
`

func (q *Queries) BumpCuratedCollectionVersion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, bumpCuratedCollectionVersion, id)
	return err
}

const clearCollectionHomePlacements = `-- name: ClearCollectionHomePlacements :exec
DELETE FROM gfg_game_collection_home_slot
`

func (q *Queries) ClearCollectionHomePlacements(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearCollectionHomePlacements)
	return err
}

const countCuratedCollections = `-- name: CountCuratedCollections :one
WITH selected_collections AS (SELECT id FROM gfg_game_collection WHERE ($2::text='' OR status=$2)),
candidate_members AS (
    SELECT i.collection_id, i.game_id FROM gfg_game_collection_item i
    JOIN selected_collections c ON c.id = i.collection_id
    UNION
    SELECT rule.collection_id, gt.game_id FROM gfg_game_collection_tag rule
    JOIN selected_collections c ON c.id = rule.collection_id
    JOIN gfg_tag t ON t.id = rule.tag_id AND t.archived_at IS NULL
    JOIN gfg_tag_category cat ON cat.id = t.category_id AND cat.archived_at IS NULL
    JOIN gfg_game_tag gt ON gt.tag_id = t.id
), effective_members AS (
    SELECT m.collection_id, m.game_id FROM candidate_members m
    WHERE NOT EXISTS (SELECT 1 FROM gfg_game_collection_exclusion x
        WHERE x.collection_id = m.collection_id AND x.game_id = m.game_id)
)
SELECT count(*) FROM gfg_game_collection c
WHERE ($1::text='' OR c.code ILIKE '%'||$1||'%' OR c.name ILIKE '%'||$1||'%' OR c.name_en ILIKE '%'||$1||'%')
AND ($2::text='' OR c.status=$2)
AND (NOT $3::boolean OR (c.status='published' AND EXISTS (
 SELECT 1 FROM effective_members i WHERE i.collection_id=c.id
 AND NOT EXISTS (SELECT 1 FROM gfg_game_tag gt JOIN gfg_tag t ON t.id=gt.tag_id WHERE gt.game_id=i.game_id AND t.code='adult')
)))
`

type CountCuratedCollectionsParams struct {
	Keyword      string `json:"keyword"`
	Status       string `json:"status"`
	HomeEligible bool   `json:"home_eligible"`
}

func (q *Queries) CountCuratedCollections(ctx context.Context, arg CountCuratedCollectionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCuratedCollections, arg.Keyword, arg.Status, arg.HomeEligible)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRemovedCollectionExclusions = `-- name: DeleteRemovedCollectionExclusions :exec
DELETE FROM gfg_game_collection_exclusion WHERE collection_id=$1 AND NOT(game_id=ANY($2::bigint[]))
`

type DeleteRemovedCollectionExclusionsParams struct {
	CollectionID int64   `json:"collection_id"`
	GameIds      []int64 `json:"game_ids"`
}

func (q *Queries) DeleteRemovedCollectionExclusions(ctx context.Context, arg DeleteRemovedCollectionExclusionsParams) error {
	_, err := q.db.Exec(ctx, deleteRemovedCollectionExclusions, arg.CollectionID, arg.GameIds)
	return err
}

const deleteRemovedCollectionMembers = `-- name: DeleteRemovedCollectionMembers :exec
DELETE FROM gfg_game_collection_item WHERE collection_id=$1 AND NOT(game_id=ANY($2::bigint[]))
`

type DeleteRemovedCollectionMembersParams struct {
	CollectionID int64   `json:"collection_id"`
	GameIds      []int64 `json:"game_ids"`
}

func (q *Queries) DeleteRemovedCollectionMembers(ctx context.Context, arg DeleteRemovedCollectionMembersParams) error {
	_, err := q.db.Exec(ctx, deleteRemovedCollectionMembers, arg.CollectionID, arg.GameIds)
	return err
}

const deleteRemovedCollectionRules = `-- name: DeleteRemovedCollectionRules :exec
DELETE FROM gfg_game_collection_tag WHERE collection_id=$1 AND NOT(tag_id=ANY($2::bigint[]))
`

type DeleteRemovedCollectionRulesParams struct {
	CollectionID int64   `json:"collection_id"`
	TagIds       []int64 `json:"tag_ids"`
}

func (q *Queries) DeleteRemovedCollectionRules(ctx context.Context, arg DeleteRemovedCollectionRulesParams) error {
	_, err := q.db.Exec(ctx, deleteRemovedCollectionRules, arg.CollectionID, arg.TagIds)
	return err
}

const existingCuratedCollectionGameIDs = `-- name: ExistingCuratedCollectionGameIDs :many
SELECT id FROM gfg_game WHERE id=ANY($1::bigint[]) ORDER BY id FOR KEY SHARE
`

func (q *Queries) ExistingCuratedCollectionGameIDs(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, existingCuratedCollectionGameIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionCompositionMembers = `-- name: GetCollectionCompositionMembers :many
WITH sources AS (
 SELECT gt.game_id, true AS automatic, false AS manual, false AS excluded
 FROM gfg_game_collection_tag rule
 JOIN gfg_tag t ON t.id=rule.tag_id AND t.archived_at IS NULL
 JOIN gfg_tag_category cat ON cat.id=t.category_id AND cat.archived_at IS NULL
 JOIN gfg_game_tag gt ON gt.tag_id=t.id
 WHERE rule.collection_id=$1
 UNION ALL
 SELECT game_id, false, true, false FROM gfg_game_collection_item WHERE collection_id=$1
 UNION ALL
 SELECT game_id, false, false, true FROM gfg_game_collection_exclusion WHERE collection_id=$1
), membership AS (
 SELECT game_id, bool_or(automatic)::boolean AS automatic, bool_or(manual)::boolean AS manual, bool_or(excluded)::boolean AS excluded
 FROM sources GROUP BY game_id
)
SELECT g.id AS game_id, g.name, g.name_en, g.appid, m.automatic, m.manual, m.excluded,
 EXISTS(SELECT 1 FROM gfg_game_tag gt JOIN gfg_tag t ON t.id=gt.tag_id WHERE gt.game_id=g.id AND t.code='adult')::boolean AS adult
FROM membership m JOIN gfg_game g ON g.id=m.game_id ORDER BY g.id
`

type GetCollectionCompositionMembersRow struct {
	GameID    int64  `json:"game_id"`
	Name      string `json:"name"`
	NameEn    string `json:"name_en"`
	Appid     int64  `json:"appid"`
	Automatic bool   `json:"automatic"`
	Manual    bool   `json:"manual"`
	Excluded  bool   `json:"excluded"`
	Adult     bool   `json:"adult"`
}

func (q *Queries) GetCollectionCompositionMembers(ctx context.Context, collectionID int64) ([]GetCollectionCompositionMembersRow, error) {
	rows, err := q.db.Query(ctx, getCollectionCompositionMembers, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCollectionCompositionMembersRow{}
	for rows.Next() {
		var i GetCollectionCompositionMembersRow
		if err := rows.Scan(
			&i.GameID,
			&i.Name,
			&i.NameEn,
			&i.Appid,
			&i.Automatic,
			&i.Manual,
			&i.Excluded,
			&i.Adult,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionExcludedIDs = `-- name: GetCollectionExcludedIDs :many
SELECT game_id FROM gfg_game_collection_exclusion WHERE collection_id=$1 ORDER BY game_id
`

func (q *Queries) GetCollectionExcludedIDs(ctx context.Context, collectionID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getCollectionExcludedIDs, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var game_id int64
		if err := rows.Scan(&game_id); err != nil {
			return nil, err
		}
		items = append(items, game_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionHomePlacements = `-- name: GetCollectionHomePlacements :many
SELECT slot,collection_id FROM gfg_game_collection_home_slot ORDER BY slot
`

type GetCollectionHomePlacementsRow struct {
	Slot         int16 `json:"slot"`
	CollectionID int64 `json:"collection_id"`
}

func (q *Queries) GetCollectionHomePlacements(ctx context.Context) ([]GetCollectionHomePlacementsRow, error) {
	rows, err := q.db.Query(ctx, getCollectionHomePlacements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCollectionHomePlacementsRow{}
	for rows.Next() {
		var i GetCollectionHomePlacementsRow
		if err := rows.Scan(&i.Slot, &i.CollectionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionRuleTags = `-- name: GetCollectionRuleTags :many
SELECT t.id AS tag_id, t.code, t.name, t.name_en,
 (t.archived_at IS NULL AND cat.archived_at IS NULL)::boolean AS active
FROM gfg_game_collection_tag rule JOIN gfg_tag t ON t.id=rule.tag_id
JOIN gfg_tag_category cat ON cat.id=t.category_id
WHERE rule.collection_id=$1 ORDER BY t.id
`

type GetCollectionRuleTagsRow struct {
	TagID  int64  `json:"tag_id"`
	Code   string `json:"code"`
	Name   string `json:"name"`
	NameEn string `json:"name_en"`
	Active bool   `json:"active"`
}

func (q *Queries) GetCollectionRuleTags(ctx context.Context, collectionID int64) ([]GetCollectionRuleTagsRow, error) {
	rows, err := q.db.Query(ctx, getCollectionRuleTags, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCollectionRuleTagsRow{}
	for rows.Next() {
		var i GetCollectionRuleTagsRow
		if err := rows.Scan(
			&i.TagID,
			&i.Code,
			&i.Name,
			&i.NameEn,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCuratedCollectionMembers = `-- name: GetCuratedCollectionMembers :many
SELECT g.id AS game_id,g.name,g.name_en,g.appid,
 EXISTS(SELECT 1 FROM gfg_game_tag gt JOIN gfg_tag t ON t.id=gt.tag_id WHERE gt.game_id=g.id AND t.code='adult')::boolean AS adult
FROM gfg_game_collection_item i JOIN gfg_game g ON g.id=i.game_id
WHERE i.collection_id=$1 ORDER BY g.id
`

type GetCuratedCollectionMembersRow struct {
	GameID int64  `json:"game_id"`
	Name   string `json:"name"`
	NameEn string `json:"name_en"`
	Appid  int64  `json:"appid"`
	Adult  bool   `json:"adult"`
}

func (q *Queries) GetCuratedCollectionMembers(ctx context.Context, collectionID int64) ([]GetCuratedCollectionMembersRow, error) {
	rows, err := q.db.Query(ctx, getCuratedCollectionMembers, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCuratedCollectionMembersRow{}
	for rows.Next() {
		var i GetCuratedCollectionMembersRow
		if err := rows.Scan(
			&i.GameID,
			&i.Name,
			&i.NameEn,
			&i.Appid,
			&i.Adult,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCuratedCollectionSnapshots = `-- name: GetCuratedCollectionSnapshots :many
WITH selected_collections AS (SELECT id FROM gfg_game_collection WHERE id=ANY($1::bigint[])),
candidate_members AS (
    SELECT i.collection_id, i.game_id FROM gfg_game_collection_item i
    JOIN selected_collections c ON c.id = i.collection_id
    UNION
    SELECT rule.collection_id, gt.game_id FROM gfg_game_collection_tag rule
    JOIN selected_collections c ON c.id = rule.collection_id
    JOIN gfg_tag t ON t.id = rule.tag_id AND t.archived_at IS NULL
    JOIN gfg_tag_category cat ON cat.id = t.category_id AND cat.archived_at IS NULL
    JOIN gfg_game_tag gt ON gt.tag_id = t.id
), effective_members AS (
    SELECT m.collection_id, m.game_id FROM candidate_members m
    WHERE NOT EXISTS (SELECT 1 FROM gfg_game_collection_exclusion x
        WHERE x.collection_id = m.collection_id AND x.game_id = m.game_id)
)
SELECT c.id, c.code, c.name, c.name_en, c.info, c.info_en, c.status, c.version, c.published_at, c.archived_at, c.created_at, c.updated_at, h.slot AS home_slot,
 (SELECT count(*) FROM effective_members i WHERE i.collection_id=c.id)::bigint AS member_count,
 (SELECT count(*) FROM effective_members i WHERE i.collection_id=c.id
  AND NOT EXISTS (SELECT 1 FROM gfg_game_tag gt JOIN gfg_tag t ON t.id=gt.tag_id WHERE gt.game_id=i.game_id AND t.code='adult'))::bigint AS sfw_member_count
FROM gfg_game_collection c LEFT JOIN gfg_game_collection_home_slot h ON h.collection_id=c.id
WHERE c.id=ANY($1::bigint[]) ORDER BY c.updated_at DESC,c.id DESC
`

type GetCuratedCollectionSnapshotsRow struct {
	GfgGameCollection GfgGameCollection `json:"gfg_game_collection"`
	HomeSlot          *int16            `json:"home_slot"`
	MemberCount       int64             `json:"member_count"`
	SfwMemberCount    int64             `json:"sfw_member_count"`
}

func (q *Queries) GetCuratedCollectionSnapshots(ctx context.Context, ids []int64) ([]GetCuratedCollectionSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, getCuratedCollectionSnapshots, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCuratedCollectionSnapshotsRow{}
	for rows.Next() {
		var i GetCuratedCollectionSnapshotsRow
		if err := rows.Scan(
			&i.GfgGameCollection.ID,
			&i.GfgGameCollection.Code,
			&i.GfgGameCollection.Name,
			&i.GfgGameCollection.NameEn,
			&i.GfgGameCollection.Info,
			&i.GfgGameCollection.InfoEn,
			&i.GfgGameCollection.Status,
			&i.GfgGameCollection.Version,
			&i.GfgGameCollection.PublishedAt,
			&i.GfgGameCollection.ArchivedAt,
			&i.GfgGameCollection.CreatedAt,
			&i.GfgGameCollection.UpdatedAt,
			&i.HomeSlot,
			&i.MemberCount,
			&i.SfwMemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCollectionExclusions = `-- name: InsertCollectionExclusions :exec
INSERT INTO gfg_game_collection_exclusion(collection_id,game_id)
SELECT $1::bigint,unnest($2::bigint[])
ON CONFLICT(collection_id,game_id) DO NOTHING
`

type InsertCollectionExclusionsParams struct {
	CollectionID int64   `json:"collection_id"`
	GameIds      []int64 `json:"game_ids"`
}

func (q *Queries) InsertCollectionExclusions(ctx context.Context, arg InsertCollectionExclusionsParams) error {
	_, err := q.db.Exec(ctx, insertCollectionExclusions, arg.CollectionID, arg.GameIds)
	return err
}

const insertCollectionHomePlacements = `-- name: InsertCollectionHomePlacements :exec
INSERT INTO gfg_game_collection_home_slot(slot,collection_id)
SELECT unnest($1::smallint[]),unnest($2::bigint[])
`

type InsertCollectionHomePlacementsParams struct {
	Slots         []int16 `json:"slots"`
	CollectionIds []int64 `json:"collection_ids"`
}

func (q *Queries) InsertCollectionHomePlacements(ctx context.Context, arg InsertCollectionHomePlacementsParams) error {
	_, err := q.db.Exec(ctx, insertCollectionHomePlacements, arg.Slots, arg.CollectionIds)
	return err
}

const insertCollectionMembers = `-- name: InsertCollectionMembers :exec
INSERT INTO gfg_game_collection_item(collection_id,game_id)
SELECT $1::bigint,unnest($2::bigint[])
ON CONFLICT(collection_id,game_id) DO NOTHING
`

type InsertCollectionMembersParams struct {
	CollectionID int64   `json:"collection_id"`
	GameIds      []int64 `json:"game_ids"`
}

func (q *Queries) InsertCollectionMembers(ctx context.Context, arg InsertCollectionMembersParams) error {
	_, err := q.db.Exec(ctx, insertCollectionMembers, arg.CollectionID, arg.GameIds)
	return err
}

const insertCollectionRules = `-- name: InsertCollectionRules :exec
INSERT INTO gfg_game_collection_tag(collection_id,tag_id)
SELECT $1::bigint,unnest($2::bigint[])
ON CONFLICT(collection_id,tag_id) DO NOTHING
`

type InsertCollectionRulesParams struct {
	CollectionID int64   `json:"collection_id"`
	TagIds       []int64 `json:"tag_ids"`
}

func (q *Queries) InsertCollectionRules(ctx context.Context, arg InsertCollectionRulesParams) error {
	_, err := q.db.Exec(ctx, insertCollectionRules, arg.CollectionID, arg.TagIds)
	return err
}

const insertCuratedCollection = `-- name: InsertCuratedCollection :one
INSERT INTO gfg_game_collection(code,name,name_en,info,info_en)
VALUES($1,$2,$3,$4,$5) RETURNING id
`

type InsertCuratedCollectionParams struct {
	Code   string `json:"code"`
	Name   string `json:"name"`
	NameEn string `json:"name_en"`
	Info   string `json:"info"`
	InfoEn string `json:"info_en"`
}

func (q *Queries) InsertCuratedCollection(ctx context.Context, arg InsertCuratedCollectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertCuratedCollection,
		arg.Code,
		arg.Name,
		arg.NameEn,
		arg.Info,
		arg.InfoEn,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCuratedCollectionIDs = `-- name: ListCuratedCollectionIDs :many
WITH selected_collections AS (SELECT id FROM gfg_game_collection WHERE ($2::text='' OR status=$2)),
candidate_members AS (
    SELECT i.collection_id, i.game_id FROM gfg_game_collection_item i
    JOIN selected_collections c ON c.id = i.collection_id
    UNION
    SELECT rule.collection_id, gt.game_id FROM gfg_game_collection_tag rule
    JOIN selected_collections c ON c.id = rule.collection_id
    JOIN gfg_tag t ON t.id = rule.tag_id AND t.archived_at IS NULL
    JOIN gfg_tag_category cat ON cat.id = t.category_id AND cat.archived_at IS NULL
    JOIN gfg_game_tag gt ON gt.tag_id = t.id
), effective_members AS (
    SELECT m.collection_id, m.game_id FROM candidate_members m
    WHERE NOT EXISTS (SELECT 1 FROM gfg_game_collection_exclusion x
        WHERE x.collection_id = m.collection_id AND x.game_id = m.game_id)
)
SELECT c.id FROM gfg_game_collection c
WHERE ($1::text='' OR c.code ILIKE '%'||$1||'%' OR c.name ILIKE '%'||$1||'%' OR c.name_en ILIKE '%'||$1||'%')
AND ($2::text='' OR c.status=$2)
AND (NOT $3::boolean OR (c.status='published' AND EXISTS (
 SELECT 1 FROM effective_members i WHERE i.collection_id=c.id
 AND NOT EXISTS (SELECT 1 FROM gfg_game_tag gt JOIN gfg_tag t ON t.id=gt.tag_id WHERE gt.game_id=i.game_id AND t.code='adult')
)))
ORDER BY c.updated_at DESC,c.id DESC LIMIT $5 OFFSET $4
`

type ListCuratedCollectionIDsParams struct {
	Keyword      string `json:"keyword"`
	Status       string `json:"status"`
	HomeEligible bool   `json:"home_eligible"`
	RowOffset    int32  `json:"row_offset"`
	RowLimit     int32  `json:"row_limit"`
}

func (q *Queries) ListCuratedCollectionIDs(ctx context.Context, arg ListCuratedCollectionIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listCuratedCollectionIDs,
		arg.Keyword,
		arg.Status,
		arg.HomeEligible,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCollectionForUpdate = `-- name: LockCollectionForUpdate :one
SELECT id, code, name, name_en, info, info_en, status, version, published_at, archived_at, created_at, updated_at FROM gfg_game_collection WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockCollectionForUpdate(ctx context.Context, id int64) (GfgGameCollection, error) {
	row := q.db.QueryRow(ctx, lockCollectionForUpdate, id)
	var i GfgGameCollection
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.Status,
		&i.Version,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockGameCollectionDomain = `-- name: LockGameCollectionDomain :exec
SELECT pg_advisory_xact_lock(hashtextextended('gfg.game-collection-domain',0))
`

// Collection writes serialize before row locks; this is unrelated to Collector Control Plane.
func (q *Queries) LockGameCollectionDomain(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockGameCollectionDomain)
	return err
}

const removeCollectionHomeSlot = `-- name: RemoveCollectionHomeSlot :exec
DELETE FROM gfg_game_collection_home_slot WHERE collection_id=$1
`

func (q *Queries) RemoveCollectionHomeSlot(ctx context.Context, collectionID int64) error {
	_, err := q.db.Exec(ctx, removeCollectionHomeSlot, collectionID)
	return err
}

const transitionCuratedCollection = `-- name: TransitionCuratedCollection :exec
UPDATE gfg_game_collection SET status=$1,
 published_at=CASE WHEN $1='published' THEN now() ELSE published_at END,
 archived_at=CASE WHEN $1='archived' THEN now() ELSE NULL END,
 version=version+1,updated_at=now() WHERE id=$2
`

type TransitionCuratedCollectionParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) TransitionCuratedCollection(ctx context.Context, arg TransitionCuratedCollectionParams) error {
	_, err := q.db.Exec(ctx, transitionCuratedCollection, arg.Status, arg.ID)
	return err
}

const updateCuratedCollectionContent = `-- name: UpdateCuratedCollectionContent :exec
UPDATE gfg_game_collection SET name=$1,name_en=$2,info=$3,info_en=$4,version=version+1,updated_at=now() WHERE id=$5
`

type UpdateCuratedCollectionContentParams struct {
	Name   string `json:"name"`
	NameEn string `json:"name_en"`
	Info   string `json:"info"`
	InfoEn string `json:"info_en"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateCuratedCollectionContent(ctx context.Context, arg UpdateCuratedCollectionContentParams) error {
	_, err := q.db.Exec(ctx, updateCuratedCollectionContent,
		arg.Name,
		arg.NameEn,
		arg.Info,
		arg.InfoEn,
		arg.ID,
	)
	return err
}

const validateCollectionRuleTags = `-- name: ValidateCollectionRuleTags :many
SELECT t.id, (t.archived_at IS NULL AND cat.archived_at IS NULL)::boolean AS active,
 EXISTS(SELECT 1 FROM gfg_game_collection_tag rule WHERE rule.collection_id=$1 AND rule.tag_id=t.id)::boolean AS already_bound
FROM gfg_tag t JOIN gfg_tag_category cat ON cat.id=t.category_id
WHERE t.id=ANY($2::bigint[]) ORDER BY t.id FOR KEY SHARE OF t
`

type ValidateCollectionRuleTagsParams struct {
	CollectionID int64   `json:"collection_id"`
	TagIds       []int64 `json:"tag_ids"`
}

type ValidateCollectionRuleTagsRow struct {
	ID           int64 `json:"id"`
	Active       bool  `json:"active"`
	AlreadyBound bool  `json:"already_bound"`
}

func (q *Queries) ValidateCollectionRuleTags(ctx context.Context, arg ValidateCollectionRuleTagsParams) ([]ValidateCollectionRuleTagsRow, error) {
	rows, err := q.db.Query(ctx, validateCollectionRuleTags, arg.CollectionID, arg.TagIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ValidateCollectionRuleTagsRow{}
	for rows.Next() {
		var i ValidateCollectionRuleTagsRow
		if err := rows.Scan(&i.ID, &i.Active, &i.AlreadyBound); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
