// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag_domain.sql

package gamesqlc

import (
	"context"
)

const activeCategoryTagCount = `-- name: ActiveCategoryTagCount :one
SELECT count(*) FROM gfg_tag WHERE category_id=$1 AND archived_at IS NULL
`

func (q *Queries) ActiveCategoryTagCount(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, activeCategoryTagCount, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const archiveTag = `-- name: ArchiveTag :one
UPDATE gfg_tag SET archived_at=CASE WHEN $1::boolean THEN COALESCE(archived_at,NOW()::timestamp(0)) ELSE NULL END,update_time=NOW()::timestamp(0)
WHERE id=$2 RETURNING id, name, name_en, info, info_en, create_time, update_time, code, category_id, archived_at
`

type ArchiveTagParams struct {
	Archive bool  `json:"archive"`
	ID      int64 `json:"id"`
}

func (q *Queries) ArchiveTag(ctx context.Context, arg ArchiveTagParams) (GfgTag, error) {
	row := q.db.QueryRow(ctx, archiveTag, arg.Archive, arg.ID)
	var i GfgTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Code,
		&i.CategoryID,
		&i.ArchivedAt,
	)
	return i, err
}

const archiveTagCategory = `-- name: ArchiveTagCategory :one
UPDATE gfg_tag_category SET archived_at=CASE WHEN $1::boolean THEN COALESCE(archived_at,NOW()::timestamp(0)) ELSE NULL END,update_time=NOW()::timestamp(0)
WHERE id=$2 RETURNING id, code, name, name_en, info, info_en, sort_order, archived_at, create_time, update_time
`

type ArchiveTagCategoryParams struct {
	Archive bool  `json:"archive"`
	ID      int64 `json:"id"`
}

func (q *Queries) ArchiveTagCategory(ctx context.Context, arg ArchiveTagCategoryParams) (GfgTagCategory, error) {
	row := q.db.QueryRow(ctx, archiveTagCategory, arg.Archive, arg.ID)
	var i GfgTagCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const clearChangedGameTagRoles = `-- name: ClearChangedGameTagRoles :exec
UPDATE gfg_game_tag SET role='normal',update_time=NOW()::timestamp(0)
WHERE game_id=$1 AND role<>'normal'
AND NOT ((role='primary' AND tag_id=$2) OR (role='secondary' AND tag_id=$3))
`

type ClearChangedGameTagRolesParams struct {
	GameID      int64 `json:"game_id"`
	PrimaryID   int64 `json:"primary_id"`
	SecondaryID int64 `json:"secondary_id"`
}

func (q *Queries) ClearChangedGameTagRoles(ctx context.Context, arg ClearChangedGameTagRolesParams) error {
	_, err := q.db.Exec(ctx, clearChangedGameTagRoles, arg.GameID, arg.PrimaryID, arg.SecondaryID)
	return err
}

const countTagCategories = `-- name: CountTagCategories :one
SELECT count(*) FROM gfg_tag_category WHERE $1::text='' OR name ILIKE '%'||$1||'%' OR name_en ILIKE '%'||$1||'%' OR code ILIKE '%'||$1||'%'
`

func (q *Queries) CountTagCategories(ctx context.Context, keyword string) (int64, error) {
	row := q.db.QueryRow(ctx, countTagCategories, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTagCategoryOptions = `-- name: CountTagCategoryOptions :one
SELECT count(*) FROM gfg_tag_category WHERE archived_at IS NULL AND ($1::text='' OR name ILIKE '%'||$1||'%' OR name_en ILIKE '%'||$1||'%' OR code ILIKE '%'||$1||'%' OR id::text=$1)
`

func (q *Queries) CountTagCategoryOptions(ctx context.Context, keyword string) (int64, error) {
	row := q.db.QueryRow(ctx, countTagCategoryOptions, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTags = `-- name: CountTags :one
SELECT count(*) FROM gfg_tag WHERE $1::text='' OR name ILIKE '%'||$1||'%' OR name_en ILIKE '%'||$1||'%' OR code ILIKE '%'||$1||'%'
`

func (q *Queries) CountTags(ctx context.Context, keyword string) (int64, error) {
	row := q.db.QueryRow(ctx, countTags, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGameTagRelations = `-- name: DeleteGameTagRelations :exec
DELETE FROM gfg_game_tag WHERE game_id=$1
`

func (q *Queries) DeleteGameTagRelations(ctx context.Context, gameID int64) error {
	_, err := q.db.Exec(ctx, deleteGameTagRelations, gameID)
	return err
}

const deleteRemovedGameTags = `-- name: DeleteRemovedGameTags :exec
DELETE FROM gfg_game_tag WHERE game_id=$1 AND NOT(tag_id=ANY($2::bigint[]))
`

type DeleteRemovedGameTagsParams struct {
	GameID int64   `json:"game_id"`
	TagIds []int64 `json:"tag_ids"`
}

func (q *Queries) DeleteRemovedGameTags(ctx context.Context, arg DeleteRemovedGameTagsParams) error {
	_, err := q.db.Exec(ctx, deleteRemovedGameTags, arg.GameID, arg.TagIds)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, name_en, info, info_en, create_time, update_time, code, category_id, archived_at FROM gfg_tag WHERE id=$1
`

func (q *Queries) GetTag(ctx context.Context, id int64) (GfgTag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i GfgTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Code,
		&i.CategoryID,
		&i.ArchivedAt,
	)
	return i, err
}

const getTagCategory = `-- name: GetTagCategory :one
SELECT id, code, name, name_en, info, info_en, sort_order, archived_at, create_time, update_time FROM gfg_tag_category WHERE id=$1
`

func (q *Queries) GetTagCategory(ctx context.Context, id int64) (GfgTagCategory, error) {
	row := q.db.QueryRow(ctx, getTagCategory, id)
	var i GfgTagCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO gfg_tag(code,name,name_en,info,info_en,category_id,create_time,update_time)
VALUES($1,$2,$3,$4,$5,$6,NOW()::timestamp(0),NOW()::timestamp(0)) RETURNING id, name, name_en, info, info_en, create_time, update_time, code, category_id, archived_at
`

type InsertTagParams struct {
	Code       string `json:"code"`
	Name       string `json:"name"`
	NameEn     string `json:"name_en"`
	Info       string `json:"info"`
	InfoEn     string `json:"info_en"`
	CategoryID int64  `json:"category_id"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (GfgTag, error) {
	row := q.db.QueryRow(ctx, insertTag,
		arg.Code,
		arg.Name,
		arg.NameEn,
		arg.Info,
		arg.InfoEn,
		arg.CategoryID,
	)
	var i GfgTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Code,
		&i.CategoryID,
		&i.ArchivedAt,
	)
	return i, err
}

const insertTagCategory = `-- name: InsertTagCategory :one
INSERT INTO gfg_tag_category(code,name,name_en,info,info_en,sort_order,create_time,update_time)
VALUES($1,$2,$3,$4,$5,$6,NOW()::timestamp(0),NOW()::timestamp(0)) RETURNING id, code, name, name_en, info, info_en, sort_order, archived_at, create_time, update_time
`

type InsertTagCategoryParams struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	NameEn    string `json:"name_en"`
	Info      string `json:"info"`
	InfoEn    string `json:"info_en"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) InsertTagCategory(ctx context.Context, arg InsertTagCategoryParams) (GfgTagCategory, error) {
	row := q.db.QueryRow(ctx, insertTagCategory,
		arg.Code,
		arg.Name,
		arg.NameEn,
		arg.Info,
		arg.InfoEn,
		arg.SortOrder,
	)
	var i GfgTagCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const invalidateGameRecommendations = `-- name: InvalidateGameRecommendations :exec
DELETE FROM gfg_game_recommendations
`

func (q *Queries) InvalidateGameRecommendations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, invalidateGameRecommendations)
	return err
}

const listGameTagRelations = `-- name: ListGameTagRelations :many
SELECT game_id, tag_id, role, create_time, update_time FROM gfg_game_tag WHERE game_id=$1 ORDER BY tag_id
`

func (q *Queries) ListGameTagRelations(ctx context.Context, gameID int64) ([]GfgGameTag, error) {
	rows, err := q.db.Query(ctx, listGameTagRelations, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfgGameTag{}
	for rows.Next() {
		var i GfgGameTag
		if err := rows.Scan(
			&i.GameID,
			&i.TagID,
			&i.Role,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagCategories = `-- name: ListTagCategories :many
SELECT id, code, name, name_en, info, info_en, sort_order, archived_at, create_time, update_time FROM gfg_tag_category WHERE $1::text='' OR name ILIKE '%'||$1||'%' OR name_en ILIKE '%'||$1||'%' OR code ILIKE '%'||$1||'%'
ORDER BY sort_order,id LIMIT $3 OFFSET $2
`

type ListTagCategoriesParams struct {
	Keyword   string `json:"keyword"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

func (q *Queries) ListTagCategories(ctx context.Context, arg ListTagCategoriesParams) ([]GfgTagCategory, error) {
	rows, err := q.db.Query(ctx, listTagCategories, arg.Keyword, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfgTagCategory{}
	for rows.Next() {
		var i GfgTagCategory
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.NameEn,
			&i.Info,
			&i.InfoEn,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagCategoryOptions = `-- name: ListTagCategoryOptions :many
SELECT id,name,name_en FROM gfg_tag_category WHERE archived_at IS NULL AND ($1::text='' OR name ILIKE '%'||$1||'%' OR name_en ILIKE '%'||$1||'%' OR code ILIKE '%'||$1||'%' OR id::text=$1) ORDER BY sort_order,id LIMIT $3 OFFSET $2
`

type ListTagCategoryOptionsParams struct {
	Keyword   string `json:"keyword"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

type ListTagCategoryOptionsRow struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	NameEn string `json:"name_en"`
}

func (q *Queries) ListTagCategoryOptions(ctx context.Context, arg ListTagCategoryOptionsParams) ([]ListTagCategoryOptionsRow, error) {
	rows, err := q.db.Query(ctx, listTagCategoryOptions, arg.Keyword, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagCategoryOptionsRow{}
	for rows.Next() {
		var i ListTagCategoryOptionsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.NameEn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, name_en, info, info_en, create_time, update_time, code, category_id, archived_at FROM gfg_tag WHERE $1::text='' OR name ILIKE '%'||$1||'%' OR name_en ILIKE '%'||$1||'%' OR code ILIKE '%'||$1||'%'
ORDER BY id LIMIT $3 OFFSET $2
`

type ListTagsParams struct {
	Keyword   string `json:"keyword"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]GfgTag, error) {
	rows, err := q.db.Query(ctx, listTags, arg.Keyword, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfgTag{}
	for rows.Next() {
		var i GfgTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameEn,
			&i.Info,
			&i.InfoEn,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Code,
			&i.CategoryID,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTagDomain = `-- name: LockTagDomain :exec
SELECT pg_advisory_xact_lock(hashtextextended('gfg.tag-domain',0))
`

// All category, tag and classification mutations acquire this transaction lock first.
// It serializes archive/assignment races across the small editorial domain and
// establishes one lock order before any game or category row locks.
func (q *Queries) LockTagDomain(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockTagDomain)
	return err
}

const setGameClassificationWeight = `-- name: SetGameClassificationWeight :exec
UPDATE gfg_game SET weight=$1,update_time=NOW()::timestamp(0) WHERE id=$2
`

type SetGameClassificationWeightParams struct {
	Weight int64 `json:"weight"`
	ID     int64 `json:"id"`
}

func (q *Queries) SetGameClassificationWeight(ctx context.Context, arg SetGameClassificationWeightParams) error {
	_, err := q.db.Exec(ctx, setGameClassificationWeight, arg.Weight, arg.ID)
	return err
}

const tagAssignmentCount = `-- name: TagAssignmentCount :one
SELECT count(*) FROM gfg_game_tag WHERE tag_id=$1
`

func (q *Queries) TagAssignmentCount(ctx context.Context, tagID int64) (int64, error) {
	row := q.db.QueryRow(ctx, tagAssignmentCount, tagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE gfg_tag SET name=$1,name_en=$2,info=$3,info_en=$4,category_id=$5,update_time=NOW()::timestamp(0)
WHERE id=$6 RETURNING id, name, name_en, info, info_en, create_time, update_time, code, category_id, archived_at
`

type UpdateTagParams struct {
	Name       string `json:"name"`
	NameEn     string `json:"name_en"`
	Info       string `json:"info"`
	InfoEn     string `json:"info_en"`
	CategoryID int64  `json:"category_id"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (GfgTag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.Name,
		arg.NameEn,
		arg.Info,
		arg.InfoEn,
		arg.CategoryID,
		arg.ID,
	)
	var i GfgTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Code,
		&i.CategoryID,
		&i.ArchivedAt,
	)
	return i, err
}

const updateTagCategory = `-- name: UpdateTagCategory :one
UPDATE gfg_tag_category SET name=$1,name_en=$2,info=$3,info_en=$4,sort_order=$5,update_time=NOW()::timestamp(0)
WHERE id=$6 RETURNING id, code, name, name_en, info, info_en, sort_order, archived_at, create_time, update_time
`

type UpdateTagCategoryParams struct {
	Name      string `json:"name"`
	NameEn    string `json:"name_en"`
	Info      string `json:"info"`
	InfoEn    string `json:"info_en"`
	SortOrder int32  `json:"sort_order"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateTagCategory(ctx context.Context, arg UpdateTagCategoryParams) (GfgTagCategory, error) {
	row := q.db.QueryRow(ctx, updateTagCategory,
		arg.Name,
		arg.NameEn,
		arg.Info,
		arg.InfoEn,
		arg.SortOrder,
		arg.ID,
	)
	var i GfgTagCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const upsertGameTag = `-- name: UpsertGameTag :exec
INSERT INTO gfg_game_tag(game_id,tag_id,role,create_time,update_time)
VALUES($1,$2,$3,NOW()::timestamp(0),NOW()::timestamp(0))
ON CONFLICT(game_id,tag_id) DO UPDATE SET role=EXCLUDED.role,update_time=EXCLUDED.update_time
WHERE gfg_game_tag.role<>EXCLUDED.role
`

type UpsertGameTagParams struct {
	GameID int64  `json:"game_id"`
	TagID  int64  `json:"tag_id"`
	Role   string `json:"role"`
}

func (q *Queries) UpsertGameTag(ctx context.Context, arg UpsertGameTagParams) error {
	_, err := q.db.Exec(ctx, upsertGameTag, arg.GameID, arg.TagID, arg.Role)
	return err
}
